//! C4 symmetry regression tests for the authored `symmetry_room`.
//!
//! The room is generated by rotating one canonical arm around the 1280x1280
//! room center. These tests do the same thing from the control side: drive the
//! controlled body with local-frame inputs in each arm, convert the resulting
//! world trace back into that arm's local frame, and require the traces to match.
//!
//! This catches reference-frame leaks without baking a per-gravity table into the
//! assertions. If a mechanic is correct by construction, the same local input in
//! each gravity well produces the same local trace up to the room rotation.

mod common;

use ambition_app::{AgentAction, SandboxSim};
use ambition_engine_core::{AccelerationFrame, Block, InputFrameMode, Vec2};
use common::{base, fixed_60hz_room_sim};
use serde_json::json;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

static FAILURE_DUMP_SEQ: AtomicU64 = AtomicU64::new(0);

const ROOM_CENTER: Vec2 = Vec2::new(640.0, 640.0);
const POS_TOL: f32 = 3.0;
const VEL_TOL: f32 = 8.0;

#[derive(Clone, Copy, Debug)]
struct Arm {
    name: &'static str,
    dir: Vec2,
}

fn arms() -> [Arm; 4] {
    [
        Arm {
            name: "down",
            dir: Vec2::new(0.0, 1.0),
        },
        Arm {
            name: "left",
            dir: Vec2::new(-1.0, 0.0),
        },
        Arm {
            name: "up",
            dir: Vec2::new(0.0, -1.0),
        },
        Arm {
            name: "right",
            dir: Vec2::new(1.0, 0.0),
        },
    ]
}

fn frame(dir: Vec2) -> AccelerationFrame {
    AccelerationFrame::new(dir)
}

/// Canonical arm-local coordinate -> world. Under down gravity this is just
/// `ROOM_CENTER + local`; under the other arms it rotates with the room.
fn world_from_local(dir: Vec2, local: Vec2) -> Vec2 {
    let f = frame(dir);
    ROOM_CENTER + f.side * local.x + f.down * local.y
}

/// World vector -> canonical arm-local vector for comparison.
fn local_vec(dir: Vec2, world: Vec2) -> Vec2 {
    let f = frame(dir);
    Vec2::new(world.dot(f.side), world.dot(f.down))
}

fn local_pos(dir: Vec2, world_pos: (f32, f32)) -> Vec2 {
    local_vec(dir, Vec2::new(world_pos.0, world_pos.1) - ROOM_CENTER)
}

fn local_vel(dir: Vec2, world_vel: (f32, f32)) -> Vec2 {
    local_vec(dir, Vec2::new(world_vel.0, world_vel.1))
}

#[derive(Clone, Debug)]
struct LocalSample {
    pos: Vec2,
    vel: Vec2,
    on_ground: bool,
    on_wall: bool,
    body_mode: String,
    facing: f32,
}

#[derive(Clone, Copy, Debug, Default)]
struct TraceCompareOptions {
    /// Axis-separated sweeps can land on the same support one frame apart when
    /// a trace is exactly on a discrete collision boundary. Keep the core trace
    /// strict, but allow tests that intentionally pass through one-way platforms
    /// and then fall onto authored solids to ignore that one boundary tick when
    /// both traces immediately converge to the same grounded state.
    allow_one_tick_landing_boundary: bool,
}

fn sample(dir: Vec2, obs: &ambition_app::rl_sim::AgentObservation) -> LocalSample {
    LocalSample {
        pos: local_pos(dir, obs.player_pos),
        vel: local_vel(dir, obs.player_vel),
        on_ground: obs.on_ground,
        on_wall: obs.on_wall,
        body_mode: obs.body_mode.clone(),
        facing: obs.facing.signum(),
    }
}

fn local_action(axis: Vec2) -> AgentAction {
    AgentAction {
        move_x: axis.x,
        move_y: axis.y,
        ..base()
    }
}

fn local_jump(axis: Vec2) -> AgentAction {
    AgentAction {
        move_x: axis.x,
        move_y: axis.y,
        jump: true,
        jump_held: true,
        ..base()
    }
}

#[derive(Clone, Copy, Debug)]
struct StartSpot {
    /// Canonical local side coordinate of the body's center.
    local_x: f32,
    /// Canonical local down-coordinate of the support face the body stands on.
    support_y: f32,
}

fn local_down_jump() -> AgentAction {
    AgentAction {
        move_y: 1.0,
        down_pressed: true,
        jump: true,
        jump_held: true,
        ..base()
    }
}

fn open_arm_sim(arm: Arm, spot: StartSpot) -> SandboxSim {
    let mut sim = fixed_60hz_room_sim("symmetry_room");
    // This makes AgentAction axes mean controlled-body-local side/down. The room
    // still supplies the gravity via zones; the setting only avoids mixing the
    // raw human-input policy into a symmetry property about mechanics.
    sim.set_movement_frame_mode(InputFrameMode::BodyRelativeStrict);
    // Use the arm's gravity as ambient fallback for the first post-teleport tick;
    // the gravity zone should then keep the same direction because the start
    // point is inside that arm's authored well.
    sim.set_base_gravity_dir((arm.dir.x, arm.dir.y));
    let half_h = sim.observation().player_size.1 * 0.5;
    let start_local = Vec2::new(spot.local_x, spot.support_y - half_h);
    let world = world_from_local(arm.dir, start_local);
    sim.teleport_player((world.x, world.y));
    for _ in 0..8 {
        sim.step(base());
    }
    let obs = sim.observation();
    assert_vec_close(
        Vec2::new(obs.gravity_dir.0, obs.gravity_dir.1),
        arm.dir,
        0.01,
        &format!("{} arm should resolve its authored gravity", arm.name),
    );
    assert!(
        obs.on_ground,
        "{} arm setup should settle on the rotated support; obs={obs:?}",
        arm.name
    );
    sim
}

fn trace_from(
    arm: Arm,
    spot: StartSpot,
    actions: impl IntoIterator<Item = AgentAction>,
) -> Vec<LocalSample> {
    let mut sim = open_arm_sim(arm, spot);
    actions
        .into_iter()
        .map(|action| {
            let obs = sim.step(action);
            sample(arm.dir, &obs)
        })
        .collect()
}

fn assert_vec_close(actual: Vec2, expected: Vec2, tol: f32, context: &str) {
    let diff = actual - expected;
    assert!(
        diff.x.abs() <= tol && diff.y.abs() <= tol,
        "{context}: got ({:.3}, {:.3}), expected ({:.3}, {:.3}), diff ({:.3}, {:.3}), tol {tol}",
        actual.x,
        actual.y,
        expected.x,
        expected.y,
        diff.x,
        diff.y,
    );
}

fn safe_dump_label(label: &str) -> String {
    label
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

fn sample_json(sample: &LocalSample) -> serde_json::Value {
    json!({
        "pos": [sample.pos.x, sample.pos.y],
        "vel": [sample.vel.x, sample.vel.y],
        "on_ground": sample.on_ground,
        "on_wall": sample.on_wall,
        "body_mode": sample.body_mode,
        "facing": sample.facing,
    })
}

fn repo_root() -> PathBuf {
    // In an integration test, CARGO_MANIFEST_DIR is game/ambition_app.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .components()
        .collect()
}

fn trace_failure_dump_dir() -> PathBuf {
    std::env::var_os("AMBITION_SYMMETRY_FAILURE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| repo_root().join("debug_traces/gravity_symmetry_room_failures"))
}

fn absolute_path(path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .join(path)
    }
}

fn write_trace_failure_dump(
    label: &str,
    reason: &str,
    expected: &[LocalSample],
    actual: &[LocalSample],
) -> Option<PathBuf> {
    let dir = trace_failure_dump_dir();
    std::fs::create_dir_all(&dir).ok()?;
    let seq = FAILURE_DUMP_SEQ.fetch_add(1, Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_nanos();
    let path = dir.join(format!(
        "failure_{}_{}_{}.json",
        safe_dump_label(label),
        nanos,
        seq
    ));
    let payload = json!({
        "test": "gravity_symmetry_room",
        "label": label,
        "reason": reason,
        "position_tolerance": POS_TOL,
        "velocity_tolerance": VEL_TOL,
        "expected_reference_arm": "down",
        "expected": expected.iter().map(sample_json).collect::<Vec<_>>(),
        "actual": actual.iter().map(sample_json).collect::<Vec<_>>(),
    });
    let text = serde_json::to_string_pretty(&payload).ok()?;
    std::fs::write(&path, text).ok()?;

    // Keep a stable pointer so upload scripts do not need to know the generated
    // timestamped filename. This file is overwritten by each failure.
    let latest = dir.join("latest_failure.json");
    let _ = std::fs::copy(&path, latest);

    Some(absolute_path(&path))
}

fn panic_trace_mismatch(
    label: &str,
    reason: String,
    expected: &[LocalSample],
    actual: &[LocalSample],
) -> ! {
    if let Some(path) = write_trace_failure_dump(label, &reason, expected, actual) {
        panic!("{reason}\nsymmetry failure dump: {}", path.display());
    }
    panic!("{reason}\nsymmetry failure dump: <failed to write>");
}

fn check_vec_close(actual: Vec2, expected: Vec2, tol: f32) -> Option<String> {
    let diff = actual - expected;
    if diff.x.abs() <= tol && diff.y.abs() <= tol {
        None
    } else {
        Some(format!(
            "got ({:.3}, {:.3}), expected ({:.3}, {:.3}), diff ({:.3}, {:.3}), tol {tol}",
            actual.x, actual.y, expected.x, expected.y, diff.x, diff.y
        ))
    }
}

fn vec_close(actual: Vec2, expected: Vec2, tol: f32) -> bool {
    check_vec_close(actual, expected, tol).is_none()
}

fn one_tick_landing_boundary(idx: usize, expected: &[LocalSample], actual: &[LocalSample]) -> bool {
    let Some((a, b)) = expected.get(idx).zip(actual.get(idx)) else {
        return false;
    };
    if a.on_ground == b.on_ground {
        return false;
    }
    let Some((next_a, next_b)) = expected.get(idx + 1).zip(actual.get(idx + 1)) else {
        return false;
    };
    if !(next_a.on_ground && next_b.on_ground) {
        return false;
    }
    const LANDING_BOUNDARY_POS_TOL: f32 = 4.0;
    vec_close(b.pos, a.pos, LANDING_BOUNDARY_POS_TOL)
        && vec_close(next_b.pos, next_a.pos, LANDING_BOUNDARY_POS_TOL)
        && vec_close(next_b.vel, next_a.vel, VEL_TOL)
        && next_b.body_mode == next_a.body_mode
        && next_b.facing == next_a.facing
}

fn assert_trace_matches_with_options(
    label: &str,
    expected: &[LocalSample],
    actual: &[LocalSample],
    options: TraceCompareOptions,
) {
    if expected.len() != actual.len() {
        panic_trace_mismatch(
            label,
            format!(
                "{label}: traces should have same length; expected {}, got {}",
                expected.len(),
                actual.len()
            ),
            expected,
            actual,
        );
    }
    for (i, (a, b)) in expected.iter().zip(actual).enumerate() {
        if options.allow_one_tick_landing_boundary && one_tick_landing_boundary(i, expected, actual)
        {
            continue;
        }
        if let Some(msg) = check_vec_close(b.pos, a.pos, POS_TOL) {
            panic_trace_mismatch(
                label,
                format!("{label} tick {i} local pos: {msg}"),
                expected,
                actual,
            );
        }
        if let Some(msg) = check_vec_close(b.vel, a.vel, VEL_TOL) {
            panic_trace_mismatch(
                label,
                format!("{label} tick {i} local vel: {msg}"),
                expected,
                actual,
            );
        }
        if b.on_ground != a.on_ground {
            panic_trace_mismatch(
                label,
                format!(
                    "{label} tick {i} on_ground: got {}, expected {}",
                    b.on_ground, a.on_ground
                ),
                expected,
                actual,
            );
        }
        if b.on_wall != a.on_wall {
            panic_trace_mismatch(
                label,
                format!(
                    "{label} tick {i} on_wall: got {}, expected {}",
                    b.on_wall, a.on_wall
                ),
                expected,
                actual,
            );
        }
        if b.body_mode != a.body_mode {
            panic_trace_mismatch(
                label,
                format!(
                    "{label} tick {i} body mode: got {}, expected {}",
                    b.body_mode, a.body_mode
                ),
                expected,
                actual,
            );
        }
        if b.facing != a.facing {
            panic_trace_mismatch(
                label,
                format!(
                    "{label} tick {i} local facing: got {}, expected {}",
                    b.facing, a.facing
                ),
                expected,
                actual,
            );
        }
    }
}

fn assert_trace_matches(label: &str, expected: &[LocalSample], actual: &[LocalSample]) {
    assert_trace_matches_with_options(label, expected, actual, TraceCompareOptions::default());
}

fn assert_c4_symmetric_trace(name: &str, spot: StartSpot, actions: impl Fn() -> Vec<AgentAction>) {
    let arms = arms();
    let reference = trace_from(arms[0], spot, actions());
    for arm in arms.iter().copied().skip(1) {
        let actual = trace_from(arm, spot, actions());
        assert_trace_matches(&format!("{name} / {} arm", arm.name), &reference, &actual);
    }
}

/// Start on the outer zig-zag step in each gravity well and run toward local
/// right. This catches raw-screen leaks in facing, acceleration, friction, wall
/// state, and support probes while staying away from the room's asymmetric
/// entrance furniture.
#[test]
fn symmetry_room_local_run_trace_is_c4_symmetric() {
    // Down-arm step A: x=[470,602], top y=1120. The center rests on that top
    // face in canonical local coordinates. The same local coordinate rotates
    // onto the equivalent step in each arm.
    let spot = StartSpot {
        local_x: -104.0,
        support_y: 1120.0 - ROOM_CENTER.y,
    };
    assert_c4_symmetric_trace("run right on step A", spot, || {
        (0..28).map(|_| local_action(Vec2::new(1.0, 0.0))).collect()
    });
}

/// Jumping is the simplest away-from-feet mechanic. The trace should be the same
/// after converting each world velocity back into the controlled body's frame.
#[test]
fn symmetry_room_local_jump_trace_is_c4_symmetric() {
    // Use the same open step A support as the run/crouch cases. Step B sits
    // close enough to the rotated zig-zag corner that the left arm can settle
    // into wall cling after local-order sweeps; that is a bad setup for a pure
    // away-from-feet jump symmetry test, not the behavior under test.
    let spot = StartSpot {
        local_x: -104.0,
        support_y: 1120.0 - ROOM_CENTER.y,
    };
    assert_c4_symmetric_trace("jump on step A", spot, || {
        let mut actions = vec![local_jump(Vec2::ZERO)];
        actions.extend((0..36).map(|_| base()));
        actions
    });
}

/// Dash is a local-side burst, not a world-X burst. The support setup is the
/// same stable step A used by run/jump/crouch so this isolates the dash impulse
/// and recovery path.
#[test]
fn symmetry_room_local_dash_trace_is_c4_symmetric() {
    let spot = StartSpot {
        local_x: -104.0,
        support_y: 1120.0 - ROOM_CENTER.y,
    };
    assert_c4_symmetric_trace("dash local right on step A", spot, || {
        let mut actions = vec![AgentAction {
            move_x: 1.0,
            dash: true,
            ..base()
        }];
        actions.extend((0..24).map(|_| base()));
        actions
    });
}

/// Crouch is a held local-down gate. The body should stay grounded and enter the
/// same body mode in every arm; this is the regression that previously appeared
/// as sideways crouch/stand flicker.
#[test]
fn symmetry_room_local_crouch_trace_is_c4_symmetric() {
    let spot = StartSpot {
        local_x: -104.0,
        support_y: 1120.0 - ROOM_CENTER.y,
    };
    assert_c4_symmetric_trace("hold local down on step A", spot, || {
        (0..18).map(|_| local_action(Vec2::new(0.0, 1.0))).collect()
    });
}

fn local_one_way_block(id: &'static str, dir: Vec2, local_min: Vec2, local_size: Vec2) -> Block {
    let f = frame(dir);
    let local_center = local_min + local_size * 0.5;
    let world_center = world_from_local(dir, local_center);
    let world_half = f.to_world_half(local_size * 0.5);
    Block::one_way(id, world_center - world_half, world_half * 2.0)
}

fn settle_on_injected_one_way(arm: Arm) -> SandboxSim {
    let mut sim = fixed_60hz_room_sim("symmetry_room");
    sim.set_movement_frame_mode(InputFrameMode::BodyRelativeStrict);
    sim.set_base_gravity_dir((arm.dir.x, arm.dir.y));

    // A small one-way in the open air between the down-arm step A and step B,
    // rotated into each arm. It deliberately avoids authored solids so failure
    // points at one-way support semantics, not room geometry.
    let local_min = Vec2::new(-150.0, 420.0);
    let local_size = Vec2::new(80.0, 12.0);
    sim.add_block(local_one_way_block(
        "sym_one_way",
        arm.dir,
        local_min,
        local_size,
    ));

    let half_h = sim.observation().player_size.1 * 0.5;
    let local_start = Vec2::new(
        local_min.x + local_size.x * 0.5,
        local_min.y - half_h - 24.0,
    );
    let world = world_from_local(arm.dir, local_start);
    sim.teleport_player((world.x, world.y));
    for _ in 0..50 {
        if sim.step(base()).on_ground {
            break;
        }
    }
    let obs = sim.observation();
    assert!(
        obs.on_ground,
        "{} arm should settle on injected one-way; obs={obs:?}",
        arm.name
    );
    sim
}

/// One-way drop-through is the contact-frame rule most likely to regress: the
/// platform's support face is gravity-relative, and local down+jump should drop
/// through it in all four arms.
#[test]
fn symmetry_room_one_way_drop_through_is_c4_symmetric() {
    let arms = arms();
    let mut reference = Vec::new();
    for (idx, arm) in arms.iter().copied().enumerate() {
        let mut sim = settle_on_injected_one_way(arm);
        let start = sample(arm.dir, &sim.observation());
        let mut trace = Vec::new();
        trace.push(sample(arm.dir, &sim.step(local_down_jump())));
        for _ in 0..42 {
            trace.push(sample(arm.dir, &sim.step(base())));
        }
        let end = trace.last().expect("trace has samples");
        assert!(
            end.pos.y > start.pos.y + 24.0,
            "{} arm should pass through one-way along local down; start={start:?} end={end:?}",
            arm.name
        );
        if idx == 0 {
            reference = trace;
        } else {
            assert_trace_matches_with_options(
                &format!("one-way drop-through / {} arm", arm.name),
                &reference,
                &trace,
                TraceCompareOptions {
                    allow_one_tick_landing_boundary: true,
                },
            );
        }
    }
}
