//! Embed every `*_spritesheet.ron` under `assets/sprites/` into the
//! built binary as a `&[(&str, &str)]` table.
//!
//! Why a build script: the runtime registry + the `LazyLock<CharacterSheetSpec>`
//! statics used to load these via `std::fs::read_dir($CARGO_MANIFEST_DIR/
//! assets/sprites)`. That works on desktop but produces an empty index on
//! Android / wasm — the manifest path is the dev machine's absolute path,
//! which doesn't exist on the device, and assets live inside the APK /
//! served bundle instead. The empty index then panicked the first time
//! `load_spec("goblin")` (or any character sheet) was forced.
//!
//! Mirrors the runtime scan: root `assets/sprites/` plus one level of
//! subdirs (the boss multi-sheet packages live there).

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rustc-check-cfg=cfg(ambition_static_sfx_bank_path)");
    println!("cargo:rerun-if-env-changed=AMBITION_STATIC_SFX_BANK_PATH");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    configure_static_sfx_bank(&manifest_dir);

    let sprites_dir = manifest_dir.join("assets/sprites");

    // Re-run if the directory contents shift. Cargo watches recursively
    // when handed a directory.
    println!("cargo:rerun-if-changed={}", sprites_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if sprites_dir.is_dir() {
        collect_spritesheet_rons(&sprites_dir, &mut entries);
        if let Ok(subdirs) = fs::read_dir(&sprites_dir) {
            for sub in subdirs.flatten() {
                let path = sub.path();
                if path.is_dir() {
                    collect_spritesheet_rons(&path, &mut entries);
                }
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("baked_sheet_rons.rs");

    let mut body = String::new();
    body.push_str("// Auto-generated by build.rs. Do not edit.\n");
    body.push_str("pub static BAKED_SHEET_RONS: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        // include_str! needs a path the rustc invocation can resolve.
        // Absolute paths from the build host are fine for `cargo build`,
        // and the build script always re-runs on the host doing the
        // compile (Android cross-compile included), so this is safe.
        let escaped_path = path.to_string_lossy().replace('\\', "\\\\");
        body.push_str(&format!(
            "    (\"{name}\", include_str!(\"{escaped_path}\")),\n",
        ));
    }
    body.push_str("];\n");

    fs::write(&out_path, body).expect("write baked_sheet_rons.rs");
}

fn configure_static_sfx_bank(manifest_dir: &Path) {
    if std::env::var_os("CARGO_FEATURE_STATIC_SFX_BANK").is_none() {
        return;
    }

    let configured = std::env::var_os("AMBITION_STATIC_SFX_BANK_PATH")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            let default_path = manifest_dir.join("assets/audio/sfx.bank");
            default_path.is_file().then_some(default_path)
        });

    if let Some(path) = configured {
        println!(
            "cargo:rustc-env=AMBITION_STATIC_SFX_BANK_PATH={}",
            path.display()
        );
        println!("cargo:rustc-cfg=ambition_static_sfx_bank_path");
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn collect_spritesheet_rons(dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(root) = name.strip_suffix("_spritesheet.ron") else {
            continue;
        };
        out.push((root.to_owned(), path));
    }
}
