//! Character sprite asset loading and actor/content joins.
//!
//! Character sheets are generated by `tools/ambition_sprite2d_renderer` and
//! loaded from `assets/sprites/`. Missing sheets leave their `Option` empty so
//! callers can fall back to rectangle visuals.
//!
//! [`assets`] owns catalog-to-sheet lookup, body-collision derivation, and prop
//! sprite construction. Animation, posed-body, and attack-hitbox derivations live
//! in `ambition_character_sprites`; sheet vocabulary lives in `ambition_sprite_sheet`.
//!
//! `character_runtime` currently calls into this module, so moving [`assets`] into
//! `ambition_character_sprites` would reverse the intended sibling dependency direction.

mod assets;

#[cfg(test)]
mod tests;

#[allow(
    unused_imports,
    reason = "sheet_for_character_id is the public catalog→spec entry; consumed by tests under content::character_catalog::tests (not by non-test crate code today). Public surface for future spawn-site callers."
)]
pub use assets::{
    all_character_sprite_filenames_in, build_npc_sprite_asset, build_prop_sprite_asset,
    build_prop_sprite_asset_packed, character_sprite_tier, load_character_sprites_in,
    demand_character_fx_sheets, ensure_fx_sheet_loaded, load_fx_sheets, load_prop_sheet_for_target, materialize_declared_character_sprite,
    portrait_for_declared_character, sheet_for_character_id_in, sheet_for_declared_character,
    sprite_body_collision_for_character_id_in, SpriteMaterialization,
};
