"""Archetype preset definitions for the toon adapter (see `toon_side.py`).

Pure data — each preset is a flat dict of body-plan + style params
passed as kwargs to `ToonSpec.__init__`. Extracted from `toon_side.py`
so adding a new archetype doesn't need to scroll past 380 lines of
palettes + 800 lines of rig code.

See GOALS.md goal #1 for the larger direction.
"""
from __future__ import annotations


PRESETS = {
    "general_hero": {
        "name": "General Hero",
        "role": "player",
        "palette_name": "hero",
        "body_plan": "hero",
        "outfit": "jacket",
        "hair_style": "swoop",
        "prop": "blade",
        "accessory": "scarf",
        "head_w": 27.0,
        "head_h": 30.0,
        "chin_h": 7.0,
        "neck_h": 4.5,
        "shoulder_w": 25.0,
        "torso_w": 22.0,
        "torso_h": 27.0,
        "hip_w": 18.5,
        "arm_upper": 13.5,
        "arm_lower": 13.0,
        "arm_radius": 2.8,
        "leg_upper": 17.0,
        "leg_lower": 16.0,
        "leg_radius": 3.0,
        "hand_r": 3.3,
        "foot_w": 12.5,
        "foot_h": 4.8,
        "coat_len": 8.0,
        "cape_len": 0.0,
        "hair_volume": 7.5,
        "nose_len": 3.0,
        "satchel_size": 0.0,
    },
    "absurd_general": {
        "name": "Absurd General",
        "role": "npc",
        "palette_name": "absurd_general",
        "body_plan": "broad",
        "outfit": "general_uniform",
        "hair_style": "general_hat",
        "prop": "baton",
        "accessory": "medals",
        "head_w": 31.0,
        "head_h": 29.0,
        "chin_h": 9.0,
        "neck_h": 3.5,
        "shoulder_w": 42.0,
        "torso_w": 34.0,
        "torso_h": 31.0,
        "hip_w": 25.0,
        "arm_upper": 12.0,
        "arm_lower": 11.0,
        "arm_radius": 3.5,
        "leg_upper": 12.5,
        "leg_lower": 11.5,
        "leg_radius": 3.4,
        "hand_r": 3.8,
        "foot_w": 13.5,
        "foot_h": 5.3,
        "coat_len": 12.0,
        "cape_len": 0.0,
        "hair_volume": 4.0,
        "nose_len": 4.4,
        "satchel_size": 0.0,
        "hat_brim_offset_x": 0.0,
        "hat_brim_offset_y": -2.0,
    },
    "fascist_enforcer": {
        "name": "Fascist Enforcer",
        "role": "enemy",
        "palette_name": "fascist",
        "body_plan": "rigid",
        "outfit": "storm_uniform",
        "hair_style": "officer_cap",
        "prop": "rifle",
        "accessory": "none",
        "head_w": 28.5,
        "head_h": 29.0,
        "chin_h": 7.2,
        "neck_h": 3.6,
        "shoulder_w": 34.5,
        "torso_w": 27.5,
        "torso_h": 31.5,
        "hip_w": 22.0,
        "arm_upper": 13.0,
        "arm_lower": 12.0,
        "arm_radius": 3.2,
        "leg_upper": 15.0,
        "leg_lower": 14.0,
        "leg_radius": 3.1,
        "hand_r": 3.2,
        "foot_w": 12.5,
        "foot_h": 4.9,
        "coat_len": 14.0,
        "cape_len": 0.0,
        "hair_volume": 2.6,
        "nose_len": 3.8,
        "satchel_size": 0.0,
    },
    "kernel_guide": {
        "name": "Kernel Guide",
        "role": "npc",
        "palette_name": "guide",
        "body_plan": "soft",
        "outfit": "poncho",
        "hair_style": "hood",
        "prop": "tablet",
        "accessory": "shawl",
        "head_w": 26.0,
        "head_h": 28.0,
        "chin_h": 6.0,
        "neck_h": 3.0,
        "shoulder_w": 34.0,
        "torso_w": 28.0,
        "torso_h": 24.0,
        "hip_w": 26.5,
        "arm_upper": 11.5,
        "arm_lower": 11.0,
        "arm_radius": 2.7,
        "leg_upper": 10.8,
        "leg_lower": 9.8,
        "leg_radius": 2.9,
        "hand_r": 3.0,
        "foot_w": 11.5,
        "foot_h": 4.5,
        "coat_len": 12.0,
        "cape_len": 18.0,
        "hair_volume": 6.0,
        "nose_len": 2.6,
        "satchel_size": 7.5,
    },
    "merchant_prototype": {
        "name": "Merchant Prototype",
        "role": "npc",
        "palette_name": "merchant",
        "body_plan": "round",
        "outfit": "apron",
        "hair_style": "cap",
        "prop": "coin_pouch",
        "accessory": "satchel",
        "head_w": 24.5,
        "head_h": 27.0,
        "chin_h": 5.5,
        "neck_h": 3.0,
        "shoulder_w": 25.5,
        "torso_w": 31.5,
        "torso_h": 28.0,
        "hip_w": 27.0,
        "arm_upper": 12.0,
        "arm_lower": 11.2,
        "arm_radius": 3.35,
        "leg_upper": 10.5,
        "leg_lower": 9.8,
        "leg_radius": 3.35,
        "hand_r": 3.2,
        "foot_w": 12.4,
        "foot_h": 4.7,
        "coat_len": 8.0,
        "cape_len": 0.0,
        "hair_volume": 5.0,
        "nose_len": 3.0,
        "satchel_size": 10.0,
    },
    "vault_keeper": {
        "name": "Vault Keeper",
        "role": "npc",
        "palette_name": "keeper",
        "body_plan": "broad",
        "outfit": "keeper_robe",
        "hair_style": "crest",
        "prop": "ledger",
        "accessory": "keys",
        "head_w": 26.5,
        "head_h": 30.0,
        "chin_h": 7.0,
        "neck_h": 4.2,
        "shoulder_w": 35.0,
        "torso_w": 29.5,
        "torso_h": 32.5,
        "hip_w": 26.5,
        "arm_upper": 14.0,
        "arm_lower": 13.0,
        "arm_radius": 3.4,
        "leg_upper": 15.0,
        "leg_lower": 14.0,
        "leg_radius": 3.3,
        "hand_r": 3.5,
        "foot_w": 13.0,
        "foot_h": 5.0,
        "coat_len": 22.0,
        "cape_len": 16.0,
        "hair_volume": 5.0,
        "nose_len": 3.2,
        "satchel_size": 0.0,
    },
    "architect": {
        "name": "Architect",
        "role": "npc",
        "palette_name": "architect",
        "body_plan": "tall",
        "outfit": "long_coat",
        "hair_style": "bob",
        "prop": "blueprint",
        "accessory": "sash",
        "head_w": 24.0,
        "head_h": 29.0,
        "chin_h": 6.4,
        "neck_h": 4.0,
        "shoulder_w": 22.5,
        "torso_w": 18.5,
        "torso_h": 29.0,
        "hip_w": 16.5,
        "arm_upper": 14.2,
        "arm_lower": 14.0,
        "arm_radius": 2.4,
        "leg_upper": 18.8,
        "leg_lower": 17.2,
        "leg_radius": 2.7,
        "hand_r": 2.9,
        "foot_w": 11.0,
        "foot_h": 4.2,
        "coat_len": 18.0,
        "cape_len": 0.0,
        "hair_volume": 6.6,
        "nose_len": 3.2,
        "satchel_size": 3.0,
    },
    # Oiler — gate mechanic, drawn after Handmann's 1753 portrait
    # of Euler: soft turban/nightcap (`savant_cap`) and a loose
    # silk banyan robe over a shirt + cravat. Still carries a
    # wrench and a tool satchel so the read is "scholar at the
    # workbench" rather than "professor on a Sunday." Stocky
    # `broad` body plan keeps him grounded and warm.
    "oiler": {
        "name": "Oiler",
        "role": "npc",
        "palette_name": "oiler",
        "body_plan": "broad",
        "outfit": "banyan",
        "hair_style": "savant_cap",
        "prop": "wrench",
        "accessory": "satchel",
        "head_w": 26.0,
        "head_h": 28.5,
        "chin_h": 6.5,
        "neck_h": 3.4,
        "shoulder_w": 32.0,
        "torso_w": 31.0,
        "torso_h": 28.5,
        "hip_w": 26.0,
        "arm_upper": 12.5,
        "arm_lower": 12.0,
        "arm_radius": 3.2,
        "leg_upper": 12.0,
        "leg_lower": 11.0,
        "leg_radius": 3.2,
        "hand_r": 3.3,
        "foot_w": 12.8,
        "foot_h": 5.0,
        "coat_len": 14.0,
        "cape_len": 0.0,
        "hair_volume": 4.0,
        "nose_len": 3.1,
        "satchel_size": 9.0,
    },
    # Erdish — graph-theory wanderer. Tall and thin, long coat,
    # satchel of paper. Body geometry is derived from `architect`
    # (tall silhouette) with the satchel inflated to match the
    # "always carrying a stack of incomplete proofs" energy.
    # Hair is `combed_back_balding` — gray, receding, swept back
    # with a few wild strands at the back. Reads as Erdős.
    "erdish": {
        "name": "Erdish",
        "role": "npc",
        "palette_name": "erdish",
        "body_plan": "tall",
        "outfit": "long_coat",
        "hair_style": "combed_back_balding",
        "prop": "tablet",
        "accessory": "satchel",
        "head_w": 23.0,
        "head_h": 28.0,
        "chin_h": 6.2,
        "neck_h": 4.2,
        "shoulder_w": 21.0,
        "torso_w": 17.0,
        "torso_h": 28.5,
        "hip_w": 15.5,
        "arm_upper": 14.5,
        "arm_lower": 14.2,
        "arm_radius": 2.3,
        "leg_upper": 19.0,
        "leg_lower": 17.5,
        "leg_radius": 2.6,
        "hand_r": 2.8,
        "foot_w": 10.5,
        "foot_h": 4.2,
        "coat_len": 20.0,
        "cape_len": 0.0,
        "hair_volume": 7.0,
        "nose_len": 3.4,
        "satchel_size": 8.5,
    },
    # ─────────────────────────────────────────────────────────────
    # Cryptography crew. Each preset locks a unique combination of
    # body_plan + outfit + hair_style + prop + palette so two
    # crew members never share a silhouette even when they share
    # an individual primitive. The story-side intent: this is the
    # first batch (Bob / Alice / Eve / Mallory / Trent / Judy) of
    # a 13-character canonical crypto roster — Trudy, Craig,
    # Sybil, Victor, Peggy, Walter, Olivia are queued in TODO.md.
    # ─────────────────────────────────────────────────────────────
    # Bob — practical key engineer. Broad workshop silhouette,
    # high-vis vest over a tee, short cropped hair, ring of keys
    # in one hand. The narrative pair to Alice (canonical Alice→
    # Bob protocol sender/receiver) but designed to read at a
    # glance as "implements the thing Alice designed."
    "bob": {
        "name": "Bob",
        "role": "npc",
        "palette_name": "bob",
        "body_plan": "broad",
        "outfit": "vest_over_shirt",
        "hair_style": "tousled_crop",
        "prop": "key_ring",
        "accessory": "satchel",
        "head_w": 26.5,
        "head_h": 28.0,
        "chin_h": 6.0,
        "neck_h": 3.6,
        "shoulder_w": 36.0,
        "torso_w": 30.0,
        "torso_h": 28.0,
        "hip_w": 25.0,
        "arm_upper": 13.0,
        "arm_lower": 12.5,
        "arm_radius": 3.3,
        "leg_upper": 14.0,
        "leg_lower": 13.0,
        "leg_radius": 3.2,
        "hand_r": 3.4,
        "foot_w": 13.0,
        "foot_h": 5.0,
        "coat_len": 6.0,
        "cape_len": 0.0,
        "hair_volume": 4.5,
        "nose_len": 3.0,
        "satchel_size": 7.5,
    },
    # Alice — cryptographer. Genuinely different silhouette from
    # the male-default toon: noticeably narrower shoulders, a
    # cinched-waist tabard with a hip-flare hem, and a long
    # single side-braid draped over the camera-side shoulder so
    # the head silhouette has a clear feminine read at any
    # render scale. The one-time-pad checker stays on the
    # tabard as her thematic cipher signature.
    "alice": {
        "name": "Alice",
        "role": "npc",
        "palette_name": "alice",
        "body_plan": "hero",
        # `cinched_tabard` adds a visible waist seam + lower
        # hip flare that the plain `tabard` doesn't have.
        "outfit": "cinched_tabard",
        # `long_side_braid` is hair that visibly hangs OVER the
        # front of her shoulder, not a tiny bun at the back.
        "hair_style": "long_side_braid",
        "prop": "cipher_scroll",
        "accessory": "scarf",
        # Head a touch smaller + cheekbones from chin_h shift.
        "head_w": 23.5,
        "head_h": 27.5,
        "chin_h": 5.6,
        "neck_h": 3.6,
        # Narrow shoulders + slightly wider hips than the male
        # hero. Torso slightly shorter so the cinched waist sits
        # high. Arms longer + thinner.
        "shoulder_w": 19.0,
        "torso_w": 16.5,
        "torso_h": 26.0,
        "hip_w": 19.5,
        "arm_upper": 14.0,
        "arm_lower": 13.6,
        "arm_radius": 2.2,
        "leg_upper": 18.0,
        "leg_lower": 17.0,
        "leg_radius": 2.6,
        "hand_r": 2.8,
        "foot_w": 10.5,
        "foot_h": 4.2,
        "coat_len": 14.0,
        "cape_len": 0.0,
        "hair_volume": 7.5,
        "nose_len": 2.4,
        "satchel_size": 0.0,
    },
    # Eve — eavesdropper. Tall hooded cloak silhouette, brass
    # listening horn cupped to one ear (the defining gesture).
    # Slightly thinner than the architect so the cloak hangs
    # straight rather than draping over a wide frame.
    "eve": {
        "name": "Eve",
        "role": "npc",
        "palette_name": "eve",
        "body_plan": "tall",
        "outfit": "eavesdrop_cloak",
        "hair_style": "hood",
        "prop": "listening_horn",
        "accessory": "satchel",
        "head_w": 23.5,
        "head_h": 28.0,
        "chin_h": 6.0,
        "neck_h": 3.8,
        "shoulder_w": 22.0,
        "torso_w": 18.0,
        "torso_h": 28.0,
        "hip_w": 17.0,
        "arm_upper": 14.0,
        "arm_lower": 13.6,
        "arm_radius": 2.5,
        "leg_upper": 18.5,
        "leg_lower": 17.0,
        "leg_radius": 2.7,
        "hand_r": 2.9,
        "foot_w": 11.0,
        "foot_h": 4.2,
        "coat_len": 20.0,
        "cape_len": 4.0,
        "hair_volume": 5.0,
        "nose_len": 3.2,
        "satchel_size": 6.0,
    },
    # Mallory — malicious attacker. Athletic silhouette: narrow
    # shoulders + defined waist via a cinched belt at the field
    # jacket. Hair has a kept-long side with a forward-draped
    # red braid hanging over the camera-side shoulder, not a
    # tucked-behind ponytail. The cliché "evil hacker hood" is
    # deliberately left for Eve; Mallory's threat is competence,
    # not theatre. Distinctly different silhouette from any of
    # the male-default toons.
    "mallory": {
        "name": "Mallory",
        "role": "npc",
        "palette_name": "mallory",
        # `hero` instead of `rigid` so the male tactical-hulk
        # read disappears.
        "body_plan": "hero",
        # `cinched_field_jacket` adds a visible belt at the
        # waist that the plain field_jacket doesn't have.
        "outfit": "cinched_field_jacket",
        # `forward_braid` drops the braid OVER the front
        # shoulder where the camera sees it.
        "hair_style": "forward_braid",
        "prop": "tablet",
        "accessory": "medals",
        "head_w": 23.0,
        "head_h": 27.0,
        "chin_h": 5.6,
        "neck_h": 3.4,
        # Narrow tactical-athlete shoulders, defined waist.
        "shoulder_w": 22.0,
        "torso_w": 18.0,
        "torso_h": 27.0,
        "hip_w": 20.0,
        "arm_upper": 13.5,
        "arm_lower": 13.0,
        "arm_radius": 2.6,
        "leg_upper": 17.0,
        "leg_lower": 16.0,
        "leg_radius": 2.8,
        "hand_r": 2.9,
        "foot_w": 11.0,
        "foot_h": 4.4,
        "coat_len": 8.0,
        "cape_len": 0.0,
        "hair_volume": 6.5,
        "nose_len": 2.6,
        "satchel_size": 0.0,
    },
    # Trent — trusted arbitrator. Stout, dignified. Long formal
    # robe with a collar, balance scales in hand, chain-of-office
    # medals across the chest. Bald with neat white side fringe
    # so the head silhouette differs sharply from Judy's wig and
    # Eve's hood.
    "trent": {
        "name": "Trent",
        "role": "npc",
        "palette_name": "trent",
        "body_plan": "broad",
        "outfit": "formal_robe",
        "hair_style": "clean_bald",
        "prop": "balance_scales",
        "accessory": "medals",
        "head_w": 26.0,
        "head_h": 28.5,
        "chin_h": 7.0,
        "neck_h": 3.6,
        "shoulder_w": 33.0,
        "torso_w": 28.0,
        "torso_h": 30.0,
        "hip_w": 25.0,
        "arm_upper": 13.0,
        "arm_lower": 12.5,
        "arm_radius": 3.2,
        "leg_upper": 13.0,
        "leg_lower": 12.0,
        "leg_radius": 3.2,
        "hand_r": 3.3,
        "foot_w": 12.5,
        "foot_h": 4.8,
        "coat_len": 22.0,
        "cape_len": 0.0,
        "hair_volume": 3.0,
        "nose_len": 3.4,
        "satchel_size": 0.0,
    },
    # Judy — the judge. Broad black judicial robe with crimson
    # placket, white jabot collar, full-bottom barrister wig,
    # gavel in hand. The wig and the jabot are what separate her
    # silhouette from Trent (also broad-robed) — same body plan,
    # different head + collar shape.
    "judy": {
        "name": "Judy",
        "role": "npc",
        "palette_name": "judy",
        "body_plan": "broad",
        "outfit": "judicial_robe",
        "hair_style": "barrister_wig",
        "prop": "gavel",
        "accessory": "jabot_collar",
        "head_w": 25.0,
        "head_h": 27.5,
        "chin_h": 6.4,
        "neck_h": 3.4,
        "shoulder_w": 33.0,
        "torso_w": 27.0,
        "torso_h": 30.0,
        "hip_w": 25.0,
        "arm_upper": 13.0,
        "arm_lower": 12.5,
        "arm_radius": 3.2,
        "leg_upper": 13.5,
        "leg_lower": 12.5,
        "leg_radius": 3.2,
        "hand_r": 3.3,
        "foot_w": 12.5,
        "foot_h": 4.8,
        "coat_len": 22.0,
        "cape_len": 0.0,
        "hair_volume": 7.5,
        "nose_len": 3.0,
        "satchel_size": 0.0,
    },
    # ─── Crypto crew batch 2 — sketches ──────────────────────────
    # Seven new presets that drop the remaining canonical
    # cryptography names into the cast with deliberate phenotype
    # variation. These are first-pass sketches on the toon
    # template; each may be promoted to a bespoke template
    # (cf. trent_elder / bob_engineer / alice_cryptographer) as
    # the story rooms call for them. The body / outfit / prop
    # picks lean on existing primitives where they work; only
    # truly unique silhouette features get new geometry.
    # Trudy — intruder; small frame, tight cropped hair, lockpick.
    "trudy": {
        "name": "Trudy",
        "role": "npc",
        "palette_name": "trudy",
        "body_plan": "hero",
        "outfit": "field_jacket",
        # Ponytail (not tousled crop) — visible long hair is the
        # primary feminine silhouette cue. Field jacket + lockpick
        # carry over.
        "hair_style": "ponytail",
        "prop": "lockpick",
        "accessory": "satchel",
        "head_w": 23.0,
        "head_h": 26.5,
        "chin_h": 5.6,
        "neck_h": 3.4,
        # Narrower shoulders + slightly wider hips so the
        # silhouette reads feminine. Was 23 / 19; now 19 / 20.
        "shoulder_w": 19.0,
        "torso_w": 16.5,
        "torso_h": 26.0,
        "hip_w": 20.0,
        "arm_upper": 13.0,
        "arm_lower": 12.6,
        "arm_radius": 2.4,
        "leg_upper": 16.5,
        "leg_lower": 15.5,
        "leg_radius": 2.8,
        "hand_r": 2.8,
        "foot_w": 10.8,
        "foot_h": 4.4,
        "coat_len": 6.0,
        "cape_len": 0.0,
        "hair_volume": 6.0,
        "nose_len": 2.4,
        "satchel_size": 6.5,
    },
    # Craig — safe-cracker; tall + bony, wide-brim hat,
    # stethoscope. Apron over a shirt reads as "workshop with
    # a notebook in the pocket" (different from Bob's vest).
    "craig": {
        "name": "Craig",
        "role": "npc",
        "palette_name": "craig",
        "body_plan": "tall",
        "outfit": "apron",
        "hair_style": "wide_brim_hat",
        "prop": "stethoscope",
        "accessory": "satchel",
        "head_w": 23.5,
        "head_h": 28.0,
        "chin_h": 7.0,
        "neck_h": 4.4,
        "shoulder_w": 22.0,
        "torso_w": 17.5,
        "torso_h": 29.0,
        "hip_w": 16.0,
        "arm_upper": 15.0,
        "arm_lower": 14.5,
        "arm_radius": 2.2,
        "leg_upper": 19.5,
        "leg_lower": 18.0,
        "leg_radius": 2.5,
        "hand_r": 2.7,
        "foot_w": 10.5,
        "foot_h": 4.2,
        "coat_len": 6.0,
        "cape_len": 0.0,
        "hair_volume": 4.0,
        "nose_len": 3.4,
        "satchel_size": 7.5,
    },
    # Sybil — pseudonymous attacker; many tight braids, layered
    # poncho-as-patchwork, holding a small mask stack.
    "sybil": {
        "name": "Sybil",
        "role": "npc",
        "palette_name": "sybil",
        "body_plan": "soft",
        "outfit": "poncho",
        "hair_style": "many_braids",
        "prop": "mask_stack",
        "accessory": "shawl",
        "head_w": 24.5,
        "head_h": 27.0,
        "chin_h": 5.8,
        "neck_h": 3.4,
        # Narrower shoulders + hips wider than shoulders.
        # Was 30 / 24 (broad-shouldered). Now 22 / 25.
        "shoulder_w": 22.0,
        "torso_w": 19.0,
        "torso_h": 25.0,
        "hip_w": 25.0,
        "arm_upper": 12.0,
        "arm_lower": 11.5,
        "arm_radius": 2.8,
        "leg_upper": 12.5,
        "leg_lower": 11.5,
        "leg_radius": 2.9,
        "hand_r": 3.0,
        "foot_w": 11.5,
        "foot_h": 4.5,
        "coat_len": 14.0,
        "cape_len": 18.0,
        "hair_volume": 6.5,
        "nose_len": 2.8,
        "satchel_size": 0.0,
    },
    # Victor — verifier; rigid square-fringe haircut, slate
    # jacket, holding a magnifier.
    "victor": {
        "name": "Victor",
        "role": "npc",
        "palette_name": "victor",
        "body_plan": "rigid",
        "outfit": "jacket",
        "hair_style": "square_fringe",
        "prop": "magnifier",
        "accessory": "scarf",
        "head_w": 24.5,
        "head_h": 28.0,
        "chin_h": 6.4,
        "neck_h": 3.6,
        "shoulder_w": 28.0,
        "torso_w": 22.0,
        "torso_h": 28.0,
        "hip_w": 20.0,
        "arm_upper": 13.5,
        "arm_lower": 13.0,
        "arm_radius": 2.8,
        "leg_upper": 15.5,
        "leg_lower": 14.5,
        "leg_radius": 2.9,
        "hand_r": 3.0,
        "foot_w": 11.5,
        "foot_h": 4.6,
        "coat_len": 8.0,
        "cape_len": 0.0,
        "hair_volume": 4.5,
        "nose_len": 3.2,
        "satchel_size": 0.0,
    },
    # Peggy — prover; athletic with a high ponytail, holding
    # a long pointer/wand. The pointer doubles as her
    # demonstrating tool.
    "peggy": {
        "name": "Peggy",
        "role": "npc",
        "palette_name": "peggy",
        "body_plan": "hero",
        "outfit": "jacket",
        "hair_style": "ponytail",
        "prop": "long_pointer",
        "accessory": "scarf",
        "head_w": 24.0,
        "head_h": 28.0,
        "chin_h": 5.8,
        "neck_h": 3.6,
        # Athletic but feminine — shoulders narrower than hips.
        # Was 24 / 21; now 20 / 22.
        "shoulder_w": 20.0,
        "torso_w": 17.0,
        "torso_h": 27.0,
        "hip_w": 22.0,
        "arm_upper": 13.5,
        "arm_lower": 13.0,
        "arm_radius": 2.5,
        "leg_upper": 17.0,
        "leg_lower": 16.0,
        "leg_radius": 2.7,
        "hand_r": 2.9,
        "foot_w": 11.0,
        "foot_h": 4.4,
        "coat_len": 8.0,
        "cape_len": 0.0,
        "hair_volume": 6.5,
        "nose_len": 2.6,
        "satchel_size": 0.0,
    },
    # Walter — warden; tricorn hat over silver hair, long
    # navy coat, brass-trim lantern. Older + dignified.
    "walter": {
        "name": "Walter",
        "role": "npc",
        "palette_name": "walter",
        "body_plan": "rigid",
        "outfit": "long_coat",
        "hair_style": "tricorn_hat",
        "prop": "lantern",
        "accessory": "keys",
        "head_w": 26.0,
        "head_h": 28.5,
        "chin_h": 6.6,
        "neck_h": 3.8,
        "shoulder_w": 31.0,
        "torso_w": 24.5,
        "torso_h": 30.0,
        "hip_w": 22.0,
        "arm_upper": 13.5,
        "arm_lower": 13.0,
        "arm_radius": 3.0,
        "leg_upper": 15.5,
        "leg_lower": 14.5,
        "leg_radius": 3.0,
        "hand_r": 3.1,
        "foot_w": 12.0,
        "foot_h": 4.8,
        "coat_len": 16.0,
        "cape_len": 0.0,
        "hair_volume": 4.5,
        "nose_len": 3.5,
        "satchel_size": 0.0,
    },
    # Olivia — oracle; veiled face, very pale skin, long
    # flowing keeper-robe in lavender. Holds nothing — both
    # hands tucked into sleeves.
    "olivia": {
        "name": "Olivia",
        "role": "npc",
        "palette_name": "olivia",
        "body_plan": "tall",
        "outfit": "keeper_robe",
        "hair_style": "veiled",
        "prop": "none",
        "accessory": "shawl",
        "head_w": 23.0,
        "head_h": 28.5,
        "chin_h": 5.8,
        "neck_h": 4.0,
        # Slender feminine frame — narrow shoulders, slightly
        # wider hips (was 21 / 16.5, which read as upside-down
        # triangle / masculine).
        "shoulder_w": 17.0,
        "torso_w": 14.0,
        "torso_h": 28.0,
        "hip_w": 18.0,
        "arm_upper": 14.0,
        "arm_lower": 13.5,
        "arm_radius": 2.3,
        "leg_upper": 18.5,
        "leg_lower": 17.0,
        "leg_radius": 2.6,
        "hand_r": 2.8,
        "foot_w": 10.5,
        "foot_h": 4.2,
        "coat_len": 22.0,
        "cape_len": 12.0,
        "hair_volume": 6.0,
        "nose_len": 2.4,
        "satchel_size": 0.0,
    },
}
