//! Item visuals (the item pickup presentation tail):
//! ground-item quads, the held-item sprite, and held-projectile sprites. Pure
//! consumers of the sim-built `sim_view` item snapshots (E4 slices 11+12+16)
//! — no live item/body queries.

use ambition_platformer_primitives::lifecycle::{
    ActiveSessionScope, SessionSpawnScope, SpawnSessionScopedExt,
};
use ambition_sim_view::{GroundItemsView, HeldItemView, HeldShotsView};

const FIREBALL_ID: &str = "fireball";
use bevy::prelude::*;
use bevy::sprite::Anchor;

// --- Wielded / held gun-sword sprite ---------------------------------------
// The spinning-lasersword sprite is the WIELDED weapon + the player's held
// gun-sword shot (a `HeldProjectile`), distinct from the faction projectile
// pool (whose art now flows through `ProjectileVisualKind`). These consumers
// keep their own static-frame helper.
//
// (Read from `lasersword_spritesheet.yaml`, row `idle`, frame 0.)
const LASERSWORD_SHEET_PATH: &str = "sprites/lasersword_spritesheet.png";
const LASERSWORD_LABEL_W: f32 = 110.0;
const LASERSWORD_FRAME_W: f32 = 169.0;
const LASERSWORD_FRAME_H: f32 = 44.0;
const LASERSWORD_IDLE_FRAME_X: f32 = LASERSWORD_LABEL_W;
const LASERSWORD_IDLE_FRAME_Y: f32 = 0.0;
/// Pommel anchor in the idle frame — rotation pivot of the sprite.
const LASERSWORD_POMMEL_X_PX: f32 = 14.0;
const LASERSWORD_POMMEL_Y_PX: f32 = 22.0;
const LASERSWORD_RENDER_WIDTH: f32 = 56.0;

/// Spritesheet path for the wielded / held gun-sword sprite.
pub const LASERSWORD_SHEET: &str = LASERSWORD_SHEET_PATH;

/// Build the lasersword sprite (idle frame, pommel-anchored) + its z-rotation
/// for a shot traveling at `vel` (world space, y-down). Used by the wielded
/// weapon and the player's held gun-sword shot so both render an identical
/// spinning sword aligned to its velocity.
///
/// AMBITION_REVIEW(spatial): Bevy +Y is up, sim +Y is down — flip Y for the
/// rotation; the pommel anchor is normalized from frame-local px (y negated).
pub fn lasersword_projectile_sprite(
    texture: Handle<Image>,
    vel: ambition_engine_core::Vec2,
) -> (Sprite, Anchor, Quat) {
    let bevy_dx = vel.x;
    let bevy_dy = -vel.y;
    let angle = if bevy_dx == 0.0 && bevy_dy == 0.0 {
        0.0
    } else {
        bevy_dy.atan2(bevy_dx)
    };
    let aspect = LASERSWORD_FRAME_W / LASERSWORD_FRAME_H;
    let render = Vec2::new(LASERSWORD_RENDER_WIDTH, LASERSWORD_RENDER_WIDTH / aspect);
    let anchor_x_norm = (LASERSWORD_POMMEL_X_PX - LASERSWORD_FRAME_W * 0.5) / LASERSWORD_FRAME_W;
    let anchor_y_norm = -(LASERSWORD_POMMEL_Y_PX - LASERSWORD_FRAME_H * 0.5) / LASERSWORD_FRAME_H;
    let mut sprite = Sprite::from_image(texture);
    sprite.custom_size = Some(render);
    sprite.rect = Some(Rect::from_corners(
        Vec2::new(LASERSWORD_IDLE_FRAME_X, LASERSWORD_IDLE_FRAME_Y),
        Vec2::new(
            LASERSWORD_IDLE_FRAME_X + LASERSWORD_FRAME_W,
            LASERSWORD_IDLE_FRAME_Y + LASERSWORD_FRAME_H,
        ),
    ));
    (
        sprite,
        Anchor(Vec2::new(anchor_x_norm, anchor_y_norm)),
        Quat::from_rotation_z(angle),
    )
}

// Presentation (visible build only).

/// Marks a sprite entity visualizing a [`GroundItem`].
#[derive(Component)]
pub struct GroundItemVisual;

/// Colored quad per ground item so it's visible. Clear-and-rebuild (few items).
/// Loaded held-item art (axe / javelin sprites). Visible build only.
/// Wielded-gauntlet ids that have a `sprites/props/gauntlet_<id>.png` icon — the
/// abstract abilities with no character prop. Shared by [`load_item_art`] (which
/// loads each) and [`item_sprite`] (which resolves them). Generated by
/// `item_icons.py::write_gauntlet_props` into `sprites/props/`.
pub const GAUNTLET_PROP_IDS: &[&str] = &[
    "shockwave",
    "volley",
    "beam",
    "vortex",
    "sentry",
    "dive",
    "meteor",
    // Item-shaped held-items: drawn as physical objects (a bomb, a hook, a
    // crystal, a fire sphere) rather than icon tiles -- see
    // `item_icons.py::render_item_object`. The fireball prop doubles as the
    // in-flight shot visual (`sync_held_projectile_visuals`).
    "bomb",
    "grapple",
    "gravity_grenade",
    "mark_recall",
    "blink",
    "puppy_slug_gun",
    "fireball",
];

#[derive(Resource)]
pub struct ItemArt {
    pub axe: Handle<Image>,
    pub javelin: Handle<Image>,
    pub gunsword: Handle<Image>,
    /// Gauntlet ground/held icons, keyed by held-item id ([`GAUNTLET_PROP_IDS`]).
    pub gauntlets: std::collections::HashMap<&'static str, Handle<Image>>,
}

/// Load the held-item sprites at startup.
pub fn load_item_art(mut commands: Commands, assets: Res<AssetServer>) {
    let gauntlets: std::collections::HashMap<&'static str, Handle<Image>> = GAUNTLET_PROP_IDS
        .iter()
        .map(|&id| (id, assets.load(format!("sprites/props/gauntlet_{id}.png"))))
        .collect();
    commands.insert_resource(ItemArt {
        axe: assets.load("sprites/props/axe.png"),
        javelin: assets.load("sprites/props/javelin.png"),
        gunsword: assets.load("sprites/props/gunsword.png"),
        gauntlets,
    });
}

/// `(image, display size)` for a held-item spec id, if it has authored art.
/// Display sizes keep each prop's native aspect ratio (axe 173×76, javelin
/// 236×29, lasersword 169×44).
fn item_sprite(art: &ItemArt, spec_id: &str) -> Option<(Handle<Image>, Vec2)> {
    match spec_id {
        "axe" => Some((art.axe.clone(), Vec2::new(40.0, 18.0))),
        "javelin" => Some((art.javelin.clone(), Vec2::new(58.0, 7.0))),
        // Same `lasersword_with_guns` proportions the pirates hold (177×46).
        "gun_sword" | "gun_sword_heavy" => Some((art.gunsword.clone(), Vec2::new(54.0, 14.0))),
        // Wielded gauntlets: a 64×64 procedural icon shown ~26px square on the
        // ground / in hand (no character prop — the ability is abstract).
        _ => art
            .gauntlets
            .get(spec_id)
            .map(|h| (h.clone(), Vec2::new(26.0, 26.0))),
    }
}

pub fn sync_ground_item_visuals(
    mut commands: Commands,
    world: ambition_platformer_primitives::lifecycle::SessionWorldRef<
        ambition_engine_core::RoomGeometry,
    >,
    art: Option<Res<ItemArt>>,
    active_session: Option<Res<ActiveSessionScope>>,
    visuals: Query<Entity, With<GroundItemVisual>>,
    grounds: Res<GroundItemsView>,
) {
    for entity in &visuals {
        commands.entity(entity).despawn();
    }
    let Some(session_scope) =
        SessionSpawnScope::for_optional_active_session(active_session.as_deref())
    else {
        return;
    };
    for ground in &grounds.0 {
        let translation = ambition_engine_core::config::world_to_bevy(&world.0, ground.pos, 8.0);
        let sprite = art
            .as_ref()
            .and_then(|a| item_sprite(a, ground.item_id.as_str()))
            .map(|(image, size)| Sprite {
                image,
                custom_size: Some(size),
                ..default()
            })
            .unwrap_or_else(|| {
                Sprite::from_color(Color::srgb(0.72, 0.52, 0.30), ground.half_extent * 2.0)
            });
        commands.spawn_session_scoped(
            session_scope,
            (
                GroundItemVisual,
                sprite,
                Transform::from_translation(translation),
                Name::new("Ground item visual"),
            ),
        );
    }
}

/// Marks a sprite entity visualizing a [`WorldItem`](ambition_actors::items::world_item::WorldItem).
#[derive(Component)]
pub struct WorldItemVisual;

/// Game-supplied art for walk-into world items, keyed by the presentation `sprite`
/// id a [`WorldItem`](ambition_actors::items::world_item::WorldItem) carries →
/// `(image, on-screen display size)`. The engine owns the SEAM (this resource + the
/// resolve in [`sync_world_item_visuals`]); each game fills it at startup with its
/// own pickups' images (e.g. Mary-O's milk carton), keeping asset knowledge out of
/// the reusable renderer. Absent / unmatched ⇒ the row-tinted placeholder quad.
#[derive(Resource, Default)]
pub struct WorldItemArt(pub std::collections::HashMap<String, (Handle<Image>, Vec2)>);

/// A sprite per walk-into world item: the real image when the item carries a
/// `sprite` id bound in [`WorldItemArt`], else a colored quad tinted by the row it
/// grants (grow-cap = cream, spark-blossom = ember, unknown = magenta) — the
/// draw-blind fallback. Clear-and-rebuild each frame — few items — mirroring
/// [`sync_ground_item_visuals`].
pub fn sync_world_item_visuals(
    mut commands: Commands,
    world: ambition_platformer_primitives::lifecycle::SessionWorldRef<
        ambition_engine_core::RoomGeometry,
    >,
    active_session: Option<Res<ActiveSessionScope>>,
    art: Option<Res<WorldItemArt>>,
    visuals: Query<Entity, With<WorldItemVisual>>,
    items: Res<ambition_sim_view::WorldItemsView>,
) {
    for entity in &visuals {
        commands.entity(entity).despawn();
    }
    let Some(session_scope) =
        SessionSpawnScope::for_optional_active_session(active_session.as_deref())
    else {
        return;
    };
    for item in &items.0 {
        let translation = ambition_engine_core::config::world_to_bevy(&world.0, item.pos, 8.0);
        // A real bound sprite wins; otherwise the row-tinted quad.
        let bound = item.sprite.as_deref().and_then(|id| {
            art.as_ref()
                .and_then(|a| a.0.get(id))
                .map(|(image, size)| (image.clone(), *size))
        });
        let sprite = match bound {
            Some((image, size)) => Sprite {
                image,
                custom_size: Some(size),
                ..default()
            },
            None => {
                let color = match item.row_id.as_str() {
                    "grow_cap" => Color::srgb(0.95, 0.93, 0.82),
                    "spark_blossom" => Color::srgb(0.95, 0.55, 0.20),
                    _ => Color::srgb(0.90, 0.20, 0.80),
                };
                Sprite::from_color(color, item.half_extent * 2.0)
            }
        };
        commands.spawn_session_scoped(
            session_scope,
            (
                WorldItemVisual,
                sprite,
                Transform::from_translation(translation),
                Name::new("World item visual"),
            ),
        );
    }
}

/// Marks the sprite shown in the player's hand for the currently held item.
#[derive(Component)]
pub struct HeldItemVisual;

/// Draw a small quad in the CONTROLLED SUBJECT's hand for whatever they're
/// holding, tinted per item (axe / javelin). Clear-and-rebuild each frame.
///
/// Keyed on [`ControlledSubject`] (the body carrying `Brain::Player(PRIMARY)`),
/// not `PrimaryPlayer`: while possessing, the held-item sprite draws on the body
/// you are DRIVING (reading ITS own `HeldItem`), never lingering on the vacated
/// home avatar — the same rule the blink reticle, camera, and nameplate follow.
/// Aim comes from the subject's brain-resolved `ActorControl`, not raw device
/// input, so a possessed body's ranged item points where THAT body aims.
pub fn sync_held_item_visual(
    mut commands: Commands,
    world: ambition_platformer_primitives::lifecycle::SessionWorldRef<
        ambition_engine_core::RoomGeometry,
    >,
    art: Option<Res<ItemArt>>,
    active_session: Option<Res<ActiveSessionScope>>,
    held_view: Res<HeldItemView>,
    visuals: Query<Entity, With<HeldItemVisual>>,
) {
    for entity in &visuals {
        commands.entity(entity).despawn();
    }
    let Some(session_scope) =
        SessionSpawnScope::for_optional_active_session(active_session.as_deref())
    else {
        return;
    };
    let Some(held) = held_view.0.as_ref() else {
        return;
    };
    let facing = if held.facing >= 0.0 { 1.0 } else { -1.0 };
    // In the subject's hand: just in front at hand height (y-down → small +y).
    let hand = held.pos + Vec2::new(facing * (held.size.x * 0.45 + 4.0), held.size.y * 0.06);
    let translation = ambition_engine_core::config::world_to_bevy(&world.0, hand, 12.0);

    // A ranged held item (the gun-sword) points where you're AIMING — the same
    // direction it fires — just like the pirates' wielded gun-sword. Melee /
    // thrown items keep the simple facing flip. Aim is the subject's
    // brain-resolved frame (screen-relative fallback to facing), so a possessed
    // body's item tracks ITS aim, not the home avatar's device stick.
    let (rotation, flip_x, flip_y) = if held.ranged {
        let aim = if held.aim.length_squared() > 1e-4 {
            held.aim.normalize()
        } else {
            Vec2::new(held.facing, 0.0)
        };
        // World is y-down, render space y-up. Aiming left flips vertically so
        // the gun stays upright instead of rotating upside-down.
        let angle = (-aim.y).atan2(aim.x);
        (Quat::from_rotation_z(angle), false, aim.x < 0.0)
    } else {
        (Quat::IDENTITY, facing < 0.0, false)
    };

    let sprite = art
        .as_ref()
        .and_then(|a| item_sprite(a, held.item_id.as_str()))
        .map(|(image, size)| Sprite {
            image,
            custom_size: Some(size),
            flip_x,
            flip_y,
            ..default()
        })
        .unwrap_or_else(|| {
            let color = match held.item_id.as_str() {
                "axe" => Color::srgb(0.72, 0.52, 0.30),
                "javelin" => Color::srgb(0.86, 0.84, 0.62),
                _ => Color::srgb(0.82, 0.82, 0.82),
            };
            Sprite::from_color(color, Vec2::new(14.0, 28.0))
        });
    commands.spawn_session_scoped(
        session_scope,
        (
            HeldItemVisual,
            sprite,
            Transform::from_translation(translation).with_rotation(rotation),
            Name::new("Held item visual"),
        ),
    );
}

/// Texture handles used by held-shot visuals. Kept alive in system-local state
/// so the per-frame clear/rebuild visual path does not also re-request and
/// repeatedly decode projectile sprite PNGs.
pub struct HeldProjectileVisualArt {
    lasersword: Handle<Image>,
    fireball: Handle<Image>,
}

impl HeldProjectileVisualArt {
    fn load(asset_server: &AssetServer) -> Self {
        Self {
            lasersword: asset_server.load(LASERSWORD_SHEET),
            fireball: asset_server.load(format!("sprites/props/gauntlet_{FIREBALL_ID}.png")),
        }
    }
}

/// Marks the streak sprite for an in-flight [`HeldProjectile`] (laser bolt).
#[derive(Component)]
pub struct HeldProjectileVisual;

/// Render each in-flight held shot. Fireballs draw as a glowing sphere; other
/// shots reuse the spinning lasersword sprite and rotate along travel.
pub fn sync_held_projectile_visuals(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    world: ambition_platformer_primitives::lifecycle::SessionWorldRef<
        ambition_engine_core::RoomGeometry,
    >,
    active_session: Option<Res<ActiveSessionScope>>,
    visuals: Query<Entity, With<HeldProjectileVisual>>,
    shots: Res<HeldShotsView>,
    mut art: Local<Option<HeldProjectileVisualArt>>,
) {
    for entity in &visuals {
        commands.entity(entity).despawn();
    }
    let Some(session_scope) =
        SessionSpawnScope::for_optional_active_session(active_session.as_deref())
    else {
        return;
    };
    let art = art.get_or_insert_with(|| HeldProjectileVisualArt::load(&asset_server));
    for shot in &shots.0 {
        let translation = ambition_engine_core::config::world_to_bevy(&world.0, shot.pos, 9.5);
        if shot.fireball {
            // Fireball: a glowing ball, sized a touch over the contact box so the
            // fire visibly fills the space that hits. No rotation — it's radial.
            commands.spawn_session_scoped(
                session_scope,
                (
                    HeldProjectileVisual,
                    Sprite {
                        image: art.fireball.clone(),
                        custom_size: Some(Vec2::splat(30.0)),
                        ..default()
                    },
                    Transform::from_translation(translation),
                    Name::new("Fireball shot"),
                ),
            );
            continue;
        }
        let (sprite, anchor, rotation) =
            lasersword_projectile_sprite(art.lasersword.clone(), shot.vel);
        commands.spawn_session_scoped(
            session_scope,
            (
                HeldProjectileVisual,
                sprite,
                anchor,
                Transform {
                    translation,
                    rotation,
                    scale: Vec3::ONE,
                },
                Name::new("Gun-sword laser shot"),
            ),
        );
    }
}
