//! Compile-time table of `(asset_relative_manifest_path, ron_text)` pairs for
//! every independently published `*_portraits.ron` under `assets/sprites/`.
//!
//! Generated by `build.rs` so desktop, Android, and wasm use the same portrait
//! clip metadata without runtime filesystem access.

include!(concat!(env!("OUT_DIR"), "/baked_portrait_rons.rs"));
