//! Host wiring for the reusable [`ambition_sprite_sheet`] registry.
//!
//! The sprite-sheet metadata SCHEMA + the [`SheetRegistry`] resource live in the
//! `ambition_sprite_sheet` foundation crate (content-free, reusable). This module
//! owns the parts specific to THIS game: the build-time baked `*_spritesheet.ron`
//! table (`baked_sheet_rons`, generated by `build.rs` from `assets/sprites/`) and
//! the Bevy plugin that installs + populates the registry resource from it.
//!
//! Re-exports the crate's vocabulary so existing
//! `crate::presentation::character_sprites::registry::*` paths keep resolving.

pub use ambition_sprite_sheet::*;

use bevy::prelude::*;

/// Build the registry from THIS game's baked sheet table — headless-friendly (no
/// Bevy `App`), for tools/tests that need sprite metrics (boss hurtbox math, the
/// geometry-debug renderer) without spinning up [`SheetRegistryPlugin`].
pub fn baked_sheet_registry() -> SheetRegistry {
    SheetRegistry::from_baked_table(super::baked_sheet_rons::BAKED_SHEET_RONS)
}

/// Bevy plugin that installs the registry resource and a Startup system to
/// populate it from the baked table.
pub struct SheetRegistryPlugin;

impl Plugin for SheetRegistryPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<SheetRegistry>()
            .add_systems(Startup, init_sheet_registry);
    }
}

fn init_sheet_registry(mut registry: ResMut<SheetRegistry>) {
    *registry = baked_sheet_registry();
}
