use bevy::prelude::*;

/// One asset-backed parallax layer in a profile.
#[derive(Clone, Copy, Debug)]
pub struct ParallaxLayerProfile {
    pub name: &'static str,
    pub asset_path: &'static str,
    pub factor: Vec2,
    pub offset: Vec2,
    pub z: f32,
    pub size: Vec2,
    pub tile_x: bool,
    pub tile_y: bool,
}

/// A named background stack. First layer spawns behind later layers.
#[derive(Clone, Copy, Debug)]
pub struct ParallaxProfile {
    pub name: &'static str,
    pub layers: &'static [ParallaxLayerProfile],
}

const DEFAULT_LAYERS: &[ParallaxLayerProfile] = &[
    ParallaxLayerProfile {
        name: "sky",
        asset_path: "backgrounds/default/sky.png",
        factor: Vec2::ZERO,
        offset: Vec2::ZERO,
        z: -80.0,
        size: Vec2::new(5200.0, 3200.0),
        tile_x: false,
        tile_y: false,
    },
    ParallaxLayerProfile {
        name: "far silhouettes",
        asset_path: "backgrounds/default/far.png",
        factor: Vec2::new(0.12, 0.08),
        offset: Vec2::new(0.0, -120.0),
        z: -70.0,
        size: Vec2::new(6400.0, 2600.0),
        tile_x: true,
        tile_y: false,
    },
    ParallaxLayerProfile {
        name: "mid structures",
        asset_path: "backgrounds/default/mid.png",
        factor: Vec2::new(0.28, 0.18),
        offset: Vec2::new(0.0, -60.0),
        z: -60.0,
        size: Vec2::new(6400.0, 2400.0),
        tile_x: true,
        tile_y: false,
    },
    ParallaxLayerProfile {
        name: "near foreground",
        asset_path: "backgrounds/default/near.png",
        factor: Vec2::new(0.55, 0.35),
        offset: Vec2::ZERO,
        z: -50.0,
        size: Vec2::new(6400.0, 2400.0),
        tile_x: true,
        tile_y: true,
    },
];

/// Default placeholder art stack generated by `ambition_background_renderer`.
pub const fn default_parallax_profile() -> ParallaxProfile {
    ParallaxProfile {
        name: "default",
        layers: DEFAULT_LAYERS,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_profile_layers_are_back_to_front() {
        let profile = default_parallax_profile();
        assert!(profile.layers.len() >= 3);
        for pair in profile.layers.windows(2) {
            assert!(
                pair[0].z < pair[1].z,
                "{} should be behind {}",
                pair[0].name,
                pair[1].name
            );
        }
    }

    #[test]
    fn default_profile_uses_generated_assets() {
        let profile = default_parallax_profile();
        for layer in profile.layers {
            assert!(layer.asset_path.starts_with("backgrounds/default/"));
            assert!(layer.asset_path.ends_with(".png"));
        }
    }
}
