//! Ambition's authored audio registries — CONTENT data, evicted from the
//! engine core (R3.2: the engine ships no tracks and no cues).
//!
//! - `music_registry.ron` is GENERATED by `scripts/regen_music_registry.py`
//!   from the rendered-OGG asset tree; do not hand-edit.
//! - `sfx_registry.ron` is hand-authored synth-cue data.
//!
//! Providers register both through `ambition_audio::catalog`; hosts select a
//! provider or deterministic combination and insert the playback resources they
//! need. Audio authority is fully App-local — no process-global install seam.


use ambition_platformer2d::content::MusicRegistry;
use ambition_platformer2d::content::SfxRegistry;
/// The music registry's embedded text, or `None` when this build reads it off
/// disk.
///
/// ⛔ **`include_str!` IS A COMPILATION INPUT, NOT A DATA READ.** Cargo tracks
/// the named file exactly like a `.rs`, so embedding this one rebuilds
/// `ambition_content` — and `ambition_audio`, `ambition_platformer2d`,
/// `ambition_combat`, `ambition_characters`, `ambition_items`,
/// `ambition_encounter`, `ambition_boss_encounter` and `ambition_app` after it —
/// every time the file changes. That is most of the game, rebuilt for a data
/// edit.
///
/// This file in particular is GENERATED by `scripts/regen_music_registry.py`
/// and carries a do-not-hand-edit banner, so it changes on every music regen
/// without anybody touching Rust. Embedding it made an asset pipeline step cost
/// a near-full recompile.
///
/// Gated the same way [`crate::worlds`] gates the LDtk world JSON behind
/// `static_map`: OFF for desktop development, ON for the builds that have no
/// filesystem to read from (web, Android) or that ship without the source tree.
/// The sibling SFX registry stays embedded unconditionally — it is hand-authored
/// and changes only when someone is already editing code.
#[cfg(feature = "static_content")]
pub const MUSIC_REGISTRY_RON_STATIC: Option<&'static str> =
    Some(include_str!("../assets/audio/music_registry.ron"));
#[cfg(not(feature = "static_content"))]
pub const MUSIC_REGISTRY_RON_STATIC: Option<&'static str> = None;

pub const SFX_REGISTRY_RON: &str = include_str!("../assets/audio/sfx_registry.ron");

/// Register Ambition's immutable audio fragments in one Bevy `App`. This is the
/// sole authority: hosts read the assembled registries from the
/// `AudioCatalogRegistry` resource (no process-global install seam remains).
pub fn register(app: &mut bevy::prelude::App) {
    use ambition_audio::catalog::{AudioCatalogAppExt, AudioCatalogFragment};

    app.register_audio_catalog_fragment(
        AudioCatalogFragment::new(
            crate::AMBITION_CONTENT_PROVIDER,
            Some(load_music_registry()),
            Some(load_sfx_registry()),
        )
        .expect("Ambition audio catalogs should be valid"),
    );
}

/// The authored music registry (generated by `scripts/regen_music_registry.py`).
///
/// `MusicRegistry::validate()` did run, but only later and only inside `AudioCatalogFragment::new`,
/// which needs an App; and nothing anywhere asked whether the OGG each track points at exists. The
/// `music_registry` schema declares every track's audio file as a requirement, so a strict asset
/// check reports a track whose file was never rendered.
pub fn load_music_registry() -> MusicRegistry {
    ambition_audio::content_schema::lowered_music_registry(crate::pack::prepared())
        .expect("the music schema lowers its registry for every pack that compiles")
        .clone()
}

/// The hand-authored SFX synthesis registry. Same move as the music registry:
/// the compiler's lowered artifact, not a re-parse.
pub fn load_sfx_registry() -> SfxRegistry {
    ambition_audio::content_schema::lowered_sfx_registry(crate::pack::prepared())
        .expect("the sfx schema lowers its registry for every pack that compiles")
        .clone()
}

#[cfg(test)]
mod tests {
    #[test]
    fn both_registries_parse() {
        let music = super::load_music_registry();
        assert!(
            !music.tracks.is_empty(),
            "music registry should have tracks"
        );
        let _sfx = super::load_sfx_registry();
    }
}
