//! Ambition's authored audio registries — CONTENT data, evicted from the
//! engine core (R3.2: the engine ships no tracks and no cues).
//!
//! - `music_registry.ron` is GENERATED by `scripts/regen_music_registry.py`
//!   from the rendered-OGG asset tree; do not hand-edit.
//! - `sfx_registry.ron` is hand-authored synth-cue data.
//!
//! The app loads both at startup and inserts them as resources; the
//! engine's audio machinery consumes the parsed types
//! (`ambition_audio::spec` re-exported through
//! `ambition_actors::session::data`) without knowing this data.

use ambition_actors::session::data::{MusicRegistry, SfxRegistry};

pub const MUSIC_REGISTRY_RON: &str = include_str!("../assets/audio/music_registry.ron");
pub const SFX_REGISTRY_RON: &str = include_str!("../assets/audio/sfx_registry.ron");

/// Install both registries into the engine's authored-audio seam
/// (`session::data::install_music_registry` / `install_sfx_registry`).
/// Called from the app's startup choke point and from
/// `AmbitionContentPlugin::build`; first install wins, so the double call
/// is harmless.
pub fn install() {
    ambition_actors::session::data::install_music_registry(load_music_registry());
    ambition_actors::session::data::install_sfx_registry(load_sfx_registry());
}

/// Parse the authored music registry (generated by
/// `scripts/regen_music_registry.py`).
pub fn load_music_registry() -> MusicRegistry {
    ron::from_str(MUSIC_REGISTRY_RON)
        .expect("ambition_content assets/audio/music_registry.ron should parse")
}

/// Parse the hand-authored SFX synthesis registry.
pub fn load_sfx_registry() -> SfxRegistry {
    ron::from_str(SFX_REGISTRY_RON)
        .expect("ambition_content assets/audio/sfx_registry.ron should parse")
}

#[cfg(test)]
mod tests {
    #[test]
    fn both_registries_parse() {
        let music = super::load_music_registry();
        assert!(
            !music.tracks.is_empty(),
            "music registry should have tracks"
        );
        let _sfx = super::load_sfx_registry();
    }
}
