//! Ambition's authored audio registries — CONTENT data, evicted from the
//! engine core (R3.2: the engine ships no tracks and no cues).
//!
//! - `music_registry.ron` is GENERATED by `scripts/regen_music_registry.py`
//!   from the rendered-OGG asset tree; do not hand-edit.
//! - `sfx_registry.ron` is hand-authored synth-cue data.
//!
//! Providers register both through `ambition_audio::catalog`; hosts select a
//! provider or deterministic combination and insert the playback resources they
//! need. The legacy actor-session install seam remains only while pure catalog
//! builders are migrated.

use ambition_actors::session::data::{MusicRegistry, SfxRegistry};

pub const MUSIC_REGISTRY_RON: &str = include_str!("../assets/audio/music_registry.ron");
pub const SFX_REGISTRY_RON: &str = include_str!("../assets/audio/sfx_registry.ron");

/// Feed the temporary process-global compatibility seam used by remaining pure
/// asset-catalog builders. New hosts use [`register`].
pub fn install() {
    ambition_actors::session::data::install_music_registry(load_music_registry());
    ambition_actors::session::data::install_sfx_registry(load_sfx_registry());
}

/// Register Ambition's immutable audio fragments in one Bevy `App`.
pub fn register(app: &mut bevy::prelude::App) {
    use ambition_audio::catalog::{AudioCatalogAppExt, AudioCatalogFragment};

    app.register_audio_catalog_fragment(
        AudioCatalogFragment::new(
            crate::AMBITION_CONTENT_PROVIDER,
            Some(load_music_registry()),
            Some(load_sfx_registry()),
        )
        .expect("Ambition audio catalogs should be valid"),
    );
    install();
}

/// Parse the authored music registry (generated by
/// `scripts/regen_music_registry.py`).
pub fn load_music_registry() -> MusicRegistry {
    ron::from_str(MUSIC_REGISTRY_RON)
        .expect("ambition_content assets/audio/music_registry.ron should parse")
}

/// Parse the hand-authored SFX synthesis registry.
pub fn load_sfx_registry() -> SfxRegistry {
    ron::from_str(SFX_REGISTRY_RON)
        .expect("ambition_content assets/audio/sfx_registry.ron should parse")
}

#[cfg(test)]
mod tests {
    #[test]
    fn both_registries_parse() {
        let music = super::load_music_registry();
        assert!(
            !music.tracks.is_empty(),
            "music registry should have tracks"
        );
        let _sfx = super::load_sfx_registry();
    }
}
