//! Sandbox-side aggregator for the [`ambition_asset_manager`] catalog.
//!
//! Owns the construction of the **single** [`SandboxAssetCatalog`]
//! resource that every visible-sandbox subsystem reads from to resolve
//! Bevy asset paths. The catalog covers:
//!
//! - entity sprites + parallax layers (built from `game_assets.rs`'s
//!   `sandbox_image_manifest`)
//! - character spritesheets (player / robot / goblin / sandbag + NPC
//!   registry)
//! - boss spritesheets (gradient-sentinel + mockingbird)
//! - UI fonts (dialog regular / semibold + debug mono, with legacy
//!   per-source fallbacks)
//! - the LDtk world (`world.sandbox_ldtk`)
//! - the sandbox tuning RON (`data.sandbox`)
//! - the packed SFX bank (`audio.sfx_bank`)
//! - every music track in `sandbox_data.audio.music_tracks`
//!
//! Construction order (`build_sandbox_catalog`):
//! 1. start with the image manifest from
//!    [`crate::assets::game_assets::sandbox_image_manifest`]
//! 2. extend with character / boss / font / music / world / data / SFX
//!    entries from the helpers in this module
//! 3. wrap into [`SandboxAssetCatalog`] with the active
//!    [`AssetProfile`].
//!
//! Everywhere else: ask the catalog for a path via
//! [`SandboxAssetCatalog::path_for`]; hand the string to Bevy's
//! `AssetServer`; let Bevy's per-platform `AssetReader` do the actual
//! IO. The catalog does **not** perform IO itself.

use std::path::PathBuf;

use bevy::prelude::{App, Plugin, Resource};

use ambition_asset_manager::{
    AmbitionAssetCatalog, AssetEntry, AssetId, AssetKind, AssetLocation, AssetManifest,
    AssetProfile, AssetResolutionError, AssetSourceProfile, MissingAssetPolicy, PreloadGroup,
    ResolvedAsset,
};

/// Path component the [`AmbitionAssetSourcePlugin`] registers the
/// sandbox LDtk world under, in Bevy's [`bevy::asset::io::embedded::EmbeddedAssetRegistry`].
/// Concatenated with `embedded://` to form the AssetPath string.
/// Catalog entries for `world.sandbox_ldtk` carry an explicit
/// `EmbeddedBinary` `LocationCandidate` pointing at this same path so
/// the resolved URL matches what the registry will serve.
pub(crate) const EMBEDDED_SANDBOX_LDTK_ASSET_PATH: &str =
    "ambition_sandbox/ambition/worlds/sandbox.ldtk";

/// Same shape as [`EMBEDDED_SANDBOX_LDTK_ASSET_PATH`] for the intro
/// LDtk world.
pub(crate) const EMBEDDED_INTRO_LDTK_ASSET_PATH: &str =
    "ambition_sandbox/ambition/worlds/intro.ldtk";

/// Declarative table of embedded core assets.
///
/// Each row is `NAME => "<embedded_url>" @ "<include_bytes_path>"`. The
/// macro emits:
///
/// 1. a `pub const NAME: &str = "<embedded_url>"` inside [`embedded_core`]
/// 2. an entry in [`embedded_core::ALL_URLS`]
/// 3. an `EmbeddedAssetRegistry::insert_asset(... include_bytes!(...))`
///    call inside [`register_embedded_core_assets`] (under
///    `static_core_assets`)
///
/// Adding a new embedded asset is one row in the macro — the previous
/// "three-line change" recipe collapses to a single declaration. The
/// guardrail tests still verify catalog candidates exist for each URL
/// (the third pairing, on the catalog-entry side).
///
/// `<include_bytes_path>` is interpreted relative to *this* source
/// file (`assets/sandbox_assets.rs`), so `"../../../assets/foo.png"` resolves
/// to `crates/ambition_sandbox/assets/foo.png`.
macro_rules! embed_core_assets {
    (
        $( $name:ident => $url:literal @ $rel_path:literal ),* $(,)?
    ) => {
        pub(crate) mod embedded_core {
            //! Public URL constants for every embedded core asset.
            //! Generated by the `embed_core_assets!` macro in
            //! `super::sandbox_assets`. Catalog candidates and registry
            //! insertions both reference these constants by name.
            $( pub const $name: &str = $url; )*

            /// Every embedded core URL, in declaration order. The
            /// `embedded_core_urls_are_unique` and
            /// `embedded_core_urls_have_authored_catalog_candidates`
            /// tests walk this slice.
            #[allow(dead_code)] // Used only by tests / future packaging tools.
            pub const ALL_URLS: &[&str] = &[ $( $name ),* ];
        }

        /// Insert every embedded core asset's bytes into Bevy's
        /// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`]. Gated
        /// by `static_core_assets` because the bytes are pulled in via
        /// `include_bytes!` from `crates/ambition_sandbox/assets/...`.
        #[cfg(feature = "static_core_assets")]
        fn register_embedded_core_assets(app: &mut ::bevy::prelude::App) {
            use ::bevy::asset::io::embedded::EmbeddedAssetRegistry;
            use ::std::path::{Path, PathBuf};
            let embedded = app
                .world_mut()
                .resource_mut::<EmbeddedAssetRegistry>();
            $(
                embedded.insert_asset(
                    PathBuf::new(),
                    Path::new(embedded_core::$name),
                    include_bytes!($rel_path) as &[u8],
                );
            )*
        }
    };
}

embed_core_assets! {
    // ── UI fonts ────────────────────────────────────────────────────
    FONT_DIALOG_REGULAR_URL =>
        "ambition_sandbox/fonts/bundled/InterDisplay-Regular.otf"
        @ "../../../assets/fonts/bundled/InterDisplay-Regular.otf",
    FONT_DIALOG_SEMIBOLD_URL =>
        "ambition_sandbox/fonts/bundled/InterDisplay-SemiBold.otf"
        @ "../../../assets/fonts/bundled/InterDisplay-SemiBold.otf",
    FONT_DEBUG_MONO_URL =>
        "ambition_sandbox/fonts/bundled/JetBrainsMono-Regular.ttf"
        @ "../../../assets/fonts/bundled/JetBrainsMono-Regular.ttf",

    // ── Primary character spritesheets ──────────────────────────────
    SPRITE_PLAYER_URL =>
        "ambition_sandbox/sprites/player_robot_spritesheet.png"
        @ "../../../assets/sprites/player_robot_spritesheet.png",
    SPRITE_ROBOT_URL =>
        "ambition_sandbox/sprites/robot_spritesheet.png"
        @ "../../../assets/sprites/robot_spritesheet.png",
    SPRITE_GOBLIN_URL =>
        "ambition_sandbox/sprites/goblin_spritesheet.png"
        @ "../../../assets/sprites/goblin_spritesheet.png",
    SPRITE_SANDBAG_URL =>
        "ambition_sandbox/sprites/sandbag_spritesheet.png"
        @ "../../../assets/sprites/sandbag_spritesheet.png",

    // ── Core entity sprites ─────────────────────────────────────────
    SPRITE_CHEST_CLOSED_URL =>
        "ambition_sandbox/sprites/entities/chest_closed.png"
        @ "../../../assets/sprites/entities/chest_closed.png",
    SPRITE_CHEST_OPEN_URL =>
        "ambition_sandbox/sprites/entities/chest_open.png"
        @ "../../../assets/sprites/entities/chest_open.png",
    SPRITE_PICKUP_HEALTH_URL =>
        "ambition_sandbox/sprites/entities/pickup_health.png"
        @ "../../../assets/sprites/entities/pickup_health.png",
    SPRITE_PICKUP_CURRENCY_URL =>
        "ambition_sandbox/sprites/entities/pickup_currency.png"
        @ "../../../assets/sprites/entities/pickup_currency.png",
    SPRITE_PICKUP_ABILITY_URL =>
        "ambition_sandbox/sprites/entities/pickup_ability.png"
        @ "../../../assets/sprites/entities/pickup_ability.png",
    SPRITE_DOOR_ZONE_URL =>
        "ambition_sandbox/sprites/entities/door_zone.png"
        @ "../../../assets/sprites/entities/door_zone.png",
    SPRITE_EDGE_EXIT_URL =>
        "ambition_sandbox/sprites/entities/edge_exit.png"
        @ "../../../assets/sprites/entities/edge_exit.png",
    SPRITE_PROJECTILE_ENERGY_URL =>
        "ambition_sandbox/sprites/entities/projectile_energy.png"
        @ "../../../assets/sprites/entities/projectile_energy.png",
    SPRITE_SOLID_TILE_URL =>
        "ambition_sandbox/sprites/entities/solid_tile.png"
        @ "../../../assets/sprites/entities/solid_tile.png",
    SPRITE_ONE_WAY_TILE_URL =>
        "ambition_sandbox/sprites/entities/one_way_tile.png"
        @ "../../../assets/sprites/entities/one_way_tile.png",
    SPRITE_HAZARD_TILE_URL =>
        "ambition_sandbox/sprites/entities/hazard_tile.png"
        @ "../../../assets/sprites/entities/hazard_tile.png",
    SPRITE_BOSS_CORE_URL =>
        "ambition_sandbox/sprites/entities/boss_core.png"
        @ "../../../assets/sprites/entities/boss_core.png",
}

use crate::assets::game_assets::{sandbox_image_manifest, GameAssetConfig};
use crate::content::data::AudioSpec;

mod builders;
pub mod ids;

use builders::{
    extend_with_boss_entries, extend_with_character_entries, extend_with_data_entries,
    extend_with_font_entries, extend_with_intro_sprite_entries, extend_with_music_entries,
    extend_with_sfx_bank_entry, extend_with_world_entries,
};

/// Wrapped [`AmbitionAssetCatalog`] + active [`AssetProfile`].
///
/// One instance per app session, installed as a Bevy `Resource` by
/// [`crate::app::init_sandbox_resources`]. Every subsystem that loads
/// an asset goes through this; nothing else owns asset-source policy.
///
/// Cheap to clone (the underlying manifest is wrapped in an `Arc`-like
/// shared shape inside [`AmbitionAssetCatalog`]'s `Clone` impl).
#[derive(Resource, Clone, Debug)]
pub struct SandboxAssetCatalog {
    catalog: AmbitionAssetCatalog,
    profile: AssetProfile,
}

impl SandboxAssetCatalog {
    /// Construct from a fully-built [`AmbitionAssetCatalog`] + the
    /// active profile. Prefer [`build_sandbox_catalog`] from
    /// production code; this is the seam for unit tests that author
    /// a partial manifest.
    pub fn new(catalog: AmbitionAssetCatalog, profile: AssetProfile) -> Self {
        Self { catalog, profile }
    }

    /// Convenience: build a desktop-dev catalog from the embedded
    /// sandbox spec, suitable for headless / RL / test fixtures that
    /// don't have a [`crate::assets::game_assets::GameAssetConfig`] resource
    /// in hand. Production startup builds the catalog from the live
    /// `GameAssetConfig` via [`build_sandbox_catalog`].
    pub fn for_desktop_dev_default() -> Self {
        let mut config = crate::assets::game_assets::GameAssetConfig::default();
        config.asset_profile = AssetProfile::DesktopDevLoose;
        let spec = crate::content::data::SandboxDataSpec::load_embedded();
        build_sandbox_catalog(&config, &spec.audio)
    }

    pub fn catalog(&self) -> &AmbitionAssetCatalog {
        &self.catalog
    }

    pub fn profile(&self) -> AssetProfile {
        self.profile
    }

    pub fn path_for(&self, id: &AssetId) -> Option<String> {
        self.catalog.path_for(id, self.profile)
    }

    pub fn resolve(&self, id: &AssetId) -> Result<ResolvedAsset, AssetResolutionError> {
        self.catalog.resolve(id, self.profile)
    }

    /// Local filesystem path the LDtk hot-reload watcher should poll,
    /// when both the active profile and the resolved location support
    /// it. `None` everywhere else (bundled / web / no-assets).
    pub fn hot_reload_local_path(&self, id: &AssetId) -> Option<PathBuf> {
        let resolved = self.resolve(id).ok()?;
        if !resolved.supports_hot_reload() {
            return None;
        }
        resolved.location.as_local_path().map(|p| p.to_path_buf())
    }

    /// Resolve `id` and apply the per-profile load gate in one call.
    ///
    /// Returns `Some(path)` when the loader should hand the path to
    /// Bevy's `AssetServer::load`; `None` when the loader should fall
    /// back (colored rectangle, silent SFX, Bevy default font, etc.).
    ///
    /// This is the **only** function loaders need to call — it combines:
    /// - `path_for(id)` (resolver),
    /// - the per-profile "is this asset actually available?" gate
    ///   ([`Self::should_attempt_resolved_load`]).
    ///
    /// Consumers that need the local on-disk path (the SFX bank byte
    /// loader, the LDtk hot-reload watcher) go through
    /// [`Self::resolve_local_file_path`] / [`Self::hot_reload_local_path`].
    pub fn try_path_for_load(&self, id: &AssetId) -> Option<String> {
        let resolved = self.resolve(id).ok()?;
        let path = resolved.bevy_asset_path()?;
        if self.should_attempt_resolved_load(&resolved, &path) {
            Some(path)
        } else {
            None
        }
    }

    /// Per-profile load gate keyed on a fully-resolved entry.
    ///
    /// - Desktop (DevLoose / Installed / SteamDeck): pre-check the host
    ///   filesystem via the candidate-roots walker
    ///   ([`desktop_candidate_roots`]) so missing optional art falls back
    ///   to colored rectangles / Bevy's default font before Bevy logs a
    ///   load failure. Required assets always attempt the load so the
    ///   `MissingAssetPolicy::Error` path can surface a useful error.
    /// - Android / iOS bundle: trust the packager; let Bevy's platform
    ///   `AssetReader` try the load.
    /// - Web / BundledStatic: attempt the load when the entry has an
    ///   **authored** embedded candidate (the bytes are packaged via
    ///   `embedded_asset!`); skip otherwise to preserve colored-rectangle
    ///   fallback.
    /// - WebHttp: attempt only when the entry has an authored
    ///   `HttpRemote` candidate. Optional images today have none, so they
    ///   fall back to placeholders.
    /// - IpfsGatewayPlaceholder: attempt when an authored `IpfsGateway`
    ///   candidate is present.
    /// - NoAssets / Headless: never attempt (catalog already returned
    ///   None for `path_for`; this is exhaustive-match insurance).
    pub fn should_attempt_resolved_load(&self, resolved: &ResolvedAsset, path: &str) -> bool {
        match self.profile {
            AssetProfile::DesktopDevLoose
            | AssetProfile::DesktopInstalled
            | AssetProfile::SteamDeckInstalled => {
                resolved.missing_policy.is_required()
                    || self.resolve_local_file_path(path).is_some()
            }
            AssetProfile::AndroidBundle | AssetProfile::IosBundle => true,
            AssetProfile::WebStatic | AssetProfile::BundledStatic => {
                resolved.authored_candidate
                    && matches!(
                        resolved.source_used,
                        Some(AssetSourceProfile::EmbeddedBinary)
                    )
            }
            // WebServedAssets attempts every resolution that produces
            // a Bevy-pathable URL: either an authored `Embedded`
            // candidate (delivered from `EmbeddedAssetRegistry`) or
            // the synthesized `BevyPath` from `logical_path` (which
            // Bevy's wasm HTTP reader fetches from `/assets/<path>`).
            // Missing files surface as Bevy load-failure logs + the
            // renderer's existing placeholder fallbacks; we cannot
            // pre-check the host filesystem from the browser, so the
            // "trust Bevy to fetch" stance matches Android/iOS.
            AssetProfile::WebServedAssets => {
                matches!(
                    resolved.source_used,
                    Some(AssetSourceProfile::EmbeddedBinary)
                        | Some(AssetSourceProfile::InstalledFilesystem)
                )
            }
            AssetProfile::WebHttp => {
                resolved.authored_candidate
                    && matches!(resolved.source_used, Some(AssetSourceProfile::HttpRemote))
            }
            AssetProfile::IpfsGatewayPlaceholder => {
                resolved.authored_candidate
                    && matches!(resolved.source_used, Some(AssetSourceProfile::IpfsGateway))
            }
            AssetProfile::NoAssets | AssetProfile::Headless => false,
        }
    }

    /// Same gate, but for **required** assets. Required entries with
    /// no host-filesystem precheck always attempt the load; the
    /// resolver's `Disabled` path is what consults
    /// [`MissingAssetPolicy::Error`].
    pub fn should_attempt_required_load(&self, _path: &str) -> bool {
        !matches!(
            self.profile,
            AssetProfile::NoAssets | AssetProfile::Headless
        )
    }

    /// Locate the absolute on-disk path for a Bevy-relative asset path
    /// under the current profile, when one is available. Returns
    /// `None` for non-desktop profiles or when the file simply isn't
    /// there. Walks the same candidate roots Bevy's file `AssetReader`
    /// consults at runtime, in this order:
    ///
    /// 1. `$BEVY_ASSET_ROOT/assets/<rel>`
    /// 2. `$BEVY_ASSET_ROOT/<rel>`
    /// 3. `$CWD/assets/<rel>`
    /// 4. `$CWD/<rel>`
    /// 5. `$CARGO_MANIFEST_DIR/assets/<rel>` (dev fallback)
    ///
    /// This is the **only** host-filesystem probe in the sandbox. The
    /// LDtk hot-reload watcher and the SFX bank byte loader both call
    /// through here — there is no duplicate candidate walk anywhere
    /// else in `crates/ambition_sandbox/src/`.
    pub fn resolve_local_file_path(&self, rel: &str) -> Option<std::path::PathBuf> {
        if !matches!(
            self.profile,
            AssetProfile::DesktopDevLoose
                | AssetProfile::DesktopInstalled
                | AssetProfile::SteamDeckInstalled
        ) {
            return None;
        }
        desktop_candidate_roots(rel)
            .into_iter()
            .find(|p| p.exists())
    }
}

/// Build the ordered candidate roots for `rel_path` on desktop / Steam
/// Deck profiles. The only candidate-roots walker in the sandbox;
/// [`SandboxAssetCatalog::resolve_local_file_path`] (and through it
/// `should_attempt_optional_load` / `try_path_for_load`) are the sole
/// callers.
fn desktop_candidate_roots(rel_path: &str) -> Vec<std::path::PathBuf> {
    let rel = std::path::Path::new(rel_path);
    let mut candidates = Vec::with_capacity(5);
    if let Some(root) = std::env::var_os("BEVY_ASSET_ROOT") {
        let root = std::path::PathBuf::from(root);
        candidates.push(root.join("assets").join(rel));
        candidates.push(root.join(rel));
    }
    if let Ok(cwd) = std::env::current_dir() {
        candidates.push(cwd.join("assets").join(rel));
        candidates.push(cwd.join(rel));
    }
    candidates.push(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("assets")
            .join(rel),
    );
    candidates
}

/// Build the full sandbox catalog: every visible-sandbox asset id +
/// the active profile. Called once during `init_sandbox_resources`.
///
/// `audio` is borrowed from the already-loaded [`crate::content::data::SandboxDataSpec`]
/// so music-track ids land in the catalog at startup; the spec itself
/// is loaded via `include_str!`, so the catalog doesn't depend on
/// disk-resident files for bootstrap.
pub fn build_sandbox_catalog(config: &GameAssetConfig, audio: &AudioSpec) -> SandboxAssetCatalog {
    let mut manifest = sandbox_image_manifest(&config.sprite_folder);
    extend_with_world_entries(&mut manifest);
    extend_with_data_entries(&mut manifest);
    extend_with_sfx_bank_entry(&mut manifest);
    extend_with_font_entries(&mut manifest);
    extend_with_character_entries(&mut manifest, &config.sprite_folder);
    extend_with_boss_entries(&mut manifest, &config.sprite_folder);
    extend_with_music_entries(&mut manifest, audio);
    extend_with_intro_sprite_entries(&mut manifest, &config.sprite_folder);
    SandboxAssetCatalog::new(AmbitionAssetCatalog::new(manifest), config.asset_profile)
}

// ─────────────────────────────────────────────────────────────────────
// Bevy AssetSource registration
// ─────────────────────────────────────────────────────────────────────

/// Bevy plugin that backs every URL the [`SandboxAssetCatalog`] hands
/// out with a real `AssetSource`.
///
/// Today this is the embedded source only: behind the `static_map`
/// feature, the plugin inserts the sandbox + intro LDtk JSON bytes into
/// Bevy's [`bevy::asset::io::embedded::EmbeddedAssetRegistry`] under
/// [`EMBEDDED_SANDBOX_LDTK_ASSET_PATH`] / [`EMBEDDED_INTRO_LDTK_ASSET_PATH`],
/// matching the explicit `EmbeddedBinary` `LocationCandidate`s authored
/// on the corresponding catalog entries. The catalog's resolution +
/// the plugin's registration are paired: change one, change the other.
///
/// Adding more embedded assets (sprites, fonts, audio) is a recipe:
/// 1. Add a `with_location(EmbeddedBinary, AssetLocation::embedded("ambition_sandbox/..."))`
///    candidate to the catalog entry.
/// 2. Add a matching `EmbeddedAssetRegistry::insert_asset(...,
///    include_bytes!(...))` call in [`register_embedded_assets`].
/// 3. Optional: extend the `static_map` feature gate or introduce a
///    separate gate (`static_fonts`, etc.) if a packaged subset is
///    desirable.
///
/// HTTP / HTTPS / IPFS source registration is a future slice; the
/// catalog already emits `https://...` URLs from authored
/// `HttpRemote` candidates, but the matching Bevy `AssetReader` isn't
/// wired yet.
///
/// ## Ordering requirement
///
/// `EmbeddedAssetRegistry` is created by Bevy's `AssetPlugin`. The
/// plugin therefore must run AFTER `DefaultPlugins`. The visible app
/// builder ([`crate::app::run_visible`] / [`crate::app::run_web`])
/// adds it as the last plugin in the
/// `SandboxPresentationPlugin` install order.
pub struct AmbitionAssetSourcePlugin {
    pub profile: AssetProfile,
}

impl AmbitionAssetSourcePlugin {
    pub fn for_profile(profile: AssetProfile) -> Self {
        Self { profile }
    }
}

impl Plugin for AmbitionAssetSourcePlugin {
    fn build(&self, app: &mut App) {
        register_embedded_assets(app);
        // HTTP / IPFS source registration hooks live alongside this
        // for future profile-conditional registration; see
        // [`add_http_asset_source`].
        let _ = self.profile;
    }
}

/// Insert every embedded asset's bytes into Bevy's
/// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`] under the
/// URLs the catalog's `Embedded` candidates point at.
///
/// Two independent feature gates:
/// - `static_map` — LDtk world JSON (sandbox + intro).
/// - `static_core_assets` — UI fonts + primary character sheets + core
///   entity sprites (see [`embedded_core`] for the URL constants).
///
/// Adding a new embedded asset is a three-line change:
/// 1. add a `const FOO_URL: &str = "ambition_sandbox/..."` to
///    [`embedded_core`] and append it to `ALL_URLS`;
/// 2. add a matching `with_embedded_core_candidate(entry, FOO_URL)`
///    on the catalog entry;
/// 3. add an `EmbeddedAssetRegistry::insert_asset(...,
///    include_bytes!("../assets/..."))` call in
///    [`register_embedded_core_assets`] below.
///
/// The `embedded_core_paths_match_registration_constants` test fails
/// loudly if any one of those three pieces is missing.
#[allow(unused_variables)]
fn register_embedded_assets(app: &mut App) {
    #[cfg(feature = "static_map")]
    {
        use bevy::asset::io::embedded::EmbeddedAssetRegistry;
        use std::path::{Path, PathBuf};

        let embedded = app.world_mut().resource_mut::<EmbeddedAssetRegistry>();
        embedded.insert_asset(
            PathBuf::new(),
            Path::new(EMBEDDED_SANDBOX_LDTK_ASSET_PATH),
            include_bytes!("../../../assets/ambition/worlds/sandbox.ldtk") as &[u8],
        );
        embedded.insert_asset(
            PathBuf::new(),
            Path::new(EMBEDDED_INTRO_LDTK_ASSET_PATH),
            include_bytes!("../../../assets/ambition/worlds/intro.ldtk") as &[u8],
        );
    }
    #[cfg(feature = "static_core_assets")]
    register_embedded_core_assets(app);
}

/// Documented stub for future HTTP/HTTPS asset source registration.
///
/// Bevy 0.18 ships `http` and `https` features that provide
/// `AssetReader`s; the consumer enables those features and adds the
/// source via `AssetPlugin::source(...)`. This function is the wiring
/// point — currently a no-op so call sites can be added now.
#[allow(dead_code)] // Slated for slice 9 (WebHttp packaging).
pub fn add_http_asset_source(_app: &mut App) {}

#[cfg(test)]
mod tests;
