//! Bevy `EmbeddedAssetRegistry` integration for the sandbox catalog.
//!
//! Centralizes the embedded URL constants ([`embedded_core`] for fonts /
//! sheets / core entity sprites; world JSON URLs come from the installed
//! `WorldManifest` rows), the
//! `include_bytes!` registrations that back them, and the
//! [`AmbitionAssetSourcePlugin`] that installs everything into Bevy at
//! startup.
//!
//! Catalog entries (built by [`super::builders`]) reference these URL
//! constants by name via `with_embedded_core_candidate`; tests in
//! `super::tests` walk [`embedded_core::ALL_URLS`] to verify every URL
//! has both an authored catalog candidate and a matching registry
//! insertion. Keeping all three coupled here avoids the "three-place
//! edit" trap when adding a new embedded asset.

use bevy::prelude::{App, Plugin};

use ambition_asset_manager::AssetProfile;

/// Declarative table of embedded core assets.
///
/// Each row is `NAME => "<embedded_url>" @ "<include_bytes_path>"`. The
/// macro emits:
///
/// 1. a `pub const NAME: &str = "<embedded_url>"` inside [`embedded_core`]
/// 2. an entry in [`embedded_core::ALL_URLS`]
/// 3. an `EmbeddedAssetRegistry::insert_asset(... include_bytes!(...))`
///    call inside [`register_embedded_core_assets`] (under
///    `static_core_assets`)
///
/// Adding a new embedded asset is one row in the macro — the previous
/// "three-line change" recipe collapses to a single declaration. The
/// guardrail tests still verify catalog candidates exist for each URL
/// (the third pairing, on the catalog-entry side).
///
/// `<include_bytes_path>` is interpreted relative to *this* source
/// file (`assets/sandbox_assets/embedded.rs`), so
/// `"../../../assets/foo.png"` resolves to
/// `crates/ambition_gameplay_core/assets/foo.png`.
macro_rules! embed_core_assets {
    (
        $( $name:ident => $url:literal @ $rel_path:literal ),* $(,)?
    ) => {
        pub(crate) mod embedded_core {
            //! Public URL constants for every embedded core asset.
            //! Generated by the `embed_core_assets!` macro in
            //! `super`. Catalog candidates and registry
            //! insertions both reference these constants by name.
            $( pub const $name: &str = $url; )*

            /// Every embedded core URL, in declaration order. The
            /// `embedded_core_urls_are_unique` and
            /// `embedded_core_urls_have_authored_catalog_candidates`
            /// tests walk this slice.
            #[allow(dead_code)] // Used only by tests / future packaging tools.
            pub const ALL_URLS: &[&str] = &[ $( $name ),* ];
        }

        /// Insert every embedded core asset's bytes into Bevy's
        /// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`]. Gated
        /// by `static_core_assets` because the bytes are pulled in via
        /// `include_bytes!` from `crates/ambition_gameplay_core/assets/...`.
        #[cfg(feature = "static_core_assets")]
        fn register_embedded_core_assets(app: &mut ::bevy::prelude::App) {
            use ::bevy::asset::io::embedded::EmbeddedAssetRegistry;
            use ::std::path::{Path, PathBuf};
            let embedded = app
                .world_mut()
                .resource_mut::<EmbeddedAssetRegistry>();
            $(
                embedded.insert_asset(
                    PathBuf::new(),
                    Path::new(embedded_core::$name),
                    include_bytes!($rel_path) as &[u8],
                );
            )*
        }
    };
}

embed_core_assets! {
    // ── UI fonts ────────────────────────────────────────────────────
    FONT_DIALOG_REGULAR_URL =>
        "ambition_gameplay_core/fonts/bundled/InterDisplay-Regular.otf"
        @ "../../../assets/fonts/bundled/InterDisplay-Regular.otf",
    FONT_DIALOG_SEMIBOLD_URL =>
        "ambition_gameplay_core/fonts/bundled/InterDisplay-SemiBold.otf"
        @ "../../../assets/fonts/bundled/InterDisplay-SemiBold.otf",
    FONT_DEBUG_MONO_URL =>
        "ambition_gameplay_core/fonts/bundled/JetBrainsMono-Regular.ttf"
        @ "../../../assets/fonts/bundled/JetBrainsMono-Regular.ttf",

    // ── Primary character spritesheets ──────────────────────────────
    SPRITE_PLAYER_URL =>
        "ambition_gameplay_core/sprites/player_robot_spritesheet.png"
        @ "../../../assets/sprites/player_robot_spritesheet.png",
    SPRITE_ROBOT_URL =>
        "ambition_gameplay_core/sprites/robot_spritesheet.png"
        @ "../../../assets/sprites/robot_spritesheet.png",
    SPRITE_GOBLIN_URL =>
        "ambition_gameplay_core/sprites/goblin_spritesheet.png"
        @ "../../../assets/sprites/goblin_spritesheet.png",
    SPRITE_SANDBAG_URL =>
        "ambition_gameplay_core/sprites/sandbag_spritesheet.png"
        @ "../../../assets/sprites/sandbag_spritesheet.png",

    // ── Core entity sprites ─────────────────────────────────────────
    SPRITE_CHEST_CLOSED_URL =>
        "ambition_gameplay_core/sprites/entities/chest_closed.png"
        @ "../../../assets/sprites/entities/chest_closed.png",
    SPRITE_CHEST_OPEN_URL =>
        "ambition_gameplay_core/sprites/entities/chest_open.png"
        @ "../../../assets/sprites/entities/chest_open.png",
    SPRITE_PICKUP_HEALTH_URL =>
        "ambition_gameplay_core/sprites/entities/pickup_health.png"
        @ "../../../assets/sprites/entities/pickup_health.png",
    SPRITE_PICKUP_CURRENCY_URL =>
        "ambition_gameplay_core/sprites/entities/pickup_currency.png"
        @ "../../../assets/sprites/entities/pickup_currency.png",
    SPRITE_PICKUP_ABILITY_URL =>
        "ambition_gameplay_core/sprites/entities/pickup_ability.png"
        @ "../../../assets/sprites/entities/pickup_ability.png",
    SPRITE_DOOR_ZONE_URL =>
        "ambition_gameplay_core/sprites/entities/door_zone.png"
        @ "../../../assets/sprites/entities/door_zone.png",
    SPRITE_EDGE_EXIT_URL =>
        "ambition_gameplay_core/sprites/entities/edge_exit.png"
        @ "../../../assets/sprites/entities/edge_exit.png",
    SPRITE_PROJECTILE_ENERGY_URL =>
        "ambition_gameplay_core/sprites/entities/projectile_energy.png"
        @ "../../../assets/sprites/entities/projectile_energy.png",
    SPRITE_SOLID_TILE_URL =>
        "ambition_gameplay_core/sprites/entities/solid_tile.png"
        @ "../../../assets/sprites/entities/solid_tile.png",
    SPRITE_ONE_WAY_TILE_URL =>
        "ambition_gameplay_core/sprites/entities/one_way_tile.png"
        @ "../../../assets/sprites/entities/one_way_tile.png",
    SPRITE_HAZARD_TILE_URL =>
        "ambition_gameplay_core/sprites/entities/hazard_tile.png"
        @ "../../../assets/sprites/entities/hazard_tile.png",
    SPRITE_BOSS_CORE_URL =>
        "ambition_gameplay_core/sprites/entities/boss_core.png"
        @ "../../../assets/sprites/entities/boss_core.png",
}

/// Bevy plugin that backs every URL the
/// [`super::SandboxAssetCatalog`] hands out with a real `AssetSource`.
///
/// Today this is the embedded source only: the plugin inserts every
/// installed `WorldManifest` row's LDtk JSON bytes (when the game built
/// them in) into Bevy's
/// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`] under the row's
/// `embedded_bevy_path`, matching the `EmbeddedBinary` candidate the
/// catalog authors from the same row — the pairing cannot drift.
///
/// Adding more embedded assets (sprites, fonts, audio) is a recipe:
/// 1. Add a `with_location(EmbeddedBinary, AssetLocation::embedded("ambition_gameplay_core/..."))`
///    candidate to the catalog entry.
/// 2. Add a matching `EmbeddedAssetRegistry::insert_asset(...,
///    include_bytes!(...))` call in [`register_embedded_assets`].
/// 3. Optional: extend the `static_map` feature gate or introduce a
///    separate gate (`static_fonts`, etc.) if a packaged subset is
///    desirable.
///
/// HTTP / HTTPS / IPFS source registration is a future slice; the
/// catalog already emits `https://...` URLs from authored
/// `HttpRemote` candidates, but the matching Bevy `AssetReader` isn't
/// wired yet.
///
/// ## Ordering requirement
///
/// `EmbeddedAssetRegistry` is created by Bevy's `AssetPlugin`. The
/// plugin therefore must run AFTER `DefaultPlugins`. The visible app builders
/// in `ambition_app::app` add it as the last plugin in the
/// `SandboxPresentationPlugin` install order.
pub struct AmbitionAssetSourcePlugin {
    pub profile: AssetProfile,
}

impl AmbitionAssetSourcePlugin {
    pub fn for_profile(profile: AssetProfile) -> Self {
        Self { profile }
    }
}

impl Plugin for AmbitionAssetSourcePlugin {
    fn build(&self, app: &mut App) {
        register_embedded_assets(app);
        // Future profile-conditional source registration (HTTP / IPFS /
        // user-data) hooks here.
        let _ = self.profile;
    }
}

/// Insert every embedded asset's bytes into Bevy's
/// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`] under the
/// URLs the catalog's `Embedded` candidates point at.
///
/// Two independent feature gates:
/// - `static_map` — LDtk world JSON (sandbox + intro).
/// - `static_core_assets` — UI fonts + primary character sheets + core
///   entity sprites (see [`embedded_core`] for the URL constants).
///
/// Adding a new embedded asset is a three-line change:
/// 1. add a `const FOO_URL: &str = "ambition_gameplay_core/..."` to
///    [`embedded_core`] and append it to `ALL_URLS`;
/// 2. add a matching `with_embedded_core_candidate(entry, FOO_URL)`
///    on the catalog entry;
/// 3. add an `EmbeddedAssetRegistry::insert_asset(...,
///    include_bytes!("../../../assets/..."))` call in
///    [`register_embedded_core_assets`] above.
///
/// The `embedded_core_paths_match_registration_constants` test fails
/// loudly if any one of those three pieces is missing.
#[allow(unused_variables)]
fn register_embedded_assets(app: &mut App) {
    // World JSON: every installed WorldManifest row that carries embedded
    // text registers its bytes under the row's EmbeddedBinary URL — the
    // same text the serde loader parses, so the two embedded
    // representations can never diverge.
    {
        use bevy::asset::io::embedded::EmbeddedAssetRegistry;
        use std::path::{Path, PathBuf};

        let mut embedded = app.world_mut().resource_mut::<EmbeddedAssetRegistry>();
        for source in &crate::ldtk_world::world_manifest().worlds {
            if let (Some(bevy_path), Some(text)) = (source.embedded_bevy_path, source.embedded_text)
            {
                embedded.insert_asset(PathBuf::new(), Path::new(bevy_path), text.as_bytes());
            }
        }
    }
    #[cfg(feature = "static_core_assets")]
    register_embedded_core_assets(app);
}
