"""Room debug bundle writer."""

from __future__ import annotations

import fnmatch
import json
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

from ambition_ldtk_tools.room_support.inspect import REPO_ROOT, format_summary_text, room_summary
from ambition_ldtk_tools.room_support.render import render_room_png, render_room_svg

def _matching_specs(level_id: str, repo_root: Path) -> list[Path]:
    specs_root = repo_root / "tools" / "ambition_ldtk_tools" / "specs"
    if not specs_root.exists():
        return []
    matches: list[Path] = []
    needles = [f'level_id: "{level_id}"', f'id: "{level_id}"', f'"level_id": "{level_id}"', f'"id": "{level_id}"']
    for path in specs_root.rglob("*"):
        if path.suffix.lower() not in {".ron", ".json", ".yaml", ".yml"}:
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        if any(n in text for n in needles) or level_id in path.stem:
            matches.append(path)
    return sorted(matches)


def _collect_debug_files(repo_root: Path, level_id: str, patterns: list[str]) -> list[Path]:
    debug_root = repo_root / "debug_traces"
    if not debug_root.exists():
        return []
    out: list[Path] = []
    for path in debug_root.rglob("*.json"):
        rel = path.relative_to(debug_root).as_posix()
        name = path.name
        if any(fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(rel, pat) for pat in patterns):
            out.append(path)
        elif level_id in name:
            out.append(path)
    return sorted(set(out))


def write_bundle(
    *,
    project: dict,
    ldtk: Path,
    level_id: str,
    out: Path,
    repo_root: Path,
    render_format: str = "svg",
    include_debug: bool = True,
    run_validate: bool = False,
) -> None:
    summary = room_summary(project, level_id)
    with tempfile.TemporaryDirectory(prefix="ambition-room-bundle-") as td:
        temp = Path(td)
        (temp / "room_describe.txt").write_text(format_summary_text(summary, include_entities=True))
        (temp / "room_describe.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
        if render_format == "png":
            render_room_png(project, level_id, temp / "room.png")
        else:
            (temp / "room.svg").write_text(render_room_svg(project, level_id))
        (temp / "README.txt").write_text(
            "Ambition LDtk room debug bundle\n"
            f"level={level_id}\n"
            f"ldtk={ldtk}\n"
            "Generated by: python -m ambition_ldtk_tools room bundle-debug\n"
        )
        specs = _matching_specs(level_id, repo_root)
        if specs:
            specs_dir = temp / "specs"
            specs_dir.mkdir()
            for spec in specs:
                target = specs_dir / spec.name
                target.write_bytes(spec.read_bytes())
        if include_debug:
            debug_files = _collect_debug_files(
                repo_root,
                level_id,
                [
                    "gravity_symmetry_room_failure_*.json",
                    "gravity_symmetry_room_failures/*.json",
                    "*failure*.json",
                ],
            )
            if debug_files:
                debug_dir = temp / "debug_traces"
                debug_dir.mkdir()
                for src in debug_files:
                    target = debug_dir / src.name
                    # Avoid collisions from recursive directories.
                    if target.exists():
                        target = debug_dir / (src.parent.name + "__" + src.name)
                    target.write_bytes(src.read_bytes())
        if run_validate:
            rc = subprocess.run(
                [sys.executable, "-m", "ambition_ldtk_tools.validate", str(ldtk)],
                cwd=repo_root,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            (temp / "validate.txt").write_text(rc.stdout + f"\nexit_code={rc.returncode}\n")
        out.parent.mkdir(parents=True, exist_ok=True)
        with tarfile.open(out, "w:gz") as tar:
            for path in sorted(temp.rglob("*")):
                if path.is_file():
                    tar.add(path, arcname=path.relative_to(temp))
