//! Embed gameplay-sheet manifests, portrait manifests, and packed-sheet
//! catalogs from the actor-owned generated asset tree into the built binary.
//!
//! Why a build script: the runtime registry + the `LazyLock<CharacterSheetSpec>`
//! statics used to load these via `std::fs::read_dir($CARGO_MANIFEST_DIR/
//! assets/sprites)`. That works on desktop but produces an empty index on
//! Android / wasm — the manifest path is the dev machine's absolute path,
//! which doesn't exist on the device, and assets live inside the APK /
//! served bundle instead. The empty index then panicked the first time
//! `load_spec("goblin")` (or any character sheet) was forced.
//!
//! Mirrors the runtime scan: root `assets/sprites/` plus one level of
//! subdirs (the boss multi-sheet packages live there), and the sibling
//! quality-variant folders (`sprites_0_5x`, `sprites_0_25x`, `sprites_potato`)
//! so packaged Android/web builds can resolve variant manifests too.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // NOTE: the static-SFX-bank cfg/env is configured in `ambition_app/build.rs`
    // now — a build script only affects its own crate, and the consumer
    // (`app::scene_setup`) lives in `ambition_app`.

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let asset_owner_dir = manifest_dir.join("../ambition_actors");

    let sprite_dirs = [
        asset_owner_dir.join("assets/sprites"),
        asset_owner_dir.join("assets/sprites_0_5x"),
        asset_owner_dir.join("assets/sprites_0_25x"),
        asset_owner_dir.join("assets/sprites_potato"),
    ];

    // Re-run if the directory contents shift. Cargo watches recursively
    // when handed a directory.
    for dir in &sprite_dirs {
        println!("cargo:rerun-if-changed={}", dir.display());
    }

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for sprites_dir in &sprite_dirs {
        if !sprites_dir.is_dir() {
            continue;
        }
        collect_spritesheet_rons(sprites_dir, &mut entries);
        if let Ok(subdirs) = fs::read_dir(sprites_dir) {
            for sub in subdirs.flatten() {
                let path = sub.path();
                if path.is_dir() {
                    collect_spritesheet_rons(&path, &mut entries);
                }
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("baked_sheet_rons.rs");

    let mut body = String::new();
    body.push_str("// Auto-generated by build.rs. Do not edit.\n");
    body.push_str("pub static BAKED_SHEET_RONS: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        // include_str! needs a path the rustc invocation can resolve.
        // Absolute paths from the build host are fine for `cargo build`,
        // and the build script always re-runs on the host doing the
        // compile (Android cross-compile included), so this is safe.
        let escaped_path = path.to_string_lossy().replace('\\', "\\\\");
        body.push_str(&format!(
            "    (\"{name}\", include_str!(\"{escaped_path}\")),\n",
        ));
    }
    body.push_str("];\n");

    fs::write(&out_path, body).expect("write baked_sheet_rons.rs");

    bake_portrait_manifests(&asset_owner_dir, &out_dir);
    bake_pack_catalogs(&asset_owner_dir, &out_dir);
}

/// Embed every full-resolution portrait manifest by its asset-relative path.
/// Portraits are presentation products and currently have no quality-tier
/// variants; recursive collection covers multipart character subdirectories.
fn bake_portrait_manifests(asset_owner_dir: &Path, out_dir: &Path) {
    let assets_dir = asset_owner_dir.join("assets");
    let sprites_dir = assets_dir.join("sprites");
    println!("cargo:rerun-if-changed={}", sprites_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect_portrait_rons(&sprites_dir, &assets_dir, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut body = String::new();
    body.push_str("// Auto-generated by build.rs. Do not edit.\n");
    body.push_str("pub static BAKED_PORTRAIT_RONS: &[(&str, &str)] = &[\n");
    for (asset_path, path) in &entries {
        let escaped_path = path.to_string_lossy().replace('\\', "\\\\");
        body.push_str(&format!(
            "    (\"{asset_path}\", include_str!(\"{escaped_path}\")),\n",
        ));
    }
    body.push_str("];\n");

    fs::write(out_dir.join("baked_portrait_rons.rs"), body).expect("write baked_portrait_rons.rs");
}

fn collect_portrait_rons(dir: &Path, assets_dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_portrait_rons(&path, assets_dir, out);
            continue;
        }
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !name.ends_with("_portraits.ron") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(assets_dir) else {
            continue;
        };
        let key = relative.to_string_lossy().replace('\\', "/");
        out.push((key, path));
    }
}

/// Embed each quality tier's ultrapack catalog (`assets/sprite_packs/<tier>/
/// ultrapack.json`, written by the regen ultrapack step) as a
/// `(tier, json_text)` table. Tier dir names match the runtime
/// `TextureResolutionScale` vocabulary (`full` / `half` / `quarter` /
/// `potato`). The table is empty on a checkout that never ran regen — the
/// pack consumer then falls back to the per-target sheet path.
fn bake_pack_catalogs(asset_owner_dir: &Path, out_dir: &Path) {
    let packs_dir = asset_owner_dir.join("assets/sprite_packs");
    println!("cargo:rerun-if-changed={}", packs_dir.display());

    let mut tiers: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&packs_dir) {
        for entry in entries.flatten() {
            let tier_dir = entry.path();
            let catalog = tier_dir.join("ultrapack.json");
            if tier_dir.is_dir() && catalog.is_file() {
                if let Some(tier) = tier_dir.file_name().and_then(|n| n.to_str()) {
                    tiers.push((tier.to_owned(), catalog));
                }
            }
        }
    }
    tiers.sort_by(|a, b| a.0.cmp(&b.0));

    let mut body = String::new();
    body.push_str("// Auto-generated by build.rs. Do not edit.\n");
    body.push_str("pub static BAKED_PACK_CATALOGS: &[(&str, &str)] = &[\n");
    for (tier, path) in &tiers {
        let escaped_path = path.to_string_lossy().replace('\\', "\\\\");
        body.push_str(&format!(
            "    (\"{tier}\", include_str!(\"{escaped_path}\")),\n",
        ));
    }
    body.push_str("];\n");

    fs::write(out_dir.join("baked_pack_catalogs.rs"), body).expect("write baked_pack_catalogs.rs");
}

fn collect_spritesheet_rons(dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(root) = name.strip_suffix("_spritesheet.ron") else {
            continue;
        };
        out.push((baked_key_for_path(root, &path), path));
    }
}

fn baked_key_for_path(root: &str, path: &Path) -> String {
    let marker = path
        .components()
        .filter_map(|component| component.as_os_str().to_str())
        .find_map(|component| match component {
            "sprites_0_5x" => Some("0_5x"),
            "sprites_0_25x" => Some("0_25x"),
            "sprites_potato" => Some("potato"),
            _ => None,
        });
    match marker {
        Some(marker) => format!("{root}.{marker}"),
        None => root.to_owned(),
    }
}
