//! Ambition-owned held/inventory item art registrations.
//!
//! Every ground-pickup / in-hand sprite Ambition's held items use — the axe, the
//! javelin, the gun-sword, and the wielded-gauntlet ability props — is declared
//! here as pure `id → path + size` data and contributed to the reusable render
//! layer's [`HeldItemArtManifest`](ambition_platformer2d_shared_tangle::held_item_art::HeldItemArtManifest).
//! The renderer names none of these paths; it resolves the merged manifest into
//! image handles at startup.

use ambition_platformer2d_shared_tangle::held_item_art::{HeldItemArtAppExt, HeldItemArtEntry};
use bevy::math::Vec2;
use bevy::prelude::App;

/// Wielded-gauntlet ids that draw a `sprites/props/gauntlet_<id>.png` icon — the
/// abstract abilities with no character prop. Generated by
/// `item_icons.py::write_gauntlet_props` into `sprites/props/`. The item-shaped
/// tail (bomb / grapple / …) is drawn as a physical object by
/// `item_icons.py::render_item_object`; the `fireball` prop doubles as the
/// in-flight held-shot visual.
const GAUNTLET_PROP_IDS: &[&str] = &[
    "shockwave",
    "volley",
    "beam",
    "vortex",
    "sentry",
    "dive",
    "meteor",
    "bomb",
    "grapple",
    "gravity_grenade",
    "mark_recall",
    "blink",
    "puppy_slug_gun",
    "fireball",
];

/// Contribute Ambition's held-item art declarations to the render manifest.
pub(super) fn register(app: &mut App) {
    let mut entries = vec![
        // Character props: drawn at their native aspect ratio.
        HeldItemArtEntry::new("axe", "sprites/props/axe.png", Vec2::new(40.0, 18.0)),
        HeldItemArtEntry::new("javelin", "sprites/props/javelin.png", Vec2::new(58.0, 7.0)),
        // The heavy archetype authors a distinct item id but the same gun-sword art.
        HeldItemArtEntry::new(
            "gun_sword",
            "sprites/props/gunsword.png",
            Vec2::new(54.0, 14.0),
        ),
        HeldItemArtEntry::new(
            "gun_sword_heavy",
            "sprites/props/gunsword.png",
            Vec2::new(54.0, 14.0),
        ),
        // ⭐ THE ADMIRAL'S OWN GUN-SWORD, drawn as the gun-sword it is. A
        // distinct ITEM id (its shot is a special's payoff, not a raider's
        // sidearm) wearing the same art, exactly as the heavy above does.
        HeldItemArtEntry::new(
            "admiral_gun_sword",
            "sprites/props/gunsword.png",
            Vec2::new(54.0, 14.0),
        ),
        // ⛔⛔ AND THE TWO THE POLYGON AUTHORED, because a held item with no art
        // registration is not a silent fallback — it is an `ERROR` per spawn
        // ("unknown held item art `polygon_bomb`") and an object drawn as
        // nothing. Measured on the first engine take of her new down-B, which
        // otherwise worked end to end.
        //
        // ✔ ALL THREE NOW WEAR THEIR OWN ART (they borrowed the gauntlet bomb,
        // the beacon and the javelin until 2026-09-06). The drawings live in
        // `item_icons.py::HELD_ITEM_ICON_SPECS` and are installed here by
        // `scripts/regen/sprites.sh`; each `key` there is the id on this line.
        //
        // ⭐ THE BOMB AND THE MINE ARE DRAWN TO BE TOLD APART AT A GLANCE, which
        // is a gameplay requirement and not a taste one: both are her stage
        // objects and they do opposite things. The bomb is a tall faceted hex on
        // a lit fuse; the mine is a wide low puck on anchor prongs with one red
        // eye. Silhouette carries it, so the distinction survives at 16px and in
        // the colour-blind case.
        //
        // ⚠ ALL THREE SOURCES ARE SQUARE (64×64), so these extents must stay
        // square too — the javelin's 44×6 was the shape of the art it borrowed,
        // and keeping it would have squashed the tress flat.
        HeldItemArtEntry::new(
            "polygon_bomb",
            "sprites/props/polygon_bomb.png",
            Vec2::new(18.0, 18.0),
        ),
        HeldItemArtEntry::new(
            "polygon_mine",
            "sprites/props/polygon_mine.png",
            Vec2::new(16.0, 16.0),
        ),
        HeldItemArtEntry::new(
            "polygon_ponytail",
            "sprites/props/polygon_ponytail.png",
            Vec2::new(28.0, 28.0),
        ),
    ];
    // Wielded gauntlets: a 64×64 procedural icon shown ~26px square on the
    // ground / in hand (no character prop — the ability is abstract).
    entries.extend(GAUNTLET_PROP_IDS.iter().map(|&id| {
        HeldItemArtEntry::new(
            id,
            format!("sprites/props/gauntlet_{id}.png"),
            Vec2::new(26.0, 26.0),
        )
    }));
    app.register_held_item_art(entries);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ambition_platformer2d_shared_tangle::held_item_art::HeldItemArtManifest;

    #[test]
    fn ambition_registers_its_held_item_props() {
        let mut app = App::new();
        register(&mut app);
        let manifest = app.world().resource::<HeldItemArtManifest>();
        // ⭐ THE POLYGON'S THREE ARE NAMED EXPLICITLY, because this module's own
        // note records that a missing art registration is not a silent fallback
        // — it is an `ERROR` per spawn and an object drawn as nothing, measured
        // on the first engine take of her down-B. Her mine is the third.
        for id in [
            "axe",
            "javelin",
            "gun_sword",
            "gun_sword_heavy",
            "blink",
            "polygon_bomb",
            "polygon_ponytail",
            "polygon_mine",
        ] {
            assert!(
                manifest.0.iter().any(|e| e.item_id == id),
                "{id} art must be registered"
            );
        }
    }
}
