//! Ambition-owned held/inventory item art registrations.
//!
//! Every ground-pickup / in-hand sprite Ambition's held items use — the axe, the
//! javelin, the gun-sword, and the wielded-gauntlet ability props — is declared
//! here as pure `id → path + size` data and contributed to the reusable render
//! layer's [`HeldItemArtManifest`](ambition_platformer_primitives::held_item_art::HeldItemArtManifest).
//! The renderer names none of these paths; it resolves the merged manifest into
//! image handles at startup.

use ambition_platformer_primitives::held_item_art::{HeldItemArtAppExt, HeldItemArtEntry};
use bevy::math::Vec2;
use bevy::prelude::App;

/// Wielded-gauntlet ids that draw a `sprites/props/gauntlet_<id>.png` icon — the
/// abstract abilities with no character prop. Generated by
/// `item_icons.py::write_gauntlet_props` into `sprites/props/`. The item-shaped
/// tail (bomb / grapple / …) is drawn as a physical object by
/// `item_icons.py::render_item_object`; the `fireball` prop doubles as the
/// in-flight held-shot visual.
const GAUNTLET_PROP_IDS: &[&str] = &[
    "shockwave",
    "volley",
    "beam",
    "vortex",
    "sentry",
    "dive",
    "meteor",
    "bomb",
    "grapple",
    "gravity_grenade",
    "mark_recall",
    "blink",
    "puppy_slug_gun",
    "fireball",
];

/// Contribute Ambition's held-item art declarations to the render manifest.
pub(super) fn register(app: &mut App) {
    let mut entries = vec![
        // Character props: drawn at their native aspect ratio.
        HeldItemArtEntry::new("axe", "sprites/props/axe.png", Vec2::new(40.0, 18.0)),
        HeldItemArtEntry::new("javelin", "sprites/props/javelin.png", Vec2::new(58.0, 7.0)),
        // The heavy archetype authors a distinct item id but the same gun-sword art.
        HeldItemArtEntry::new(
            "gun_sword",
            "sprites/props/gunsword.png",
            Vec2::new(54.0, 14.0),
        ),
        HeldItemArtEntry::new(
            "gun_sword_heavy",
            "sprites/props/gunsword.png",
            Vec2::new(54.0, 14.0),
        ),
    ];
    // Wielded gauntlets: a 64×64 procedural icon shown ~26px square on the
    // ground / in hand (no character prop — the ability is abstract).
    entries.extend(GAUNTLET_PROP_IDS.iter().map(|&id| {
        HeldItemArtEntry::new(
            id,
            format!("sprites/props/gauntlet_{id}.png"),
            Vec2::new(26.0, 26.0),
        )
    }));
    app.register_held_item_art(entries);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ambition_platformer_primitives::held_item_art::HeldItemArtManifest;

    #[test]
    fn ambition_registers_its_held_item_props() {
        let mut app = App::new();
        register(&mut app);
        let manifest = app.world().resource::<HeldItemArtManifest>();
        for id in ["axe", "javelin", "gun_sword", "gun_sword_heavy", "blink"] {
            assert!(
                manifest.0.iter().any(|e| e.item_id == id),
                "{id} art must be registered"
            );
        }
    }
}
