#!/usr/bin/env python3
"""Author game/ambition_demo_sanic/assets/worlds/sanic_speedway.ldtk.

The Sanic demo's level file is GENERATED by this script through the
sanctioned `ambition_ldtk_tools` pipeline (world init -> area create ->
entity add -> repair -> validate); the .ldtk JSON is never hand-edited.
Re-run from the repo root after changing the layout constants below:

    python3 game/ambition_demo_sanic/tools/author_speedway_ldtk.py

The file owns the SPATIAL layout: terrain chains (with the rolling hills
baked into the polyline), floor solids (with the pit gap), one-way
platforms, springs/boosters (ReboundPad), hazards, enemy spawns, and the
named monitor boxes. The LOOP stays code-generated in `lib.rs`
(`raised_full_loop_points`) and is grafted onto the loaded room at
runtime, because LDtk has no vocabulary for depth lanes / route junctions;
the graft anchors on floor-chain vertices this script authors at
RAMP_JUNCTION_X / RUNOUT_JUNCTION_X, and the demo's tests fail loudly if
those drift.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TOOLS = REPO / "tools" / "ambition_ldtk_tools"
TARGET = REPO / "game" / "ambition_demo_sanic" / "assets" / "worlds" / "sanic_speedway.ldtk"

# ── Layout constants (mirrored by game/ambition_demo_sanic/src/lib.rs) ──────
LEVEL_W = 6400
LEVEL_H = 720
FLOOR_TOP = 672  # LEVEL_H - 48

# Loop graft anchors: the floor chain MUST have vertices exactly here.
RAMP_JUNCTION_X = 1740
RUNOUT_JUNCTION_X = 2920

# The pit (bottomless in spirit; a hazard strip resets to spawn).
PIT_LEFT = 4000
PIT_RIGHT = 4256

# Rolling hills: two smooth sin^2 bumps rising from the flat floor.
HILL_1 = (350.0, 900.0, 90.0)  # (start_x, end_x, amplitude)
HILL_2 = (900.0, 1450.0, 70.0)
HILL_STEP = 25.0


def hill_points(start: float, end: float, amplitude: float) -> list[tuple[float, float]]:
    """Interior samples of `FLOOR_TOP - A*sin^2(pi*(x-start)/(end-start))`."""
    out = []
    x = start + HILL_STEP
    while x < end - HILL_STEP / 2:
        t = (x - start) / (end - start)
        y = FLOOR_TOP - amplitude * math.sin(math.pi * t) ** 2
        out.append((round(x, 1), round(y, 1)))
        x += HILL_STEP
    return out


def floor_route_points() -> list[tuple[float, float]]:
    pts: list[tuple[float, float]] = [(0, FLOOR_TOP), (HILL_1[0], FLOOR_TOP)]
    pts += hill_points(*HILL_1)
    pts.append((HILL_2[0], FLOOR_TOP))
    pts += hill_points(*HILL_2)
    pts += [
        (HILL_2[1], FLOOR_TOP),
        (RAMP_JUNCTION_X, FLOOR_TOP),
        (RUNOUT_JUNCTION_X, FLOOR_TOP),
        (PIT_LEFT, FLOOR_TOP),
    ]
    return pts


def points_field(points: list[tuple[float, float]]) -> str:
    return "; ".join(f"{x:g},{y:g}" for x, y in points)


def rect(kind: str, px: tuple[int, int], size: tuple[int, int], **fields) -> dict:
    entry: dict = {"type": kind, "px": list(px), "size": list(size)}
    if fields:
        entry["fields"] = fields
    return entry


def area_spec() -> dict:
    entities = [
        rect("PlayerStart", (146, 626), (28, 46), name="sanic_start"),
        # Terrain guide chains momentum bodies ride. Left route carries the
        # hills and the loop-junction anchor vertices; the pit splits it from
        # the runout route.
        rect(
            "SurfaceChain",
            (0, 656),
            (16, 16),
            name="sanic_floor_route",
            points=points_field(floor_route_points()),
            closed=False,
        ),
        rect(
            "SurfaceChain",
            (PIT_RIGHT, 656),
            (16, 16),
            name="sanic_floor_runout",
            points=points_field([(PIT_RIGHT, FLOOR_TOP), (LEVEL_W, FLOOR_TOP)]),
            closed=False,
        ),
        # Solid ground (lowered to IntGrid): split around the pit; the finish
        # tower caps the runout.
        rect("Solid", (0, FLOOR_TOP), (PIT_LEFT, 48), name="speedway_floor_west"),
        rect("Solid", (PIT_RIGHT, FLOOR_TOP), (LEVEL_W - PIT_RIGHT, 48), name="speedway_floor_east"),
        rect("Solid", (6320, 416), (32, 256), name="finish_tower"),
        # One-way platforms — every lift a plain jump must reach is <= 144px
        # (jump apex is ~169px at the authored 700px/s jump under 1450 gravity);
        # the two high ones are spring-served on purpose.
        rect("OneWayPlatform", (64, 528), (256, 16), name="start_gantry"),
        rect("OneWayPlatform", (752, 528), (112, 16), name="marker_platform_1"),
        rect("OneWayPlatform", (1552, 528), (112, 16), name="marker_platform_2"),
        rect("OneWayPlatform", (2544, 528), (112, 16), name="marker_platform_3"),
        rect("OneWayPlatform", (3552, 528), (112, 16), name="marker_platform_4"),
        rect("OneWayPlatform", (4944, 528), (112, 16), name="marker_platform_5"),
        # The spring perch is 256px up — unreachable by the ~169px jump apex,
        # exactly the point: the vertical spring below serves it. Wide enough
        # that a walk-on launch (which keeps forward momentum) still lands.
        rect("OneWayPlatform", (4560, 416), (288, 16), name="spring_perch"),
        rect("OneWayPlatform", (5392, 528), (160, 16), name="diagonal_perch"),
        # Springs and the loop feed booster (ReboundPad = the engine's pad).
        rect("ReboundPad", (1640, 650), (72, 22), impulseX=1120, impulseY=-260),
        rect("ReboundPad", (4680, 648), (48, 24), impulseX=0, impulseY=-1000),
        rect("ReboundPad", (5152, 648), (48, 24), impulseX=700, impulseY=-700),
        # Hazards: the pit floor (reset), a mid-course spike strip, and the
        # finish warning spikes.
        rect("HazardBlock", (PIT_LEFT, 704), (PIT_RIGHT - PIT_LEFT, 16), name="pit_hazard"),
        rect("HazardBlock", (5648, 656), (96, 16), name="mid_spikes"),
        rect("HazardBlock", (6144, 656), (112, 16), name="finish_warning_spikes"),
        # Badniks pace the flats (axis walkers cannot patrol chain hills yet —
        # see dev/journals/code_smells.md).
        rect("EnemySpawn", (3136, 640), (28, 32), brain="sanic_badnik"),
        rect("EnemySpawn", (3552, 640), (28, 32), brain="sanic_badnik"),
        rect("EnemySpawn", (5056, 640), (28, 32), brain="sanic_badnik"),
        rect("EnemySpawn", (5760, 640), (28, 32), brain="sanic_badnik"),
    ]
    return {
        "id": "sanic_speedway",
        "level_id": "sanic_speedway",
        "world_x": 0,
        "world_y": 0,
        "px_wid": LEVEL_W,
        "px_hei": LEVEL_H,
        "fill_collision": "empty",
        "bg_color": "#16202e",
        "entities": entities,
    }


# Monitors stay ENTITY instances (never IntGrid): the demo identifies them as
# named blocks to break + grant, so `area create`'s static-collision lowering
# must not eat their names.
MONITORS = {
    "level_id": "sanic_speedway",
    "entities": [
        rect("Solid", (1490, 646), (26, 26), name="monitor_super"),
        rect("Solid", (4650, 390), (26, 26), name="monitor_speed"),
    ],
}


def run_tool(*args: str) -> None:
    cmd = [sys.executable, "-m", "ambition_ldtk_tools", *args]
    print("::", " ".join(str(a) for a in args))
    env = {"PYTHONPATH": str(TOOLS), "PATH": "/usr/bin:/bin"}
    result = subprocess.run(cmd, cwd=REPO, env=env)
    if result.returncode != 0:
        sys.exit(f"tool step failed: {' '.join(args)}")


def main() -> None:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if TARGET.exists():
        TARGET.unlink()
    run_tool("world", "init", str(TARGET), "--identifier", "ambition-sanic-speedway-world")
    with tempfile.TemporaryDirectory() as tmp:
        spec = Path(tmp) / "sanic_speedway_area.json"
        spec.write_text(json.dumps(area_spec(), indent=2))
        run_tool("area", "create", str(spec), "--ldtk", str(TARGET))
        monitors = Path(tmp) / "sanic_speedway_monitors.json"
        monitors.write_text(json.dumps(MONITORS, indent=2))
        run_tool("entity", "add", str(monitors), "--ldtk", str(TARGET), "--in-place")
    run_tool("repair", str(TARGET), "--in-place")
    run_tool("validate", str(TARGET))
    print(f"authored {TARGET.relative_to(REPO)}")


if __name__ == "__main__":
    main()
