#!/usr/bin/env python3
"""Author game/ambition_demo_sanic/assets/worlds/sanic_speedway.ldtk.

The Sanic demo's level file is GENERATED by this script through the
sanctioned `ambition_ldtk_tools` pipeline (world init -> area create ->
entity add -> repair -> validate); the .ldtk JSON is never hand-edited.
Re-run from the repo root after changing the layout constants below:

    python3 game/ambition_demo_sanic/tools/author_speedway_ldtk.py

The file owns the SPATIAL layout: terrain chains (with the rolling hills
baked into the polyline), floor solids (with the pit gap), one-way
platforms, springs/boosters (ReboundPad), hazards, enemy spawns, and the
named monitor boxes. The LOOP stays code-generated in `lib.rs`
(`raised_full_loop_points`) and is grafted onto the loaded room at
runtime, because LDtk has no vocabulary for depth lanes / route junctions;
the graft anchors on floor-chain vertices this script authors at
RAMP_JUNCTION_X / RUNOUT_JUNCTION_X, and the demo's tests fail loudly if
those drift.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TOOLS = REPO / "tools" / "ambition_ldtk_tools"
TARGET = REPO / "game" / "ambition_demo_sanic" / "assets" / "worlds" / "sanic_speedway.ldtk"

# ── Layout constants (mirrored by game/ambition_demo_sanic/src/lib.rs) ──────
LEVEL_W = 6400
LEVEL_H = 720
FLOOR_TOP = 672  # LEVEL_H - 48

# Loop graft anchors: the floor chain MUST have vertices exactly here.
RAMP_JUNCTION_X = 1740
RUNOUT_JUNCTION_X = 2920

# The pit (bottomless in spirit; a hazard strip resets to spawn).
PIT_LEFT = 4000
PIT_RIGHT = 4256

# Rolling hills: two smooth sin^2 bumps rising from the flat floor.
HILL_1 = (350.0, 900.0, 90.0)  # (start_x, end_x, amplitude)
HILL_2 = (900.0, 1450.0, 70.0)
HILL_STEP = 25.0


def hill_points(start: float, end: float, amplitude: float) -> list[tuple[float, float]]:
    """Interior samples of `FLOOR_TOP - A*sin^2(pi*(x-start)/(end-start))`."""
    out = []
    x = start + HILL_STEP
    while x < end - HILL_STEP / 2:
        t = (x - start) / (end - start)
        y = FLOOR_TOP - amplitude * math.sin(math.pi * t) ** 2
        out.append((round(x, 1), round(y, 1)))
        x += HILL_STEP
    return out


def floor_route_points() -> list[tuple[float, float]]:
    pts: list[tuple[float, float]] = [(0, FLOOR_TOP), (HILL_1[0], FLOOR_TOP)]
    pts += hill_points(*HILL_1)
    pts.append((HILL_2[0], FLOOR_TOP))
    pts += hill_points(*HILL_2)
    pts += [
        (HILL_2[1], FLOOR_TOP),
        (RAMP_JUNCTION_X, FLOOR_TOP),
        (RUNOUT_JUNCTION_X, FLOOR_TOP),
        (PIT_LEFT, FLOOR_TOP),
    ]
    return pts


def points_field(points: list[tuple[float, float]]) -> str:
    return "; ".join(f"{x:g},{y:g}" for x, y in points)


def rect(etype: str, px: tuple[int, int], size: tuple[int, int], **fields) -> dict:
    entry: dict = {"type": etype, "px": list(px), "size": list(size)}
    if fields:
        entry["fields"] = fields
    return entry


# Rings are lowered as `currency:1` pickups: the shared collection loop credits
# the player's wallet (the ring counter), sparks, and dings — the demo adds no
# collection code. Authored at a runner's chest height so a grounded dash sweeps
# them; arcs over the hills / pit reward the fast air routes. The box is SQUARE so
# the round `sanic_ring_prop` sprite (bound demo-side) isn't stretched; `px` is
# its top-left, so a ring is centred on (cx, cy).
RING_SIZE = (30, 30)
# : The sheet each ring wears, authored on the placement.
# :
# : `PickupSpawn` does not carry a `sprite` field in the shared defs, so
# : `main()` mints one with `def update-entity` before the area is built. That
# : field reached the committed world file out-of-band once (an `entity`/`def`
# : edit run by hand), which left THIS script unable to reproduce it: a
# : regeneration silently dropped the binding from all 35 rings and they fell
# : back to the generic coin. Authoring it here is what makes the script the
# : file's only author again.
RING_SPRITE = "sanic_ring_prop"
BADNIK_CHARACTER_ID = "sanic_badnik"
BADNIK_DISPLAY_NAME = "Sanic Badnik"


def ring(cx: float, cy: float) -> dict:
    return rect(
        "PickupSpawn",
        (round(cx - RING_SIZE[0] / 2), round(cy - RING_SIZE[1] / 2)),
        RING_SIZE,
        name="ring",
        kind="currency:1",
        sprite=RING_SPRITE,
    )


def ring_line(x0: float, x1: float, cy: float, step: float = 60.0) -> list[dict]:
    out, x = [], x0
    while x <= x1 + 1e-3:
        out.append(ring(x, cy))
        x += step
    return out


def ring_arc(cx0: float, cx1: float, cy_flat: float, peak_rise: float, n: int) -> list[dict]:
    """`n` rings tracing a shallow arc that peaks `peak_rise` above `cy_flat`."""
    out = []
    for i in range(n):
        t = i / (n - 1)
        cx = cx0 + (cx1 - cx0) * t
        cy = cy_flat - peak_rise * math.sin(math.pi * t)
        out.append(ring(cx, cy))
    return out


def ring_placements() -> list[dict]:
    rings: list[dict] = []
    # Opening straight — a welcoming line the first dash runs through.
    rings += ring_line(220, 340, 632)
    # Arcs following the two rolling hills (peaks track the sin^2 bumps).
    rings += ring_arc(470, 780, 628, 66, 5)
    rings += ring_arc(950, 1400, 628, 52, 5)
    # Into the loop feed / spring at x=1640.
    rings += ring_line(1490, 1610, 632)
    # Out of the loop runout, before the first badnik at x=3136.
    rings += ring_line(2970, 3110, 632)
    # The classic reward arc over the pit (x 4000..4256) — collected by a body
    # that carries enough speed to clear the gap.
    rings += ring_arc(4020, 4236, 612, 78, 4)
    # Runout straight leading to the vertical spring at x=4680.
    rings += ring_line(4360, 4600, 632)
    # High payout on the spring_perch (y=416): only the spring reaches it.
    rings += ring_line(4630, 4790, 380)
    # Home straight before the finish (kept clear of the spike strips).
    rings += ring_line(5850, 6030, 632)
    return rings


def area_spec() -> dict:
    entities = [
        rect("PlayerStart", (146, 626), (28, 46), name="sanic_start"),
        # Terrain guide chains momentum bodies ride. Left route carries the
        # hills and the loop-junction anchor vertices; the pit splits it from
        # the runout route.
        rect(
            "SurfaceChain",
            (0, 656),
            (16, 16),
            name="sanic_floor_route",
            points=points_field(floor_route_points()),
            closed=False,
        ),
        rect(
            "SurfaceChain",
            (PIT_RIGHT, 656),
            (16, 16),
            name="sanic_floor_runout",
            points=points_field([(PIT_RIGHT, FLOOR_TOP), (LEVEL_W, FLOOR_TOP)]),
            closed=False,
        ),
        # Solid ground (lowered to IntGrid): split around the pit; the finish
        # tower caps the runout.
        rect("Solid", (0, FLOOR_TOP), (PIT_LEFT, 48), name="speedway_floor_west"),
        rect("Solid", (PIT_RIGHT, FLOOR_TOP), (LEVEL_W - PIT_RIGHT, 48), name="speedway_floor_east"),
        rect("Solid", (6320, 416), (32, 256), name="finish_tower"),
        # One-way platforms — every lift a plain jump must reach is <= 144px
        # (jump apex is ~169px at the authored 700px/s jump under 1450 gravity);
        # the two high ones are spring-served on purpose.
        rect("OneWayPlatform", (64, 528), (256, 16), name="start_gantry"),
        rect("OneWayPlatform", (752, 528), (112, 16), name="marker_platform_1"),
        rect("OneWayPlatform", (1552, 528), (112, 16), name="marker_platform_2"),
        rect("OneWayPlatform", (2544, 528), (112, 16), name="marker_platform_3"),
        rect("OneWayPlatform", (3552, 528), (112, 16), name="marker_platform_4"),
        rect("OneWayPlatform", (4944, 528), (112, 16), name="marker_platform_5"),
        # The spring perch is 256px up — unreachable by the ~169px jump apex,
        # exactly the point: the vertical spring below serves it. Wide enough
        # that a walk-on launch (which keeps forward momentum) still lands.
        rect("OneWayPlatform", (4560, 416), (288, 16), name="spring_perch"),
        rect("OneWayPlatform", (5392, 528), (160, 16), name="diagonal_perch"),
        # Springs and the loop feed booster (ReboundPad = the engine's pad).
        rect("ReboundPad", (1640, 650), (72, 22), impulseX=1120, impulseY=-260),
        rect("ReboundPad", (4680, 648), (48, 24), impulseX=0, impulseY=-1000),
        rect("ReboundPad", (5152, 648), (48, 24), impulseX=700, impulseY=-700),
        # `HazardBlock` has exactly one outcome: return the body to spawn. It lowers to IntGrid
        # value 5 → `BlockKind::Hazard` → `ResetCause::Hazard`, and no health, currency, or i-frame
        # is ever consulted. The ring shield was never broken; it was waiting for a damage event
        # that the reset road does not emit.
        #
        #  the strip is a `DamageVolume`: the engine's damage hazard, which
        # publishes an ordinary `HitEvent` and therefore reaches everything a hit
        # already means here — the wallet shield spends the rings, they burst
        # outward as real pickups, i-frames arm, and a super Sanic is untouched
        # because `update_ecs_hazards` asks `body_vulnerable` like every other
        # emitter. It also finally LOOKS like spikes: a damage volume draws
        # `hazard_spikes` while a reset block draws the flat `hazard_tile`.
        #
        # It was not a warning about the finish; it was a punishment for reaching it. Crossing
        # the line at speed carried Sanic into it and he died inside his own four-second results
        # card (room-replay triage §1, which mis-diagnosed this as running out of level —
        # measuring showed the death at x≈6130, well inside a 6400-wide course).
        rect("HazardBlock", (PIT_LEFT, 704), (PIT_RIGHT - PIT_LEFT, 16), name="pit_hazard"),
        rect("DamageVolume", (5648, 656), (96, 16), name="mid_spikes", damage=1),
        # Badniks pace the flats (axis walkers cannot patrol chain hills yet —
        # see dev/journals/code_smells.md).
        *(
            rect(
                "EnemySpawn",
                (x, 640),
                (28, 32),
                brain=BADNIK_CHARACTER_ID,
                character_id=BADNIK_CHARACTER_ID,
                name=BADNIK_DISPLAY_NAME,
            )
            for x in (3136, 3552, 5056, 5760)
        ),
    ]
    entities += ring_placements()
    return {
        "id": "sanic_speedway",
        "level_id": "sanic_speedway",
        "world_x": 0,
        "world_y": 0,
        "px_wid": LEVEL_W,
        "px_hei": LEVEL_H,
        "fill_collision": "empty",
        "bg_color": "#16202e",
        "entities": entities,
    }


# Monitors stay ENTITY instances (never IntGrid): the demo identifies them as
# named blocks to break + grant, so `area create`'s static-collision lowering
# must not eat their names.
#
# Authored `Solid`, they became walls the moment the momentum solver learned to sweep blocks while
# riding: Sanic stopped dead at x=1474 in front of the super monitor's lid at 1490, and could not
# break it because breaking requires rolling and rolling requires moving.
#
# There is a key for it."* The transformation is reachable ONLY from the Utility action (D in the
# classic preset) — a course pickup that hands it out is the thing being removed, not a thing to
# re-author at a safer position.
MONITORS = {
    "level_id": "sanic_speedway",
    "entities": [
        rect("OneWayPlatform", (4650, 390), (26, 26), name="monitor_speed"),
    ],
}


def run_tool(*args: str) -> None:
    cmd = [sys.executable, "-m", "ambition_ldtk_tools", *args]
    print("::", " ".join(str(a) for a in args))
    env = {"PYTHONPATH": str(TOOLS), "PATH": "/usr/bin:/bin"}
    result = subprocess.run(cmd, cwd=REPO, env=env)
    if result.returncode != 0:
        sys.exit(f"tool step failed: {' '.join(args)}")


def real_target() -> Path:
    """The file to GENERATE INTO, following `TARGET` if it is a symlink.

    ⛔ **`TARGET` is a tracked symlink into the `game/ambition_map_assets`
    submodule** (2026-08-08: the six LDtk worlds moved there so ~5 MB of dense
    JSON leaves every checkout, and a fresh clone reaches them through the
    links). `TARGET.unlink()` here DELETED that link and the tool chain then
    wrote a 296 KB regular file in its place — a git TYPECHANGE that puts the
    world's bytes back in the main repo and silently forks them from the
    submodule's copy. `scripts/tests/test_map_symlinks_stay_links.py` is the
    guard, and it went red the first time this script ran after the move.

    Resolving here fixes it for every step at once: `world init` creates the
    file at the REAL path, and the link above it is never touched.
    """
    return TARGET.resolve() if TARGET.is_symlink() else TARGET


def main() -> None:
    target = real_target()
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        target.unlink()
    run_tool("world", "init", str(target), "--identifier", "ambition-sanic-speedway-world")
    # `world init` clones the shared defs from sandbox.ldtk, whose `PickupSpawn`
    # has only `name` + `kind`. The rings need a third field to name their sheet,
    # and `area create` REFUSES an unknown field rather than dropping it — so the
    # def is extended before the area is built. See `RING_SPRITE`.
    run_tool(
        "def",
        "update-entity",
        "PickupSpawn",
        str(target),
        "--add-field",
        "sprite:String:",
        "--in-place",
        # the tool's own repair+validate post-pass rejects a project with no
        # levels, and at this point there are none — `area create` is the next
        # step. `main()`'s closing repair+validate covers the finished file.
        "--no-repair",
    )
    with tempfile.TemporaryDirectory() as tmp:
        spec = Path(tmp) / "sanic_speedway_area.json"
        spec.write_text(json.dumps(area_spec(), indent=2))
        run_tool("area", "create", str(spec), "--ldtk", str(target))
        monitors = Path(tmp) / "sanic_speedway_monitors.json"
        monitors.write_text(json.dumps(MONITORS, indent=2))
        run_tool("entity", "add", str(monitors), "--ldtk", str(target), "--in-place")
    run_tool("repair", str(target), "--in-place")
    run_tool("validate", str(target))
    print(f"authored {target.relative_to(REPO)}")


if __name__ == "__main__":
    main()
