#!/usr/bin/env python3
"""Author game/ambition_demo_sanic/assets/worlds/sanic_speedway.ldtk.

The Sanic demo's level file is GENERATED by this script through the
sanctioned `ambition_ldtk_tools` pipeline (world init -> area create ->
entity add -> repair -> validate); the .ldtk JSON is never hand-edited.
Re-run from the repo root after changing the layout constants below:

    python3 game/ambition_demo_sanic/tools/author_speedway_ldtk.py

The file owns the SPATIAL layout. The ground is PAINTED on the `Terrain`
layer (the rolling hills, the spike pit, the finish tower), so the editor
shows what Sanic rides. The loop is a `SurfaceLoop` whose box is its circle,
attached to the painted floor under it. Also: one-way platforms,
springs/boosters (ReboundPad), hazards, enemy spawns, and the named monitor
boxes.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TOOLS = REPO / "tools" / "ambition_ldtk_tools"
TARGET = REPO / "game" / "ambition_demo_sanic" / "assets" / "worlds" / "sanic_speedway.ldtk"
sys.path.insert(0, str(TOOLS))
from ambition_ldtk_tools import terrain  # noqa: E402

GRID = 16

# ── Layout constants (mirrored by game/ambition_demo_sanic/src/lib.rs) ──────
LEVEL_W = 6400
LEVEL_H = 816
FLOOR_TOP = 672

# The loop: its centre and radius. It attaches to the painted floor, its ramp
# rising from x = 1740 and its runout landing at x = 2920 (the SurfaceLoop's
# default spans for a 180 px loop).
LOOP_CENTRE_X = 2200
LOOP_RADIUS = 180

# The spike pit: a trench whose floor is a bed of spikes. Falling in is a HIT
# (rings burst out, or death with none); its depth is under a jump's apex
# (~169px), so a player who landed with rings jumps back out.
PIT_LEFT = 4000
PIT_RIGHT = 4256
PIT_FLOOR = 784
SPIKE_HEIGHT = 16

# Rolling hills: two smooth sin^2 bumps rising from the flat floor.
HILL_1 = (350.0, 900.0, 90.0)  # (start_x, end_x, amplitude)
HILL_2 = (900.0, 1450.0, 70.0)

# The finish tower: a wall the runner meets at the end of the course.
TOWER = (6320, 6352, 416)  # (left, right, top)


def west_profile(x: float) -> float:
    """The west ground's top: the flat floor with the two hills."""
    y = FLOOR_TOP
    for start, end, amplitude in (HILL_1, HILL_2):
        if start < x < end:
            y -= amplitude * math.sin(math.pi * (x - start) / (end - start)) ** 2
    return y


#: The painted west ground's top, as the quantizer drew it.
WEST_HEIGHTS = terrain.quantize(west_profile, 0, PIT_LEFT // GRID, GRID)
ground_y = terrain.surface(WEST_HEIGHTS, 0, GRID)


def painted() -> dict:
    """The level's painted cells: the ground on `Terrain`."""
    rows = LEVEL_H // GRID
    cells = terrain.ground(west_profile, 0, PIT_LEFT // GRID, GRID, bottom=rows)
    cells.update(terrain.ground(lambda x: PIT_FLOOR, PIT_LEFT // GRID, PIT_RIGHT // GRID, GRID, bottom=rows))
    cells.update(terrain.ground(lambda x: FLOOR_TOP, PIT_RIGHT // GRID, LEVEL_W // GRID, GRID, bottom=rows))
    left, right, top = TOWER
    for cx in range(left // GRID, right // GRID):
        for cy in range(top // GRID, FLOOR_TOP // GRID):
            cells[(cx, cy)] = terrain.FULL
    return {
        "level_id": "sanic_speedway",
        "layers": {"Terrain": [[cx, cy, v] for (cx, cy), v in sorted(cells.items())]},
    }


def surface_loop(name: str, centre_x: float, radius: float) -> dict:
    """A loop whose box is its circle, standing the speedway's rise above the
    painted floor at its ramp's foot (the converter's default approach)."""
    ramp_x = centre_x - radius * 460 / 180
    cy = ground_y(ramp_x) - radius * 84 / 180 - radius
    return rect(
        "SurfaceLoop", (round(centre_x - radius), round(cy - radius)), (round(2 * radius),) * 2,
        name=name, attach_to="terrain",
    )


def rect(etype: str, px: tuple[int, int], size: tuple[int, int], **fields) -> dict:
    entry: dict = {"type": etype, "px": list(px), "size": list(size)}
    if fields:
        entry["fields"] = fields
    return entry


# Rings are lowered as `currency:1` pickups: the shared collection loop credits
# the player's wallet (the ring counter), sparks, and dings — the demo adds no
# collection code. Authored at a runner's chest height so a grounded dash sweeps
# them; arcs over the hills / pit reward the fast air routes. The box is SQUARE so
# the round `sanic_ring_prop` sprite (bound demo-side) isn't stretched; `px` is
# its top-left, so a ring is centred on (cx, cy).
# : The same side as a ring a hit scatters (`RING_SIZE` in `src/lib.rs`); the
# : demo's `every_ring_the_speedway_places_is_the_size_a_hit_scatters` holds them together.
RING_SIZE = (18, 18)
# : The sheet each ring wears, authored on the placement.
# :
# : `PickupSpawn` does not carry a `sprite` field in the shared defs, so
# : `main()` mints one with `def update-entity` before the area is built. That
# : field reached the committed world file out-of-band once (an `entity`/`def`
# : edit run by hand), which left THIS script unable to reproduce it: a
# : regeneration silently dropped the binding from all 35 rings and they fell
# : back to the generic coin. Authoring it here is what makes the script the
# : file's only author again.
RING_SPRITE = "sanic_ring_prop"
BADNIK_CHARACTER_ID = "sanic_badnik"
BADNIK_DISPLAY_NAME = "Sanic Badnik"


def ring(cx: float, cy: float) -> dict:
    return rect(
        "PickupSpawn",
        (round(cx - RING_SIZE[0] / 2), round(cy - RING_SIZE[1] / 2)),
        RING_SIZE,
        name="ring",
        kind="currency:1",
        sprite=RING_SPRITE,
    )


def ring_line(x0: float, x1: float, cy: float, step: float = 60.0) -> list[dict]:
    out, x = [], x0
    while x <= x1 + 1e-3:
        out.append(ring(x, cy))
        x += step
    return out


def ring_arc(cx0: float, cx1: float, cy_flat: float, peak_rise: float, n: int) -> list[dict]:
    """`n` rings tracing a shallow arc that peaks `peak_rise` above `cy_flat`."""
    out = []
    for i in range(n):
        t = i / (n - 1)
        cx = cx0 + (cx1 - cx0) * t
        cy = cy_flat - peak_rise * math.sin(math.pi * t)
        out.append(ring(cx, cy))
    return out


def ring_placements() -> list[dict]:
    rings: list[dict] = []
    # Opening straight — a welcoming line the first dash runs through.
    rings += ring_line(220, 340, 632)
    # Arcs following the two rolling hills (peaks track the sin^2 bumps).
    rings += ring_arc(470, 780, 628, 66, 5)
    rings += ring_arc(950, 1400, 628, 52, 5)
    # Into the loop feed / spring at x=1640.
    rings += ring_line(1490, 1610, 632)
    # Out of the loop runout, before the first badnik at x=3136.
    rings += ring_line(2970, 3110, 632)
    # The classic reward arc over the pit (x 4000..4256) — collected by a body
    # that carries enough speed to clear the gap.
    rings += ring_arc(4020, 4236, 612, 78, 4)
    # Runout straight leading to the vertical spring at x=4680.
    rings += ring_line(4360, 4600, 632)
    # High payout on the spring_perch (y=416): only the spring reaches it.
    rings += ring_line(4630, 4790, 380)
    # Home straight before the finish (kept clear of the spike strips).
    rings += ring_line(5850, 6030, 632)
    return rings


def area_spec() -> dict:
    entities = [
        rect("PlayerStart", (146, 626), (28, 46), name="sanic_start"),
        # The ground (hills, pit, finish tower) is painted; see `painted`.
        surface_loop("sanic_loop", LOOP_CENTRE_X, LOOP_RADIUS),
        # One-way platforms — every lift a plain jump must reach is <= 144px
        # (jump apex is ~169px at the authored 700px/s jump under 1450 gravity);
        # the two high ones are spring-served on purpose.
        rect("OneWayPlatform", (64, 528), (256, 16), name="start_gantry"),
        rect("OneWayPlatform", (752, 528), (112, 16), name="marker_platform_1"),
        rect("OneWayPlatform", (1552, 528), (112, 16), name="marker_platform_2"),
        rect("OneWayPlatform", (2544, 528), (112, 16), name="marker_platform_3"),
        rect("OneWayPlatform", (3552, 528), (112, 16), name="marker_platform_4"),
        rect("OneWayPlatform", (4944, 528), (112, 16), name="marker_platform_5"),
        # The spring perch is 256px up — unreachable by the ~169px jump apex,
        # exactly the point: the vertical spring below serves it. Wide enough
        # that a walk-on launch (which keeps forward momentum) still lands.
        rect("OneWayPlatform", (4560, 416), (288, 16), name="spring_perch"),
        rect("OneWayPlatform", (5392, 528), (160, 16), name="diagonal_perch"),
        # Springs and the loop feed booster (ReboundPad = the engine's pad).
        rect("ReboundPad", (1640, 650), (72, 22), impulseX=1120, impulseY=-260),
        rect("ReboundPad", (4680, 648), (48, 24), impulseX=0, impulseY=-1000),
        rect("ReboundPad", (5152, 648), (48, 24), impulseX=700, impulseY=-700),
        # Both spike beds are `DamageVolume`s: the engine's damage hazard, which
        # publishes an ordinary `HitEvent` and so reaches everything a hit means
        # here: the wallet shield spends the rings, they burst out as real
        # pickups, i-frames arm, and a super Sanic is untouched (the volume asks
        # `body_vulnerable` like every emitter). A damage volume draws
        # `hazard_spikes`. The pit used to be a `HazardBlock`, whose one outcome
        # is a reset to spawn and which draws a flat tile: it looked like a hole
        # and cost nothing but the run.
        rect(
            "DamageVolume",
            (PIT_LEFT, PIT_FLOOR - SPIKE_HEIGHT),
            (PIT_RIGHT - PIT_LEFT, SPIKE_HEIGHT),
            name="pit_spikes",
            damage=1,
        ),
        rect("DamageVolume", (5648, 656), (96, 16), name="mid_spikes", damage=1),
        # Badniks. They ride the surface solver, so a badnik walks the hills
        # like Sanic does and turns back at the pit's lip.
        *(
            rect(
                "EnemySpawn",
                (x, 640),
                (28, 32),
                brain=BADNIK_CHARACTER_ID,
                character_id=BADNIK_CHARACTER_ID,
                name=BADNIK_DISPLAY_NAME,
            )
            for x in (3136, 3552, 5056, 5760)
        ),
    ]
    entities += ring_placements()
    return {
        "id": "sanic_speedway",
        "level_id": "sanic_speedway",
        "world_x": 0,
        "world_y": 0,
        "px_wid": LEVEL_W,
        "px_hei": LEVEL_H,
        "fill_collision": "empty",
        "bg_color": "#16202e",
        "entities": entities,
    }


# Monitors stay ENTITY instances (never IntGrid): the demo identifies them as
# named blocks to break + grant, so `area create`'s static-collision lowering
# must not eat their names.
#
# Authored `Solid`, they became walls the moment the momentum solver learned to sweep blocks while
# riding: Sanic stopped dead at x=1474 in front of the super monitor's lid at 1490, and could not
# break it because breaking requires rolling and rolling requires moving.
#
# There is a key for it."* The transformation is reachable ONLY from the Utility action (D in the
# classic preset) — a course pickup that hands it out is the thing being removed, not a thing to
# re-author at a safer position.
MONITORS = {
    "level_id": "sanic_speedway",
    "entities": [
        rect("OneWayPlatform", (4650, 390), (26, 26), name="monitor_speed"),
    ],
}


def run_tool(*args: str) -> None:
    cmd = [sys.executable, "-m", "ambition_ldtk_tools", *args]
    print("::", " ".join(str(a) for a in args))
    env = {"PYTHONPATH": str(TOOLS), "PATH": "/usr/bin:/bin"}
    result = subprocess.run(cmd, cwd=REPO, env=env)
    if result.returncode != 0:
        sys.exit(f"tool step failed: {' '.join(args)}")


def real_target() -> Path:
    """The file to GENERATE INTO, following `TARGET` if it is a symlink.

    ⛔ **`TARGET` is a tracked symlink into the `game/ambition_map_assets`
    submodule** (2026-08-08: the six LDtk worlds moved there so ~5 MB of dense
    JSON leaves every checkout, and a fresh clone reaches them through the
    links). `TARGET.unlink()` here DELETED that link and the tool chain then
    wrote a 296 KB regular file in its place — a git TYPECHANGE that puts the
    world's bytes back in the main repo and silently forks them from the
    submodule's copy. `scripts/tests/test_map_symlinks_stay_links.py` is the
    guard, and it went red the first time this script ran after the move.

    Resolving here fixes it for every step at once: `world init` creates the
    file at the REAL path, and the link above it is never touched.
    """
    return TARGET.resolve() if TARGET.is_symlink() else TARGET


def main() -> None:
    target = real_target()
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        target.unlink()
    run_tool("world", "init", str(target), "--identifier", "ambition-sanic-speedway-world")
    # `world init` clones the shared defs from sandbox.ldtk, whose `PickupSpawn`
    # has only `name` + `kind`. The rings need a third field to name their sheet,
    # and `area create` REFUSES an unknown field rather than dropping it — so the
    # def is extended before the area is built. See `RING_SPRITE`.
    run_tool(
        "def",
        "update-entity",
        "PickupSpawn",
        str(target),
        "--add-field",
        "sprite:String:",
        "--in-place",
        # the tool's own repair+validate post-pass rejects a project with no
        # levels, and at this point there are none — `area create` is the next
        # step. `main()`'s closing repair+validate covers the finished file.
        "--no-repair",
    )
    with tempfile.TemporaryDirectory() as tmp:
        spec = Path(tmp) / "sanic_speedway_area.json"
        spec.write_text(json.dumps(area_spec(), indent=2))
        run_tool("area", "create", str(spec), "--ldtk", str(target))
        monitors = Path(tmp) / "sanic_speedway_monitors.json"
        monitors.write_text(json.dumps(MONITORS, indent=2))
        run_tool("entity", "add", str(monitors), "--ldtk", str(target), "--in-place")
        cells = Path(tmp) / "sanic_speedway_terrain.json"
        cells.write_text(json.dumps(painted()))
        run_tool("terrain", "paint", str(cells), "--ldtk", str(target))
    # A loop's box is its circle: loops live on their own layer, under the rest.
    run_tool("entity", "change-layer", str(target), "--identifier", "SurfaceLoop",
             "--from-layer", "Ambition", "--to-layer", "AmbitionLoops", "--in-place")
    # Where this act's goal leads: Act 2 (`author_highway_ldtk.py`).
    run_tool("level", "add-field-def", "next_room", "--type", "String", str(target), "--in-place")
    run_tool(
        "level", "set-field", "--ldtk", str(target), "--level", "sanic_speedway",
        "--set", "next_room=sanic_highway", "--in-place",
    )
    run_tool("repair", str(target), "--in-place")
    run_tool("validate", str(target))
    print(f"authored {target.relative_to(REPO)}")


if __name__ == "__main__":
    main()
