//! Game asset wiring with fallback-friendly loading.
//!
//! The sandbox loads two layers of art on top of its colored-rectangle
//! placeholders:
//!
//! - **Character spritesheets** (robot/goblin/boss) — animated, owned by
//!   `character_sprites`. Loaded here to keep all asset config in one place.
//! - **Entity sprites** — single-image placeholders for chests, pickups,
//!   breakables, hazards, NPCs, blocks, loading zones, and so on. Their
//!   identity/path is emitted by
//!   `python -m ambition_sprite2d_renderer draw-entities` as
//!   `entity_manifest.yaml` next to the generated PNGs.
//! - **Background/parallax layers** — biome-specific sky and atmosphere
//!   plates generated by `python -m ambition_parallax_renderer`, intentionally
//!   outside the sprite asset folder.
//!
//! Two design rules:
//!
//! 1. **The game must always run.** Every asset is `Option<Handle<Image>>`;
//!    if a PNG is missing on disk the rendering layer falls back to its
//!    legacy colored rectangle. The `--no-assets` CLI flag forces every
//!    handle to `None` regardless of disk state, so designers can sanity-
//!    check the placeholder visuals at any moment.
//! 2. **Asset *source* is pluggable.** Today's loader walks the
//!    `assets/<sprite_folder>/` directory; a future loader can synthesize
//!    `Image` assets at runtime and insert them into `Assets<Image>` —
//!    callers only see `GameAssets` and don't care where handles came from.
//!    To make that swap painless we go through the high-level `GameAssets`
//!    struct rather than baking specific paths into call sites.

use ambition_engine as ae;
use bevy::prelude::*;
use std::collections::HashMap;

use ambition_asset_manager::{
    AmbitionAssetCatalog, AssetEntry, AssetId, AssetKind, AssetManifest, AssetProfile,
    MissingAssetPolicy, PreloadGroup,
};

use crate::boss_sprites::{self, BossSpriteAsset};
use crate::character_sprites::{self, CharacterSpriteAssets};
use crate::features::FeatureVisualKind;
use crate::rooms::{LoadingZoneActivation, RoomMetadata};

/// Pick a sensible default [`AssetProfile`] for the current build target.
///
/// - wasm32 → [`AssetProfile::WebStatic`] (today's first-pass browser
///   build embeds the LDtk bootstrap; optional sprite/parallax PNGs
///   aren't packaged yet, so the catalog skips them and the rendering
///   layer paints colored rectangles).
/// - Android → [`AssetProfile::AndroidBundle`] (Bevy's Android
///   AssetReader pulls from the APK).
/// - everything else → [`AssetProfile::DesktopDevLoose`] (assumes a
///   workspace-relative `assets/` directory; supports hot reload via
///   the loose-filesystem source).
///
/// `cargo run --bin sandbox -- --no-assets` overrides to [`AssetProfile::NoAssets`]
/// via [`GameAssetConfig::from_arg_slice`].
pub fn default_asset_profile() -> AssetProfile {
    if cfg!(target_arch = "wasm32") {
        AssetProfile::WebStatic
    } else if cfg!(target_os = "android") {
        AssetProfile::AndroidBundle
    } else {
        AssetProfile::DesktopDevLoose
    }
}

/// CLI/runtime configuration for asset loading. Inserted as a Bevy resource
/// before the presentation startup system runs.
#[derive(Resource, Clone, Debug)]
pub struct GameAssetConfig {
    /// When true, skip every disk asset load and force colored-rectangle
    /// placeholders everywhere. Set via the `--no-assets` CLI flag.
    /// Equivalent to setting `asset_profile = AssetProfile::NoAssets`;
    /// kept as a separate flag so the existing "rendering with
    /// placeholders only" log line is preserved.
    pub no_assets: bool,
    /// Directory under `assets/` that holds character + entity sprites.
    /// Default `"sprites"`. Lets designers point at experimental sets
    /// without recompiling.
    pub sprite_folder: String,
    /// Active [`AssetProfile`] for catalog resolution. Defaults from
    /// [`default_asset_profile`] (per-target cfg). `--no-assets` flips
    /// it to [`AssetProfile::NoAssets`].
    pub asset_profile: AssetProfile,
}

impl Default for GameAssetConfig {
    fn default() -> Self {
        Self {
            no_assets: false,
            sprite_folder: "sprites".into(),
            asset_profile: default_asset_profile(),
        }
    }
}

impl GameAssetConfig {
    /// Parse the supported flags out of process args. Unknown args are left
    /// alone (Bevy may consume some itself).
    pub fn from_args() -> Self {
        let args: Vec<String> = std::env::args().skip(1).collect();
        Self::from_arg_slice(&args)
    }

    /// Parse the supported flags out of an explicit arg slice. Unit-testable
    /// counterpart of `from_args` that doesn't read `env::args`.
    pub fn from_arg_slice(args: &[String]) -> Self {
        let mut config = Self::default();
        let mut i = 0;
        while i < args.len() {
            match args[i].as_str() {
                "--no-assets" => {
                    config.no_assets = true;
                    // Keep the asset profile in sync so the catalog
                    // resolver reports every entry as Disabled too.
                    config.asset_profile = AssetProfile::NoAssets;
                }
                "--sprite-folder" => {
                    if let Some(folder) = args.get(i + 1) {
                        config.sprite_folder = folder.clone();
                        i += 1;
                    }
                }
                _ => {}
            }
            i += 1;
        }
        config
    }
}

/// Single-frame entity sprites keyed off the gen2d manifest.
///
/// Every variant maps to `entities/<lower_snake_case>.png` under the
/// configured sprite folder. Adding a new entry here only requires a path
/// in `relative_path` — loading is data-driven.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum EntitySprite {
    // Features
    ChestClosed,
    ChestOpen,
    BreakableIntact,
    BreakableCracked,
    BreakableBroken,
    PickupHealth,
    PickupCurrency,
    PickupAbility,
    HazardSpikes,
    NpcTerminal,
    BossCore,
    SandbagDummy,
    // Blocks / surfaces
    SolidBlock,
    OneWayPlatform,
    SoftBlinkWall,
    HardBlinkWall,
    PogoOrb,
    ReboundPad,
    MovingPlatform,
    // Loading zones
    DoorZone,
    EdgeExit,
    // Player projectiles (Fireball + Hadouken share the same sprite)
    ProjectileEnergy,
    // 32×32 tile sprites for IntGrid-derived block surfaces. Rendered
    // via `Sprite::image_mode = Tiled` so they REPEAT across the
    // arbitrary aspect ratios that long floors / tall walls produce,
    // instead of stretching one sprite across the whole footprint.
    SolidTile,
    OneWayTile,
    HazardTile,
    SoftBlinkTile,
    HardBlinkTile,
    /// Visual for the encounter-driven "lock wall" block that
    /// `sync_lock_walls` inserts into `world.blocks` while an
    /// encounter is in flight. Uses a dedicated tile so it reads as
    /// "this just appeared" rather than blending into adjacent walls.
    LockWallTile,
}

impl EntitySprite {
    /// Path relative to the configured sprite folder.
    pub const fn relative_path(self) -> &'static str {
        match self {
            Self::ChestClosed => "entities/chest_closed.png",
            Self::ChestOpen => "entities/chest_open.png",
            Self::BreakableIntact => "entities/breakable_intact.png",
            Self::BreakableCracked => "entities/breakable_cracked.png",
            Self::BreakableBroken => "entities/breakable_broken.png",
            Self::PickupHealth => "entities/pickup_health.png",
            Self::PickupCurrency => "entities/pickup_currency.png",
            Self::PickupAbility => "entities/pickup_ability.png",
            Self::HazardSpikes => "entities/hazard_spikes.png",
            Self::NpcTerminal => "entities/npc_terminal.png",
            Self::BossCore => "entities/boss_core.png",
            Self::SandbagDummy => "entities/sandbag_dummy.png",
            Self::SolidBlock => "entities/solid_block.png",
            Self::OneWayPlatform => "entities/one_way_platform.png",
            Self::SoftBlinkWall => "entities/soft_blink_wall.png",
            Self::HardBlinkWall => "entities/hard_blink_wall.png",
            Self::PogoOrb => "entities/pogo_orb.png",
            Self::ReboundPad => "entities/rebound_pad.png",
            Self::MovingPlatform => "entities/moving_platform.png",
            Self::DoorZone => "entities/door_zone.png",
            Self::EdgeExit => "entities/edge_exit.png",
            Self::ProjectileEnergy => "entities/projectile_energy.png",
            Self::SolidTile => "entities/solid_tile.png",
            Self::OneWayTile => "entities/one_way_tile.png",
            Self::HazardTile => "entities/hazard_tile.png",
            Self::SoftBlinkTile => "entities/soft_blink_tile.png",
            Self::HardBlinkTile => "entities/hard_blink_tile.png",
            Self::LockWallTile => "entities/lock_wall_tile.png",
        }
    }

    pub const ALL: &'static [Self] = &[
        Self::ChestClosed,
        Self::ChestOpen,
        Self::BreakableIntact,
        Self::BreakableCracked,
        Self::BreakableBroken,
        Self::PickupHealth,
        Self::PickupCurrency,
        Self::PickupAbility,
        Self::HazardSpikes,
        Self::NpcTerminal,
        Self::BossCore,
        Self::SandbagDummy,
        Self::SolidBlock,
        Self::OneWayPlatform,
        Self::SoftBlinkWall,
        Self::HardBlinkWall,
        Self::PogoOrb,
        Self::ReboundPad,
        Self::MovingPlatform,
        Self::DoorZone,
        Self::EdgeExit,
        Self::ProjectileEnergy,
        Self::SolidTile,
        Self::OneWayTile,
        Self::HazardTile,
        Self::SoftBlinkTile,
        Self::HardBlinkTile,
        Self::LockWallTile,
    ];
}

/// Stable [`AssetId`] for an [`EntitySprite`].
///
/// The id namespace is `sprite.entity.<lower_snake>` — part of the
/// public asset-catalog contract. Changing the format silently would
/// invalidate authored manifests, so the per-variant suffix mapping is
/// pinned by the test
/// [`tests::every_entity_sprite_has_a_unique_asset_id_in_sprite_entity_namespace`].
pub fn entity_sprite_asset_id(key: EntitySprite) -> AssetId {
    let suffix = match key {
        EntitySprite::ChestClosed => "chest_closed",
        EntitySprite::ChestOpen => "chest_open",
        EntitySprite::BreakableIntact => "breakable_intact",
        EntitySprite::BreakableCracked => "breakable_cracked",
        EntitySprite::BreakableBroken => "breakable_broken",
        EntitySprite::PickupHealth => "pickup_health",
        EntitySprite::PickupCurrency => "pickup_currency",
        EntitySprite::PickupAbility => "pickup_ability",
        EntitySprite::HazardSpikes => "hazard_spikes",
        EntitySprite::NpcTerminal => "npc_terminal",
        EntitySprite::BossCore => "boss_core",
        EntitySprite::SandbagDummy => "sandbag_dummy",
        EntitySprite::SolidBlock => "solid_block",
        EntitySprite::OneWayPlatform => "one_way_platform",
        EntitySprite::SoftBlinkWall => "soft_blink_wall",
        EntitySprite::HardBlinkWall => "hard_blink_wall",
        EntitySprite::PogoOrb => "pogo_orb",
        EntitySprite::ReboundPad => "rebound_pad",
        EntitySprite::MovingPlatform => "moving_platform",
        EntitySprite::DoorZone => "door_zone",
        EntitySprite::EdgeExit => "edge_exit",
        EntitySprite::ProjectileEnergy => "projectile_energy",
        EntitySprite::SolidTile => "solid_tile",
        EntitySprite::OneWayTile => "one_way_tile",
        EntitySprite::HazardTile => "hazard_tile",
        EntitySprite::SoftBlinkTile => "soft_blink_tile",
        EntitySprite::HardBlinkTile => "hard_blink_tile",
        EntitySprite::LockWallTile => "lock_wall_tile",
    };
    AssetId::new(format!("sprite.entity.{suffix}"))
}

/// Stable [`AssetId`] for a parallax background layer.
///
/// Namespace: `background.parallax.<theme>.<layer>` — same shape as
/// the existing relative path `backgrounds/parallax_layers/{theme}_{layer}.png`
/// but flattened into a dotted logical id.
pub fn parallax_layer_asset_id(theme: ParallaxTheme, layer: ParallaxLayerAsset) -> AssetId {
    AssetId::new(format!(
        "background.parallax.{}.{}",
        theme.key(),
        layer.key(),
    ))
}

/// Build the sandbox's optional-image manifest: every [`EntitySprite`]
/// plus every `(ParallaxTheme, ParallaxLayerAsset)` pair, keyed by
/// stable logical ids and pointed at the configured `sprite_folder` /
/// the canonical `backgrounds/parallax_layers/` tree.
///
/// All entries are optional — [`MissingAssetPolicy::SilentPlaceholder`]
/// so the rendering layer's colored-rectangle fallback fires for any
/// asset Bevy fails to locate. Preload groups:
///
/// - Entity sprites → [`PreloadGroup::SandboxCore`] (used everywhere)
/// - Parallax layers → [`PreloadGroup::Zone`] (per-room art)
///
/// The function is `pub` so tests + future tools (e.g. a content
/// validator) can introspect the registered ids without going through
/// Bevy. Live image loading consumes it through
/// [`load_game_assets`] / [`load_entity_sprites`] / [`load_parallax_layers`].
pub fn sandbox_image_manifest(sprite_folder: &str) -> AssetManifest {
    let mut manifest = AssetManifest::new();
    for &sprite in EntitySprite::ALL {
        let id = entity_sprite_asset_id(sprite);
        let logical_path = format!("{sprite_folder}/{}", sprite.relative_path());
        manifest.insert(
            AssetEntry::new(id, AssetKind::Image, logical_path)
                .with_missing_policy(MissingAssetPolicy::SilentPlaceholder)
                .with_preload_group(PreloadGroup::SandboxCore),
        );
    }
    for &theme in ParallaxTheme::ALL {
        for &layer in ParallaxLayerAsset::ALL {
            let id = parallax_layer_asset_id(theme, layer);
            let logical_path = layer.relative_path(theme);
            manifest.insert(
                AssetEntry::new(id, AssetKind::Image, logical_path)
                    .with_missing_policy(MissingAssetPolicy::SilentPlaceholder)
                    .with_preload_group(PreloadGroup::Zone),
            );
        }
    }
    manifest
}

/// Convenience: wrap [`sandbox_image_manifest`] in a Bevy-side catalog
/// resource. Constructed per [`load_game_assets`] call so a future
/// `--sprite-folder` toggle re-resolves cleanly.
pub fn build_sandbox_image_catalog(sprite_folder: &str) -> AmbitionAssetCatalog {
    AmbitionAssetCatalog::new(sandbox_image_manifest(sprite_folder))
}

/// Map from `EntitySprite` to its loaded `Handle<Image>`. Missing handles
/// (file absent on disk OR no-asset mode) simply aren't keyed, so callers
/// just consult `get(...) -> Option<&Handle<Image>>`.
#[derive(Default, Clone)]
pub struct EntitySpriteSet {
    handles: HashMap<EntitySprite, Handle<Image>>,
}

impl EntitySpriteSet {
    pub fn get(&self, key: EntitySprite) -> Option<&Handle<Image>> {
        self.handles.get(&key)
    }

    pub fn len(&self) -> usize {
        self.handles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.handles.is_empty()
    }
}

/// Biome/theme key for generated parallax layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxTheme {
    Hub,
    Lab,
    Basement,
    Cove,
    Skybridge,
    Boss,
    Water,
    Forest,
    Cave,
}

impl ParallaxTheme {
    pub const ALL: &'static [Self] = &[
        Self::Hub,
        Self::Lab,
        Self::Basement,
        Self::Cove,
        Self::Skybridge,
        Self::Boss,
        Self::Water,
        Self::Forest,
        Self::Cave,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Hub => "hub",
            Self::Lab => "lab",
            Self::Basement => "basement",
            Self::Cove => "cove",
            Self::Skybridge => "skybridge",
            Self::Boss => "boss",
            Self::Water => "water",
            Self::Forest => "forest",
            Self::Cave => "cave",
        }
    }

    pub fn from_room_metadata(metadata: &RoomMetadata) -> Self {
        // Explicit room visual profiles are the preferred authoring seam for
        // real rooms. `visual_profile` is a stable id, while `parallax_theme`
        // chooses the generated art stack directly.
        if let Some(theme) = metadata
            .visual_profile
            .parallax_theme
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }
        if let Some(theme) = metadata
            .visual_profile
            .id
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }

        // Compatibility fallback for older rooms that only have loose metadata.
        // New authored content should set visual_profile/parallax_theme instead
        // of relying on these heuristic mappings.
        for value in [
            metadata.music_track.as_deref(),
            metadata.biome.as_deref(),
            metadata.ambient_profile.as_deref(),
            metadata.visual_theme.as_deref(),
        ]
        .into_iter()
        .flatten()
        {
            let key = value.trim().to_ascii_lowercase().replace('-', "_");
            if key.contains("ninja") || key.contains("dojo") || key.contains("forest") {
                return Self::Forest;
            }
        }
        if let Some(theme) = metadata.biome.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.visual_theme.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.ambient_profile.as_deref().and_then(Self::from_key) {
            return theme;
        }
        Self::Hub
    }

    fn from_key(value: &str) -> Option<Self> {
        let key = value.trim().to_ascii_lowercase().replace('-', "_");
        match key.as_str() {
            "hub" | "default" | "cantina" | "orange" => Some(Self::Hub),
            "lab" | "laboratory" | "teal" => Some(Self::Lab),
            "basement" | "ruins" | "pink" => Some(Self::Basement),
            "cove" | "coast" | "beach" => Some(Self::Cove),
            "skybridge" | "sky" | "blue" => Some(Self::Skybridge),
            "boss" | "mob_arena" | "arena" => Some(Self::Boss),
            "water" | "underwater" | "tide" => Some(Self::Water),
            "forest" | "woods" | "grove" | "bamboo" | "dojo" | "ninja" | "ninja_dojo" => {
                Some(Self::Forest)
            }
            "cave" | "damp" => Some(Self::Cave),
            _ => None,
        }
    }
}

/// Generated background/parallax image key.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxLayerAsset {
    /// Mostly opaque biome sky/backdrop. This is what prevents the room from
    /// falling back to a transparent-on-grid-only look.
    Sky,
    FarBackplate,
    NearBackground,
    ForegroundAtmosphere,
}

impl ParallaxLayerAsset {
    pub const ALL: &'static [Self] = &[
        Self::Sky,
        Self::FarBackplate,
        Self::NearBackground,
        Self::ForegroundAtmosphere,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Sky => "sky",
            Self::FarBackplate => "far_backplate",
            Self::NearBackground => "near_background",
            Self::ForegroundAtmosphere => "foreground_atmosphere",
        }
    }

    pub fn relative_path(self, theme: ParallaxTheme) -> String {
        format!(
            "backgrounds/parallax_layers/{}_{}.png",
            theme.key(),
            self.key()
        )
    }
}

/// Map from generated background/parallax layer keys to loaded image handles.
#[derive(Default, Clone)]
pub struct ParallaxLayerSet {
    handles: HashMap<(ParallaxTheme, ParallaxLayerAsset), Handle<Image>>,
}

impl ParallaxLayerSet {
    pub fn get(&self, theme: ParallaxTheme, layer: ParallaxLayerAsset) -> Option<&Handle<Image>> {
        self.handles.get(&(theme, layer))
    }

    pub fn len(&self) -> usize {
        self.handles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.handles.is_empty()
    }
}

/// All image-handle assets the sandbox knows about. Inserted as a Bevy
/// resource by the presentation startup system; consumed by rendering
/// systems via [`get`]-style accessors that always tolerate `None`.
#[derive(Resource, Default, Clone)]
pub struct GameAssets {
    pub characters: CharacterSpriteAssets,
    pub entities: EntitySpriteSet,
    /// Boss spritesheet — separate from `characters` because the boss
    /// generator emits its own animation rows
    /// (rest/floor_slam/side_sweep/spike_halo/dash_echo/hit/death) that
    /// don't fit `CharacterAnim`. `None` falls back to the static
    /// `EntitySprite::BossCore` image.
    pub boss: Option<BossSpriteAsset>,
    /// Mockingbird boss spritesheet — different generator (the
    /// standalone PIL-based mockingbird tool) with a 6-row layout
    /// (hover / thrust / bite / slash / hit / death). The rendering
    /// layer dispatches on the boss's authored name to pick this
    /// asset; other bosses fall back to `boss`.
    pub mockingbird: Option<BossSpriteAsset>,
    /// Optional generated biome sky/background/parallax layers. Missing PNGs
    /// are fine: room rendering simply skips the extra layers and keeps the
    /// existing clear-color/grid/block visuals.
    pub parallax_layers: ParallaxLayerSet,
}

/// Build a fresh `GameAssets`, honoring `config` + the shared
/// [`SandboxAssetCatalog`] resource.
///
/// All path/existence/profile policy goes through `catalog`; this
/// function only assembles the `GameAssets` struct from the catalog's
/// resolutions + a few Bevy `AssetServer::load` calls. `config.no_assets
/// == true` (and the equivalent `AssetProfile::NoAssets`) short-circuits
/// to an empty `GameAssets` so the visible sandbox always boots.
pub fn load_game_assets(
    config: &GameAssetConfig,
    catalog: &crate::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    layouts: &mut Assets<TextureAtlasLayout>,
) -> GameAssets {
    if config.no_assets {
        eprintln!("[game_assets] --no-assets in effect: rendering with colored-rectangle placeholders only");
        return GameAssets::default();
    }

    let characters = character_sprites::load_character_sprites_in(catalog, asset_server, layouts);
    let entities = load_entity_sprites(catalog, asset_server);
    let boss = boss_sprites::load_boss_sprite_in(catalog, asset_server, layouts);
    let mockingbird = boss_sprites::load_mockingbird_sprite_in(catalog, asset_server, layouts);
    let parallax_layers = load_parallax_layers(catalog, asset_server);

    let missing = EntitySprite::ALL.len() - entities.len();
    if missing > 0 {
        eprintln!(
            "[game_assets] {missing}/{} entity sprites missing under assets/{}/ — those entities use colored rectangles. Drop matching files in to enable them.",
            EntitySprite::ALL.len(),
            config.sprite_folder,
        );
    }

    GameAssets {
        characters,
        entities,
        boss,
        mockingbird,
        parallax_layers,
    }
}

fn load_entity_sprites(
    catalog: &crate::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
) -> EntitySpriteSet {
    let mut handles = HashMap::with_capacity(EntitySprite::ALL.len());
    for &key in EntitySprite::ALL {
        let id = entity_sprite_asset_id(key);
        let Some(path) = catalog.try_path_for_load(&id) else {
            continue;
        };
        handles.insert(key, asset_server.load(path));
    }
    EntitySpriteSet { handles }
}

fn load_parallax_layers(
    catalog: &crate::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
) -> ParallaxLayerSet {
    let mut handles = HashMap::new();
    for &theme in ParallaxTheme::ALL {
        for &layer in ParallaxLayerAsset::ALL {
            let id = parallax_layer_asset_id(theme, layer);
            let Some(path) = catalog.try_path_for_load(&id) else {
                continue;
            };
            handles.insert((theme, layer), asset_server.load(path));
        }
    }
    if !handles.is_empty() {
        eprintln!(
            "[game_assets] loaded {}/{} generated background/parallax layers under assets/backgrounds/parallax_layers/",
            handles.len(),
            ParallaxTheme::ALL.len() * ParallaxLayerAsset::ALL.len(),
        );
    }
    ParallaxLayerSet { handles }
}

/// Whether the loader should hand `path` to Bevy's `AssetServer::load`
/// for an *optional* image (entity sprites, parallax layers). Decides
/// per-[`AssetProfile`] without any `target_os` cfg branches.
///
/// Forwards to [`crate::sandbox_assets::SandboxAssetCatalog::should_attempt_optional_load`]
/// for the live decision; kept as a thin wrapper for the existing test
/// surface in this module. New code should call the catalog method
/// directly.
///
/// - Desktop profiles (DevLoose / Installed / SteamDeck): pre-check the
///   host filesystem so missing optional art falls back to colored
///   rectangles before Bevy logs a load failure.
/// - Bundled / mobile profiles (Android / iOS): trust the packager and
///   let Bevy's platform `AssetReader` try the load. A missing asset
///   here is a packaging mistake, not a content-author concern.
/// - Web / bundled-static / IPFS profiles: optional sprite/parallax
///   PNGs aren't packaged with these builds today, so skip the load
///   entirely. The rendering layer paints colored rectangles. A future
///   slice can author per-asset explicit candidates to opt back in
///   once packaging lands.
/// - NoAssets / Headless: the catalog already returned `None` upstream;
///   the arms are here only for match exhaustiveness.
// `should_attempt_optional_image_load` and `desktop_loose_file_exists`
// moved to `crate::sandbox_assets` so the SandboxAssetCatalog owns the
// only per-profile load gate + the only host-filesystem probe. See
// `SandboxAssetCatalog::should_attempt_optional_load`.

/// Build a `Sprite` for the given entity-sprite key, falling back to the
/// supplied colored-rectangle if the handle is missing. Render size always
/// equals `size`, so block/feature spawns can pass through their authored
/// AABB without rewriting.
pub fn entity_sprite(
    assets: &GameAssets,
    key: EntitySprite,
    size: Vec2,
    fallback_color: Color,
) -> Sprite {
    match assets.entities.get(key) {
        Some(handle) => {
            let mut sprite = Sprite::from_image(handle.clone());
            sprite.custom_size = Some(size);
            sprite
        }
        None => Sprite::from_color(fallback_color, size),
    }
}

/// Same as [`entity_sprite`] but `kind` is optional — `None` always falls
/// through to the colored rectangle. Useful for call sites that map a
/// runtime kind (e.g. `BlockKind`) to an `Option<EntitySprite>` because
/// some variants don't have a dedicated sprite.
pub fn entity_sprite_or_color(
    assets: &GameAssets,
    key: Option<EntitySprite>,
    size: Vec2,
    fallback_color: Color,
) -> Sprite {
    match key.and_then(|k| assets.entities.get(k)) {
        Some(handle) => {
            let mut sprite = Sprite::from_image(handle.clone());
            sprite.custom_size = Some(size);
            sprite
        }
        None => Sprite::from_color(fallback_color, size),
    }
}

/// Resolve the entity sprite to use at SPAWN time based on the engine's
/// authored room object. Stateless choice — the runtime sync system swaps
/// the sprite later for state-driven kinds (chest open, breakable cracked).
pub fn entity_sprite_for_room_object(kind: &ae::RoomObjectKind) -> Option<EntitySprite> {
    match kind {
        ae::RoomObjectKind::DamageVolume(_) => Some(EntitySprite::HazardSpikes),
        ae::RoomObjectKind::Pickup(p) => Some(pickup_sprite(&p.kind)),
        ae::RoomObjectKind::Chest(_) => Some(EntitySprite::ChestClosed),
        ae::RoomObjectKind::Breakable(_) => Some(EntitySprite::BreakableIntact),
        ae::RoomObjectKind::Interactable(interactable)
            if matches!(interactable.kind, ae::InteractionKind::Npc { .. }) =>
        {
            Some(EntitySprite::NpcTerminal)
        }
        ae::RoomObjectKind::EnemySpawn(ae::EnemyBrain::Custom(name))
            if name.starts_with("sandbag_") =>
        {
            Some(EntitySprite::SandbagDummy)
        }
        ae::RoomObjectKind::BossSpawn(_) => Some(EntitySprite::BossCore),
        // Enemies use the goblin spritesheet (animated), not a static
        // entity sprite — `upgrade_enemy_sprites` handles them.
        _ => None,
    }
}

fn pickup_sprite(kind: &ae::PickupKind) -> EntitySprite {
    match kind {
        ae::PickupKind::Health { .. } => EntitySprite::PickupHealth,
        ae::PickupKind::Currency { .. } => EntitySprite::PickupCurrency,
        ae::PickupKind::Ability { .. } => EntitySprite::PickupAbility,
        // StoryFlag and Custom fall back to the ability look until they
        // get dedicated art.
        _ => EntitySprite::PickupAbility,
    }
}

/// State-aware sprite for a breakable based on its current health state.
pub fn breakable_state_sprite(state: ae::BreakableState) -> EntitySprite {
    match state {
        ae::BreakableState::Intact => EntitySprite::BreakableIntact,
        ae::BreakableState::Cracking => EntitySprite::BreakableCracked,
        ae::BreakableState::Broken | ae::BreakableState::Respawning => {
            EntitySprite::BreakableBroken
        }
    }
}

/// State-aware sprite for a chest by opened-flag.
pub fn chest_state_sprite(opened: bool) -> EntitySprite {
    if opened {
        EntitySprite::ChestOpen
    } else {
        EntitySprite::ChestClosed
    }
}

/// Block-kind sprites. `BlockKind::Hazard` reuses the hazard-spikes art.
pub fn block_sprite(kind: ae::BlockKind) -> Option<EntitySprite> {
    match kind {
        ae::BlockKind::Solid => Some(EntitySprite::SolidBlock),
        ae::BlockKind::OneWay => Some(EntitySprite::OneWayPlatform),
        ae::BlockKind::Hazard => Some(EntitySprite::HazardSpikes),
        ae::BlockKind::PogoOrb => Some(EntitySprite::PogoOrb),
        ae::BlockKind::Rebound { .. } => Some(EntitySprite::ReboundPad),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Soft,
        } => Some(EntitySprite::SoftBlinkWall),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Hard,
        } => Some(EntitySprite::HardBlinkWall),
    }
}

/// Tile-sprite variant of `block_sprite` for IntGrid-derived blocks.
/// Returns the seamless 32×32 tile texture that the renderer should
/// REPEAT (via `Sprite::image_mode = Tiled`) across the block's
/// arbitrary aspect ratio. Returns `None` for kinds that don't have
/// a tile generator yet (PogoOrb / Rebound — those are point-shaped
/// authored entities, not tiled surfaces).
pub fn block_tile_sprite(kind: ae::BlockKind) -> Option<EntitySprite> {
    match kind {
        ae::BlockKind::Solid => Some(EntitySprite::SolidTile),
        ae::BlockKind::OneWay => Some(EntitySprite::OneWayTile),
        ae::BlockKind::Hazard => Some(EntitySprite::HazardTile),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Soft,
        } => Some(EntitySprite::SoftBlinkTile),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Hard,
        } => Some(EntitySprite::HardBlinkTile),
        // PogoOrb / Rebound stay on the entity-art path because they
        // are point objects, not tiled surfaces. Authored as single
        // entities with fixed-aspect art.
        _ => None,
    }
}

/// Loading-zone sprites — cosmetic, the actual zone behavior comes from
/// the gameplay layer.
pub fn loading_zone_sprite(activation: LoadingZoneActivation) -> EntitySprite {
    match activation {
        LoadingZoneActivation::Door => EntitySprite::DoorZone,
        LoadingZoneActivation::EdgeExit => EntitySprite::EdgeExit,
        // `Walk` zones (mid-room walk-through portals) reuse the
        // EdgeExit sprite for now — both are overlap-triggered, no
        // interact prompt. A dedicated portal-glow sprite can land
        // when art does.
        LoadingZoneActivation::Walk => EntitySprite::EdgeExit,
    }
}

/// Map a `FeatureVisualKind` to a default entity sprite, ignoring per-
/// instance state. Used as a backstop when the engine kind isn't known
/// in detail (e.g. inside `sync_visuals`).
pub fn entity_sprite_for_kind(kind: FeatureVisualKind) -> Option<EntitySprite> {
    match kind {
        FeatureVisualKind::Hazard => Some(EntitySprite::HazardSpikes),
        FeatureVisualKind::Sandbag => Some(EntitySprite::SandbagDummy),
        FeatureVisualKind::Boss => Some(EntitySprite::BossCore),
        FeatureVisualKind::Breakable => Some(EntitySprite::BreakableIntact),
        FeatureVisualKind::Chest => Some(EntitySprite::ChestClosed),
        FeatureVisualKind::Pickup => Some(EntitySprite::PickupHealth),
        FeatureVisualKind::Npc => Some(EntitySprite::NpcTerminal),
        // Enemies are animated; rendering handles them through the
        // character spritesheet, not a static entity sprite.
        FeatureVisualKind::Enemy => None,
        // Switches render as a colored block (red / green) rather
        // than a static entity sprite — see `feature_color` and
        // `switch_on_color` in `rendering.rs`.
        FeatureVisualKind::Switch => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(slice: &[&str]) -> Vec<String> {
        slice.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn default_config_loads_assets_from_sprites_folder() {
        let c = GameAssetConfig::default();
        assert!(!c.no_assets);
        assert_eq!(c.sprite_folder, "sprites");
    }

    #[test]
    fn no_assets_flag_forces_placeholder_mode() {
        let c = GameAssetConfig::from_arg_slice(&args(&["--no-assets"]));
        assert!(c.no_assets);
        assert_eq!(c.sprite_folder, "sprites", "folder unaffected");
        // --no-assets must also flip the catalog profile so the resolver
        // returns Disabled for every entry. Otherwise a future call site
        // that consults the catalog (without the no_assets early-return)
        // would still get a Bevy path.
        assert_eq!(c.asset_profile, AssetProfile::NoAssets);
    }

    #[test]
    fn default_config_uses_target_cfg_asset_profile() {
        // The default profile is cfg-driven (Desktop on dev hosts).
        // Tests run on the host architecture; assert against the same
        // expression to lock in the wiring.
        let c = GameAssetConfig::default();
        assert_eq!(c.asset_profile, default_asset_profile());
    }

    #[test]
    fn sprite_folder_flag_overrides_default() {
        let c = GameAssetConfig::from_arg_slice(&args(&["--sprite-folder", "experimental"]));
        assert!(!c.no_assets);
        assert_eq!(c.sprite_folder, "experimental");
    }

    #[test]
    fn unknown_flags_are_left_alone() {
        // Bevy may consume args itself; the parser ignores anything unknown.
        let c = GameAssetConfig::from_arg_slice(&args(&["--bevy-flag", "--no-assets"]));
        assert!(c.no_assets);
    }

    #[test]
    fn sprite_folder_flag_without_value_is_a_noop() {
        // Trailing flag with no folder argument: keep the default.
        let c = GameAssetConfig::from_arg_slice(&args(&["--sprite-folder"]));
        assert_eq!(c.sprite_folder, "sprites");
    }

    /// Every `EntitySprite::ALL` variant has a stable, unique `AssetId`
    /// in the `sprite.entity.*` namespace. Catches accidental id
    /// collisions and namespace drift.
    #[test]
    fn every_entity_sprite_has_a_unique_asset_id_in_sprite_entity_namespace() {
        let mut seen = std::collections::HashSet::new();
        for &sprite in EntitySprite::ALL {
            let id = entity_sprite_asset_id(sprite);
            assert!(
                id.as_str().starts_with("sprite.entity."),
                "{sprite:?} id `{id}` not in sprite.entity.* namespace",
            );
            assert!(seen.insert(id.clone()), "duplicate asset id for {sprite:?}: `{id}`");
        }
        // Lock the chest_closed variant by name so refactors that
        // change the snake_case scheme don't go unnoticed.
        assert_eq!(
            entity_sprite_asset_id(EntitySprite::ChestClosed).as_str(),
            "sprite.entity.chest_closed",
        );
    }

    /// Every parallax `(theme, layer)` pair has a stable, unique id in
    /// the `background.parallax.<theme>.<layer>` namespace.
    #[test]
    fn every_parallax_layer_has_a_unique_asset_id() {
        let mut seen = std::collections::HashSet::new();
        for &theme in ParallaxTheme::ALL {
            for &layer in ParallaxLayerAsset::ALL {
                let id = parallax_layer_asset_id(theme, layer);
                assert!(
                    id.as_str().starts_with("background.parallax."),
                    "{:?}/{:?} id `{id}` not in background.parallax.* namespace",
                    theme,
                    layer,
                );
                assert!(seen.insert(id.clone()), "duplicate parallax id: `{id}`");
            }
        }
    }

    /// The full sandbox image manifest has exactly one entry per
    /// `EntitySprite::ALL` variant + one per `(theme, layer)`, no
    /// duplicates, and every entry has the `Image` kind.
    #[test]
    fn sandbox_image_manifest_registers_every_entity_and_parallax_entry() {
        let manifest = sandbox_image_manifest("sprites");
        let expected =
            EntitySprite::ALL.len() + ParallaxTheme::ALL.len() * ParallaxLayerAsset::ALL.len();
        assert_eq!(
            manifest.len(),
            expected,
            "manifest len mismatch (entity={} parallax={}x{}={})",
            EntitySprite::ALL.len(),
            ParallaxTheme::ALL.len(),
            ParallaxLayerAsset::ALL.len(),
            ParallaxTheme::ALL.len() * ParallaxLayerAsset::ALL.len(),
        );
        for &sprite in EntitySprite::ALL {
            let id = entity_sprite_asset_id(sprite);
            let entry = manifest
                .get(&id)
                .unwrap_or_else(|| panic!("manifest missing {sprite:?}"));
            assert!(matches!(entry.kind, ambition_asset_manager::AssetKind::Image));
        }
        for &theme in ParallaxTheme::ALL {
            for &layer in ParallaxLayerAsset::ALL {
                let id = parallax_layer_asset_id(theme, layer);
                let entry = manifest
                    .get(&id)
                    .unwrap_or_else(|| panic!("manifest missing {theme:?}/{layer:?}"));
                assert!(matches!(entry.kind, ambition_asset_manager::AssetKind::Image));
            }
        }
    }

    /// The catalog under `DesktopDevLoose` produces the exact path
    /// strings the prior raw-path loader would have built. Locks in
    /// migration parity for every entity sprite + every parallax layer.
    #[test]
    fn catalog_paths_match_legacy_loader_paths_under_desktop_dev_loose() {
        let catalog = build_sandbox_image_catalog("sprites");
        let profile = AssetProfile::DesktopDevLoose;

        for &sprite in EntitySprite::ALL {
            let id = entity_sprite_asset_id(sprite);
            let path = catalog
                .path_for(&id, profile)
                .unwrap_or_else(|| panic!("desktop catalog missing path for {sprite:?}"));
            assert_eq!(
                path,
                format!("sprites/{}", sprite.relative_path()),
                "{sprite:?} path drift",
            );
        }
        for &theme in ParallaxTheme::ALL {
            for &layer in ParallaxLayerAsset::ALL {
                let id = parallax_layer_asset_id(theme, layer);
                let path = catalog
                    .path_for(&id, profile)
                    .unwrap_or_else(|| panic!("desktop catalog missing {theme:?}/{layer:?}"));
                assert_eq!(path, layer.relative_path(theme), "{theme:?}/{layer:?} path drift");
            }
        }
    }

    /// `--sprite-folder custom_sprites` propagates through the catalog
    /// so the resolved entity-sprite paths point at the override
    /// directory. Parallax layers live under a fixed `backgrounds/`
    /// path independent of `--sprite-folder` and must not move.
    #[test]
    fn sprite_folder_flag_propagates_through_catalog() {
        let catalog = build_sandbox_image_catalog("custom_sprites");
        let id = entity_sprite_asset_id(EntitySprite::ChestClosed);
        let path = catalog
            .path_for(&id, AssetProfile::DesktopDevLoose)
            .unwrap();
        assert_eq!(
            path,
            format!("custom_sprites/{}", EntitySprite::ChestClosed.relative_path()),
        );
        // Parallax layers don't follow --sprite-folder; verify the
        // override doesn't accidentally remap their path.
        let parallax_id = parallax_layer_asset_id(ParallaxTheme::Hub, ParallaxLayerAsset::Sky);
        assert_eq!(
            catalog
                .path_for(&parallax_id, AssetProfile::DesktopDevLoose)
                .unwrap(),
            ParallaxLayerAsset::Sky.relative_path(ParallaxTheme::Hub),
        );
    }

    /// `NoAssets` profile reports every entry as Disabled, so
    /// `path_for` returns `None` and the loaders insert no handles —
    /// the same outcome the `--no-assets` early-return produces.
    #[test]
    fn no_assets_profile_disables_every_image_in_the_manifest() {
        let catalog = build_sandbox_image_catalog("sprites");
        for &sprite in EntitySprite::ALL {
            let id = entity_sprite_asset_id(sprite);
            assert!(
                catalog.path_for(&id, AssetProfile::NoAssets).is_none(),
                "{sprite:?} not disabled under NoAssets",
            );
        }
        for &theme in ParallaxTheme::ALL {
            for &layer in ParallaxLayerAsset::ALL {
                let id = parallax_layer_asset_id(theme, layer);
                assert!(
                    catalog.path_for(&id, AssetProfile::NoAssets).is_none(),
                    "{theme:?}/{layer:?} not disabled under NoAssets",
                );
            }
        }
    }

    /// WebStatic synthesizes `embedded://` URLs for every entry;
    /// `SandboxAssetCatalog::should_attempt_optional_load` then skips
    /// them today (optional sprites aren't packaged into the wasm
    /// bundle yet), preserving the colored-rectangle fallback.
    #[test]
    fn web_static_synthesizes_embedded_scheme_but_loader_skips_today() {
        use crate::sandbox_assets::SandboxAssetCatalog;

        let inner = build_sandbox_image_catalog("sprites");
        let catalog = SandboxAssetCatalog::new(inner, AssetProfile::WebStatic);
        let id = entity_sprite_asset_id(EntitySprite::ChestClosed);
        let path = catalog.path_for(&id).unwrap();
        assert_eq!(
            path,
            format!(
                "embedded://sprites/{}",
                EntitySprite::ChestClosed.relative_path()
            ),
        );
        assert!(
            !catalog.should_attempt_optional_load(&path),
            "WebStatic optional images must skip the load until packaging lands",
        );
    }

    /// The per-profile load gate matches the legacy desktop / android
    /// behavior exactly. Locks in the migration contract documented in
    /// `SandboxAssetCatalog::should_attempt_optional_load`.
    #[test]
    fn should_attempt_optional_load_matches_legacy_per_profile_behavior() {
        use crate::sandbox_assets::SandboxAssetCatalog;
        let inner = build_sandbox_image_catalog("sprites");

        // Android / iOS bundles trust the packager — always attempt.
        for profile in [AssetProfile::AndroidBundle, AssetProfile::IosBundle] {
            let catalog = SandboxAssetCatalog::new(inner.clone(), profile);
            assert!(catalog.should_attempt_optional_load("sprites/x.png"));
        }
        // Web / bundled / IPFS skip optional images entirely today.
        for profile in [
            AssetProfile::WebStatic,
            AssetProfile::WebHttp,
            AssetProfile::BundledStatic,
            AssetProfile::IpfsGatewayPlaceholder,
        ] {
            let catalog = SandboxAssetCatalog::new(inner.clone(), profile);
            assert!(!catalog.should_attempt_optional_load("sprites/x.png"));
        }
        // NoAssets / Headless never attempt.
        for profile in [AssetProfile::NoAssets, AssetProfile::Headless] {
            let catalog = SandboxAssetCatalog::new(inner.clone(), profile);
            assert!(!catalog.should_attempt_optional_load("sprites/x.png"));
        }
        // Desktop profiles pre-check; pass a path that definitely
        // doesn't exist under any of the candidate roots.
        for profile in [
            AssetProfile::DesktopDevLoose,
            AssetProfile::DesktopInstalled,
            AssetProfile::SteamDeckInstalled,
        ] {
            let catalog = SandboxAssetCatalog::new(inner.clone(), profile);
            assert!(!catalog
                .should_attempt_optional_load("sprites/__nonexistent_test_asset_for_load_gate__.png"));
        }
        // Conversely, an asset that DOES exist under CARGO_MANIFEST_DIR/assets/
        // (the workspace cargo-test fallback) should pass the desktop
        // gate. Use the sandbox.ron data file the test crate always ships.
        let catalog = SandboxAssetCatalog::new(inner, AssetProfile::DesktopDevLoose);
        assert!(catalog.should_attempt_optional_load("ambition/sandbox.ron"));
    }

    #[test]
    fn entity_sprite_for_kind_handles_all_visual_kinds() {
        // Sanity: every FeatureVisualKind variant returns something
        // (either Some(sprite) or an explicit None for animated/dynamic
        // visuals). Ensures a new variant doesn't silently reach the
        // pattern-match catch-all and break the visual layer.
        for kind in [
            FeatureVisualKind::Hazard,
            FeatureVisualKind::Sandbag,
            FeatureVisualKind::Boss,
            FeatureVisualKind::Breakable,
            FeatureVisualKind::Chest,
            FeatureVisualKind::Pickup,
            FeatureVisualKind::Npc,
        ] {
            assert!(
                entity_sprite_for_kind(kind).is_some(),
                "static sprite expected for {kind:?}"
            );
        }
        assert!(entity_sprite_for_kind(FeatureVisualKind::Enemy).is_none());
        assert!(entity_sprite_for_kind(FeatureVisualKind::Switch).is_none());
    }
}
