#!/usr/bin/env python3
"""Can anything walk the FIELDS of the rollback-canonical state generically?

⭐⭐ THE QUESTION THIS SETTLES, and it settles a design rather than reporting a
count. A guard over the canonical state — "no finite-typed field is NaN after a
tick" — must enumerate FIELDS. A hand-written list of types is the failure mode
that guard exists to avoid: it reports on whatever it happens to name, and the
snapshot codec writes fields no grep sees. So the guard needs a GENERIC road, and
Rust offers exactly three:

    Reflect     `#[derive(Reflect)]` + `register_type::<T>()`, walked through
                `AppTypeRegistry`
    Serialize   `serde`, walked as a generic value tree
    SnapshotState  the repo's own canonical encoding — `encode(&self, &mut Vec<u8>)`

⛔⛔ MEASURED 2026-09-10: **440 canonical type names in the rollback schema. ZERO
are registered for reflection. THREE derive `Serialize`.** The whole repository
makes 19 `register_type::<>` calls and not one of them is a canonical type. And
`SnapshotState::encode` writes OPAQUE BYTES — it is the authority on what is in
the snapshot and it cannot say which of those bytes were an `f32`.

⇒ There is no generic field walk over this state today. A per-field guard costs a
derive across ~440 types, or a typed field-walk added to `SnapshotState`. Either
is a packet; neither is a guard. ⚠ A guard written without one is a hand list
wearing a census's clothes, and it will report exactly what its author already
suspected.

⚠ WHAT THIS CANNOT SEE: it reads the COMMITTED schema baseline, not a live
registry, so a registration added since the baseline was written is missing here
and `the_rollback_schema_matches_its_recorded_baseline` is what keeps the two
honest. The derive check reads the eight lines above each definition, so a derive
spelled further up, generated by a macro, or written as a manual `impl` is not
counted — which makes the Serialize/Reflect figures a LOWER BOUND and the
conclusion stronger, not weaker.

    python3 scripts/measure_canonical_state_field_reachability.py
    python3 scripts/measure_canonical_state_field_reachability.py --list-serialize
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
BASELINE = REPO / "game/ambition_app/tests/rollback_schema_baseline.txt"
DERIVE_WINDOW = 8


def canonical_type_names() -> set[str]:
    """The TYPE column of the recorded rollback schema."""
    names = set()
    for line in BASELINE.read_text(encoding="utf-8").split("\n"):
        parts = line.split("\t")
        if len(parts) >= 3:
            name = parts[2].strip()
            # A type, not a wire key or a prose column.
            if re.match(r"^[A-Z][A-Za-z0-9_]*$", name):
                names.add(name)
    return names


def definitions(names: set[str]) -> dict[str, tuple[str, int]]:
    if not names:
        return {}
    pattern = r"^(pub )?(struct|enum) (" + "|".join(re.escape(n) for n in sorted(names)) + r")\b"
    found: dict[str, tuple[str, int]] = {}
    out = subprocess.run(
        ["git", "grep", "-n", "-E", pattern], cwd=REPO, capture_output=True, text=True
    ).stdout
    for line in out.split("\n"):
        if not line.strip():
            continue
        path, lineno, text = line.split(":", 2)
        match = re.search(r"(?:struct|enum)\s+([A-Za-z0-9_]+)", text)
        if match:
            found.setdefault(match.group(1), (path, int(lineno)))
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list-serialize", action="store_true")
    args = parser.parse_args()

    names = canonical_type_names()
    found = definitions(names)

    registered = set(
        re.findall(
            r"register_type::<\s*([A-Za-z0-9_:]+)",
            subprocess.run(
                ["git", "grep", "-h", "register_type::<"], cwd=REPO, capture_output=True, text=True
            ).stdout,
        )
    )
    registered_leaf = {r.split("::")[-1] for r in registered}

    serialize, reflect = [], []
    cache: dict[str, list[str]] = {}
    for name, (path, lineno) in found.items():
        if path not in cache:
            cache[path] = (REPO / path).read_text(encoding="utf-8", errors="ignore").split("\n")
        head = "\n".join(cache[path][max(0, lineno - DERIVE_WINDOW) : lineno - 1])
        if "Serialize" in head:
            serialize.append(name)
        if "Reflect" in head:
            reflect.append(name)

    print("⛔ CAN ANYTHING WALK THE CANONICAL STATE'S FIELDS GENERICALLY?\n")
    print(f"   canonical type names in the recorded schema   {len(names)}")
    print(f"   definitions located                           {len(found)}")
    print(f"   registered for REFLECTION                     {len(set(found) & registered_leaf)}")
    print(f"   deriving SERIALIZE                            {len(serialize)}")
    print(f"   deriving REFLECT                              {len(reflect)}")
    print(f"\n   `register_type::<>` calls in the whole repo   {len(registered)}")
    if args.list_serialize and serialize:
        print("\n   the Serialize few:")
        for name in sorted(serialize):
            print(f"      {name}  ({found[name][0]}:{found[name][1]})")

    print("\n⇒ THE CONCLUSION, and it is a design fact rather than a score:")
    print("   no generic field walk over the canonical state exists today.")
    print("   `SnapshotState::encode` is the authority on what is IN the snapshot and")
    print("   writes opaque bytes; it cannot say which of them were an `f32`.")
    print("   A per-field guard therefore costs a derive across the whole canonical")
    print("   set, or a typed field-walk added to `SnapshotState`. Either is a")
    print("   PACKET. A guard written without one is a hand list wearing a census's")
    print("   clothes.")
    print("\n⛔ WHAT THIS CANNOT SEE")
    print("   * It reads the COMMITTED baseline, not a live registry.")
    print("     `the_rollback_schema_matches_its_recorded_baseline` keeps those honest.")
    print(f"   * The derive check reads {DERIVE_WINDOW} lines above each definition, so a")
    print("     derive further up, macro-generated, or a manual `impl` is not counted.")
    print("     ⇒ the Serialize/Reflect figures are a LOWER BOUND, which makes the")
    print("     conclusion stronger rather than weaker.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
