//! Game asset wiring with fallback-friendly loading.
//!
//! The sandbox loads two layers of art on top of its colored-rectangle
//! placeholders:
//!
//! - **Character spritesheets** (robot/goblin/boss) — animated, owned by
//!   `character_sprites`. Loaded here to keep all asset config in one place.
//! - **Entity sprites** — single-image placeholders for chests, pickups,
//!   breakables, hazards, NPCs, blocks, loading zones, and so on. Their
//!   identity/path is emitted by
//!   `python -m ambition_sprite2d_renderer draw-entities` as
//!   `entity_manifest.yaml` next to the generated PNGs.
//! - **Background/parallax layers** — biome-specific sky and atmosphere
//!   plates generated by `python -m ambition_parallax_renderer`, intentionally
//!   outside the sprite asset folder.
//!
//! Two design rules:
//!
//! 1. **The game must always run.** Every asset is `Option<Handle<Image>>`;
//!    if a PNG is missing on disk the rendering layer falls back to its
//!    legacy colored rectangle. The `--no-assets` CLI flag forces every
//!    handle to `None` regardless of disk state, so designers can sanity-
//!    check the placeholder visuals at any moment.
//! 2. **Asset *source* is pluggable.** Today's loader walks the
//!    `assets/<sprite_folder>/` directory; a future loader can synthesize
//!    `Image` assets at runtime and insert them into `Assets<Image>` —
//!    callers only see `GameAssets` and don't care where handles came from.
//!    To make that swap painless we go through the high-level `GameAssets`
//!    struct rather than baking specific paths into call sites.

use crate::engine_core as ae;
use bevy::prelude::*;
use std::collections::HashMap;

use ambition_asset_manager::{
    AmbitionAssetCatalog, AssetEntry, AssetId, AssetKind, AssetManifest, AssetProfile,
    MissingAssetPolicy, PreloadGroup,
};

use crate::boss_encounter::sprites::{self, BossSpriteAsset};
use crate::features::FeatureVisualKind;
use crate::character_sprites::{self, CharacterSpriteAssets};
use crate::rooms::{LoadingZoneActivation, RoomMetadata};

/// Pick a sensible default [`AssetProfile`] for the current build target.
///
/// - wasm32 → [`AssetProfile::WebStatic`] (today's first-pass browser
///   build embeds the LDtk bootstrap; optional sprite/parallax PNGs
///   aren't packaged yet, so the catalog skips them and the rendering
///   layer paints colored rectangles).
/// - Android → [`AssetProfile::AndroidBundle`] (Bevy's Android
///   AssetReader pulls from the APK).
/// - everything else → [`AssetProfile::DesktopDevLoose`] (assumes a
///   workspace-relative `assets/` directory; supports hot reload via
///   the loose-filesystem source).
///
/// `cargo run --bin sandbox -- --no-assets` overrides to [`AssetProfile::NoAssets`]
/// via [`GameAssetConfig::from_arg_slice`].
pub fn default_asset_profile() -> AssetProfile {
    if cfg!(target_arch = "wasm32") {
        if cfg!(feature = "web_served") {
            // Build composed `--features web_served_assets` →
            // browser fetches `/assets/*` over HTTP.
            AssetProfile::WebServedAssets
        } else {
            // Build composed `--features web` → only assets with an
            // authored `EmbeddedBinary` candidate are attempted.
            AssetProfile::WebStatic
        }
    } else if cfg!(target_os = "android") {
        AssetProfile::AndroidBundle
    } else {
        AssetProfile::DesktopDevLoose
    }
}

/// CLI/runtime configuration for asset loading. Inserted as a Bevy resource
/// before the presentation startup system runs.
#[derive(Resource, Clone, Debug)]
pub struct GameAssetConfig {
    /// When true, skip every disk asset load and force colored-rectangle
    /// placeholders everywhere. Set via the `--no-assets` CLI flag.
    /// Equivalent to setting `asset_profile = AssetProfile::NoAssets`;
    /// kept as a separate flag so the existing "rendering with
    /// placeholders only" log line is preserved.
    pub no_assets: bool,
    /// Directory under `assets/` that holds character + entity sprites.
    /// Default `"sprites"`. Lets designers point at experimental sets
    /// without recompiling.
    pub sprite_folder: String,
    /// Active [`AssetProfile`] for catalog resolution. Defaults from
    /// [`default_asset_profile`] (per-target cfg). `--no-assets` flips
    /// it to [`AssetProfile::NoAssets`].
    pub asset_profile: AssetProfile,
}

impl Default for GameAssetConfig {
    fn default() -> Self {
        Self {
            no_assets: false,
            sprite_folder: "sprites".into(),
            asset_profile: default_asset_profile(),
        }
    }
}

impl GameAssetConfig {
    /// Parse the supported flags out of process args. Unknown args are left
    /// alone (Bevy may consume some itself).
    pub fn from_args() -> Self {
        let args: Vec<String> = std::env::args().skip(1).collect();
        Self::from_arg_slice(&args)
    }

    /// Parse the supported flags out of an explicit arg slice. Unit-testable
    /// counterpart of `from_args` that doesn't read `env::args`.
    pub fn from_arg_slice(args: &[String]) -> Self {
        let mut config = Self::default();
        let mut i = 0;
        while i < args.len() {
            match args[i].as_str() {
                "--no-assets" => {
                    config.no_assets = true;
                    // Keep the asset profile in sync so the catalog
                    // resolver reports every entry as Disabled too.
                    config.asset_profile = AssetProfile::NoAssets;
                }
                "--sprite-folder" => {
                    if let Some(folder) = args.get(i + 1) {
                        config.sprite_folder = folder.clone();
                        i += 1;
                    }
                }
                _ => {}
            }
            i += 1;
        }
        config
    }
}

/// Single-frame entity sprites keyed off the gen2d manifest.
///
/// Every variant maps to `entities/<lower_snake_case>.png` under the
/// configured sprite folder. Adding a new entry here only requires a path
/// in `relative_path` — loading is data-driven.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum EntitySprite {
    // Features
    ChestClosed,
    ChestOpen,
    BreakableIntact,
    BreakableCracked,
    BreakableBroken,
    PickupHealth,
    PickupCurrency,
    PickupAbility,
    HazardSpikes,
    NpcTerminal,
    BossCore,
    SandbagDummy,
    // Switch on/off — chosen state-aware in `state_aware_entity_sprite` by the
    // `FeatureView::switch_on` flag (armed = on, disabled = off).
    SwitchArmed,
    SwitchDisabled,
    // Blocks / surfaces
    SolidBlock,
    OneWayPlatform,
    SoftBlinkWall,
    HardBlinkWall,
    PogoOrb,
    ReboundPad,
    MovingPlatform,
    // Loading zones
    DoorZone,
    EdgeExit,
    // Player projectiles (Fireball + Hadouken share the same sprite)
    ProjectileEnergy,
    // 32×32 tile sprites for IntGrid-derived block surfaces. Rendered
    // via `Sprite::image_mode = Tiled` so they REPEAT across the
    // arbitrary aspect ratios that long floors / tall walls produce,
    // instead of stretching one sprite across the whole footprint.
    SolidTile,
    OneWayTile,
    HazardTile,
    SoftBlinkTile,
    HardBlinkTile,
    /// Visual for the encounter-driven "lock wall" block that
    /// `sync_lock_walls` inserts into `world.blocks` while an
    /// encounter is in flight. Uses a dedicated tile so it reads as
    /// "this just appeared" rather than blending into adjacent walls.
    LockWallTile,
}

impl EntitySprite {
    /// Path relative to the configured sprite folder.
    pub const fn relative_path(self) -> &'static str {
        match self {
            Self::ChestClosed => "entities/chest_closed.png",
            Self::ChestOpen => "entities/chest_open.png",
            Self::BreakableIntact => "entities/breakable_intact.png",
            Self::BreakableCracked => "entities/breakable_cracked.png",
            Self::BreakableBroken => "entities/breakable_broken.png",
            Self::PickupHealth => "entities/pickup_health.png",
            Self::PickupCurrency => "entities/pickup_currency.png",
            Self::PickupAbility => "entities/pickup_ability.png",
            Self::HazardSpikes => "entities/hazard_spikes.png",
            Self::NpcTerminal => "entities/npc_terminal.png",
            Self::BossCore => "entities/boss_core.png",
            Self::SandbagDummy => "entities/sandbag_dummy.png",
            Self::SwitchArmed => "entities/switch_armed.png",
            Self::SwitchDisabled => "entities/switch_disabled.png",
            Self::SolidBlock => "entities/solid_block.png",
            Self::OneWayPlatform => "entities/one_way_platform.png",
            Self::SoftBlinkWall => "entities/soft_blink_wall.png",
            Self::HardBlinkWall => "entities/hard_blink_wall.png",
            Self::PogoOrb => "entities/pogo_orb.png",
            Self::ReboundPad => "entities/rebound_pad.png",
            Self::MovingPlatform => "entities/moving_platform.png",
            Self::DoorZone => "entities/door_zone.png",
            Self::EdgeExit => "entities/edge_exit.png",
            Self::ProjectileEnergy => "entities/projectile_energy.png",
            Self::SolidTile => "entities/solid_tile.png",
            Self::OneWayTile => "entities/one_way_tile.png",
            Self::HazardTile => "entities/hazard_tile.png",
            Self::SoftBlinkTile => "entities/soft_blink_tile.png",
            Self::HardBlinkTile => "entities/hard_blink_tile.png",
            Self::LockWallTile => "entities/lock_wall_tile.png",
        }
    }

    pub const ALL: &'static [Self] = &[
        Self::ChestClosed,
        Self::ChestOpen,
        Self::BreakableIntact,
        Self::BreakableCracked,
        Self::BreakableBroken,
        Self::PickupHealth,
        Self::PickupCurrency,
        Self::PickupAbility,
        Self::HazardSpikes,
        Self::NpcTerminal,
        Self::BossCore,
        Self::SandbagDummy,
        Self::SwitchArmed,
        Self::SwitchDisabled,
        Self::SolidBlock,
        Self::OneWayPlatform,
        Self::SoftBlinkWall,
        Self::HardBlinkWall,
        Self::PogoOrb,
        Self::ReboundPad,
        Self::MovingPlatform,
        Self::DoorZone,
        Self::EdgeExit,
        Self::ProjectileEnergy,
        Self::SolidTile,
        Self::OneWayTile,
        Self::HazardTile,
        Self::SoftBlinkTile,
        Self::HardBlinkTile,
        Self::LockWallTile,
    ];
}

/// Stable [`AssetId`] for an [`EntitySprite`].
///
/// The id namespace is `sprite.entity.<lower_snake>` — part of the
/// public asset-catalog contract. Changing the format silently would
/// invalidate authored manifests, so the per-variant suffix mapping is
/// pinned by the test
/// [`tests::every_entity_sprite_has_a_unique_asset_id_in_sprite_entity_namespace`].
pub fn entity_sprite_asset_id(key: EntitySprite) -> AssetId {
    let suffix = match key {
        EntitySprite::ChestClosed => "chest_closed",
        EntitySprite::ChestOpen => "chest_open",
        EntitySprite::BreakableIntact => "breakable_intact",
        EntitySprite::BreakableCracked => "breakable_cracked",
        EntitySprite::BreakableBroken => "breakable_broken",
        EntitySprite::PickupHealth => "pickup_health",
        EntitySprite::PickupCurrency => "pickup_currency",
        EntitySprite::PickupAbility => "pickup_ability",
        EntitySprite::HazardSpikes => "hazard_spikes",
        EntitySprite::NpcTerminal => "npc_terminal",
        EntitySprite::BossCore => "boss_core",
        EntitySprite::SandbagDummy => "sandbag_dummy",
        EntitySprite::SwitchArmed => "switch_armed",
        EntitySprite::SwitchDisabled => "switch_disabled",
        EntitySprite::SolidBlock => "solid_block",
        EntitySprite::OneWayPlatform => "one_way_platform",
        EntitySprite::SoftBlinkWall => "soft_blink_wall",
        EntitySprite::HardBlinkWall => "hard_blink_wall",
        EntitySprite::PogoOrb => "pogo_orb",
        EntitySprite::ReboundPad => "rebound_pad",
        EntitySprite::MovingPlatform => "moving_platform",
        EntitySprite::DoorZone => "door_zone",
        EntitySprite::EdgeExit => "edge_exit",
        EntitySprite::ProjectileEnergy => "projectile_energy",
        EntitySprite::SolidTile => "solid_tile",
        EntitySprite::OneWayTile => "one_way_tile",
        EntitySprite::HazardTile => "hazard_tile",
        EntitySprite::SoftBlinkTile => "soft_blink_tile",
        EntitySprite::HardBlinkTile => "hard_blink_tile",
        EntitySprite::LockWallTile => "lock_wall_tile",
    };
    AssetId::new(format!("sprite.entity.{suffix}"))
}

/// Stable [`AssetId`] for a parallax background layer.
///
/// Namespace: `background.parallax.<theme>.<layer>` — same shape as
/// the existing relative path `backgrounds/parallax_layers/{theme}_{layer}.png`
/// but flattened into a dotted logical id.
pub fn parallax_layer_asset_id(theme: ParallaxTheme, layer: ParallaxLayerAsset) -> AssetId {
    AssetId::new(format!(
        "background.parallax.{}.{}",
        theme.key(),
        layer.key(),
    ))
}

/// Build the sandbox's optional-image manifest: every [`EntitySprite`]
/// plus every `(ParallaxTheme, ParallaxLayerAsset)` pair, keyed by
/// stable logical ids and pointed at the configured `sprite_folder` /
/// the canonical `backgrounds/parallax_layers/` tree.
///
/// All entries are optional — [`MissingAssetPolicy::SilentPlaceholder`]
/// so the rendering layer's colored-rectangle fallback fires for any
/// asset Bevy fails to locate. Preload groups:
///
/// - Entity sprites → [`PreloadGroup::SandboxCore`] (used everywhere)
/// - Parallax layers → [`PreloadGroup::Zone`] (per-room art)
///
/// The function is `pub` so tests + future tools (e.g. a content
/// validator) can introspect the registered ids without going through
/// Bevy. Live image loading consumes it through
/// [`load_game_assets`] / [`load_entity_sprites`] / [`load_parallax_layers`].
pub fn sandbox_image_manifest(sprite_folder: &str) -> AssetManifest {
    let mut manifest = AssetManifest::new();
    for &sprite in EntitySprite::ALL {
        let id = entity_sprite_asset_id(sprite);
        let logical_path = format!("{sprite_folder}/{}", sprite.relative_path());
        let entry = AssetEntry::new(id, AssetKind::Image, logical_path)
            .with_missing_policy(MissingAssetPolicy::SilentPlaceholder)
            .with_preload_group(PreloadGroup::SandboxCore);
        // Only author the Embedded candidate when the
        // `static_core_assets` feature is on. Without the feature,
        // `AmbitionAssetSourcePlugin` doesn't insert the bytes — the
        // candidate would resolve to a 404 on WebStatic.
        #[cfg(feature = "static_core_assets")]
        let entry = if let Some(embedded_url) = entity_sprite_embedded_core_url(sprite) {
            entry.with_location(
                ambition_asset_manager::AssetSourceProfile::EmbeddedBinary,
                ambition_asset_manager::AssetLocation::embedded(embedded_url.to_string()),
            )
        } else {
            entry
        };
        manifest.insert(entry);
    }
    for &theme in ParallaxTheme::ALL {
        for &layer in ParallaxLayerAsset::ALL {
            let id = parallax_layer_asset_id(theme, layer);
            let logical_path = layer.relative_path(theme);
            manifest.insert(
                AssetEntry::new(id, AssetKind::Image, logical_path)
                    .with_missing_policy(MissingAssetPolicy::SilentPlaceholder)
                    .with_preload_group(PreloadGroup::Zone),
            );
        }
    }
    manifest
}

/// Return the embedded-core URL for an [`EntitySprite`] when that
/// sprite is part of the bounded "core visual" set the
/// `static_core_assets` feature packages. The URL pairs with the
/// `EmbeddedAssetRegistry::insert_asset` call inside
/// `crate::assets::sandbox_assets::register_embedded_core_assets`.
///
/// Out-of-set sprites (parallax layers, breakables, boss variants,
/// LDtk debug tiles) return `None` — they keep the colored-rectangle
/// fallback on `WebStatic` / `BundledStatic` until a follow-up slice
/// packages them.
#[cfg_attr(not(feature = "static_core_assets"), allow(dead_code))]
pub fn entity_sprite_embedded_core_url(sprite: EntitySprite) -> Option<&'static str> {
    use crate::assets::sandbox_assets::embedded_core;
    match sprite {
        EntitySprite::ChestClosed => Some(embedded_core::SPRITE_CHEST_CLOSED_URL),
        EntitySprite::ChestOpen => Some(embedded_core::SPRITE_CHEST_OPEN_URL),
        EntitySprite::PickupHealth => Some(embedded_core::SPRITE_PICKUP_HEALTH_URL),
        EntitySprite::PickupCurrency => Some(embedded_core::SPRITE_PICKUP_CURRENCY_URL),
        EntitySprite::PickupAbility => Some(embedded_core::SPRITE_PICKUP_ABILITY_URL),
        EntitySprite::DoorZone => Some(embedded_core::SPRITE_DOOR_ZONE_URL),
        EntitySprite::EdgeExit => Some(embedded_core::SPRITE_EDGE_EXIT_URL),
        EntitySprite::ProjectileEnergy => Some(embedded_core::SPRITE_PROJECTILE_ENERGY_URL),
        EntitySprite::SolidTile => Some(embedded_core::SPRITE_SOLID_TILE_URL),
        EntitySprite::OneWayTile => Some(embedded_core::SPRITE_ONE_WAY_TILE_URL),
        EntitySprite::HazardTile => Some(embedded_core::SPRITE_HAZARD_TILE_URL),
        EntitySprite::BossCore => Some(embedded_core::SPRITE_BOSS_CORE_URL),
        _ => None,
    }
}

/// Convenience: wrap [`sandbox_image_manifest`] in a Bevy-side catalog
/// resource. Constructed per [`load_game_assets`] call so a future
/// `--sprite-folder` toggle re-resolves cleanly.
///
/// Only the tests in this file build the catalog this way today;
/// production startup uses `build_sandbox_catalog` instead. Kept
/// pub so future `--sprite-folder` toggles can adopt it without a
/// visibility change.
#[cfg_attr(not(test), allow(dead_code))]
pub fn build_sandbox_image_catalog(sprite_folder: &str) -> AmbitionAssetCatalog {
    AmbitionAssetCatalog::new(sandbox_image_manifest(sprite_folder))
}

/// Map from `EntitySprite` to its loaded `Handle<Image>`. Missing handles
/// (file absent on disk OR no-asset mode) simply aren't keyed, so callers
/// just consult `get(...) -> Option<&Handle<Image>>`.
#[derive(Default, Clone)]
pub struct EntitySpriteSet {
    handles: HashMap<EntitySprite, Handle<Image>>,
}

impl EntitySpriteSet {
    pub fn get(&self, key: EntitySprite) -> Option<&Handle<Image>> {
        self.handles.get(&key)
    }

    pub fn len(&self) -> usize {
        self.handles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.handles.is_empty()
    }
}

/// Biome/theme key for generated parallax layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxTheme {
    Hub,
    Lab,
    Basement,
    Cove,
    Skybridge,
    Boss,
    Water,
    Forest,
    Cave,
}

impl ParallaxTheme {
    pub const ALL: &'static [Self] = &[
        Self::Hub,
        Self::Lab,
        Self::Basement,
        Self::Cove,
        Self::Skybridge,
        Self::Boss,
        Self::Water,
        Self::Forest,
        Self::Cave,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Hub => "hub",
            Self::Lab => "lab",
            Self::Basement => "basement",
            Self::Cove => "cove",
            Self::Skybridge => "skybridge",
            Self::Boss => "boss",
            Self::Water => "water",
            Self::Forest => "forest",
            Self::Cave => "cave",
        }
    }

    pub fn from_room_metadata(metadata: &RoomMetadata) -> Self {
        // Explicit room visual profiles are the preferred authoring seam for
        // real rooms. `visual_profile` is a stable id, while `parallax_theme`
        // chooses the generated art stack directly.
        if let Some(theme) = metadata
            .visual_profile
            .parallax_theme
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }
        if let Some(theme) = metadata
            .visual_profile
            .id
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }

        // Compatibility fallback for older rooms that only have loose metadata.
        // New authored content should set visual_profile/parallax_theme instead
        // of relying on these heuristic mappings.
        for value in [
            metadata.music_track.as_deref(),
            metadata.biome.as_deref(),
            metadata.ambient_profile.as_deref(),
            metadata.visual_theme.as_deref(),
        ]
        .into_iter()
        .flatten()
        {
            let key = value.trim().to_ascii_lowercase().replace('-', "_");
            if key.contains("ninja") || key.contains("dojo") || key.contains("forest") {
                return Self::Forest;
            }
        }
        if let Some(theme) = metadata.biome.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.visual_theme.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.ambient_profile.as_deref().and_then(Self::from_key) {
            return theme;
        }
        Self::Hub
    }

    fn from_key(value: &str) -> Option<Self> {
        let key = value.trim().to_ascii_lowercase().replace('-', "_");
        match key.as_str() {
            "hub" | "default" | "cantina" | "orange" => Some(Self::Hub),
            "lab" | "laboratory" | "teal" => Some(Self::Lab),
            "basement" | "ruins" | "pink" => Some(Self::Basement),
            "cove" | "coast" | "beach" => Some(Self::Cove),
            "skybridge" | "sky" | "blue" => Some(Self::Skybridge),
            "boss" | "mob_arena" | "arena" => Some(Self::Boss),
            "water" | "underwater" | "tide" => Some(Self::Water),
            "forest" | "woods" | "grove" | "bamboo" | "dojo" | "ninja" | "ninja_dojo" => {
                Some(Self::Forest)
            }
            "cave" | "damp" => Some(Self::Cave),
            _ => None,
        }
    }
}

/// Generated background/parallax image key.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxLayerAsset {
    /// Mostly opaque biome sky/backdrop. This is what prevents the room from
    /// falling back to a transparent-on-grid-only look.
    Sky,
    FarBackplate,
    NearBackground,
    ForegroundAtmosphere,
}

impl ParallaxLayerAsset {
    pub const ALL: &'static [Self] = &[
        Self::Sky,
        Self::FarBackplate,
        Self::NearBackground,
        Self::ForegroundAtmosphere,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Sky => "sky",
            Self::FarBackplate => "far_backplate",
            Self::NearBackground => "near_background",
            Self::ForegroundAtmosphere => "foreground_atmosphere",
        }
    }

    pub fn relative_path(self, theme: ParallaxTheme) -> String {
        format!(
            "backgrounds/parallax_layers/{}_{}.png",
            theme.key(),
            self.key()
        )
    }
}

/// Map from generated background/parallax layer keys to loaded image handles.
#[derive(Default, Clone)]
pub struct ParallaxLayerSet {
    handles: HashMap<(ParallaxTheme, ParallaxLayerAsset), Handle<Image>>,
}

impl ParallaxLayerSet {
    pub fn get(&self, theme: ParallaxTheme, layer: ParallaxLayerAsset) -> Option<&Handle<Image>> {
        self.handles.get(&(theme, layer))
    }

    /// Ensure the generated parallax stack for `theme` has been requested from
    /// Bevy's [`AssetServer`]. Repeated calls are cheap: already-present layer
    /// handles are left alone, and missing optional assets continue to fall back
    /// to the room renderer's clear color / grid visuals.
    pub fn ensure_theme_loaded(
        &mut self,
        catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
        asset_server: &AssetServer,
        theme: ParallaxTheme,
    ) -> usize {
        let mut added = 0usize;
        for &layer in ParallaxLayerAsset::ALL {
            if self.handles.contains_key(&(theme, layer)) {
                continue;
            }
            let id = parallax_layer_asset_id(theme, layer);
            let Some(path) = catalog.try_path_for_load(&id) else {
                continue;
            };
            self.handles.insert((theme, layer), asset_server.load(path));
            added += 1;
        }
        added
    }

    pub fn len(&self) -> usize {
        self.handles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.handles.is_empty()
    }
}

/// All image-handle assets the sandbox knows about. Inserted as a Bevy
/// resource by the presentation startup system; consumed by rendering
/// systems via [`get`]-style accessors that always tolerate `None`.
#[derive(Resource, Default, Clone)]
pub struct GameAssets {
    pub characters: CharacterSpriteAssets,
    pub entities: EntitySpriteSet,
    /// Generic boss spritesheet — the fallback the renderer uses for any boss
    /// without a dedicated sheet in `boss_sprites`. Separate from `characters`
    /// because the boss generator emits its own animation rows
    /// (rest/floor_slam/side_sweep/spike_halo/dash_echo/hit/death) that don't fit
    /// `CharacterAnim`. `None` falls back to the static `EntitySprite::BossCore`.
    pub boss: Option<BossSpriteAsset>,
    /// Dedicated per-boss spritesheets, keyed by the boss's lowercased behavior
    /// id (`boss_key`) — the renderer looks up `boss_sprites.get(&boss_key)` and
    /// falls back to `boss`. This replaced a hand-maintained set of named fields
    /// (`gnu_ton`, `mockingbird`, `trex_boss`, …) + a per-boss if-else chain in
    /// the render layer, so the MACHINERY no longer names any boss: adding a boss
    /// sheet is a new [`boss_sprite_keys`] entry + its loader, not a struct edit.
    ///
    /// Multi-part bosses store their pieces under suffixed keys: GNU-ton's split
    /// body/hands render reads `"gnu_ton_body"` / `"gnu_ton_hands"`.
    pub boss_sprites: HashMap<&'static str, BossSpriteAsset>,
    /// Optional generated biome sky/background/parallax layers. Missing PNGs
    /// are fine: room rendering simply skips the extra layers and keeps the
    /// existing clear-color/grid/block visuals.
    pub parallax_layers: ParallaxLayerSet,
}

impl GameAssets {
    /// Dedicated boss spritesheet for `key` (the lowercased boss behavior id, or
    /// a multi-part suffix like `"gnu_ton_hands"`), if one was loaded. The render
    /// layer falls back to [`Self::boss`] when this is `None`.
    pub fn boss_sprite(&self, key: &str) -> Option<&BossSpriteAsset> {
        self.boss_sprites.get(key)
    }
}

/// Build a fresh `GameAssets`, honoring `config` + the shared
/// [`SandboxAssetCatalog`] resource.
///
/// All path/existence/profile policy goes through `catalog`; this
/// function only assembles the `GameAssets` struct from the catalog's
/// resolutions + a few Bevy `AssetServer::load` calls. `config.no_assets
/// == true` (and the equivalent `AssetProfile::NoAssets`) short-circuits
/// to an empty `GameAssets` so the visible sandbox always boots.
pub fn load_game_assets(
    config: &GameAssetConfig,
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    layouts: &mut Assets<TextureAtlasLayout>,
    active_room_metadata: &RoomMetadata,
) -> GameAssets {
    if config.no_assets {
        eprintln!("[game_assets] --no-assets in effect: rendering with colored-rectangle placeholders only");
        return GameAssets::default();
    }

    let characters = character_sprites::load_character_sprites_in(catalog, asset_server, layouts);
    let entities = load_entity_sprites(catalog, asset_server);
    let boss = sprites::load_boss_sprite_in(catalog, asset_server, layouts);
    // Dedicated per-boss sheets, driven by the `(boss_key, BossSheetSpec)` data
    // table in `boss_encounter::sprites` — the machinery names each boss only
    // there, not in a per-boss loader fn or a struct field.
    let mut boss_sprites: HashMap<&'static str, BossSpriteAsset> = HashMap::new();
    for (key, spec) in sprites::dedicated_boss_sheets() {
        if let Some(sheet) =
            sprites::load_named_boss_sprite_via_catalog(catalog, asset_server, layouts, key, spec)
        {
            boss_sprites.insert(key, sheet);
        }
    }
    let active_parallax_theme = ParallaxTheme::from_room_metadata(active_room_metadata);
    let parallax_layers =
        load_parallax_layers_for_theme(catalog, asset_server, active_parallax_theme);

    let missing = EntitySprite::ALL.len() - entities.len();
    if missing > 0 {
        eprintln!(
            "[game_assets] {missing}/{} entity sprites missing under assets/{}/ — those entities use colored rectangles. Drop matching files in to enable them.",
            EntitySprite::ALL.len(),
            config.sprite_folder,
        );
    }

    GameAssets {
        characters,
        entities,
        boss,
        boss_sprites,
        parallax_layers,
    }
}

fn load_entity_sprites(
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
) -> EntitySpriteSet {
    let mut handles = HashMap::with_capacity(EntitySprite::ALL.len());
    for &key in EntitySprite::ALL {
        let id = entity_sprite_asset_id(key);
        let Some(path) = catalog.try_path_for_load(&id) else {
            continue;
        };
        handles.insert(key, asset_server.load(path));
    }
    EntitySpriteSet { handles }
}

fn load_parallax_layers_for_theme(
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    theme: ParallaxTheme,
) -> ParallaxLayerSet {
    let mut set = ParallaxLayerSet::default();
    let added = set.ensure_theme_loaded(catalog, asset_server, theme);
    if added > 0 {
        eprintln!(
            "[game_assets] loaded {added}/{} generated background/parallax layers for '{}' under assets/backgrounds/parallax_layers/ (other themes lazy-load on room transition)",
            ParallaxLayerAsset::ALL.len(),
            theme.key(),
        );
    }
    set
}

/// Load the generated parallax stack for the room that is about to become
/// active. Visual room transitions call this before spawning parallax sprites so
/// startup only pays for the first room's zone art, while later rooms still get
/// their authored background the first time the player visits them.
pub fn ensure_parallax_layers_for_room(
    assets: &mut GameAssets,
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    metadata: &RoomMetadata,
) {
    let theme = ParallaxTheme::from_room_metadata(metadata);
    let added = assets
        .parallax_layers
        .ensure_theme_loaded(catalog, asset_server, theme);
    if added > 0 {
        bevy::log::debug!(
            target: "ambition::assets",
            "lazy-loaded {added}/{} parallax layers for '{}'",
            ParallaxLayerAsset::ALL.len(),
            theme.key(),
        );
    }
}

// Optional-image load policy lives in `SandboxAssetCatalog`:
// desktop profiles pre-check loose files, bundled/mobile profiles trust
// packaging, web/static profiles skip optional PNGs, and headless/no-assets have
// already returned `None` upstream.

/// Build a `Sprite` for the given entity-sprite key, falling back to the
/// supplied colored-rectangle if the handle is missing. Render size always
/// equals `size`, so block/feature spawns can pass through their authored
/// AABB without rewriting.
pub fn entity_sprite(
    assets: &GameAssets,
    key: EntitySprite,
    size: Vec2,
    fallback_color: Color,
) -> Sprite {
    match assets.entities.get(key) {
        Some(handle) => {
            let mut sprite = Sprite::from_image(handle.clone());
            sprite.custom_size = Some(size);
            sprite
        }
        None => Sprite::from_color(fallback_color, size),
    }
}

/// Same as [`entity_sprite`] but `kind` is optional — `None` always falls
/// through to the colored rectangle. Useful for call sites that map a
/// runtime kind (e.g. `BlockKind`) to an `Option<EntitySprite>` because
/// some variants don't have a dedicated sprite.
pub fn entity_sprite_or_color(
    assets: &GameAssets,
    key: Option<EntitySprite>,
    size: Vec2,
    fallback_color: Color,
) -> Sprite {
    match key.and_then(|k| assets.entities.get(k)) {
        Some(handle) => {
            let mut sprite = Sprite::from_image(handle.clone());
            sprite.custom_size = Some(size);
            sprite
        }
        None => Sprite::from_color(fallback_color, size),
    }
}

/// Per-family entity-sprite resolvers. Stateless choices — the
/// runtime sync system swaps the sprite later for state-driven kinds
/// (chest open, breakable cracked).
pub fn entity_sprite_for_hazard(_volume: &crate::combat::DamageVolume) -> Option<EntitySprite> {
    Some(EntitySprite::HazardSpikes)
}

pub fn entity_sprite_for_pickup(pickup: &crate::interaction::Pickup) -> Option<EntitySprite> {
    Some(pickup_sprite(&pickup.kind))
}

pub fn entity_sprite_for_chest(_chest: &crate::interaction::Chest) -> Option<EntitySprite> {
    Some(EntitySprite::ChestClosed)
}

pub fn entity_sprite_for_breakable(
    _breakable: &crate::interaction::Breakable,
) -> Option<EntitySprite> {
    Some(EntitySprite::BreakableIntact)
}

pub fn entity_sprite_for_interactable(
    interactable: &crate::interaction::Interactable,
) -> Option<EntitySprite> {
    if matches!(
        interactable.kind,
        crate::interaction::InteractionKind::Npc { .. }
    ) {
        Some(EntitySprite::NpcTerminal)
    } else {
        None
    }
}

pub fn entity_sprite_for_enemy(brain: &crate::actor::EnemyBrain) -> Option<EntitySprite> {
    // Training dummies use a dedicated static sprite (authored
    // archetype data); other enemies use animated spritesheets, not a
    // static entity sprite — `upgrade_enemy_sprites` handles them.
    match crate::features::enemy_visual_kind(brain) {
        crate::features::FeatureVisualKind::TrainingDummy => Some(EntitySprite::SandbagDummy),
        _ => None,
    }
}

pub fn entity_sprite_for_boss(_brain: &crate::actor::BossBrain) -> Option<EntitySprite> {
    Some(EntitySprite::BossCore)
}

fn pickup_sprite(kind: &crate::interaction::PickupKind) -> EntitySprite {
    match kind {
        crate::interaction::PickupKind::Health { .. } => EntitySprite::PickupHealth,
        crate::interaction::PickupKind::Currency { .. } => EntitySprite::PickupCurrency,
        crate::interaction::PickupKind::Ability { .. } => EntitySprite::PickupAbility,
        // StoryFlag and Custom fall back to the ability look until they
        // get dedicated art.
        _ => EntitySprite::PickupAbility,
    }
}

/// State-aware sprite for a breakable based on its current health state.
pub fn breakable_state_sprite(state: crate::interaction::BreakableState) -> EntitySprite {
    match state {
        crate::interaction::BreakableState::Intact => EntitySprite::BreakableIntact,
        crate::interaction::BreakableState::Cracking => EntitySprite::BreakableCracked,
        crate::interaction::BreakableState::Broken
        | crate::interaction::BreakableState::Respawning => EntitySprite::BreakableBroken,
    }
}

/// State-aware sprite for a chest by opened-flag.
pub fn chest_state_sprite(opened: bool) -> EntitySprite {
    if opened {
        EntitySprite::ChestOpen
    } else {
        EntitySprite::ChestClosed
    }
}

/// Block-kind sprites. `BlockKind::Hazard` reuses the hazard-spikes art.
pub fn block_sprite(kind: ae::BlockKind) -> Option<EntitySprite> {
    match kind {
        ae::BlockKind::Solid => Some(EntitySprite::SolidBlock),
        ae::BlockKind::OneWay => Some(EntitySprite::OneWayPlatform),
        ae::BlockKind::Hazard => Some(EntitySprite::HazardSpikes),
        ae::BlockKind::PogoOrb => Some(EntitySprite::PogoOrb),
        ae::BlockKind::Rebound { .. } => Some(EntitySprite::ReboundPad),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Soft,
        } => Some(EntitySprite::SoftBlinkWall),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Hard,
        } => Some(EntitySprite::HardBlinkWall),
    }
}

/// Tile-sprite variant of `block_sprite` for IntGrid-derived blocks.
/// Returns the seamless 32×32 tile texture that the renderer should
/// REPEAT (via `Sprite::image_mode = Tiled`) across the block's
/// arbitrary aspect ratio. Returns `None` for kinds that don't have
/// a tile generator yet (PogoOrb / Rebound — those are point-shaped
/// authored entities, not tiled surfaces).
pub fn block_tile_sprite(kind: ae::BlockKind) -> Option<EntitySprite> {
    match kind {
        ae::BlockKind::Solid => Some(EntitySprite::SolidTile),
        ae::BlockKind::OneWay => Some(EntitySprite::OneWayTile),
        ae::BlockKind::Hazard => Some(EntitySprite::HazardTile),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Soft,
        } => Some(EntitySprite::SoftBlinkTile),
        ae::BlockKind::BlinkWall {
            tier: ae::BlinkWallTier::Hard,
        } => Some(EntitySprite::HardBlinkTile),
        // PogoOrb / Rebound stay on the entity-art path because they
        // are point objects, not tiled surfaces. Authored as single
        // entities with fixed-aspect art.
        _ => None,
    }
}

/// Loading-zone sprites — cosmetic, the actual zone behavior comes from
/// the gameplay layer.
pub fn loading_zone_sprite(activation: LoadingZoneActivation) -> EntitySprite {
    match activation {
        LoadingZoneActivation::Door => EntitySprite::DoorZone,
        LoadingZoneActivation::EdgeExit => EntitySprite::EdgeExit,
        // `Walk` zones (mid-room walk-through portals) reuse the
        // EdgeExit sprite for now — both are overlap-triggered, no
        // interact prompt. A dedicated portal-glow sprite can land
        // when art does.
        LoadingZoneActivation::Walk => EntitySprite::EdgeExit,
    }
}

/// Map a `FeatureVisualKind` to a default entity sprite, ignoring per-
/// instance state. Used as a backstop when the engine kind isn't known
/// in detail (e.g. inside `sync_visuals`).
///
/// Today only the tests use this; production sprite resolution goes
/// through the per-state helpers (`pickup_sprite`, `chest_state_sprite`,
/// etc.). Kept pub so a future "kind is the only signal" call site can
/// adopt it without re-deriving the mapping.
#[cfg_attr(not(test), allow(dead_code))]
pub fn entity_sprite_for_kind(kind: FeatureVisualKind) -> Option<EntitySprite> {
    match kind {
        FeatureVisualKind::Hazard => Some(EntitySprite::HazardSpikes),
        FeatureVisualKind::TrainingDummy => Some(EntitySprite::SandbagDummy),
        FeatureVisualKind::Boss => Some(EntitySprite::BossCore),
        FeatureVisualKind::Breakable => Some(EntitySprite::BreakableIntact),
        FeatureVisualKind::Chest => Some(EntitySprite::ChestClosed),
        FeatureVisualKind::Pickup => Some(EntitySprite::PickupHealth),
        FeatureVisualKind::Npc => Some(EntitySprite::NpcTerminal),
        // Enemies are animated; rendering handles them through the
        // character spritesheet, not a static entity sprite.
        FeatureVisualKind::Enemy => None,
        // Switches render as a colored block (red / green) rather
        // than a static entity sprite — see `feature_color` and
        // `switch_on_color` in `rendering.rs`.
        FeatureVisualKind::Switch => None,
    }
}

#[cfg(test)]
mod tests;
