//! Game asset wiring with fallback-friendly loading.
//!
//! The sandbox loads two layers of art on top of its colored-rectangle
//! placeholders:
//!
//! - **Character spritesheets** (robot/goblin/boss) — animated, owned by
//!   `character_sprites`. Loaded here to keep all asset config in one place.
//! - **Entity sprites** — single-image placeholders for chests, pickups,
//!   breakables, hazards, NPCs, blocks, loading zones, and so on. Their
//!   identity/path is emitted by
//!   `python -m ambition_sprite2d_renderer draw-entities` as
//!   `entity_manifest.yaml` next to the generated PNGs.
//! - **Background/parallax layers** — biome-specific sky and atmosphere
//!   plates generated by `python -m ambition_parallax_renderer`, intentionally
//!   outside the sprite asset folder.
//!
//! Two design rules:
//!
//! 1. **The game must always run.** Every asset is `Option<Handle<Image>>`;
//!    if a PNG is missing on disk the rendering layer falls back to its
//!    legacy colored rectangle. The `--no-assets` CLI flag forces every
//!    handle to `None` regardless of disk state, so designers can sanity-
//!    check the placeholder visuals at any moment.
//! 2. **Asset *source* is pluggable.** Today's loader walks the
//!    `assets/<sprite_folder>/` directory; a future loader can synthesize
//!    `Image` assets at runtime and insert them into `Assets<Image>` —
//!    callers only see `GameAssets` and don't care where handles came from.
//!    To make that swap painless we go through the high-level `GameAssets`
//!    struct rather than baking specific paths into call sites.

use bevy::prelude::*;
use std::collections::HashMap;

use ambition_asset_manager::AssetProfile;

use crate::boss_encounter::sprites::{self, BossSpriteAsset};
use crate::character_sprites::{self, CharacterSpriteAssets};
use crate::rooms::RoomMetadata;

/// Pick a sensible default [`AssetProfile`] for the current build target.
///
/// - wasm32 → [`AssetProfile::WebStatic`] (today's first-pass browser
///   build embeds the LDtk bootstrap; optional sprite/parallax PNGs
///   aren't packaged yet, so the catalog skips them and the rendering
///   layer paints colored rectangles).
/// - Android → [`AssetProfile::AndroidBundle`] (Bevy's Android
///   AssetReader pulls from the APK).
/// - everything else → [`AssetProfile::DesktopDevLoose`] (assumes a
///   workspace-relative `assets/` directory; supports hot reload via
///   the loose-filesystem source).
///
/// `cargo run --bin sandbox -- --no-assets` overrides to [`AssetProfile::NoAssets`]
/// via [`GameAssetConfig::from_arg_slice`].
pub fn default_asset_profile() -> AssetProfile {
    if cfg!(target_arch = "wasm32") {
        if cfg!(feature = "web_served") {
            // Build composed `--features web_served_assets` →
            // browser fetches `/assets/*` over HTTP.
            AssetProfile::WebServedAssets
        } else {
            // Build composed `--features web` → only assets with an
            // authored `EmbeddedBinary` candidate are attempted.
            AssetProfile::WebStatic
        }
    } else if cfg!(target_os = "android") {
        AssetProfile::AndroidBundle
    } else {
        AssetProfile::DesktopDevLoose
    }
}

/// CLI/runtime configuration for asset loading. Inserted as a Bevy resource
/// before the presentation startup system runs.
#[derive(Resource, Clone, Debug)]
pub struct GameAssetConfig {
    /// When true, skip every disk asset load and force colored-rectangle
    /// placeholders everywhere. Set via the `--no-assets` CLI flag.
    /// Equivalent to setting `asset_profile = AssetProfile::NoAssets`;
    /// kept as a separate flag so the existing "rendering with
    /// placeholders only" log line is preserved.
    pub no_assets: bool,
    /// Directory under `assets/` that holds character + entity sprites.
    /// Default `"sprites"`. Lets designers point at experimental sets
    /// without recompiling.
    pub sprite_folder: String,
    /// Active [`AssetProfile`] for catalog resolution. Defaults from
    /// [`default_asset_profile`] (per-target cfg). `--no-assets` flips
    /// it to [`AssetProfile::NoAssets`].
    pub asset_profile: AssetProfile,
}

impl Default for GameAssetConfig {
    fn default() -> Self {
        Self {
            no_assets: false,
            sprite_folder: "sprites".into(),
            asset_profile: default_asset_profile(),
        }
    }
}

impl GameAssetConfig {
    /// Parse the supported flags out of process args. Unknown args are left
    /// alone (Bevy may consume some itself).
    pub fn from_args() -> Self {
        let args: Vec<String> = std::env::args().skip(1).collect();
        Self::from_arg_slice(&args)
    }

    /// Parse the supported flags out of an explicit arg slice. Unit-testable
    /// counterpart of `from_args` that doesn't read `env::args`.
    pub fn from_arg_slice(args: &[String]) -> Self {
        let mut config = Self::default();
        let mut i = 0;
        while i < args.len() {
            match args[i].as_str() {
                "--no-assets" => {
                    config.no_assets = true;
                    // Keep the asset profile in sync so the catalog
                    // resolver reports every entry as Disabled too.
                    config.asset_profile = AssetProfile::NoAssets;
                }
                "--sprite-folder" => {
                    if let Some(folder) = args.get(i + 1) {
                        config.sprite_folder = folder.clone();
                        i += 1;
                    }
                }
                _ => {}
            }
            i += 1;
        }
        config
    }
}

mod entity_sprite;
mod resolvers;
pub use entity_sprite::*;
pub use resolvers::*;

/// Biome/theme key for generated parallax layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxTheme {
    Hub,
    Lab,
    Basement,
    Cove,
    Skybridge,
    Boss,
    Water,
    Forest,
    Cave,
}

impl ParallaxTheme {
    pub const ALL: &'static [Self] = &[
        Self::Hub,
        Self::Lab,
        Self::Basement,
        Self::Cove,
        Self::Skybridge,
        Self::Boss,
        Self::Water,
        Self::Forest,
        Self::Cave,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Hub => "hub",
            Self::Lab => "lab",
            Self::Basement => "basement",
            Self::Cove => "cove",
            Self::Skybridge => "skybridge",
            Self::Boss => "boss",
            Self::Water => "water",
            Self::Forest => "forest",
            Self::Cave => "cave",
        }
    }

    pub fn from_room_metadata(metadata: &RoomMetadata) -> Self {
        // Explicit room visual profiles are the preferred authoring seam for
        // real rooms. `visual_profile` is a stable id, while `parallax_theme`
        // chooses the generated art stack directly.
        if let Some(theme) = metadata
            .visual_profile
            .parallax_theme
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }
        if let Some(theme) = metadata
            .visual_profile
            .id
            .as_deref()
            .and_then(Self::from_key)
        {
            return theme;
        }

        // Compatibility fallback for older rooms that only have loose metadata.
        // New authored content should set visual_profile/parallax_theme instead
        // of relying on these heuristic mappings.
        for value in [
            metadata.music_track.as_deref(),
            metadata.biome.as_deref(),
            metadata.ambient_profile.as_deref(),
            metadata.visual_theme.as_deref(),
        ]
        .into_iter()
        .flatten()
        {
            let key = value.trim().to_ascii_lowercase().replace('-', "_");
            if key.contains("ninja") || key.contains("dojo") || key.contains("forest") {
                return Self::Forest;
            }
        }
        if let Some(theme) = metadata.biome.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.visual_theme.as_deref().and_then(Self::from_key) {
            return theme;
        }
        if let Some(theme) = metadata.ambient_profile.as_deref().and_then(Self::from_key) {
            return theme;
        }
        Self::Hub
    }

    fn from_key(value: &str) -> Option<Self> {
        let key = value.trim().to_ascii_lowercase().replace('-', "_");
        match key.as_str() {
            "hub" | "default" | "cantina" | "orange" => Some(Self::Hub),
            "lab" | "laboratory" | "teal" => Some(Self::Lab),
            "basement" | "ruins" | "pink" => Some(Self::Basement),
            "cove" | "coast" | "beach" => Some(Self::Cove),
            "skybridge" | "sky" | "blue" => Some(Self::Skybridge),
            "boss" | "mob_arena" | "arena" => Some(Self::Boss),
            "water" | "underwater" | "tide" => Some(Self::Water),
            "forest" | "woods" | "grove" | "bamboo" | "dojo" | "ninja" | "ninja_dojo" => {
                Some(Self::Forest)
            }
            "cave" | "damp" => Some(Self::Cave),
            _ => None,
        }
    }
}

/// Generated background/parallax image key.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParallaxLayerAsset {
    /// Mostly opaque biome sky/backdrop. This is what prevents the room from
    /// falling back to a transparent-on-grid-only look.
    Sky,
    FarBackplate,
    NearBackground,
    ForegroundAtmosphere,
}

impl ParallaxLayerAsset {
    pub const ALL: &'static [Self] = &[
        Self::Sky,
        Self::FarBackplate,
        Self::NearBackground,
        Self::ForegroundAtmosphere,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::Sky => "sky",
            Self::FarBackplate => "far_backplate",
            Self::NearBackground => "near_background",
            Self::ForegroundAtmosphere => "foreground_atmosphere",
        }
    }

    pub fn relative_path(self, theme: ParallaxTheme) -> String {
        format!(
            "backgrounds/parallax_layers/{}_{}.png",
            theme.key(),
            self.key()
        )
    }
}

/// Map from generated background/parallax layer keys to loaded image handles.
#[derive(Default, Clone)]
pub struct ParallaxLayerSet {
    handles: HashMap<(ParallaxTheme, ParallaxLayerAsset), Handle<Image>>,
}

impl ParallaxLayerSet {
    pub fn get(&self, theme: ParallaxTheme, layer: ParallaxLayerAsset) -> Option<&Handle<Image>> {
        self.handles.get(&(theme, layer))
    }

    /// Ensure the generated parallax stack for `theme` has been requested from
    /// Bevy's [`AssetServer`]. Repeated calls are cheap: already-present layer
    /// handles are left alone, and missing optional assets continue to fall back
    /// to the room renderer's clear color / grid visuals.
    pub fn ensure_theme_loaded(
        &mut self,
        catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
        asset_server: &AssetServer,
        theme: ParallaxTheme,
    ) -> usize {
        let mut added = 0usize;
        for &layer in ParallaxLayerAsset::ALL {
            if self.handles.contains_key(&(theme, layer)) {
                continue;
            }
            let id = parallax_layer_asset_id(theme, layer);
            let Some(path) = catalog.try_path_for_load(&id) else {
                continue;
            };
            self.handles.insert((theme, layer), asset_server.load(path));
            added += 1;
        }
        added
    }

    pub fn len(&self) -> usize {
        self.handles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.handles.is_empty()
    }
}

/// All image-handle assets the sandbox knows about. Inserted as a Bevy
/// resource by the presentation startup system; consumed by rendering
/// systems via [`get`]-style accessors that always tolerate `None`.
#[derive(Resource, Default, Clone)]
pub struct GameAssets {
    pub characters: CharacterSpriteAssets,
    pub entities: EntitySpriteSet,
    /// Generic boss spritesheet — the fallback the renderer uses for any boss
    /// without a dedicated sheet in `boss_sprites`. Separate from `characters`
    /// because the boss generator emits its own animation rows
    /// (rest/floor_slam/side_sweep/spike_halo/dash_echo/hit/death) that don't fit
    /// `CharacterAnim`. `None` falls back to the static `EntitySprite::BossCore`.
    pub boss: Option<BossSpriteAsset>,
    /// Dedicated per-boss spritesheets, keyed by the boss's lowercased behavior
    /// id (`boss_key`) — the renderer looks up `boss_sprites.get(&boss_key)` and
    /// falls back to `boss`. This replaced a hand-maintained set of named fields
    /// (`gnu_ton`, `mockingbird`, `trex_boss`, …) + a per-boss if-else chain in
    /// the render layer, so the MACHINERY no longer names any boss: adding a boss
    /// sheet is a new [`boss_sprite_keys`] entry + its loader, not a struct edit.
    ///
    /// Multi-part bosses store their pieces under suffixed keys: GNU-ton's split
    /// body/hands render reads `"gnu_ton_body"` / `"gnu_ton_hands"`.
    pub boss_sprites: HashMap<&'static str, BossSpriteAsset>,
    /// Optional generated biome sky/background/parallax layers. Missing PNGs
    /// are fine: room rendering simply skips the extra layers and keeps the
    /// existing clear-color/grid/block visuals.
    pub parallax_layers: ParallaxLayerSet,
}

impl GameAssets {
    /// Dedicated boss spritesheet for `key` (the lowercased boss behavior id, or
    /// a multi-part suffix like `"gnu_ton_hands"`), if one was loaded. The render
    /// layer falls back to [`Self::boss`] when this is `None`.
    pub fn boss_sprite(&self, key: &str) -> Option<&BossSpriteAsset> {
        self.boss_sprites.get(key)
    }
}

/// Build a fresh `GameAssets`, honoring `config` + the shared
/// [`SandboxAssetCatalog`] resource.
///
/// All path/existence/profile policy goes through `catalog`; this
/// function only assembles the `GameAssets` struct from the catalog's
/// resolutions + a few Bevy `AssetServer::load` calls. `config.no_assets
/// == true` (and the equivalent `AssetProfile::NoAssets`) short-circuits
/// to an empty `GameAssets` so the visible sandbox always boots.
pub fn load_game_assets(
    config: &GameAssetConfig,
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    layouts: &mut Assets<TextureAtlasLayout>,
    active_room_metadata: &RoomMetadata,
) -> GameAssets {
    if config.no_assets {
        eprintln!("[game_assets] --no-assets in effect: rendering with colored-rectangle placeholders only");
        return GameAssets::default();
    }

    let characters = character_sprites::load_character_sprites_in(catalog, asset_server, layouts);
    let entities = load_entity_sprites(catalog, asset_server);
    let boss = sprites::load_boss_sprite_in(catalog, asset_server, layouts);
    // Dedicated per-boss sheets, driven by the `(boss_key, BossSheetSpec)` data
    // table in `boss_encounter::sprites` — the machinery names each boss only
    // there, not in a per-boss loader fn or a struct field.
    let mut boss_sprites: HashMap<&'static str, BossSpriteAsset> = HashMap::new();
    for (key, spec) in sprites::dedicated_boss_sheets() {
        if let Some(sheet) =
            sprites::load_named_boss_sprite_via_catalog(catalog, asset_server, layouts, key, spec)
        {
            boss_sprites.insert(key, sheet);
        }
    }
    let active_parallax_theme = ParallaxTheme::from_room_metadata(active_room_metadata);
    let parallax_layers =
        load_parallax_layers_for_theme(catalog, asset_server, active_parallax_theme);

    let missing = EntitySprite::ALL.len() - entities.len();
    if missing > 0 {
        eprintln!(
            "[game_assets] {missing}/{} entity sprites missing under assets/{}/ — those entities use colored rectangles. Drop matching files in to enable them.",
            EntitySprite::ALL.len(),
            config.sprite_folder,
        );
    }

    GameAssets {
        characters,
        entities,
        boss,
        boss_sprites,
        parallax_layers,
    }
}

fn load_entity_sprites(
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
) -> EntitySpriteSet {
    let mut handles = HashMap::with_capacity(EntitySprite::ALL.len());
    for &key in EntitySprite::ALL {
        let id = entity_sprite_asset_id(key);
        let Some(path) = catalog.try_path_for_load(&id) else {
            continue;
        };
        handles.insert(key, asset_server.load(path));
    }
    EntitySpriteSet { handles }
}

fn load_parallax_layers_for_theme(
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    theme: ParallaxTheme,
) -> ParallaxLayerSet {
    let mut set = ParallaxLayerSet::default();
    let added = set.ensure_theme_loaded(catalog, asset_server, theme);
    if added > 0 {
        eprintln!(
            "[game_assets] loaded {added}/{} generated background/parallax layers for '{}' under assets/backgrounds/parallax_layers/ (other themes lazy-load on room transition)",
            ParallaxLayerAsset::ALL.len(),
            theme.key(),
        );
    }
    set
}

/// Load the generated parallax stack for the room that is about to become
/// active. Visual room transitions call this before spawning parallax sprites so
/// startup only pays for the first room's zone art, while later rooms still get
/// their authored background the first time the player visits them.
pub fn ensure_parallax_layers_for_room(
    assets: &mut GameAssets,
    catalog: &crate::assets::sandbox_assets::SandboxAssetCatalog,
    asset_server: &AssetServer,
    metadata: &RoomMetadata,
) {
    let theme = ParallaxTheme::from_room_metadata(metadata);
    let added = assets
        .parallax_layers
        .ensure_theme_loaded(catalog, asset_server, theme);
    if added > 0 {
        bevy::log::debug!(
            target: "ambition::assets",
            "lazy-loaded {added}/{} parallax layers for '{}'",
            ParallaxLayerAsset::ALL.len(),
            theme.key(),
        );
    }
}

// Optional-image load policy lives in `SandboxAssetCatalog`:
// desktop profiles pre-check loose files, bundled/mobile profiles trust
// packaging, web/static profiles skip optional PNGs, and headless/no-assets have
// already returned `None` upstream.

/// Build a `Sprite` for the given entity-sprite key, falling back to the
/// supplied colored-rectangle if the handle is missing. Render size always
/// equals `size`, so block/feature spawns can pass through their authored
/// AABB without rewriting.

#[cfg(test)]
mod tests;

