"""Generate the `symmetry_room` area spec with provable 4-fold (C4) symmetry.

The Noether Chamber. A plus-shaped interior framed by four corner blocks. Each
ARM has its own fixed OUTWARD gravity zone (down/left/up/right) — the four
reference frames — plus a zig-zag climb of platforms and one grounded Emmy clone.
At the centre, a small KERNEL carries a gravity switch on each face that sets the
*ambient* (centre) gravity toward that face (`SetGravityDown|Up|Left|Right` — no
colon: the switch payload round-trips through a ':'-delimited string). Short ring
shelves hug the kernel faces for footing; pogo orbs sit at the kernel corners; a
4-colour portal gun waits at the entrance. Pogo orbs sit at the kernel corners.
The only asymmetry is the entrance.

Each gravity zone stops ZONE_INSET short of the wall it pulls toward, leaving a
one-tile gap at that wall (kept at 16px so a *standing* actor's centre is still
inside the zone and stays grounded in that frame).

Authored by rotating ONE canonical side 90 degrees x3, so symmetry is exact.

    cd tools/ambition_ldtk_tools
    uv run --no-project --python 3.12 python gen_symmetry_room.py
    uv run --python 3.12 python -m ambition_ldtk_tools area create \
        specs/symmetry_room_area.ron --replace-existing
"""

from __future__ import annotations

from pathlib import Path

SIZE = 1280
C = SIZE / 2.0
WALL = 32
ARM = 448
K0, K1 = 576, 704       # kernel extent (128x128, centred — small core, more space)
ZONE_INSET = 16         # 1-tile gap between each zone and the wall it pulls to

DIR_SUFFIX = {"down": "Down", "up": "Up", "left": "Left", "right": "Right"}


def rot_rect(x, y, w, h):
    """Rotate a rectangle 90 degrees about the room centre (screen y-down)."""
    bx, by = x + w / 2.0, y + h / 2.0
    dx, dy = bx - C, by - C
    nx, ny = (C + (-dy)) - h / 2.0, (C + dx) - w / 2.0
    return int(round(nx)), int(round(ny)), int(round(h)), int(round(w))


def rotn(rect, n):
    for _ in range(n):
        rect = rot_rect(*rect)
    return rect


def fnum(v):
    return str(int(round(v)))


def entity(etype, x, y, w, h, fields):
    parts = ", ".join(f"{k}: {v}" for k, v in fields.items())
    return (f'        ( type: "{etype}", px: [{fnum(x)}, {fnum(y)}], '
            f'size: [{fnum(w)}, {fnum(h)}], fields: ( {parts} ) ),')


# ---- Canonical DOWN-side features; rotated x90 to fill all four arms. ----
# Gravity zone: fills the down arm but stops ZONE_INSET above the bottom wall.
CANON_ZONE = (448, 832, 384, (SIZE - WALL - 832) - ZONE_INSET)   # (448,832,384,400)
CANON_SWITCH = (606, K1, 68, 24)                                  # on the kernel bottom face
CANON_RING = (600, 736, 80, 18)                                   # small footing shelf below the face
CANON_POGO = (704, 704, 36, 36)                                   # at the kernel's bottom-right corner
CANON_STEPS = [                                                   # zig-zag climb: floor -> centre
    (470, 1120, 132, 24, "step_a"),
    (650, 1000, 132, 24, "step_b"),
    (470, 880, 132, 24, "step_c"),
]
CANON_EMMY = (560, 1206, 42, 42)                                  # grounded on the arm's wall


lines = []
A = lines.append
A('// symmetry_room — "The Noether Chamber": a C4-symmetric gravity tutorial.')
A('//')
A('// GENERATED by tools/ambition_ldtk_tools/gen_symmetry_room.py — do NOT hand-edit;')
A('// edit the generator (it guarantees the quarter-turn symmetry) and re-run, then')
A('//   area create specs/symmetry_room_area.ron --replace-existing')
A('//')
A('// Four arms, each: a fixed OUTWARD gravity zone (inset one tile from its wall),')
A('// a zig-zag climb, and one grounded Emmy clone. A small central KERNEL has a')
A('// gravity switch per face (sets ambient gravity), small footing shelves, and a')
A('// pogo orb at each corner. An entrance portal gun completes the kit. Only the')
A('// entrance breaks the symmetry.')
A('(')
A('    id: "symmetry_room",')
A('    level_id: "symmetry_room",')
A('    world_x: 120000,')
A('    world_y: 0,')
A(f'    px_wid: {SIZE},')
A(f'    px_hei: {SIZE},')
A('    fill_collision: "empty",')
A('    bg_color: "#12161F",')
A('    biome: "lab",')
A('    music_track: "for_emmy_forever_ago",')
A('    entities: [')

# Border walls.
A('        // Outer border.')
A(entity("Solid", 0, 0, SIZE, WALL, {"name": '"wall_top"'}))
A(entity("Solid", 0, SIZE - WALL, SIZE, WALL, {"name": '"wall_bottom"'}))
A(entity("Solid", 0, 0, WALL, SIZE, {"name": '"wall_left"'}))
A(entity("Solid", SIZE - WALL, 0, WALL, SIZE, {"name": '"wall_right"'}))

# Corner blocks (plus shape).
A('        // Four corner blocks carve the open space into a symmetric plus.')
A(entity("Solid", WALL, WALL, ARM - WALL, ARM - WALL, {"name": '"corner_tl"'}))
A(entity("Solid", SIZE - ARM, WALL, ARM - WALL, ARM - WALL, {"name": '"corner_tr"'}))
A(entity("Solid", WALL, SIZE - ARM, ARM - WALL, ARM - WALL, {"name": '"corner_bl"'}))
A(entity("Solid", SIZE - ARM, SIZE - ARM, ARM - WALL, ARM - WALL, {"name": '"corner_br"'}))

# Kernel (shrunk).
A('        // The small kernel: a gravity switch on each face sets ambient gravity.')
A(entity("Solid", K0, K0, K1 - K0, K1 - K0, {"name": '"kernel"'}))

# Per-arm features (rotated).
for n in range(4):
    d = ["down", "left", "up", "right"][n]
    A(f'        // ---- {d.upper()} arm: fixed {d}-gravity frame + climb + kernel-{d} switch. ----')
    zx, zy, zw, zh = rotn(CANON_ZONE, n)
    A(entity("GravityZone", zx, zy, zw, zh, {
        "id": f'"grav_{d}"', "name": f'"gravity {d}"', "dir": f'"{d}"'}))
    sx, sy, sw, sh = rotn(CANON_SWITCH, n)
    A(entity("Switch", sx, sy, sw, sh, {
        "id": f'"kernel_switch_{d}"', "name": f'"kernel gravity {d}"',
        "prompt": f'"Set ambient gravity {d.upper()}"',
        "action": f'"SetGravity{DIR_SUFFIX[d]}"', "target_encounter": '""'}))
    rx, ry, rw, rh = rotn(CANON_RING, n)
    A(entity("Solid", rx, ry, rw, rh, {"name": f'"ring_{d}"'}))
    px, py, pw, ph = rotn(CANON_POGO, n)
    A(entity("PogoOrb", px, py, pw, ph, {"name": f'"pogo_{d}"'}))
    for step in CANON_STEPS:
        stx, sty, stw, sth = rotn(step[:4], n)
        A(entity("Solid", stx, sty, stw, sth, {"name": f'"{d}_{step[4]}"'}))
    ex, ey, ew, eh = rotn(CANON_EMMY, n)
    dialogue = "emmy_noether" if d == "down" else f"emmy_noether_{d}"
    A(entity("NpcSpawn", ex, ey, ew, eh, {
        "prompt": f'"Talk to Emmy No-Ether ({d})"', "dialogue_id": f'"{dialogue}"',
        "character_id": '"npc_noether"', "patrol_radius": "0"}))

# Entrance furniture (the one symmetry-breaker) — inside the down arm floor.
A('        // ---- Entrance (the only asymmetry): spawn, door, portal gun. ----')
A(entity("PlayerStart", 470, 1202, 28, 46, {"name": '"symmetry_spawn"'}))
A(entity("PortalGunSpawn", 648, 1208, 40, 40, {
    "id": '"symmetry_portal_gun"', "name": '"Portal Gun (4 colours)"'}))
A(entity("LoadingZone", 752, 1152, 64, 96, {
    "id": '"symmetry_entry"', "name": '"symmetry_entry"', "activation": '"Door"',
    "target_room": '"central_hub_complex"', "target_zone": '"basement_to_symmetry_room_door"',
    "bidirectional": "true"}))

# Signage.
A('        // Signage.')
A(entity("DebugLabel", 466, 520, 360, 24, {
    "name": '"kernel_label"', "text": '"Kernel: a switch on each face sets which way is down."',
    "category": '"Custom"'}))
A(entity("DebugLabel", 460, 1090, 372, 24, {
    "name": '"entry_label"',
    "text": '"Grab the portal gun. Each arm is a different down. Talk to all four Emmys."',
    "category": '"Custom"'}))

A(entity("CameraZone", 0, 0, SIZE, SIZE, {
    "id": '"symmetry_camera"', "name": '"symmetry_camera"', "mode": '"Default"'}))

A('    ],')
A(')')

OUT = Path(__file__).resolve().parent / "specs" / "symmetry_room_area.ron"
OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
print(f"wrote {OUT}")
