"""Generate the `symmetry_room` area spec with provable 4-fold (C4) symmetry.

The Noether Chamber: a big square room whose interior is invariant under a
quarter-turn. We author ONE canonical side and rotate its features 90 degrees
three times, so the geometry is symmetric *by construction*.

At the centre sits the KERNEL — a block with a gravity switch on each of its four
faces. Each switch sets the room's ambient gravity toward that face, so any face
can become "down" (handler: `SetGravity:<dir>` in encounter/systems.rs). Because
the chamber is C4-symmetric, whatever climb reaches a switch under one gravity
reaches the rotated switch under the rotated gravity — so the player is never
stranded (the kernel "breaks" the symmetry the player restores). Pogo orbs sit at
the kernel's corners; a portal gun at the entrance lets the player place up to
four colour pairs. The only asymmetry is the entrance (door + spawn + Emmy).

    cd tools/ambition_ldtk_tools
    uv run --no-project --python 3.12 python gen_symmetry_room.py
    uv run --python 3.12 python -m ambition_ldtk_tools area create \
        specs/symmetry_room_area.ron --replace-existing
"""

from __future__ import annotations

from pathlib import Path

SIZE = 1280
C = SIZE / 2.0          # rotation centre (640, 640)
WALL = 32
ARM = 448               # corner blocks span [WALL..ARM] / [SIZE-ARM..SIZE-WALL]
K0, K1 = 512, 768       # kernel extent (256x256, centred)

# down -> left -> up -> right under the rotation (dx,dy) -> (-dy, dx).
DIR_ROT = {"down": "left", "left": "up", "up": "right", "right": "down"}


def rot_rect(x, y, w, h):
    """Rotate a rectangle 90 degrees about the room centre (screen y-down)."""
    bx, by = x + w / 2.0, y + h / 2.0
    dx, dy = bx - C, by - C
    nx, ny = (C + (-dy)) - h / 2.0, (C + dx) - w / 2.0
    return int(round(nx)), int(round(ny)), int(round(h)), int(round(w))


def fnum(v):
    return str(int(round(v)))


def entity(etype, x, y, w, h, fields):
    parts = ", ".join(f"{k}: {v}" for k, v in fields.items())
    return (f'        ( type: "{etype}", px: [{fnum(x)}, {fnum(y)}], '
            f'size: [{fnum(w)}, {fnum(h)}], fields: ( {parts} ) ),')


# ---- Canonical features for the DOWN side; rotated x90 to fill all four. ----
# Kernel-face gravity switch (bottom face): just below the kernel, centred.
CANON_SWITCH = (624, K1, 32, 32, "down")
# Ring shelf hugging the bottom face — footing to reach the side faces.
CANON_RING = (528, 800, 224, 24)
# A pogo orb tucked at the kernel's bottom-right corner.
CANON_POGO = (744, 744, 36, 36)
# An Emmy clone grounded in the down arm; rotations place one per face so the
# quartet is C4-symmetric (each is "the Emmy who lives in that frame").
CANON_EMMY = (470, 1200, 42, 42)
# Zig-zag climb in the down arm: floor -> centre.
CANON_STEPS = [
    (470, 1120, 132, 24, "step_a"),
    (678, 992, 132, 24, "step_b"),
    (470, 864, 132, 24, "step_c"),
]


def rotn(rect, n):
    x, y, w, h = rect
    for _ in range(n):
        x, y, w, h = rot_rect(x, y, w, h)
    return x, y, w, h


lines = []
A = lines.append
A('// symmetry_room — "The Noether Chamber": a C4-symmetric gravity tutorial.')
A('//')
A('// GENERATED by tools/ambition_ldtk_tools/gen_symmetry_room.py — do NOT hand-edit;')
A('// edit the generator (it guarantees the quarter-turn symmetry) and re-run, then')
A('//   area create specs/symmetry_room_area.ron --replace-existing')
A('//')
A('// A plus-shaped interior framed by four corner blocks. At the centre, the')
A('// KERNEL carries a gravity switch on each face (SetGravity:<dir>) so any side')
A('// can become "down". Pogo orbs ring the kernel corners; a 4-colour portal gun')
A('// waits at the entrance. The only asymmetry is the entrance (door/spawn/Emmy).')
A('(')
A('    id: "symmetry_room",')
A('    level_id: "symmetry_room",')
A('    world_x: 120000,')
A('    world_y: 0,')
A(f'    px_wid: {SIZE},')
A(f'    px_hei: {SIZE},')
A('    fill_collision: "empty",')
A('    bg_color: "#12161F",')
A('    biome: "lab",')
A('    music_track: "for_emmy_forever_ago",')
A('    entities: [')

# ---- Border walls (C4) ----
A('        // Outer border (each wall is a "floor" under the matching gravity).')
A(entity("Solid", 0, 0, SIZE, WALL, {"name": '"wall_top"'}))
A(entity("Solid", 0, SIZE - WALL, SIZE, WALL, {"name": '"wall_bottom"'}))
A(entity("Solid", 0, 0, WALL, SIZE, {"name": '"wall_left"'}))
A(entity("Solid", SIZE - WALL, 0, WALL, SIZE, {"name": '"wall_right"'}))

# ---- Corner blocks (plus shape) ----
A('        // Four corner blocks carve the open space into a symmetric plus.')
A(entity("Solid", WALL, WALL, ARM - WALL, ARM - WALL, {"name": '"corner_tl"'}))
A(entity("Solid", SIZE - ARM, WALL, ARM - WALL, ARM - WALL, {"name": '"corner_tr"'}))
A(entity("Solid", WALL, SIZE - ARM, ARM - WALL, ARM - WALL, {"name": '"corner_bl"'}))
A(entity("Solid", SIZE - ARM, SIZE - ARM, ARM - WALL, ARM - WALL, {"name": '"corner_br"'}))

# ---- The kernel ----
A('        // The kernel: a gravity switch on each face sets that side as "down".')
A(entity("Solid", K0, K0, K1 - K0, K1 - K0, {"name": '"kernel"'}))

# ---- Rotated per-side features ----
for n in range(4):
    d = ["down", "left", "up", "right"][n]
    A(f'        // ---- {d.upper()} face / approach. ----')
    sx, sy, sw, sh = rotn(CANON_SWITCH[:4], n)
    A(entity("Switch", sx, sy, sw, sh, {
        "id": f'"kernel_switch_{d}"', "name": f'"gravity {d}"',
        "prompt": f'"Set gravity {d.upper()}"', "action": f'"SetGravity:{d}"',
        "target_encounter": '""'}))
    rx, ry, rw, rh = rotn(CANON_RING, n)
    A(entity("Solid", rx, ry, rw, rh, {"name": f'"ring_{d}"'}))
    px, py, pw, ph = rotn(CANON_POGO, n)
    A(entity("PogoOrb", px, py, pw, ph, {"name": f'"pogo_{d}"'}))
    for step in CANON_STEPS:
        stx, sty, stw, sth = rotn(step[:4], n)
        A(entity("Solid", stx, sty, stw, sth, {"name": f'"{d}_{step[4]}"'}))
    # One Emmy clone per face — symmetric quartet, distinct dialogue each.
    ex, ey, ew, eh = rotn(CANON_EMMY, n)
    dialogue = "emmy_noether" if d == "down" else f"emmy_noether_{d}"
    A(entity("NpcSpawn", ex, ey, ew, eh, {
        "prompt": f'"Talk to Emmy No-Ether ({d})"', "dialogue_id": f'"{dialogue}"',
        "character_id": '"npc_noether"', "patrol_radius": "0"}))

# ---- Entrance furniture (the intentional asymmetry, bottom arm) ----
A('        // ---- Entrance (the one symmetry-breaker): door, spawn, gun. ----')
A(entity("PlayerStart", 700, 1202, 28, 46, {"name": '"symmetry_spawn"'}))
A(entity("LoadingZone", 596, 1152, 80, 96, {
    "id": '"symmetry_entry"', "name": '"symmetry_entry"', "activation": '"Door"',
    "target_room": '"central_hub_complex"', "target_zone": '"basement_to_symmetry_room_door"',
    "bidirectional": "true"}))
A(entity("PortalGunSpawn", 764, 1208, 40, 40, {
    "id": '"symmetry_portal_gun"', "name": '"Portal Gun (4 colours)"'}))

# ---- Signage (spaced so none overlap) ----
A('        // Signage.')
A(entity("DebugLabel", 360, 470, 560, 24, {
    "name": '"title"',
    "text": '"The Noether Chamber: a quarter-turn changes nothing. The kernel lets you choose which way is down."',
    "category": '"Custom"'}))
A(entity("DebugLabel", 470, 1090, 360, 24, {
    "name": '"entry_label"',
    "text": '"Grab the portal gun. Talk to Emmy. Flip gravity at the kernel."',
    "category": '"Custom"'}))

# ---- Camera ----
A(entity("CameraZone", 0, 0, SIZE, SIZE, {
    "id": '"symmetry_camera"', "name": '"symmetry_camera"', "mode": '"Default"'}))

A('    ],')
A(')')

OUT = Path(__file__).resolve().parent / "specs" / "symmetry_room_area.ron"
OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
print(f"wrote {OUT}")
