//! Authored-content schemas for the audio capability.
//!
//! `music_registry.ron` declares pre-rendered tracks and asset requirements;
//! `sfx_registry.ron` declares procedural cues. Schema handlers reuse the
//! registry types' canonical `validate()` methods and add source diagnostics,
//! unknown-field rejection, and content identities. `music_registry.ron` is
//! generated by `scripts/regen_music_registry.py`.

use std::sync::Arc;

use ambition_content_pack::{
    AssetRequirement, CapabilityId, ContentSchemaHandler, DiagnosticCode, FacetOutcome,
    FacetSource, RuntimeDisposition, SchemaId, SchemaRegistration, SchemaVersion,
};

use crate::spec::{MusicRegistry, SfxRegistry};

/// The capability that owns both schemas here.
pub const AUDIO_CAPABILITY: &str = "audio";

pub const MUSIC_REGISTRY_SCHEMA: &str = "music_registry";
/// One playable track.
pub const MUSIC_TRACK_SCHEMA: &str = "music_track";
pub const SFX_REGISTRY_SCHEMA: &str = "sfx_registry";
/// One procedural cue.
pub const SFX_CUE_SCHEMA: &str = "sfx_cue";

pub const MUSIC_REGISTRY_VERSION: SchemaVersion = SchemaVersion(1);
pub const SFX_REGISTRY_VERSION: SchemaVersion = SchemaVersion(1);

fn canonical<T: std::fmt::Debug>(value: &T) -> String {
    format!("{value:?}")
}

fn code_for(error: &ron::error::SpannedError) -> DiagnosticCode {
    match error.code {
        ron::error::Error::NoSuchStructField { .. } => DiagnosticCode::UnknownField,
        _ => DiagnosticCode::MalformedSource,
    }
}

// ── music ────────────────────────────────────────────────────────────────────

struct MusicRegistrySchema;

impl ContentSchemaHandler for MusicRegistrySchema {
    fn check(&self, facet: &FacetSource<'_>, out: &mut FacetOutcome) {
        let registry: MusicRegistry = match ron::from_str(facet.text) {
            Ok(registry) => registry,
            Err(error) => {
                out.report(
                    facet
                        .diagnostic(code_for(&error), format!("{error}"))
                        .fix(GENERATED_FIX),
                );
                return;
            }
        };

        // Reuse the registry's canonical validation rules.
        if let Err(message) = registry.validate() {
            out.report(
                facet
                    .diagnostic(DiagnosticCode::MalformedProviderBinding, message)
                    .fix(GENERATED_FIX),
            );
        }

        // REGISTRY-LEVEL STATE MUST REACH THE FINGERPRINT. The pack
        // fingerprint is taken over `out.define(...)` entries only — not the
        // lowered artifact, not the source bytes. Defining one entry per TRACK
        // therefore left `default_track` and the track ORDER contributing
        // nothing: two packs that start on different music, or sequence the
        // radio differently, fingerprinted identically. Both are runtime-real
        // (`AudioLibrary` resolves the default at startup and indexes
        // `music_tracks[next]` for next/prev).
        out.define(facet.content_id_in(MUSIC_REGISTRY_SCHEMA, "registry"), {
            // serialized, not `join(",")`. A track id is only required
            // to be non-empty and unique — commas are legal — so an
            // unescaped delimiter let two different orders encode
            // identically: `["a", "b,c", "a,b", "c"]` and
            // `["a,b", "c", "a", "b,c"]` both flatten to `a,b,c,a,b,c`, with
            // the per-track entries unchanged, so the whole fingerprint
            // held still while the order moved.
            let order: Vec<&str> = registry.tracks.iter().map(|t| t.id.as_str()).collect();
            format!(
                "default_track={}\norder={}",
                ron::ser::to_string(&registry.default_track)
                    .unwrap_or_else(|_| registry.default_track.clone()),
                ron::ser::to_string(&order).unwrap_or_else(|e| format!("<uncanonical: {e}>"))
            )
        });

        for track in &registry.tracks {
            let id = facet.content_id_in(MUSIC_TRACK_SCHEMA, &track.id);
            out.define(id.clone(), canonical(track));
            // The asset half nothing checked before: `AudioCatalogFragment`
            // validates the registry's SHAPE and never asks whether the OGG it
            // points at is there.
            out.need_asset(AssetRequirement::new(
                track.resolved_asset_path(),
                id,
                "asset_path",
            ));
        }

        if !out.failed() {
            out.lower(registry);
        }
    }
}

const GENERATED_FIX: &str =
    "⛔ `music_registry.ron` is GENERATED by scripts/regen_music_registry.py — fix the generator \
     or the asset tree, not this file, because the next render overwrites it";

// ── sfx ──────────────────────────────────────────────────────────────────────

struct SfxRegistrySchema;

impl ContentSchemaHandler for SfxRegistrySchema {
    fn check(&self, facet: &FacetSource<'_>, out: &mut FacetOutcome) {
        let registry: SfxRegistry = match ron::from_str(facet.text) {
            Ok(registry) => registry,
            Err(error) => {
                out.report(facet.diagnostic(code_for(&error), format!("{error}")));
                return;
            }
        };

        if let Err(message) = registry.validate() {
            out.report(facet.diagnostic(DiagnosticCode::MalformedProviderBinding, message));
        }

        // The same fingerprint gap as the music registry: `sample_rate` is
        // registry-level, changes procedural synthesis for every cue, and would
        // otherwise contribute nothing to the pack's identity.
        out.define(
            facet.content_id_in(SFX_REGISTRY_SCHEMA, "registry"),
            format!("sample_rate={}", registry.sample_rate),
        );

        // A procedural cue has no asset — it IS the synthesis spec. Identities
        // still matter so a caller can name what a provider authorized.
        for spec in &registry.sfx {
            // Named by what the AUTHOR wrote — the open `id` string, or the
            // typed cue — not by the hashed `SfxId`, which is an opaque u64 and
            // would make every identity unreadable in a diagnostic.
            //
            // A spec whose id does not resolve is already reported by
            // `validate()` above; minting an identity for it would invent a name
            // the registry does not actually authorize.
            if spec.sfx_id().is_err() {
                continue;
            }
            let name = match (&spec.id, spec.cue) {
                (Some(id), _) => id.clone(),
                (None, Some(cue)) => format!("{cue:?}"),
                (None, None) => continue,
            };
            out.define(facet.content_id_in(SFX_CUE_SCHEMA, name), canonical(spec));
        }

        if !out.failed() {
            out.lower(registry);
        }
    }
}

// ── lowered accessors — the runtime's load path ──────────────────────────────

pub fn lowered_music_registry(
    pack: &ambition_content_pack::PreparedContentPack,
) -> Option<&MusicRegistry> {
    pack.lowered::<MusicRegistry>(&SchemaId::new(MUSIC_REGISTRY_SCHEMA))
}

pub fn lowered_sfx_registry(
    pack: &ambition_content_pack::PreparedContentPack,
) -> Option<&SfxRegistry> {
    pack.lowered::<SfxRegistry>(&SchemaId::new(SFX_REGISTRY_SCHEMA))
}

// ── registrations ────────────────────────────────────────────────────────────

pub fn music_registry_schema() -> SchemaRegistration {
    SchemaRegistration {
        id: SchemaId::new(MUSIC_REGISTRY_SCHEMA),
        version: MUSIC_REGISTRY_VERSION,
        capability: CapabilityId::new(AUDIO_CAPABILITY),
        disposition: RuntimeDisposition::Runtime,
        doc: "Radio and room music: one pre-rendered track per row, plus the default. \
              Defines `music_track` identities and requires each track's audio file. GENERATED.",
        handler: Arc::new(MusicRegistrySchema),
    }
}

pub fn sfx_registry_schema() -> SchemaRegistration {
    SchemaRegistration {
        id: SchemaId::new(SFX_REGISTRY_SCHEMA),
        version: SFX_REGISTRY_VERSION,
        capability: CapabilityId::new(AUDIO_CAPABILITY),
        disposition: RuntimeDisposition::Runtime,
        doc: "Procedural sound-design cues: the synth sample rate and one waveform/envelope \
              spec per cue. Defines `sfx_cue` identities.",
        handler: Arc::new(SfxRegistrySchema),
    }
}

#[cfg(test)]
mod tests;
