//! The startup vanity card, DRAWN rather than played back.
//!
//! The authored card is nine rendered images plus a committed manifest
//! ([`crate::vanity_card`]), and the images are a git-ignored payload addressed
//! through an ipfs location. That is fine for a machine that has them and
//! nothing at all for one that does not — a fresh clone plays a card of
//! correctly-timed blank slots. This module draws the same beat out of ordinary
//! UI nodes, so the card is a property of the SOURCE and a checkout can always
//! play it.
//!
//! It is a shell SEGMENT, not a special case: the host registers
//! [`AMBITION_VANITY_CARD_SEGMENT_KIND`] as one card in the startup run-in, and
//! this module spawns its scene when that segment becomes current and reports
//! `ProgrammaticSegmentCompleted` when the beat is over. Skip, route
//! replacement, and failure all tear the scene down through
//! `ShellSegmentScopedEntity`, which the sequence plugin already owns — there is
//! no lifecycle here to get wrong.
//!
//! The joke is the robot's, and then it is the human's: *I MADE THIS* → the
//! handoff → *YOU MADE THIS?* → *I MADE THIS*. The timing is pinned to the
//! authored card's own total ([`crate::vanity_card::vanity_card_total_duration`])
//! so the two versions play at the same pace.

use std::time::Duration;

use ambition_platformer2d::game_shell::{
    ActiveShellSequence, FrontendOwnedEntity, FrontendPresentationKind, ShellActivationId,
    ShellSegmentId, ShellSegmentScopedEntity, ShellSequenceCommand,
};
use bevy::prelude::*;

/// Registered shell-segment kind for the programmatic replacement of the old
/// prerendered startup card.
pub const AMBITION_VANITY_CARD_SEGMENT_KIND: &str = "ambition_vanity_card";

/// The five beats, as RELATIVE weights rather than milliseconds.
///
/// ⚠ **they were five absolute constants and they were already wrong.** They
/// summed to 3900 ms against the authored card's 3902, so the equality this
/// module claims — that both versions tell the joke at the same pace — was
/// false the day it was written, by an amount no reviewer would ever spot. The
/// manifest is REGENERATED by an exporter, so any absolute copy of its length
/// drifts again on the next render.
///
/// Weights fix that by construction: the card is exactly as long as the authored
/// sequence, whatever that becomes, and only the SHAPE of the beat lives here.
const BEAT_WEIGHTS: Beats<u32> = Beats {
    intro: 700,
    handoff: 1000,
    question: 500,
    replay: 500,
    claim: 1200,
};

/// The card's five beats: the robot's claim, the handoff, the human's question,
/// a replayed glance, and the human's identical claim.
#[derive(Clone, Copy)]
struct Beats<T> {
    intro: T,
    handoff: T,
    question: T,
    replay: T,
    claim: T,
}

/// The beats in milliseconds, summing EXACTLY to the authored card's total.
///
/// The last beat takes the remainder rather than its own rounded share, so
/// integer division cannot leave the card a millisecond short of the segment
/// the host scheduled for it.
fn beats() -> Beats<Duration> {
    let total = crate::vanity_card::vanity_card_total_duration().as_millis() as u64;
    let weight_total = (BEAT_WEIGHTS.intro
        + BEAT_WEIGHTS.handoff
        + BEAT_WEIGHTS.question
        + BEAT_WEIGHTS.replay
        + BEAT_WEIGHTS.claim) as u64;
    let share = |weight: u32| total * weight as u64 / weight_total;

    let intro = share(BEAT_WEIGHTS.intro);
    let handoff = share(BEAT_WEIGHTS.handoff);
    let question = share(BEAT_WEIGHTS.question);
    let replay = share(BEAT_WEIGHTS.replay);
    Beats {
        intro: Duration::from_millis(intro),
        handoff: Duration::from_millis(handoff),
        question: Duration::from_millis(question),
        replay: Duration::from_millis(replay),
        claim: Duration::from_millis(total.saturating_sub(intro + handoff + question + replay)),
    }
}

/// How long the drawn card plays — the authored card's own total, so retiming
/// the manifest retimes this and there is nothing to keep in sync by hand.
pub fn programmatic_vanity_card_duration() -> Duration {
    crate::vanity_card::vanity_card_total_duration()
}

pub struct AmbitionVanityCardPresentationPlugin;

impl Plugin for AmbitionVanityCardPresentationPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            Update,
            (
                spawn_programmatic_vanity_card,
                animate_programmatic_vanity_card,
            ),
        );
    }
}

#[derive(Component)]
struct VanityCardSceneRoot {
    activation_id: ShellActivationId,
    segment_id: ShellSegmentId,
    elapsed: Duration,
    completion_sent: bool,
    bubble: Entity,
    bubble_text: Entity,
    device: Entity,
    robot_arm: Entity,
    human_arm: Entity,
    robot_card: Entity,
    human_card: Entity,
}

fn spawn_programmatic_vanity_card(
    mut commands: Commands,
    active: Res<ActiveShellSequence>,
    roots: Query<&VanityCardSceneRoot>,
) {
    let Some((activation_id, segment_id, kind)) = active
        .registered_segment()
        .map(|(activation_id, segment_id, kind)| (activation_id, segment_id.clone(), kind.clone()))
    else {
        return;
    };
    if kind.as_str() != AMBITION_VANITY_CARD_SEGMENT_KIND {
        return;
    }
    if roots
        .iter()
        .any(|root| root.activation_id == activation_id && root.segment_id == segment_id)
    {
        return;
    }

    let mut bubble = None;
    let mut bubble_text = None;
    let mut device = None;
    let mut robot_arm = None;
    let mut human_arm = None;
    let mut robot_card = None;
    let mut human_card = None;

    let root_entity = commands
        .spawn((
            Node {
                position_type: PositionType::Absolute,
                left: Val::Px(0.0),
                right: Val::Px(0.0),
                top: Val::Px(0.0),
                bottom: Val::Px(0.0),
                justify_content: JustifyContent::Center,
                align_items: AlignItems::Center,
                ..default()
            },
            BackgroundColor(Color::srgba(0.03, 0.04, 0.07, 0.98)),
            GlobalZIndex(4_500),
            FrontendOwnedEntity::shell(activation_id, FrontendPresentationKind::StartupRoot),
            ShellSegmentScopedEntity {
                activation_id,
                segment_id: segment_id.clone(),
            },
            Name::new("Ambition Vanity Card Root"),
        ))
        .with_children(|root| {
            // ⚠ **no drop shadow.** The port drew one — a 78%-sized black
            // rectangle pinned 18px from the ROOT's top-left while the panel it
            // was shadowing is CENTRED, so at 1280x720 it sat 137px left and
            // 65px above the panel and read as a stray black rectangle rather
            // than a shadow. Photographed, not reasoned about. Drop shadows are
            // not this project's look in any case, so it is deleted rather than
            // realigned.

            root.spawn((
                Node {
                    width: Val::Percent(78.0),
                    max_width: Val::Px(980.0),
                    height: Val::Percent(78.0),
                    max_height: Val::Px(720.0),
                    border: UiRect::all(Val::Px(5.0)),
                    padding: UiRect::all(Val::Px(22.0)),
                    ..default()
                },
                BackgroundColor(Color::srgb(0.97, 0.95, 0.91)),
                BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                Name::new("Ambition Vanity Card Panel"),
            ))
            .with_children(|panel| {
                // ⚠ no caption row. The zip this was ported from drew "A
                // programmatic shell-startup card preview" here, which is a note
                // about the IMPLEMENTATION on a card whose whole job is the joke
                // — and it would have shipped in front of every boot.

                panel
                    .spawn((
                        Node {
                            flex_grow: 1.0,
                            width: Val::Percent(100.0),
                            position_type: PositionType::Relative,
                            ..default()
                        },
                        BackgroundColor(Color::srgb(0.94, 0.92, 0.87)),
                        Name::new("Ambition Vanity Card Stage"),
                    ))
                    .with_children(|stage| {
                        bubble = Some(
                            stage
                                .spawn((
                                    Node {
                                        position_type: PositionType::Absolute,
                                        width: Val::Percent(32.0),
                                        min_width: Val::Px(220.0),
                                        max_width: Val::Px(320.0),
                                        top: Val::Percent(7.0),
                                        left: Val::Percent(8.0),
                                        padding: UiRect::axes(Val::Px(18.0), Val::Px(14.0)),
                                        border: UiRect::all(Val::Px(4.0)),
                                        border_radius: BorderRadius::all(Val::Px(26.0)),
                                        ..default()
                                    },
                                    BackgroundColor(Color::srgb(1.0, 1.0, 1.0)),
                                    BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                    Visibility::Hidden,
                                    Name::new("Ambition Vanity Speech Bubble"),
                                ))
                                .with_children(|bubble_node| {
                                    bubble_text = Some(
                                        bubble_node
                                            .spawn((
                                                Text::new(""),
                                                TextFont {
                                                    font_size: 34.0,
                                                    ..default()
                                                },
                                                TextColor(Color::srgb(0.05, 0.05, 0.06)),
                                                TextLayout::new(
                                                    Justify::Center,
                                                    LineBreak::WordBoundary,
                                                ),
                                                Name::new("Ambition Vanity Speech Text"),
                                            ))
                                            .id(),
                                    );
                                })
                                .id(),
                        );

                        stage.spawn((
                            Node {
                                position_type: PositionType::Absolute,
                                left: Val::Percent(6.0),
                                right: Val::Percent(6.0),
                                bottom: Val::Percent(8.0),
                                height: Val::Px(6.0),
                                ..default()
                            },
                            BackgroundColor(Color::srgb(0.11, 0.10, 0.10)),
                            Name::new("Ambition Vanity Ground"),
                        ));

                        robot_card = Some(
                            stage
                                .spawn((
                                    Node {
                                        position_type: PositionType::Absolute,
                                        left: Val::Percent(8.0),
                                        bottom: Val::Percent(14.0),
                                        width: Val::Percent(27.0),
                                        min_width: Val::Px(220.0),
                                        max_width: Val::Px(280.0),
                                        height: Val::Percent(56.0),
                                        min_height: Val::Px(260.0),
                                        max_height: Val::Px(360.0),
                                        border: UiRect::all(Val::Px(4.0)),
                                        padding: UiRect::all(Val::Px(12.0)),
                                        border_radius: BorderRadius::all(Val::Px(18.0)),
                                        ..default()
                                    },
                                    BackgroundColor(Color::srgb(0.73, 0.92, 0.98)),
                                    BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                    Name::new("Ambition Vanity Robot Card"),
                                ))
                                .with_children(|robot| {
                                    robot.spawn((
                                        Text::new("AUTHORING ROBOT"),
                                        TextFont {
                                            font_size: 18.0,
                                            ..default()
                                        },
                                        TextColor(Color::srgb(0.06, 0.14, 0.18)),
                                        TextLayout::new(Justify::Center, LineBreak::NoWrap),
                                        Node {
                                            width: Val::Percent(100.0),
                                            ..default()
                                        },
                                        Name::new("Ambition Vanity Robot Label"),
                                    ));
                                    robot
                                        .spawn((
                                            Node {
                                                position_type: PositionType::Absolute,
                                                left: Val::Percent(25.0),
                                                top: Val::Percent(22.0),
                                                width: Val::Percent(50.0),
                                                height: Val::Percent(24.0),
                                                border: UiRect::all(Val::Px(4.0)),
                                                border_radius: BorderRadius::all(Val::Px(8.0)),
                                                ..default()
                                            },
                                            BackgroundColor(Color::srgb(0.18, 0.30, 0.36)),
                                            BorderColor::all(Color::srgb(0.08, 0.09, 0.11)),
                                            Name::new("Ambition Vanity Robot Head"),
                                        ))
                                        .with_children(|head| {
                                            head.spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    left: Val::Percent(18.0),
                                                    top: Val::Percent(38.0),
                                                    width: Val::Percent(18.0),
                                                    height: Val::Percent(20.0),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.94, 0.97, 1.0)),
                                                Name::new("Ambition Vanity Robot Eye Left"),
                                            ));
                                            head.spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    right: Val::Percent(18.0),
                                                    top: Val::Percent(38.0),
                                                    width: Val::Percent(18.0),
                                                    height: Val::Percent(20.0),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.94, 0.97, 1.0)),
                                                Name::new("Ambition Vanity Robot Eye Right"),
                                            ));
                                        });
                                    robot.spawn((
                                        Node {
                                            position_type: PositionType::Absolute,
                                            left: Val::Percent(27.0),
                                            top: Val::Percent(49.0),
                                            width: Val::Percent(46.0),
                                            height: Val::Percent(28.0),
                                            border: UiRect::all(Val::Px(4.0)),
                                            border_radius: BorderRadius::all(Val::Px(10.0)),
                                            ..default()
                                        },
                                        BackgroundColor(Color::srgb(0.32, 0.54, 0.62)),
                                        BorderColor::all(Color::srgb(0.08, 0.09, 0.11)),
                                        Name::new("Ambition Vanity Robot Body"),
                                    ));
                                    robot_arm = Some(
                                        robot
                                            .spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    right: Val::Px(-12.0),
                                                    top: Val::Percent(56.0),
                                                    width: Val::Px(84.0),
                                                    height: Val::Px(18.0),
                                                    border: UiRect::all(Val::Px(3.0)),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.32, 0.54, 0.62)),
                                                BorderColor::all(Color::srgb(0.08, 0.09, 0.11)),
                                                Name::new("Ambition Vanity Robot Arm"),
                                            ))
                                            .id(),
                                    );
                                })
                                .id(),
                        );

                        human_card = Some(
                            stage
                                .spawn((
                                    Node {
                                        position_type: PositionType::Absolute,
                                        right: Val::Percent(8.0),
                                        bottom: Val::Percent(14.0),
                                        width: Val::Percent(27.0),
                                        min_width: Val::Px(220.0),
                                        max_width: Val::Px(280.0),
                                        height: Val::Percent(56.0),
                                        min_height: Val::Px(260.0),
                                        max_height: Val::Px(360.0),
                                        border: UiRect::all(Val::Px(4.0)),
                                        padding: UiRect::all(Val::Px(12.0)),
                                        border_radius: BorderRadius::all(Val::Px(18.0)),
                                        ..default()
                                    },
                                    BackgroundColor(Color::srgb(0.99, 0.86, 0.69)),
                                    BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                    Name::new("Ambition Vanity Human Card"),
                                ))
                                .with_children(|human| {
                                    human.spawn((
                                        Text::new("VERY REAL HUMAN"),
                                        TextFont {
                                            font_size: 18.0,
                                            ..default()
                                        },
                                        TextColor(Color::srgb(0.20, 0.11, 0.06)),
                                        TextLayout::new(Justify::Center, LineBreak::NoWrap),
                                        Node {
                                            width: Val::Percent(100.0),
                                            ..default()
                                        },
                                        Name::new("Ambition Vanity Human Label"),
                                    ));
                                    human
                                        .spawn((
                                            Node {
                                                position_type: PositionType::Absolute,
                                                left: Val::Percent(30.0),
                                                top: Val::Percent(20.0),
                                                width: Val::Percent(40.0),
                                                height: Val::Percent(22.0),
                                                border: UiRect::all(Val::Px(4.0)),
                                                border_radius: BorderRadius::all(Val::Px(999.0)),
                                                ..default()
                                            },
                                            BackgroundColor(Color::srgb(0.98, 0.74, 0.56)),
                                            BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                            Name::new("Ambition Vanity Human Head"),
                                        ))
                                        .with_children(|head| {
                                            head.spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    left: Val::Percent(24.0),
                                                    top: Val::Percent(42.0),
                                                    width: Val::Percent(12.0),
                                                    height: Val::Percent(10.0),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.08, 0.08, 0.09)),
                                                Name::new("Ambition Vanity Human Eye Left"),
                                            ));
                                            head.spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    right: Val::Percent(24.0),
                                                    top: Val::Percent(42.0),
                                                    width: Val::Percent(12.0),
                                                    height: Val::Percent(10.0),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.08, 0.08, 0.09)),
                                                Name::new("Ambition Vanity Human Eye Right"),
                                            ));
                                        });
                                    human.spawn((
                                        Node {
                                            position_type: PositionType::Absolute,
                                            left: Val::Percent(29.0),
                                            top: Val::Percent(47.0),
                                            width: Val::Percent(42.0),
                                            height: Val::Percent(30.0),
                                            border: UiRect::all(Val::Px(4.0)),
                                            border_radius: BorderRadius::all(Val::Px(12.0)),
                                            ..default()
                                        },
                                        BackgroundColor(Color::srgb(0.90, 0.53, 0.31)),
                                        BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                        Name::new("Ambition Vanity Human Body"),
                                    ));
                                    human_arm = Some(
                                        human
                                            .spawn((
                                                Node {
                                                    position_type: PositionType::Absolute,
                                                    left: Val::Px(-12.0),
                                                    top: Val::Percent(56.0),
                                                    width: Val::Px(24.0),
                                                    height: Val::Px(18.0),
                                                    border: UiRect::all(Val::Px(3.0)),
                                                    border_radius: BorderRadius::all(Val::Px(
                                                        999.0,
                                                    )),
                                                    ..default()
                                                },
                                                BackgroundColor(Color::srgb(0.90, 0.53, 0.31)),
                                                BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                                Name::new("Ambition Vanity Human Arm"),
                                            ))
                                            .id(),
                                    );
                                })
                                .id(),
                        );

                        device = Some(
                            stage
                                .spawn((
                                    Node {
                                        position_type: PositionType::Absolute,
                                        left: Val::Percent(42.0),
                                        top: Val::Percent(57.0),
                                        width: Val::Px(118.0),
                                        height: Val::Px(78.0),
                                        border: UiRect::all(Val::Px(4.0)),
                                        justify_content: JustifyContent::Center,
                                        align_items: AlignItems::Center,
                                        border_radius: BorderRadius::all(Val::Px(14.0)),
                                        ..default()
                                    },
                                    BackgroundColor(Color::srgb(0.24, 0.26, 0.30)),
                                    BorderColor::all(Color::srgb(0.09, 0.09, 0.11)),
                                    Name::new("Ambition Vanity Game Cart"),
                                ))
                                .with_children(|game| {
                                    game.spawn((
                                        Text::new("GAME"),
                                        TextFont {
                                            font_size: 20.0,
                                            ..default()
                                        },
                                        TextColor(Color::srgb(0.95, 0.97, 1.0)),
                                        TextLayout::new(Justify::Center, LineBreak::NoWrap),
                                        Name::new("Ambition Vanity Game Label"),
                                    ));
                                })
                                .id(),
                        );
                    });
            });
        })
        .id();

    commands.entity(root_entity).insert(VanityCardSceneRoot {
        activation_id,
        segment_id,
        elapsed: Duration::ZERO,
        completion_sent: false,
        bubble: bubble.expect("bubble entity"),
        bubble_text: bubble_text.expect("bubble text entity"),
        device: device.expect("device entity"),
        robot_arm: robot_arm.expect("robot arm entity"),
        human_arm: human_arm.expect("human arm entity"),
        robot_card: robot_card.expect("robot card entity"),
        human_card: human_card.expect("human card entity"),
    });
}

fn animate_programmatic_vanity_card(
    time: Res<Time>,
    mut roots: Query<&mut VanityCardSceneRoot>,
    mut nodes: Query<&mut Node>,
    mut visibilities: Query<&mut Visibility>,
    mut backgrounds: Query<&mut BackgroundColor>,
    mut texts: Query<&mut Text>,
    mut commands: MessageWriter<ShellSequenceCommand>,
) {
    for mut root in &mut roots {
        root.elapsed = (root.elapsed + time.delta()).min(programmatic_vanity_card_duration());
        let state = sample_state(root.elapsed);

        if let Ok(mut bubble_node) = nodes.get_mut(root.bubble) {
            bubble_node.left = Val::Percent(state.bubble_left_pct);
            bubble_node.top = Val::Percent(7.0);
        }
        if let Ok(mut visibility) = visibilities.get_mut(root.bubble) {
            *visibility = if state.bubble_text.is_empty() {
                Visibility::Hidden
            } else {
                Visibility::Visible
            };
        }
        if let Ok(mut text) = texts.get_mut(root.bubble_text) {
            text.0 = state.bubble_text.to_string();
        }

        if let Ok(mut node) = nodes.get_mut(root.device) {
            node.left = Val::Percent(state.device_left_pct);
            node.top = Val::Percent(state.device_top_pct);
        }
        if let Ok(mut node) = nodes.get_mut(root.robot_arm) {
            node.width = Val::Px(state.robot_arm_width_px);
        }
        if let Ok(mut node) = nodes.get_mut(root.human_arm) {
            node.width = Val::Px(state.human_arm_width_px);
        }
        if let Ok(mut node) = nodes.get_mut(root.robot_card) {
            node.bottom = Val::Percent(state.robot_bottom_pct);
        }
        if let Ok(mut node) = nodes.get_mut(root.human_card) {
            node.bottom = Val::Percent(state.human_bottom_pct);
        }
        if let Ok(mut bg) = backgrounds.get_mut(root.robot_card) {
            *bg = BackgroundColor(if state.robot_emphasis {
                Color::srgb(0.80, 0.95, 1.0)
            } else {
                Color::srgb(0.73, 0.92, 0.98)
            });
        }
        if let Ok(mut bg) = backgrounds.get_mut(root.human_card) {
            *bg = BackgroundColor(if state.human_emphasis {
                Color::srgb(1.0, 0.92, 0.75)
            } else {
                Color::srgb(0.99, 0.86, 0.69)
            });
        }

        if !root.completion_sent && root.elapsed >= programmatic_vanity_card_duration() {
            commands.write(ShellSequenceCommand::ProgrammaticSegmentCompleted {
                activation_id: root.activation_id,
                segment_id: root.segment_id.clone(),
            });
            root.completion_sent = true;
        }
    }
}

#[derive(Clone, Copy)]
struct VanityCardSceneState {
    bubble_text: &'static str,
    bubble_left_pct: f32,
    device_left_pct: f32,
    device_top_pct: f32,
    robot_arm_width_px: f32,
    human_arm_width_px: f32,
    robot_bottom_pct: f32,
    human_bottom_pct: f32,
    robot_emphasis: bool,
    human_emphasis: bool,
}

fn sample_state(elapsed: Duration) -> VanityCardSceneState {
    let beats = beats();

    if elapsed < beats.intro {
        let mut pose = frame_pose(0);
        pose.bubble_text = "I MADE THIS";
        pose.bubble_left_pct = 8.0;
        pose.robot_emphasis = true;
        return pose;
    }

    let mut t = elapsed - beats.intro;
    if t < beats.handoff {
        let frame = ((t.as_secs_f32() / beats.handoff.as_secs_f32()) * 6.0)
            .floor()
            .clamp(0.0, 5.0) as usize;
        return frame_pose(frame);
    }

    t -= beats.handoff;
    if t < beats.question {
        let mut pose = frame_pose(5);
        pose.bubble_text = "YOU MADE THIS?";
        pose.bubble_left_pct = 58.0;
        pose.human_emphasis = true;
        return pose;
    }

    t -= beats.question;
    if t < beats.replay {
        // The glance back is the first half of the replay beat, whatever that
        // beat's length works out to — a fixed 250ms would silently become the
        // whole beat if the authored card ever got shorter.
        let frame = if t < beats.replay / 2 { 4 } else { 5 };
        return frame_pose(frame);
    }

    let mut pose = frame_pose(5);
    pose.bubble_text = "I MADE THIS";
    pose.bubble_left_pct = 60.0;
    pose.human_emphasis = true;
    pose.human_bottom_pct = 15.5;
    pose.device_top_pct = 55.5;
    pose
}

fn frame_pose(frame: usize) -> VanityCardSceneState {
    match frame {
        0 => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 39.0,
            device_top_pct: 58.0,
            robot_arm_width_px: 82.0,
            human_arm_width_px: 24.0,
            robot_bottom_pct: 14.0,
            human_bottom_pct: 14.0,
            robot_emphasis: false,
            human_emphasis: false,
        },
        1 => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 43.0,
            device_top_pct: 57.5,
            robot_arm_width_px: 98.0,
            human_arm_width_px: 36.0,
            robot_bottom_pct: 14.3,
            human_bottom_pct: 14.0,
            robot_emphasis: false,
            human_emphasis: false,
        },
        2 => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 47.0,
            device_top_pct: 57.0,
            robot_arm_width_px: 112.0,
            human_arm_width_px: 56.0,
            robot_bottom_pct: 14.6,
            human_bottom_pct: 14.4,
            robot_emphasis: false,
            human_emphasis: false,
        },
        3 => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 51.0,
            device_top_pct: 56.8,
            robot_arm_width_px: 118.0,
            human_arm_width_px: 78.0,
            robot_bottom_pct: 14.2,
            human_bottom_pct: 14.9,
            robot_emphasis: false,
            human_emphasis: false,
        },
        4 => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 54.5,
            device_top_pct: 56.2,
            robot_arm_width_px: 108.0,
            human_arm_width_px: 102.0,
            robot_bottom_pct: 14.0,
            human_bottom_pct: 15.2,
            robot_emphasis: false,
            human_emphasis: false,
        },
        _ => VanityCardSceneState {
            bubble_text: "",
            bubble_left_pct: 8.0,
            device_left_pct: 58.0,
            device_top_pct: 56.0,
            robot_arm_width_px: 92.0,
            human_arm_width_px: 124.0,
            robot_bottom_pct: 14.0,
            human_bottom_pct: 15.0,
            robot_emphasis: false,
            human_emphasis: false,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// ⚠ **this replaces a test that could not fail.** The ported version
    /// asserted `programmatic_vanity_card_duration() == vanity_card_total_duration()`,
    /// which is now the function's own body — green by construction, and it
    /// would stay green while the beats it schedules summed to something else
    /// entirely. THAT is the failure the original had: five absolute constants
    /// summing to 3900 ms against an authored 3902.
    ///
    /// So the property is the one integer division can actually break — the
    /// five beats reconstitute the whole card, leaving no unscheduled tail.
    #[test]
    fn the_beats_sum_to_the_whole_card_with_nothing_left_over() {
        let beats = beats();
        assert_eq!(
            beats.intro + beats.handoff + beats.question + beats.replay + beats.claim,
            programmatic_vanity_card_duration(),
            "the beats must reconstitute the card the host scheduled",
        );
    }

    #[test]
    fn opener_and_punchline_land_on_the_expected_speaker() {
        let intro = sample_state(Duration::from_millis(100));
        assert_eq!(intro.bubble_text, "I MADE THIS");
        assert!(intro.robot_emphasis);

        let end = sample_state(programmatic_vanity_card_duration());
        assert_eq!(end.bubble_text, "I MADE THIS");
        assert!(end.human_emphasis);
    }
}
