//! Bevy `EmbeddedAssetRegistry` integration for platformer assets.
//!
//! This module couples embedded URL constants with their `include_bytes!`
//! registrations. Catalog tests verify each URL also has an authored candidate.
//! World JSON registrations come from installed `WorldManifest` rows.

use bevy::prelude::{App, Plugin};

use crate::AssetProfile;

/// Declarative embedded-core table. Each row emits the public URL constant, an
/// `ALL_URLS` entry, and the matching registry insertion. Include paths are
/// relative to this source file.
macro_rules! embed_core_assets {
    (
        $( $name:ident => $url:literal @ $rel_path:literal ),* $(,)?
    ) => {
        pub mod embedded_core {
            //! Public URL constants for every embedded core asset.
            //! Generated by the `embed_core_assets!` macro in
            //! `super`. Catalog candidates and registry
            //! insertions both reference these constants by name.
            $( pub const $name: &str = $url; )*

            /// Every embedded core URL, in declaration order. The
            /// `embedded_core_urls_are_unique` and
            /// `embedded_core_urls_have_authored_catalog_candidates`
            /// tests walk this slice.
            #[allow(dead_code)] // Used only by tests / future packaging tools.
            pub const ALL_URLS: &[&str] = &[ $( $name ),* ];
        }

        /// Insert every embedded core asset's bytes into Bevy's
        /// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`]. Gated
        /// by `static_core_assets` because the bytes are pulled in via
        /// `include_bytes!` from `crates/ambition_platformer2d_actor_monolith/assets/...`.
        #[cfg(feature = "static_core_assets")]
        fn register_embedded_core_assets(app: &mut ::bevy::prelude::App) {
            use ::bevy::asset::io::embedded::EmbeddedAssetRegistry;
            use ::std::path::{Path, PathBuf};
            let embedded = app
                .world_mut()
                .resource_mut::<EmbeddedAssetRegistry>();
            $(
                embedded.insert_asset(
                    PathBuf::new(),
                    Path::new(embedded_core::$name),
                    include_bytes!($rel_path) as &[u8],
                );
            )*
        }
    };
}

embed_core_assets! {
    // ── UI fonts ────────────────────────────────────────────────────
    FONT_DIALOG_REGULAR_URL =>
        "ambition_platformer2d_actor_monolith/fonts/bundled/InterDisplay-Regular.otf"
        @ "../../../ambition_platformer2d_actor_monolith/assets/fonts/bundled/InterDisplay-Regular.otf",
    FONT_DIALOG_SEMIBOLD_URL =>
        "ambition_platformer2d_actor_monolith/fonts/bundled/InterDisplay-SemiBold.otf"
        @ "../../../ambition_platformer2d_actor_monolith/assets/fonts/bundled/InterDisplay-SemiBold.otf",
    FONT_DEBUG_MONO_URL =>
        "ambition_platformer2d_actor_monolith/fonts/bundled/JetBrainsMono-Regular.ttf"
        @ "../../../ambition_platformer2d_actor_monolith/assets/fonts/bundled/JetBrainsMono-Regular.ttf",

    // ── Primary character spritesheets ──────────────────────────────
    SPRITE_PLAYER_URL =>
        "ambition_platformer2d_actor_monolith/sprites/player_robot_v3_spritesheet.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/player_robot_v3_spritesheet.png",
    SPRITE_ROBOT_URL =>
        "ambition_platformer2d_actor_monolith/sprites/robot_spritesheet.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/robot_spritesheet.png",
    SPRITE_GOBLIN_URL =>
        "ambition_platformer2d_actor_monolith/sprites/goblin_spritesheet.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/goblin_spritesheet.png",
    SPRITE_SANDBAG_URL =>
        "ambition_platformer2d_actor_monolith/sprites/sandbag_spritesheet.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/sandbag_spritesheet.png",

    // ── Core entity sprites ─────────────────────────────────────────
    SPRITE_CHEST_CLOSED_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/chest_closed.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/chest_closed.png",
    SPRITE_CHEST_OPEN_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/chest_open.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/chest_open.png",
    SPRITE_PICKUP_HEALTH_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/pickup_health.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/pickup_health.png",
    SPRITE_PICKUP_CURRENCY_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/pickup_currency.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/pickup_currency.png",
    SPRITE_PICKUP_ABILITY_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/pickup_ability.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/pickup_ability.png",
    SPRITE_DOOR_ZONE_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/door_zone.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/door_zone.png",
    SPRITE_EDGE_EXIT_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/edge_exit.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/edge_exit.png",
    SPRITE_PROJECTILE_ENERGY_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/projectile_energy.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/projectile_energy.png",
    SPRITE_SOLID_TILE_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/solid_tile.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/solid_tile.png",
    SPRITE_ONE_WAY_TILE_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/one_way_tile.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/one_way_tile.png",
    SPRITE_HAZARD_TILE_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/hazard_tile.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/hazard_tile.png",
    SPRITE_BOSS_CORE_URL =>
        "ambition_platformer2d_actor_monolith/sprites/entities/boss_core.png"
        @ "../../../ambition_platformer2d_actor_monolith/assets/sprites/entities/boss_core.png",
}

/// Registers embedded catalog assets and installed world JSON with Bevy.
///
/// The registry is created by Bevy's `AssetPlugin`, so this plugin must run
/// after `DefaultPlugins`. World rows use the same `embedded_bevy_path` authored
/// by their `EmbeddedBinary` catalog candidate.
pub struct AmbitionAssetSourcePlugin {
    pub profile: AssetProfile,
    pub embedded_worlds: Vec<EmbeddedWorldAsset>,
}

impl AmbitionAssetSourcePlugin {
    pub fn for_profile(profile: AssetProfile) -> Self {
        Self {
            profile,
            embedded_worlds: Vec::new(),
        }
    }

    pub fn with_embedded_worlds(
        profile: AssetProfile,
        embedded_worlds: Vec<EmbeddedWorldAsset>,
    ) -> Self {
        Self {
            profile,
            embedded_worlds,
        }
    }
}

impl Plugin for AmbitionAssetSourcePlugin {
    fn build(&self, app: &mut App) {
        register_embedded_assets(app, &self.embedded_worlds);
        // Future profile-conditional source registration (HTTP / IPFS /
        // user-data) hooks here.
        let _ = self.profile;
    }
}

/// Embedded LDtk world bytes supplied by the game/content layer.
#[derive(Clone, Debug)]
pub struct EmbeddedWorldAsset {
    pub bevy_path: &'static str,
    pub text: &'static str,
}

/// Insert every embedded asset's bytes into Bevy's
/// [`bevy::asset::io::embedded::EmbeddedAssetRegistry`] under the
/// URLs the catalog's `Embedded` candidates point at.
///
/// Two independent feature gates:
/// - `static_map` — LDtk world JSON (sandbox + intro).
/// - `static_core_assets` — UI fonts + primary character sheets + core
///   entity sprites (see [`embedded_core`] for the URL constants).
///
/// Adding a new embedded asset is a three-line change:
/// 1. add a `const FOO_URL: &str = "ambition_platformer2d_actor_monolith/..."` to
///    [`embedded_core`] and append it to `ALL_URLS`;
/// 2. add a matching `with_embedded_core_candidate(entry, FOO_URL)`
///    on the catalog entry;
/// 3. add an `EmbeddedAssetRegistry::insert_asset(...,
///    include_bytes!("../../../ambition_platformer2d_actor_monolith/assets/..."))` call in
///    [`register_embedded_core_assets`] above.
///
/// The `embedded_core_paths_match_registration_constants` test fails
/// loudly if any one of those three pieces is missing.
#[allow(unused_variables)]
fn register_embedded_assets(app: &mut App, embedded_worlds: &[EmbeddedWorldAsset]) {
    // World JSON: every installed WorldManifest row that carries embedded
    // text registers its bytes under the row's EmbeddedBinary URL — the
    // same text the serde loader parses, so the two embedded
    // representations can never diverge.
    {
        use bevy::asset::io::embedded::EmbeddedAssetRegistry;
        use std::path::{Path, PathBuf};

        let embedded = app.world_mut().resource_mut::<EmbeddedAssetRegistry>();
        for source in embedded_worlds {
            embedded.insert_asset(
                PathBuf::new(),
                Path::new(source.bevy_path),
                source.text.as_bytes(),
            );
        }
    }
    #[cfg(feature = "static_core_assets")]
    register_embedded_core_assets(app);
}
