//! Audio builders: packed SFX bank + per-track music entries.

use ambition_asset_manager::{
    AssetEntry, AssetKind, AssetLocation, AssetManifest, AssetSourceProfile, MissingAssetPolicy,
    PreloadGroup,
};

use super::super::ids;
use crate::session::data::MusicRegistry;

/// Packed SFX bank entry. `WarnAndPlaceholder` matches the current
/// runtime contract: a missing bank degrades to procedural / silent
/// SFX instead of refusing to start.
///
/// `AMBITION_SFX_BANK_PATH` is honored as an explicit
/// `LooseFilesystem` `LocationCandidate` so dev workflows can point
/// the sandbox at a freshly-packed bank without re-publishing assets.
pub(in super::super) fn extend_with_sfx_bank_entry(manifest: &mut AssetManifest) {
    let mut entry = AssetEntry::new(ids::sfx_bank(), AssetKind::AudioBank, "audio/sfx.bank")
        .with_missing_policy(MissingAssetPolicy::WarnAndPlaceholder)
        .with_preload_group(PreloadGroup::SandboxCore);
    if let Ok(env_path) = std::env::var("AMBITION_SFX_BANK_PATH") {
        entry = entry.with_location(
            AssetSourceProfile::LooseFilesystem,
            AssetLocation::LocalPath(std::path::PathBuf::from(env_path)),
        );
    }
    manifest.insert(entry);
}

/// Music track entries — one per [`crate::session::data::MusicTrack`] in
/// the music registry. Each resolves to a pre-rendered OGG via
/// [`crate::session::data::MusicTrack::resolved_asset_path`] (the explicit
/// `asset_path` override, else `audio/music/generated/<id>/full.ogg`). A
/// genuinely missing OGG degrades to a placeholder at load time; the
/// procedural fundsp music generator was retired (see
/// `docs/archive/retired/fundsp-audio.md`). Author cues via
/// `tools/ambition_music_renderer`; `music_registry.ron` is generated by
/// `scripts/regen_music_registry.py`.
pub(in super::super) fn extend_with_music_entries(
    manifest: &mut AssetManifest,
    music: &MusicRegistry,
) {
    for track in &music.tracks {
        let id = ids::music_track(&track.id);
        manifest.insert(
            AssetEntry::new(id, AssetKind::AudioClip, track.resolved_asset_path())
                .with_missing_policy(MissingAssetPolicy::WarnAndPlaceholder)
                .with_preload_group(PreloadGroup::SandboxCore),
        );
    }
}
