//! Sanic-style demo content home.
//!
//! This crate intentionally depends only on the `ambition` facade crate. It is
//! the E9 engine-for-other-games ORACLE: a second platformer's content is
//! authored entirely through the umbrella surface, never by reaching into a
//! lower `ambition_*` crate or copying `game/ambition_app`'s dependency wall.
//! If authoring a room here needs a type the umbrella does not re-export, that
//! is a real engine leak — and it fails to compile HERE, which is the point.
//!
//! What lives here is the SHOWCASE COURSE — rolling hills, a rideable loop,
//! springs, one-way platforms, a pit, monitors, and badniks — plus the
//! mode-local rules that make progress legible through milestone SFX. The
//! SPATIAL layout is authored in the demo's own LDtk file
//! (`assets/worlds/sanic_speedway.ldtk`, generated by
//! `tools/author_speedway_ldtk.py`); the LOOP route (depth lanes + junctions,
//! which LDtk has no vocabulary for) is grafted onto the loaded room in
//! [`sanic_speedway`]. The windowed shell loads the shared Ambition art tree
//! through the public facade, so generated Sanic art and existing parallax /
//! block assets light up without an `ambition_app` dependency.

use ambition::engine_core as ae;
use ambition::prelude::*;
use ambition::world::rooms::RoomSpec;

/// Stable room id for the momentum speedway.
pub const SPEEDWAY_ROOM_ID: &str = "sanic_speedway";

/// The game-MODE tag this demo's rooms carry (decomposition D-C).
///
/// Ambition hosts this demo by loading its rooms alongside its own; a Sanic
/// rules plugin gates its systems on `ambition::runtime::in_mode(SANIC_MODE)`
/// so they sleep everywhere else. [`SanicRulesPlugin`] is that ruleset, and its
/// `hosted()` / `global()` constructor flag is the D-C pattern made real.
pub const SANIC_MODE: &str = "sanic";

/// Authored soundtrack for the standalone Sanic demo. The rendered asset lives
/// in the shared engine asset tree beside the other generated music tracks.
pub const SANIC_MUSIC_ASSET_PATH: &str = "audio/music/generated/you_are_too_slow/full.ogg";

/// Number of segments in the full 360-degree loop body.
pub const LOOP_SEGMENTS: usize = 128;

/// Samples in the raised entry ramp. The ramp, loop, and runout are one open
/// surface route; there is no chain-transfer seam at either side of the loop.
pub const LOOP_RAMP_SEGMENTS: usize = 32;

/// Samples in the post-loop route: a flat foreground overpass clears the
/// crossover before a separate descent returns to the tiled floor.
pub const LOOP_RUNOUT_SEGMENTS: usize = 32;

/// Flat samples after the full revolution. Keeping the rider attached until it
/// is horizontally clear of the inbound rail is the physical half of the 2.5D
/// crossover; depth ordering supplies the visual half.
pub const LOOP_OVERPASS_SEGMENTS: usize = 12;

/// Remaining samples in the descent from the overpass to the floor.
pub const LOOP_DESCENT_SEGMENTS: usize = LOOP_RUNOUT_SEGMENTS - LOOP_OVERPASS_SEGMENTS;

/// Index of the loop's first arc point inside the combined route.
pub const LOOP_ENTRY_POINT_INDEX: usize = LOOP_RAMP_SEGMENTS;

/// Index where the full loop returns to the crossover after 360 degrees.
pub const LOOP_CLOSURE_POINT_INDEX: usize = LOOP_ENTRY_POINT_INDEX + LOOP_SEGMENTS;

/// Lower-arc segments rendered in front of the player on each side of the
/// loop. The remaining loop body is on the ordinary/back lane.
pub const LOOP_FOREGROUND_SEGMENTS_PER_SIDE: usize = 22;

/// Index of the route's final floor-level runout point.
pub const LOOP_EXIT_POINT_INDEX: usize = LOOP_CLOSURE_POINT_INDEX + LOOP_RUNOUT_SEGMENTS;

const LOOP_RADIUS: f32 = 180.0;
const LOOP_START_ANGLE: f32 = std::f32::consts::FRAC_PI_2;
const LOOP_SWEEP_ANGLE: f32 = std::f32::consts::TAU;
const LOOP_CENTER_X: f32 = 2200.0;
const LOOP_TRACK_RISE: f32 = 84.0;
const LOOP_RAMP_START_X: f32 = 1740.0;
const LOOP_OVERPASS_END_X: f32 = 2480.0;
const LOOP_RUNOUT_END_X: f32 = 2920.0;

/// Course dimensions, mirrored by `tools/author_speedway_ldtk.py` (the level
/// generator) — the loop graft and the oracles anchor on these.
pub const LEVEL_WIDTH: f32 = 6400.0;
pub const FLOOR_TOP: f32 = 672.0;
/// The pit: the west floor route ends at the left lip, the east runout route
/// starts at the right lip, and a hazard strip rests at the bottom.
pub const PIT_LEFT_X: f32 = 4000.0;
pub const PIT_RIGHT_X: f32 = 4256.0;

/// The LDtk world this demo ships — a SEPARATE file from Ambition's worlds,
/// embedded so the standalone shell needs no asset-root negotiation. Authored
/// by `tools/author_speedway_ldtk.py` through `ambition_ldtk_tools`; never
/// hand-edited.
pub const SPEEDWAY_WORLD_JSON: &str = include_str!("../assets/worlds/sanic_speedway.ldtk");

fn cubic_bezier(p0: ae::Vec2, p1: ae::Vec2, p2: ae::Vec2, p3: ae::Vec2, t: f32) -> ae::Vec2 {
    let u = 1.0 - t;
    p0 * (u * u * u) + p1 * (3.0 * u * u * t) + p2 * (3.0 * u * t * t) + p3 * (t * t * t)
}

/// Build one continuous entry-ramp → full-loop → runout route.
///
/// The loop starts at its bottom with a horizontal tangent, makes a complete
/// 360-degree revolution, returns to the same screen-space point at a later arc
/// length, and continues into a distinct runout. The repeated point is a 2.5D
/// crossover: per-segment depth lanes distinguish the inbound/back rail from the
/// outbound/front rail while the riding solver follows one unambiguous arc-length
/// route. This is the classic Sonic topology rather than a literal planar circle.
fn raised_full_loop_points(floor_top: f32) -> (Vec<ae::Vec2>, ae::Vec2) {
    let center = ae::Vec2::new(LOOP_CENTER_X, floor_top - LOOP_TRACK_RISE - LOOP_RADIUS);
    let ramp_start = ae::Vec2::new(LOOP_RAMP_START_X, floor_top);
    let loop_start =
        center + ae::Vec2::new(LOOP_START_ANGLE.cos(), LOOP_START_ANGLE.sin()) * LOOP_RADIUS;
    debug_assert!((loop_start.y - (floor_top - LOOP_TRACK_RISE)).abs() < 1.0e-3);

    let mut points =
        Vec::with_capacity(1 + LOOP_RAMP_SEGMENTS + LOOP_SEGMENTS + LOOP_RUNOUT_SEGMENTS);
    points.push(ramp_start);

    // Rise from the tiled floor to the loop bottom with a horizontal tangent at
    // both ends. The first segment is a real ramp, not a teleport or rebound-only
    // gap, while the final tangent exactly matches the loop's bottom tangent.
    let ramp_control_1 = ramp_start + ae::Vec2::new(150.0, 0.0);
    let ramp_control_2 = loop_start - ae::Vec2::new(170.0, 0.0);
    for step in 1..=LOOP_RAMP_SEGMENTS {
        let t = step as f32 / LOOP_RAMP_SEGMENTS as f32;
        points.push(cubic_bezier(
            ramp_start,
            ramp_control_1,
            ramp_control_2,
            loop_start,
            t,
        ));
    }

    // Decreasing theta gives the rideable inward normals expected by the
    // surface kernel. The final sample intentionally equals `loop_start`: it is
    // non-adjacent to the entry sample, so no degenerate segment is introduced.
    for step in 1..=LOOP_SEGMENTS {
        let t = step as f32 / LOOP_SEGMENTS as f32;
        let theta = LOOP_START_ANGLE - LOOP_SWEEP_ANGLE * t;
        points.push(center + ae::Vec2::new(theta.cos(), theta.sin()) * LOOP_RADIUS);
    }

    // Cross the loop mouth on a flat foreground deck first. A high-speed rider
    // may legitimately launch when a track begins descending; doing that at the
    // coincident inbound/outbound point lets the airborne circle immediately
    // re-hit the back rail. The flat deck keeps the rider attached until the
    // simulated-depth crossover is physically clear.
    let overpass_end = ae::Vec2::new(LOOP_OVERPASS_END_X, loop_start.y);
    for step in 1..=LOOP_OVERPASS_SEGMENTS {
        let t = step as f32 / LOOP_OVERPASS_SEGMENTS as f32;
        points.push(loop_start.lerp(overpass_end, t));
    }

    // Descend only after clearing the loop's rightmost extent. Both cubic end
    // tangents are horizontal, so the overpass/descent seam and the return to
    // the tiled floor are smooth. Launching from this convex descent is valid
    // Sonic behavior because no back-lane rail remains underneath it.
    let runout_end = ae::Vec2::new(LOOP_RUNOUT_END_X, floor_top);
    let runout_control_1 = overpass_end + ae::Vec2::new(120.0, 0.0);
    let runout_control_2 = runout_end - ae::Vec2::new(160.0, 0.0);
    for step in 1..=LOOP_DESCENT_SEGMENTS {
        let t = step as f32 / LOOP_DESCENT_SEGMENTS as f32;
        points.push(cubic_bezier(
            overpass_end,
            runout_control_1,
            runout_control_2,
            runout_end,
            t,
        ));
    }

    (points, center)
}

/// Canonical transform pair for the demo's semantic Utility action (D in the
/// classic arrows+Z/X/C preset).
pub const SANIC_CHARACTER_ID: &str = "sanic";
pub const SUPER_SANIC_CHARACTER_ID: &str = "super_sanic";

/// Visually authored distance markers. The floating marker platforms (in the
/// LDtk file) and the one-shot milestone SFX share this table so the eye and
/// ear measure the same positions instead of drifting as the speedway changes.
pub const SPEED_MARKER_XS: [f32; 5] = [808.0, 1608.0, 2600.0, 3608.0, 5000.0];

/// Build the Sanic showcase room: parse the demo's own LDtk world (hills,
/// pit, springs, platforms, monitors, badniks — everything spatial), then
/// graft the code-generated loop route onto it. The loop stays code-side
/// because its depth lanes and route junctions have no LDtk vocabulary; it
/// anchors on floor-chain vertices the level generator authors at
/// [`struct@LOOP_RAMP_START_X`]/[`struct@LOOP_RUNOUT_END_X`], and this
/// function panics loudly if the two files drift.
pub fn sanic_speedway() -> RoomSpec {
    let project = ambition::ldtk_map::LdtkProject::from_json_str(SPEEDWAY_WORLD_JSON)
        .expect("sanic_speedway.ldtk parses (regen: game/ambition_demo_sanic/tools/author_speedway_ldtk.py)");
    let room_set = project
        .to_room_set_with_entry(SPEEDWAY_ROOM_ID)
        .unwrap_or_else(|errors| panic!("sanic_speedway.ldtk converts to rooms: {errors:?}"));
    let mut room = room_set
        .rooms
        .into_iter()
        .find(|room| room.id == SPEEDWAY_ROOM_ID)
        .expect("the world file authors the sanic_speedway area");

    let loop_center = graft_loop_route(&mut room.world);
    // The LDtk EnemySpawn entities carry positions and the roster brain key;
    // the demo supplies the render identity (the catalog display name that
    // resolves the badnik sheet).
    for spawn in &mut room.enemy_spawns {
        spawn.name = badnik::BADNIK_DISPLAY_NAME.to_string();
    }
    room.metadata.mode = Some(SANIC_MODE.to_string());
    // Borrow Ambition's generated skybridge stack. The visible shell loads the
    // shared `GameAssets`; if those optional images are absent the renderer keeps
    // the deterministic clear-color + landmark geometry fallback.
    room.metadata.biome = Some("skybridge".to_string());
    room.metadata.visual_theme = Some("skybridge".to_string());
    room.metadata.visual_profile.id = Some("sanic_speedway".to_string());
    room.metadata.visual_profile.parallax_theme = Some("skybridge".to_string());

    // World-space labels turn the speedway into a ruler. They are ordinary room
    // debug labels rendered by the generic presentation face, not app-local UI.
    let mut labels = vec![
        (
            "start".to_string(),
            "START   Z: JUMP   DOWN+X: REV   RELEASE DOWN: DASH   D: SUPER".to_string(),
            ae::Vec2::new(300.0, FLOOR_TOP - 230.0),
        ),
        (
            "loop".to_string(),
            "LOOP".to_string(),
            ae::Vec2::new(loop_center.x, loop_center.y - LOOP_RADIUS - 36.0),
        ),
        (
            "finish".to_string(),
            "FINISH".to_string(),
            ae::Vec2::new(LEVEL_WIDTH - 130.0, FLOOR_TOP - 300.0),
        ),
    ];
    labels.extend(SPEED_MARKER_XS.into_iter().enumerate().map(|(index, x)| {
        (
            format!("marker_{}", index + 1),
            format!("{x:.0}"),
            ae::Vec2::new(x, FLOOR_TOP - 280.0),
        )
    }));
    room.debug_labels = labels
        .into_iter()
        .map(|(id, text, position)| {
            ambition::world::rooms::Authored::new(
                format!("sanic_{id}"),
                text.clone(),
                ae::Aabb::new(position, ae::Vec2::splat(1.0)),
                ambition::world::debug_label::DebugLabel::new(
                    text,
                    position,
                    ambition::world::debug_label::DebugLabelKind::Custom,
                ),
            )
        })
        .collect();
    room
}

/// Graft the ramp→loop→runout route (the code-generated topology LDtk cannot
/// express: per-segment depth lanes + the loop-mouth / floor-fork junctions)
/// onto the LDtk-loaded world, and return the loop center for the label.
///
/// The loop chain is INSERTED AT INDEX 0 so long-lived test fixtures keep the
/// loop as `chains[0]`; junction ports name the floor route by its post-insert
/// index. Anchor vertices are looked up by POSITION on the authored floor
/// chain, so if the level generator and these constants drift the panic names
/// the exact seam.
fn graft_loop_route(world: &mut ae::World) -> ae::Vec2 {
    let (ramp_loop_points, loop_center) = raised_full_loop_points(FLOOR_TOP);
    let mut loop_depths = vec![0_i8; ramp_loop_points.len() - 1];
    // The approach lives behind the player. The two lower loop shoulders and
    // the outbound runout live in front, creating the classic inside/outside
    // crossover without adding a second collision surface.
    loop_depths[..LOOP_RAMP_SEGMENTS].fill(-1);
    let front = LOOP_FOREGROUND_SEGMENTS_PER_SIDE.min(LOOP_SEGMENTS / 2);
    loop_depths[LOOP_ENTRY_POINT_INDEX..LOOP_ENTRY_POINT_INDEX + front].fill(1);
    loop_depths[LOOP_CLOSURE_POINT_INDEX - front..].fill(1);

    let floor_index = world
        .chains
        .iter()
        .position(|chain| chain.name == "sanic_floor_route")
        .expect("the LDtk world authors the sanic_floor_route chain");
    let vertex_at = |x: f32| {
        world.chains[floor_index]
            .points
            .iter()
            .position(|p| (p.x - x).abs() < 0.5 && (p.y - FLOOR_TOP).abs() < 0.5)
            .unwrap_or_else(|| {
                panic!(
                    "sanic_floor_route must have a junction anchor vertex at \
                     ({x}, {FLOOR_TOP}) — regenerate the level with \
                     tools/author_speedway_ldtk.py"
                )
            })
    };
    let ramp_vertex = vertex_at(LOOP_RAMP_START_X);
    let runout_vertex = vertex_at(LOOP_RUNOUT_END_X);
    // Momentum bodies ride the authored floor guide over the solid ground.
    // The floor/ramp split is a first-class route junction: the player keeps
    // running on the floor or holds toward the raised ramp, no airborne hack.
    let floor_after_insert = floor_index + 1;
    let ramp_loop = ae::SurfaceChain::open("sanic_loop", ramp_loop_points)
        .with_segment_depths(loop_depths)
        .with_junctions(vec![
            ae::SurfaceJunction::new(vec![LOOP_ENTRY_POINT_INDEX, LOOP_CLOSURE_POINT_INDEX]),
            ae::SurfaceJunction::across(vec![
                ae::SurfacePort::local(0),
                ae::SurfacePort::chain(floor_after_insert, ramp_vertex),
            ]),
            ae::SurfaceJunction::across(vec![
                ae::SurfacePort::local(LOOP_EXIT_POINT_INDEX),
                ae::SurfacePort::chain(floor_after_insert, runout_vertex),
            ]),
        ]);
    world.chains.insert(0, ramp_loop);

    // The IntGrid-lowered ground keeps Ambition's tiled block-art fill: re-id
    // the floor-level solids the way the old code-built room did.
    let mut ground_index = 0;
    for block in &mut world.blocks {
        if matches!(block.kind, ae::BlockKind::Solid) && (block.aabb.min.y - FLOOR_TOP).abs() < 0.5
        {
            block.id = ae::GeoId::tile_layer("sanic_speedway_ground", ground_index);
            ground_index += 1;
        }
    }
    loop_center
}

/// The demo's two-form catalog. Every demo installs its own roster; the engine
/// ships none (ADR 0017). The visible shell resolves both generated Sanic forms
/// through the shared Ambition asset catalog. Missing local artifacts remain a
/// loud, marked fallback rather than a second sprite path.
const SANIC_CATALOG_RON: &str = r#"(
    brain_presets: { "stand_still": StandStill },
    action_set_presets: {
        // A peaceful speedster: the momentum ride + ball dash ARE the kit; no
        // combat moveset. Referenced by the row below so the catalog is valid.
        "peaceful": (
            move_style: Walk,
            melee: None,
            ranged: None,
            special: None,
        ),
    },
    characters: {
        "sanic": (
            sprite_tuning: Some((collision_scale: 1.6, frame_sample_inset: 1)),
            display_name: "Sanic",
            spritesheet: "sprites/sanic_spritesheet.png",
            manifest: "sprites/sanic_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            composition: None,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["player"],
            // The MOVEMENT identity that makes this a Sanic demo: the worn home
            // box opts into `MotionModel::SurfaceMomentum` (rides the speedway +
            // loop), which is also what `ball_dash` requires to charge/launch.
            // Without this the body is axis-swept and ball dash is inert — the
            // demo would be an Ambition player wearing the name "Sanic".
            // `stick_factor` is the sticky-sneakers knob: at the authored top
            // speed the ramp crest's convex joints legitimately exceed the
            // physical (1.5x) hold, and a launched runner cannot ride the
            // loop. 4.0 keeps the flagship route attached at full speed.
            momentum: Some((
                ground_accel: 900.0,
                top_speed: 1200.0,
                jump_speed: 700.0,
                stick_factor: 4.0,
            )),
        ),
        "super_sanic": (
            sprite_tuning: Some((collision_scale: 1.6, frame_sample_inset: 1)),
            display_name: "Super Sanic",
            spritesheet: "sprites/super_sanic_spritesheet.png",
            manifest: "sprites/super_sanic_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            composition: None,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["player", "super", "transformation"],
            // The SUPER form is a real transformation, not a palette swap: the
            // boosted movement is authored ON the identity row (classic Super
            // Sonic ratios over the base row — ~2x accel, ~5/3 top speed,
            // ~1.2x jump), so wearing the form IS the grant. A worn re-wear
            // replaces params while PRESERVING live riding state
            // (`sync_worn_motion_model_preserving_state`), and reverting to
            // the base row restores the authored base exactly — one identity
            // authority, no save/restore bookkeeping. The jump apex stays
            // under the spring perch's 256px lift (840² / 2g ≈ 243px) so the
            // perch remains spring-served even for a super runner.
            momentum: Some((
                ground_accel: 1800.0,
                top_speed: 2000.0,
                jump_speed: 840.0,
                stick_factor: 4.0,
            )),
        ),
        // The badnik's IDENTITY row: its sprite resolves from this display
        // name (the Mary-O crony pattern). It points its OWN name at the
        // published `ai_slop` sheet — Ambition owns the "Ai Slop" display
        // name, and a duplicate would fail catalog assembly when hosted.
        // Behavior/HP/contact come from the `sanic_badnik` ROSTER archetype
        // (see `badnik.rs`); this row is only the sprite + name.
        "sanic_badnik": (
            display_name: "Sanic Badnik",
            spritesheet: "sprites/ai_slop_spritesheet.png",
            manifest: "sprites/ai_slop_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["enemy"],
        ),
    },
)"#;

pub mod badnik;
pub mod ball_dash;
pub mod monitors;
pub mod provider;

pub use provider::{
    sanic_session_world, SanicExperiencePlugin, SanicSessionWorld, SANIC_EXPERIENCE,
    SANIC_GAMEPLAY_ROUTE, SANIC_LAUNCHER_ROUTE,
};

/// Content plugin for the Sanic movement demo: registers Sanic's App-local
/// authored catalogs, installs the world, and adds the engine's sim-world setup. This is the shape
/// `crates/ambition_host/tests/demo_shell_smoke.rs` prescribes, built through the
/// `ambition` umbrella alone.
pub struct SanicDemoContentPlugin;

/// Register Sanic's immutable authored definitions in one Bevy `App`: the
/// character fragment and the provider-indexed music/SFX fragments. Shared by the historical
/// [`SanicDemoContentPlugin`] (Startup-driven construction) and the new
/// [`provider::SanicExperiencePlugin`] (shell-activation-driven construction), so
/// there is one definition of Sanic's content seam.
///
/// The registered App-local resources are the sole composition authority.
/// Runtime simulation, presentation, dialogue, and combat consumers receive
/// the assembled catalog explicitly through Bevy resources.
pub fn install_sanic_content(app: &mut App) {
    use ambition::audio::catalog::{AudioCatalogAppExt, AudioCatalogFragment};
    use ambition::characters::actor::character_catalog::{
        CharacterCatalogAppExt, CharacterCatalogFragment,
    };

    app.register_character_catalog_fragment(
        CharacterCatalogFragment::from_ron(
            provider::SANIC_EXPERIENCE,
            Some(SANIC_CHARACTER_ID),
            SANIC_CATALOG_RON,
        )
        .expect("Sanic character catalog should be valid"),
    );
    badnik::register_badnik_roster(app);
    app.register_audio_catalog_fragment(
        AudioCatalogFragment::new(
            provider::SANIC_EXPERIENCE,
            Some(ambition::audio::spec::MusicRegistry {
                default_track: "you_are_too_slow".to_string(),
                tracks: vec![ambition::audio::spec::MusicTrack {
                    id: "you_are_too_slow".to_string(),
                    display_name: "You Are Too Slow".to_string(),
                    asset_path: Some(SANIC_MUSIC_ASSET_PATH.to_string()),
                }],
            }),
            // Sanic AUTHORS the cues it emits (Dash, Jump) rather than
            // inheriting them from the resident Ambition synth table. Declaring
            // them is what authorizes them under provider-relative SFX: a Sanic
            // session plays these and nothing else, and an Ambition-only bank id
            // resident in the shared bank cannot resolve here.
            Some(ambition::audio::spec::SfxRegistry {
                sample_rate: 44_100,
                sfx: vec![
                    sanic_cue(ambition::audio::spec::SoundCueKey::Dash, 900.0, 1400.0),
                    sanic_cue(ambition::audio::spec::SoundCueKey::Jump, 700.0, 1200.0),
                    sanic_open_cue("ui.menu.move_icon", 760.0, 980.0),
                    sanic_open_cue("ui.menu.accept", 880.0, 1320.0),
                    sanic_open_cue("ui.menu.back", 620.0, 360.0),
                ],
            }),
        )
        .expect("Sanic audio catalogs should be valid"),
    );
}

/// An open provider-local procedural cue for shell/menu vocabulary.
fn sanic_open_cue(id: &str, frequency: f32, frequency_end: f32) -> ambition::audio::spec::SfxSpec {
    ambition::audio::spec::SfxSpec {
        cue: None,
        id: Some(id.to_owned()),
        waveform: ambition::audio::spec::WaveformSpec::Square,
        frequency,
        frequency_end,
        duration: 0.09,
        volume: 0.35,
        attack: 0.004,
        release: 0.045,
        noise: 0.0,
    }
}

/// A bright, fast procedural cue spec in Sanic's voice.
fn sanic_cue(
    cue: ambition::audio::spec::SoundCueKey,
    frequency: f32,
    frequency_end: f32,
) -> ambition::audio::spec::SfxSpec {
    ambition::audio::spec::SfxSpec {
        cue: Some(cue),
        id: None,
        waveform: ambition::audio::spec::WaveformSpec::Square,
        frequency,
        frequency_end,
        duration: 0.12,
        volume: 0.5,
        attack: 0.005,
        release: 0.06,
        noise: 0.0,
    }
}

impl Plugin for SanicDemoContentPlugin {
    fn build(&self, app: &mut App) {
        use ambition::runtime::demo_fixture::{ActiveRoomMetadata, RoomSet};
        use bevy::prelude::IntoScheduleConfigs;

        install_sanic_content(app);
        let room = sanic_speedway();
        app.world_mut().spawn((
            ambition::platformer::lifecycle::SessionRoot(
                ambition::platformer::lifecycle::SessionScopeId(0),
            ),
            ambition::runtime::PlatformerSessionWorld::new(
                SANIC_EXPERIENCE,
                RoomSet::from_parts(SPEEDWAY_ROOM_ID, vec![room.clone()], Vec::new()),
                ae::RoomGeometry(room.world.clone()),
                ActiveRoomMetadata(room.metadata.clone()),
                ambition::runtime::demo_fixture::StartingCharacter::new(SANIC_CHARACTER_ID),
                ambition::runtime::demo_fixture::LdtkRuntimeIndex::default(),
            ),
        ));
        app.add_systems(
            bevy::app::Startup,
            sanic_setup.in_set(ambition::runtime::demo_fixture::SimulationSetupSet),
        );
    }
}

/// The demo's world construction: the engine's `simulation_world` on the
/// speedway. Labeled `SimulationSetupSet` so the host's input attach orders after
/// the player body exists.
#[allow(clippy::too_many_arguments)]
fn sanic_setup(
    mut commands: bevy::prelude::Commands,
    world: ambition::platformer::lifecycle::SessionWorldRef<ae::RoomGeometry>,
    room_set: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::RoomSet,
    >,
    ldtk_index: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::LdtkRuntimeIndex,
    >,
    editable_abilities: bevy::prelude::Res<ambition::runtime::demo_fixture::EditableAbilitySet>,
    editable_tuning: bevy::prelude::Res<ambition::runtime::demo_fixture::EditableMovementTuning>,
    starting_character: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::StartingCharacter,
    >,
    asset_server: bevy::prelude::Res<bevy::asset::AssetServer>,
    character_catalog: bevy::prelude::Res<
        ambition::characters::actor::character_catalog::CharacterCatalog,
    >,
    character_roster: bevy::prelude::Res<ambition::actors::features::CharacterRoster>,
    boss_catalog: bevy::prelude::Res<ambition::actors::boss_encounter::BossCatalog>,
    placement_lowering: bevy::prelude::Res<
        ambition::runtime::demo_fixture::PlacementLoweringRegistry,
    >,
) {
    ambition::runtime::demo_fixture::simulation_world(
        &mut commands,
        ambition::platformer::lifecycle::SessionSpawnScope::UNSCOPED,
        ambition::runtime::demo_fixture::SimulationSetup {
            world: &world,
            room_set: &room_set,
            ldtk_index: &ldtk_index,
            editable_abilities: &editable_abilities,
            editable_tuning: &editable_tuning,
            starting_character: &starting_character,
            character_catalog: &character_catalog,
            character_roster: &character_roster,
            placement_lowering: &placement_lowering,
            boss_catalog: &boss_catalog,
            default_character_id: SANIC_CHARACTER_ID,
            sandbox_data_asset: None,
            sandbox_asset_collection: None,
            asset_server: &asset_server,
        },
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// The RULES plugin — the D-C mode-scope seam, used for real.
// ─────────────────────────────────────────────────────────────────────────────

/// The act's live state, owned by the mode. It rides a `ModeScopedEntity`, so
/// leaving the Sanic rooms tears it down through the engine's lifetime-scope
/// vocabulary rather than a bespoke reset.
#[derive(bevy::prelude::Component, Default, Debug)]
pub struct SanicActState {
    /// Seconds the act has been running (sim clock, so bullet-time slows it).
    pub elapsed: f32,
    /// Next index in [`SPEED_MARKER_XS`] that should emit its one-shot progress
    /// cue. Mode-scoped with the act, so leaving and re-entering the demo resets
    /// the audible ruler without a global resource leak.
    pub next_milestone: usize,
}

/// Sanic's level rules. **ONE system list; a constructor flag decides its gating**
/// — [`SanicRulesPlugin::hosted`] when Ambition hosts the demo alongside its own
/// rooms, [`SanicRulesPlugin::global`] when the demo IS the game. That is the D-C
/// pattern (`docs/planning/engine/decomposition.md` §Phase D-C), and this is its
/// first real consumer: before this, `in_mode` had no ruleset to gate.
pub struct SanicRulesPlugin {
    hosted: bool,
}

impl SanicRulesPlugin {
    /// Ambition hosts this demo: every rule sleeps outside the Sanic rooms.
    pub fn hosted() -> Self {
        Self { hosted: true }
    }

    /// The demo IS the game: the rules run unconditionally.
    pub fn global() -> Self {
        Self { hosted: false }
    }
}

impl Plugin for SanicRulesPlugin {
    fn build(&self, app: &mut App) {
        // The plugin OWNS its mandatory message channels and shared resources:
        // its systems write SFX cues, pop VFX bursts, read room-load facts, and
        // contribute to the collision overlay. A full app registers all of
        // these through the engine plugins; a thin rules-only harness may not,
        // and `add_message`/`init_resource` are idempotent.
        app.add_message::<ambition::sfx::OwnedSfxMessage>();
        app.add_message::<ambition::vfx::VfxMessage>();
        app.add_message::<ambition::actors::rooms::RoomLoaded>();
        app.init_resource::<ambition::actors::features::FeatureEcsWorldOverlay>();
        use bevy::prelude::IntoScheduleConfigs;
        let sim = ambition::platformer::schedule::SimScheduleExt::sim_schedule(app);
        app.init_resource::<ball_dash::BallDashTuning>();
        // Attach the mode-local state and consume Sanic's semantic input verbs
        // before the generic peaceful-kit gate erases combat intent. Chaining
        // provides an apply-deferred seam, so the first eligible X edge cannot be
        // lost on a newly controlled body. Utility is D in the classic preset;
        // the transform system consumes that edge so it cannot also toggle a
        // host-code flight ability inherited by the control box.
        let sanic_input_rules = (
            ball_dash::attach_ball_dash,
            ball_dash::capture_ball_dash_input,
            toggle_sanic_form,
        )
            .chain()
            .in_set(ambition::platformer::schedule::SandboxSet::PlayerInput)
            .after(ambition::actors::avatar::tick_player_brains)
            .before(ambition::actors::avatar::gate_worn_player_control);
        if self.hosted {
            app.add_systems(
                sim,
                sanic_input_rules.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
        } else {
            app.add_systems(sim, sanic_input_rules);
        }

        // The ball dash is a RULE, not world content: it exists while the Sanic
        // mode is live and nowhere else, exactly like the act clock. Effects run
        // after PlayerInput captured the technique and before later presentation.
        // `tick_ball_dash` precedes `tick_rolling`, so a launch cannot un-ball in
        // the same frame even if tuning changes.
        let rules = (
            spawn_sanic_mode_owner,
            tick_sanic_act,
            ball_dash::tick_ball_dash,
            ball_dash::tick_rolling,
            // The super form's derived traits (invincibility + sparkles) track
            // the worn identity every frame — toggle- and monitor-agnostic.
            sync_super_form_traits,
        )
            .chain()
            .in_set(ambition::platformer::schedule::SandboxSet::GameplayEffects);
        let milestone_sfx = emit_sanic_milestone_sfx
            .in_set(ambition::platformer::schedule::SandboxSet::GameplayEffects);
        // The badnik defeat runs BEFORE the engine's shared body-contact-damage
        // pass so a stomp/roll never also hurts Sanic (the rule zeroes the
        // badnik's health that frame; the contact pass skips a dead attacker).
        let badniks =
            badnik::defeat_badniks.before(ambition::actors::features::apply_actor_contact_damage);
        // Monitor boxes: re-arm on (re)load, break on stomp/roll, tick the
        // speed-shoes grant. Broken monitors contribute to the overlay's
        // `removed_block_names` AFTER the engine's per-frame rebuild clears it
        // (the same slot Mary-O's bricks and encounter lock walls take).
        app.init_resource::<monitors::SpentMonitors>();
        let monitor_rules = (
            monitors::rearm_monitors_on_room_loaded,
            monitors::break_monitor_boxes,
            monitors::tick_speed_shoes,
        );
        let monitor_overlay = monitors::contribute_broken_monitors_to_overlay
            .after(ambition::actors::features::rebuild_feature_ecs_world_overlay);
        if self.hosted {
            app.add_systems(sim, rules.run_if(ambition::runtime::in_mode(SANIC_MODE)));
            app.add_systems(
                sim,
                milestone_sfx.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(sim, badniks.run_if(ambition::runtime::in_mode(SANIC_MODE)));
            app.add_systems(
                sim,
                monitor_rules.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(
                sim,
                monitor_overlay.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
        } else {
            app.add_systems(sim, rules);
            app.add_systems(sim, milestone_sfx);
            app.add_systems(sim, badniks);
            app.add_systems(sim, monitor_rules);
            app.add_systems(sim, monitor_overlay);
        }
    }
}

/// Toggle the controlled body between the two catalog-authored Sanic forms.
///
/// This consumes the already-semantic Utility edge (`D` in the demo's classic
/// keyboard preset), never a raw key. The super row authors the form's boosted
/// movement and `sync_super_form_traits` derives the rest (invincibility,
/// sparkles, badnik destroy-on-touch) from the worn identity every frame — so
/// this toggle grants and revokes the FULL form, and `WornCharacter` stays the
/// single gameplay + presentation authority. No timer: a future ring drain can
/// wear the form off the same way this toggle does.
fn toggle_sanic_form(
    subject: Option<bevy::prelude::Res<ambition::platformer::markers::ControlledSubject>>,
    mut bodies: bevy::prelude::Query<(
        &mut ambition::characters::brain::ActorControl,
        &mut ambition::characters::actor::WornCharacter,
        &ae::BodyKinematics,
    )>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    let Some(entity) = subject.and_then(|subject| subject.0) else {
        return;
    };
    let Ok((mut control, mut worn, kinematics)) = bodies.get_mut(entity) else {
        return;
    };
    if !control.0.fly_toggle_pressed {
        return;
    }

    // Utility belongs to this mode-local transformation. Consume the edge before
    // lower movement layers can interpret it as the generic fly toggle.
    control.0.fly_toggle_pressed = false;
    let next = match worn.id() {
        SANIC_CHARACTER_ID => SUPER_SANIC_CHARACTER_ID,
        SUPER_SANIC_CHARACTER_ID => SANIC_CHARACTER_ID,
        _ => return,
    };
    *worn = ambition::characters::actor::WornCharacter::new(next);
    sfx.write(ambition::sfx::SfxMessage::Dash {
        pos: kinematics.pos,
    });
}

/// How often the super form's sparkle trail pulses (sim seconds).
const SUPER_SPARKLE_PERIOD: f32 = 0.15;

/// Derive the super form's non-movement traits from the worn identity, every
/// sim frame. The movement boost is authored on the `super_sanic` catalog row
/// (the wear itself grants it); what the catalog CANNOT express lives here:
///
/// - **Invincibility**: `Health::invulnerable` tracks the worn identity, so
///   badnik contact can't hurt a super Sanic. (Kernel hazards — the pit, the
///   spikes — still reset the body: falling off the world outranks any form.)
/// - **Sparkles**: a golden pulse trails the form, so the transformation reads
///   on screen and not just on the spritesheet.
///
/// The form is NOT a timed grant: the D-toggle (or a future ring drain) wears
/// it off, and every trait here reverts the same frame because it is derived,
/// never stored. Badnik destroy-on-touch derives from the same identity read
/// in `badnik::defeat_badniks`.
fn sync_super_form_traits(
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut sparkle_accum: bevy::prelude::Local<f32>,
    mut vfx: bevy::prelude::MessageWriter<ambition::vfx::VfxMessage>,
    mut players: bevy::prelude::Query<
        (
            &ambition::characters::actor::WornCharacter,
            &mut ambition::characters::actor::BodyHealth,
            &ae::BodyKinematics,
        ),
        bevy::prelude::With<ambition::actors::actor::PrimaryPlayer>,
    >,
) {
    let Ok((worn, mut health, kinematics)) = players.single_mut() else {
        return;
    };
    let is_super = worn.id() == SUPER_SANIC_CHARACTER_ID;
    if health.health.invulnerable != is_super {
        health.health.invulnerable = is_super;
    }
    if !is_super {
        *sparkle_accum = 0.0;
        return;
    }
    *sparkle_accum += time.scaled_dt;
    if *sparkle_accum >= SUPER_SPARKLE_PERIOD {
        *sparkle_accum -= SUPER_SPARKLE_PERIOD;
        vfx.write(ambition::vfx::VfxMessage::Burst {
            pos: kinematics.pos,
            count: 3,
            speed: 60.0,
            color: [1.0, 0.9, 0.35, 1.0],
            kind: ambition::vfx::ParticleKind::Shard,
        });
    }
}

/// Bring the act state into being the first frame the mode is live. Spawned
/// `spawn_mode_scoped`, so the engine despawns it when the active room's mode
/// changes — no teardown code here.
fn spawn_sanic_mode_owner(
    mut commands: bevy::prelude::Commands,
    existing: bevy::prelude::Query<(), bevy::prelude::With<SanicActState>>,
    session: Option<bevy::prelude::Res<ambition::platformer::lifecycle::ActiveSessionScope>>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    use ambition::platformer::lifecycle::{SessionSpawnScope, SpawnSessionScopedExt};
    // Sleep when a session-scoped host has retired the live session (i.e. at the
    // launcher): the room metadata may still read "sanic" until the next
    // activation overwrites it, but there is no session to own new state, so the
    // act owner must not be resurrected. When no `ActiveSessionScope` exists at
    // all (the historical Startup path and the D-C tests) the guard is inert.
    let session_live = session
        .as_ref()
        .map_or(true, |scope| scope.current().is_some());
    let spawn_scope = session
        .as_ref()
        .map_or(SessionSpawnScope::UNSCOPED, |scope| scope.spawn_scope());
    if session_live && existing.iter().next().is_none() {
        // Owned by BOTH the mode (survives in-session room changes) and the
        // active session (torn down on a shell relaunch, which a same-mode
        // reload is NOT — so mode-scope alone would leak the act across a
        // launch → quit → relaunch cycle).
        commands
            .spawn_session_scoped(spawn_scope, SanicActState::default())
            .insert(ambition::platformer::lifecycle::ModeScopedEntity(
                SANIC_MODE.to_string(),
            ));
        // Audible confirmation that the standalone shell is draining the
        // standard SfxMessage seam. Distance markers emit alternating cues as
        // the player advances, so this one also proves the bank at room entry.
        sfx.write(ambition::sfx::SfxMessage::Dash {
            pos: ae::Vec2::ZERO,
        });
    }
}

/// The act timer runs on the SIM clock (`scaled_dt`), so bullet-time and pause
/// slow it exactly as they slow everything else — `WorldTime`, never `Res<Time>`.
fn tick_sanic_act(
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut act: bevy::prelude::Query<&mut SanicActState>,
) {
    for mut state in &mut act {
        state.elapsed += time.scaled_dt;
    }
}

/// Emit a small, existing Ambition cue when the primary body crosses each
/// visible distance marker. These are deliberately simple diagnostic sounds:
/// the demo is proving that its shell drains the standard [`ambition::sfx::SfxMessage`] seam,
/// not inventing a parallel Sanic audio stack.
fn emit_sanic_milestone_sfx(
    player: bevy::prelude::Query<
        &ae::BodyKinematics,
        bevy::prelude::With<ambition::actors::actor::PrimaryPlayer>,
    >,
    mut act: bevy::prelude::Query<&mut SanicActState>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    let Ok(kin) = player.single() else {
        return;
    };
    for mut state in &mut act {
        while let Some(&marker_x) = SPEED_MARKER_XS.get(state.next_milestone) {
            if kin.pos.x < marker_x {
                break;
            }
            let message = if state.next_milestone % 2 == 0 {
                ambition::sfx::SfxMessage::Dash { pos: kin.pos }
            } else {
                ambition::sfx::SfxMessage::Jump { pos: kin.pos }
            };
            sfx.write(message);
            state.next_milestone += 1;
        }
    }
}

/// Install the Sanic demo content layer into an engine app.
pub fn add_demo_content(app: &mut App) {
    app.add_plugins(SanicDemoContentPlugin);
}

#[cfg(test)]
mod tests;
