//! Sanic-style demo content home.
//!
//! This crate intentionally depends only on the `ambition` facade crate. It is
//! the E9 engine-for-other-games ORACLE: a second platformer's content is
//! authored entirely through the umbrella surface, never by reaching into a
//! lower `ambition_*` crate or copying `game/ambition_app`'s dependency wall.
//! If authoring a room here needs a type the umbrella does not re-export, that
//! is a real engine leak — and it fails to compile HERE, which is the point.
//!
//! What lives here is the SHOWCASE COURSE — rolling hills, a rideable loop,
//! springs, one-way platforms, a pit, monitors, and badniks — plus the
//! mode-local rules that make progress legible through milestone SFX. The
//! SPATIAL layout is authored in the demo's own LDtk file
//! (`assets/worlds/sanic_speedway.ldtk`, generated by
//! `tools/author_speedway_ldtk.py`); the LOOP route (depth lanes + junctions,
//! which LDtk has no vocabulary for) is grafted onto the loaded room in
//! [`sanic_speedway`]. The windowed shell loads the shared Ambition art tree
//! through the public facade, so generated Sanic art and existing parallax /
//! block assets light up without an `ambition_app` dependency.

use ambition::engine_core as ae;
use ambition::prelude::*;
use ambition::world::rooms::RoomSpec;

/// Stable room id for the momentum speedway.
pub const SPEEDWAY_ROOM_ID: &str = "sanic_speedway";

/// The game-MODE tag this demo's rooms carry (decomposition D-C).
///
/// Ambition hosts this demo by loading its rooms alongside its own; a Sanic
/// rules plugin gates its systems on `ambition::runtime::in_mode(SANIC_MODE)`
/// so they sleep everywhere else. [`SanicRulesPlugin`] is that ruleset, and its
/// `hosted()` / `global()` constructor flag is the D-C pattern made real.
pub const SANIC_MODE: &str = "sanic";

/// Authored soundtrack for the standalone Sanic demo. The rendered asset lives
/// in the shared engine asset tree beside the other generated music tracks.
pub const SANIC_MUSIC_ASSET_PATH: &str = "audio/music/generated/you_are_too_slow/full.ogg";

/// Number of segments in the full 360-degree loop body.
pub const LOOP_SEGMENTS: usize = 128;

/// Samples in the raised entry ramp. The ramp, loop, and runout are one open
/// surface route; there is no chain-transfer seam at either side of the loop.
pub const LOOP_RAMP_SEGMENTS: usize = 32;

/// Samples in the post-loop route: a flat foreground overpass clears the
/// crossover before a separate descent returns to the tiled floor.
pub const LOOP_RUNOUT_SEGMENTS: usize = 32;

/// Flat samples after the full revolution. Keeping the rider attached until it
/// is horizontally clear of the inbound rail is the physical half of the 2.5D
/// crossover; depth ordering supplies the visual half.
pub const LOOP_OVERPASS_SEGMENTS: usize = 12;

/// Remaining samples in the descent from the overpass to the floor.
pub const LOOP_DESCENT_SEGMENTS: usize = LOOP_RUNOUT_SEGMENTS - LOOP_OVERPASS_SEGMENTS;

/// Index of the loop's first arc point inside the combined route.
pub const LOOP_ENTRY_POINT_INDEX: usize = LOOP_RAMP_SEGMENTS;

/// Index where the full loop returns to the crossover after 360 degrees.
pub const LOOP_CLOSURE_POINT_INDEX: usize = LOOP_ENTRY_POINT_INDEX + LOOP_SEGMENTS;

/// Lower-arc segments rendered in front of the player on each side of the
/// loop. The remaining loop body is on the ordinary/back lane.
pub const LOOP_FOREGROUND_SEGMENTS_PER_SIDE: usize = 22;

/// Index of the route's final floor-level runout point.
pub const LOOP_EXIT_POINT_INDEX: usize = LOOP_CLOSURE_POINT_INDEX + LOOP_RUNOUT_SEGMENTS;

const LOOP_RADIUS: f32 = 180.0;
const LOOP_START_ANGLE: f32 = std::f32::consts::FRAC_PI_2;
const LOOP_SWEEP_ANGLE: f32 = std::f32::consts::TAU;
const LOOP_CENTER_X: f32 = 2200.0;
const LOOP_TRACK_RISE: f32 = 84.0;
const LOOP_RAMP_START_X: f32 = 1740.0;
const LOOP_OVERPASS_END_X: f32 = 2480.0;
const LOOP_RUNOUT_END_X: f32 = 2920.0;

/// Course dimensions, mirrored by `tools/author_speedway_ldtk.py` (the level
/// generator) — the loop graft and the oracles anchor on these.
pub const LEVEL_WIDTH: f32 = 6400.0;
pub const FLOOR_TOP: f32 = 672.0;
/// The pit: the west floor route ends at the left lip, the east runout route
/// starts at the right lip, and a hazard strip rests at the bottom.
pub const PIT_LEFT_X: f32 = 4000.0;
pub const PIT_RIGHT_X: f32 = 4256.0;

/// The LDtk world this demo ships — a SEPARATE file from Ambition's worlds,
/// embedded so the standalone shell needs no asset-root negotiation. Authored
/// by `tools/author_speedway_ldtk.py` through `ambition_ldtk_tools`; never
/// hand-edited.
pub const SPEEDWAY_WORLD_JSON: &str = include_str!("../assets/worlds/sanic_speedway.ldtk");

fn cubic_bezier(p0: ae::Vec2, p1: ae::Vec2, p2: ae::Vec2, p3: ae::Vec2, t: f32) -> ae::Vec2 {
    let u = 1.0 - t;
    p0 * (u * u * u) + p1 * (3.0 * u * u * t) + p2 * (3.0 * u * t * t) + p3 * (t * t * t)
}

/// Build one continuous entry-ramp → full-loop → runout route.
///
/// The loop starts at its bottom with a horizontal tangent, makes a complete
/// 360-degree revolution, returns to the same screen-space point at a later arc
/// length, and continues into a distinct runout. The repeated point is a 2.5D
/// crossover: per-segment depth lanes distinguish the inbound/back rail from the
/// outbound/front rail while the riding solver follows one unambiguous arc-length
/// route. This is the classic Sonic topology rather than a literal planar circle.
fn raised_full_loop_points(floor_top: f32) -> (Vec<ae::Vec2>, ae::Vec2) {
    let center = ae::Vec2::new(LOOP_CENTER_X, floor_top - LOOP_TRACK_RISE - LOOP_RADIUS);
    let ramp_start = ae::Vec2::new(LOOP_RAMP_START_X, floor_top);
    let loop_start =
        center + ae::Vec2::new(LOOP_START_ANGLE.cos(), LOOP_START_ANGLE.sin()) * LOOP_RADIUS;
    debug_assert!((loop_start.y - (floor_top - LOOP_TRACK_RISE)).abs() < 1.0e-3);

    let mut points =
        Vec::with_capacity(1 + LOOP_RAMP_SEGMENTS + LOOP_SEGMENTS + LOOP_RUNOUT_SEGMENTS);
    points.push(ramp_start);

    // Rise from the tiled floor to the loop bottom with a horizontal tangent at
    // both ends. The first segment is a real ramp, not a teleport or rebound-only
    // gap, while the final tangent exactly matches the loop's bottom tangent.
    let ramp_control_1 = ramp_start + ae::Vec2::new(150.0, 0.0);
    let ramp_control_2 = loop_start - ae::Vec2::new(170.0, 0.0);
    for step in 1..=LOOP_RAMP_SEGMENTS {
        let t = step as f32 / LOOP_RAMP_SEGMENTS as f32;
        points.push(cubic_bezier(
            ramp_start,
            ramp_control_1,
            ramp_control_2,
            loop_start,
            t,
        ));
    }

    // Decreasing theta gives the rideable inward normals expected by the
    // surface kernel. The final sample intentionally equals `loop_start`: it is
    // non-adjacent to the entry sample, so no degenerate segment is introduced.
    for step in 1..=LOOP_SEGMENTS {
        let t = step as f32 / LOOP_SEGMENTS as f32;
        let theta = LOOP_START_ANGLE - LOOP_SWEEP_ANGLE * t;
        points.push(center + ae::Vec2::new(theta.cos(), theta.sin()) * LOOP_RADIUS);
    }

    // Cross the loop mouth on a flat foreground deck first. A high-speed rider
    // may legitimately launch when a track begins descending; doing that at the
    // coincident inbound/outbound point lets the airborne circle immediately
    // re-hit the back rail. The flat deck keeps the rider attached until the
    // simulated-depth crossover is physically clear.
    let overpass_end = ae::Vec2::new(LOOP_OVERPASS_END_X, loop_start.y);
    for step in 1..=LOOP_OVERPASS_SEGMENTS {
        let t = step as f32 / LOOP_OVERPASS_SEGMENTS as f32;
        points.push(loop_start.lerp(overpass_end, t));
    }

    // Descend only after clearing the loop's rightmost extent. Both cubic end
    // tangents are horizontal, so the overpass/descent seam and the return to
    // the tiled floor are smooth. Launching from this convex descent is valid
    // Sonic behavior because no back-lane rail remains underneath it.
    let runout_end = ae::Vec2::new(LOOP_RUNOUT_END_X, floor_top);
    let runout_control_1 = overpass_end + ae::Vec2::new(120.0, 0.0);
    let runout_control_2 = runout_end - ae::Vec2::new(160.0, 0.0);
    for step in 1..=LOOP_DESCENT_SEGMENTS {
        let t = step as f32 / LOOP_DESCENT_SEGMENTS as f32;
        points.push(cubic_bezier(
            overpass_end,
            runout_control_1,
            runout_control_2,
            runout_end,
            t,
        ));
    }

    (points, center)
}

/// Canonical transform pair for the demo's semantic Utility action (D in the
/// classic arrows+Z/X/C preset).
pub const SANIC_CHARACTER_ID: &str = "sanic";
pub const SUPER_SANIC_CHARACTER_ID: &str = "super_sanic";

/// The animated ring sprite sheet (generated `sanic_ring_prop` target: an
/// idle-spin row + a collect row). Registered as a `GameAssets` prop in the app
/// and named on each ring pickup so the pickup renderer binds the spinning sheet
/// instead of the static coin. The AABB is square so the round sprite isn't
/// stretched.
pub const RING_SPRITE_KIND: &str = "sanic_ring_prop";

/// A ring placement: one of the `currency:1` pickups the author script lays down
/// (named `ring`). The demo tags these with the animated sprite and the tests
/// count them through this one predicate.
pub fn is_ring_placement(record: &ambition::world::placements::PlacementRecord) -> bool {
    use ambition::entity_catalog::placements::{PickupKindSpec, PlacementSchema};
    record.name == "ring"
        && matches!(
            &record.schema,
            PlacementSchema::Pickup(pickup)
                if matches!(pickup.kind, PickupKindSpec::Currency { .. })
        )
}

/// Sanic's own SFX vocabulary (provider-local open ids). Authoring a spec for
/// each in the provider registry both AUTHORIZES the id under provider-relative
/// playback and supplies its procedural voice — a Sanic session plays these and
/// nothing else. The spin-dash rev is three ascending tiers so a charge builds
/// the classic "reh-reh-REH" without needing per-play pitch on the message.
pub const SFX_REV_TIERS: [&str; 3] = ["sanic.rev.0", "sanic.rev.1", "sanic.rev.2"];
pub const SFX_LAUNCH: &str = "sanic.launch";
pub const SFX_TRANSFORM: &str = "sanic.transform";
pub const SFX_DETRANSFORM: &str = "sanic.detransform";
pub const SFX_MONITOR: &str = "sanic.monitor";
pub const SFX_BADNIK: &str = "sanic.badnik";
pub const SFX_SKID: &str = "sanic.skid";
/// The ring-collect ding. Rings are lowered as `Currency` pickups, so the shared
/// `collect_ecs_pickups` loop emits `ids::WORLD_COIN_PICKUP` on pickup — voicing
/// THAT id (not a private `sanic.*` one) is what makes a ring audible. Kept in
/// sync with `ambition::sfx::ids::WORLD_COIN_PICKUP` by a test.
pub const SFX_RING: &str = "world.coin.pickup";
/// Scatter cue for the (deferred) drop-on-hit; authored ahead so the loss path
/// is a pure emit when it lands.
pub const SFX_RING_LOSS: &str = "sanic.ring_loss";

/// Pick the rev tier from the post-tap charge (`0..=1`): the three buckets land
/// on the three natural tap counts (`rev_per_tap` 0.4 → ~0.4, ~0.8, 1.0).
pub fn rev_tier_id(charge: f32) -> &'static str {
    if charge < 0.5 {
        SFX_REV_TIERS[0]
    } else if charge < 0.85 {
        SFX_REV_TIERS[1]
    } else {
        SFX_REV_TIERS[2]
    }
}

/// Visually authored distance markers. The floating marker platforms (in the
/// LDtk file) and the one-shot milestone SFX share this table so the eye and
/// ear measure the same positions instead of drifting as the speedway changes.
pub const SPEED_MARKER_XS: [f32; 5] = [808.0, 1608.0, 2600.0, 3608.0, 5000.0];

/// Build the Sanic showcase room: parse the demo's own LDtk world (hills,
/// pit, springs, platforms, monitors, badniks — everything spatial), then
/// graft the code-generated loop route onto it. The loop stays code-side
/// because its depth lanes and route junctions have no LDtk vocabulary; it
/// anchors on floor-chain vertices the level generator authors at
/// [`struct@LOOP_RAMP_START_X`]/[`struct@LOOP_RUNOUT_END_X`], and this
/// function panics loudly if the two files drift.
pub fn sanic_speedway() -> RoomSpec {
    let project = ambition::ldtk_map::LdtkProject::from_json_str(SPEEDWAY_WORLD_JSON)
        .expect("sanic_speedway.ldtk parses (regen: game/ambition_demo_sanic/tools/author_speedway_ldtk.py)");
    let room_set = project
        .to_room_set_with_entry(SPEEDWAY_ROOM_ID)
        .unwrap_or_else(|errors| panic!("sanic_speedway.ldtk converts to rooms: {errors:?}"));
    let mut room = room_set
        .rooms
        .into_iter()
        .find(|room| room.id == SPEEDWAY_ROOM_ID)
        .expect("the world file authors the sanic_speedway area");

    let loop_center = graft_loop_route(&mut room.world);
    // The LDtk EnemySpawn entities carry positions and the roster brain key;
    // the demo supplies the render identity (the catalog display name that
    // resolves the badnik sheet).
    for spawn in &mut room.enemy_spawns {
        spawn.name = badnik::BADNIK_DISPLAY_NAME.to_string();
    }
    // Rings lower as generic `currency` pickups (LDtk owns their spatial layout);
    // the demo supplies their render identity here, the same way it names the
    // badnik above — the pickup renderer then binds the animated ring sheet.
    for record in &mut room.placements {
        if is_ring_placement(record) {
            if let ambition::entity_catalog::placements::PlacementSchema::Pickup(pickup) =
                &mut record.schema
            {
                pickup.sprite = Some(RING_SPRITE_KIND.to_string());
            }
        }
    }
    room.metadata.mode = Some(SANIC_MODE.to_string());
    // Borrow Ambition's generated skybridge stack. The visible shell loads the
    // shared `GameAssets`; if those optional images are absent the renderer keeps
    // the deterministic clear-color + landmark geometry fallback.
    room.metadata.biome = Some("skybridge".to_string());
    room.metadata.visual_theme = Some("skybridge".to_string());
    room.metadata.visual_profile.id = Some("sanic_speedway".to_string());
    room.metadata.visual_profile.parallax_theme = Some("skybridge".to_string());

    // World-space labels turn the speedway into a ruler. They are ordinary room
    // debug labels rendered by the generic presentation face, not app-local UI.
    let mut labels = vec![
        (
            "start".to_string(),
            "START   Z: JUMP   DOWN+X: REV   RELEASE DOWN: DASH   D: SUPER".to_string(),
            ae::Vec2::new(300.0, FLOOR_TOP - 230.0),
        ),
        (
            "loop".to_string(),
            "LOOP".to_string(),
            ae::Vec2::new(loop_center.x, loop_center.y - LOOP_RADIUS - 36.0),
        ),
        (
            "finish".to_string(),
            "FINISH".to_string(),
            // Derived from `GOAL_X`, not a second copy of the same arithmetic.
            // Claiming the sign and the trigger "cannot drift" while writing
            // the expression twice is how the sign ended up marking a line the
            // trigger was 270px past.
            ae::Vec2::new(GOAL_X, FLOOR_TOP - 300.0),
        ),
    ];
    labels.extend(SPEED_MARKER_XS.into_iter().enumerate().map(|(index, x)| {
        (
            format!("marker_{}", index + 1),
            format!("{x:.0}"),
            ae::Vec2::new(x, FLOOR_TOP - 280.0),
        )
    }));
    room.debug_labels = labels
        .into_iter()
        .map(|(id, text, position)| {
            ambition::world::rooms::Authored::new(
                format!("sanic_{id}"),
                text.clone(),
                ae::Aabb::new(position, ae::Vec2::splat(1.0)),
                ambition::world::debug_label::DebugLabel::new(
                    text,
                    position,
                    ambition::world::debug_label::DebugLabelKind::Custom,
                ),
            )
        })
        .collect();
    room
}

/// Graft the ramp→loop→runout route (the code-generated topology LDtk cannot
/// express: per-segment depth lanes + the loop-mouth / floor-fork junctions)
/// onto the LDtk-loaded world, and return the loop center for the label.
///
/// The loop chain is INSERTED AT INDEX 0 so long-lived test fixtures keep the
/// loop as `chains[0]`; junction ports name the floor route by its post-insert
/// index. Anchor vertices are looked up by POSITION on the authored floor
/// chain, so if the level generator and these constants drift the panic names
/// the exact seam.
fn graft_loop_route(world: &mut ae::World) -> ae::Vec2 {
    let (ramp_loop_points, loop_center) = raised_full_loop_points(FLOOR_TOP);
    let mut loop_depths = vec![0_i8; ramp_loop_points.len() - 1];
    // The approach lives behind the player. The two lower loop shoulders and
    // the outbound runout live in front, creating the classic inside/outside
    // crossover without adding a second collision surface.
    loop_depths[..LOOP_RAMP_SEGMENTS].fill(-1);
    let front = LOOP_FOREGROUND_SEGMENTS_PER_SIDE.min(LOOP_SEGMENTS / 2);
    loop_depths[LOOP_ENTRY_POINT_INDEX..LOOP_ENTRY_POINT_INDEX + front].fill(1);
    loop_depths[LOOP_CLOSURE_POINT_INDEX - front..].fill(1);

    let floor_index = world
        .chains
        .iter()
        .position(|chain| chain.name == "sanic_floor_route")
        .expect("the LDtk world authors the sanic_floor_route chain");
    let vertex_at = |x: f32| {
        world.chains[floor_index]
            .points
            .iter()
            .position(|p| (p.x - x).abs() < 0.5 && (p.y - FLOOR_TOP).abs() < 0.5)
            .unwrap_or_else(|| {
                panic!(
                    "sanic_floor_route must have a junction anchor vertex at \
                     ({x}, {FLOOR_TOP}) — regenerate the level with \
                     tools/author_speedway_ldtk.py"
                )
            })
    };
    let ramp_vertex = vertex_at(LOOP_RAMP_START_X);
    let runout_vertex = vertex_at(LOOP_RUNOUT_END_X);
    // Momentum bodies ride the authored floor guide over the solid ground.
    // The floor/ramp split is a first-class route junction: the player keeps
    // running on the floor or holds toward the raised ramp, no airborne hack.
    let floor_after_insert = floor_index + 1;
    let ramp_loop = ae::SurfaceChain::open("sanic_loop", ramp_loop_points)
        .with_segment_depths(loop_depths)
        .with_junctions(vec![
            ae::SurfaceJunction::new(vec![LOOP_ENTRY_POINT_INDEX, LOOP_CLOSURE_POINT_INDEX]),
            ae::SurfaceJunction::across(vec![
                ae::SurfacePort::local(0),
                ae::SurfacePort::chain(floor_after_insert, ramp_vertex),
            ]),
            ae::SurfaceJunction::across(vec![
                ae::SurfacePort::local(LOOP_EXIT_POINT_INDEX),
                ae::SurfacePort::chain(floor_after_insert, runout_vertex),
            ]),
        ]);
    world.chains.insert(0, ramp_loop);

    // The IntGrid-lowered ground keeps Ambition's tiled block-art fill: re-id
    // the floor-level solids the way the old code-built room did.
    let mut ground_index = 0;
    for block in &mut world.blocks {
        if matches!(block.kind, ae::BlockKind::Solid) && (block.aabb.min.y - FLOOR_TOP).abs() < 0.5
        {
            block.id = ae::GeoId::tile_layer("sanic_speedway_ground", ground_index);
            ground_index += 1;
        }
    }
    loop_center
}

/// The demo's two-form catalog. Every demo installs its own roster; the engine
/// ships none (ADR 0017). The visible shell resolves both generated Sanic forms
/// through the shared Ambition asset catalog. Missing local artifacts remain a
/// loud, marked fallback rather than a second sprite path.
const SANIC_CATALOG_RON: &str = r#"(
    brain_presets: { "stand_still": StandStill },
    action_set_presets: {
        // A peaceful speedster: the momentum ride + ball dash ARE the kit; no
        // combat moveset. Referenced by the row below so the catalog is valid.
        "peaceful": (
            move_style: Walk,
            melee: None,
            ranged: None,
            special: None,
        ),
    },
    characters: {
        "sanic": (
            sprite_tuning: Some((collision_scale: 1.6, frame_sample_inset: 1)),
            display_name: "Sanic",
            spritesheet: "sprites/sanic_spritesheet.png",
            manifest: "sprites/sanic_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            composition: None,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["player"],
            // The MOVEMENT identity that makes this a Sanic demo: the worn home
            // box opts into `MotionModel::SurfaceMomentum` (rides the speedway +
            // loop), which is also what `ball_dash` requires to charge/launch.
            // Without this the body is axis-swept and ball dash is inert — the
            // demo would be an Ambition player wearing the name "Sanic".
            // `stick_factor` is the sticky-sneakers knob: at the authored top
            // speed the ramp crest's convex joints legitimately exceed the
            // physical (1.5x) hold, and a launched runner cannot ride the
            // loop. 4.0 keeps the flagship route attached at full speed.
            momentum: Some((
                ground_accel: 900.0,
                top_speed: 1200.0,
                jump_speed: 700.0,
                stick_factor: 4.0,
            )),
            barks: (
                hall: ["The pedestal asked me to idle. I said no.", "Where am I going? Yes.", "The camera is filing a complaint."],
            ),
            hall_dialogue_id: Some("hall_sanic"),
        ),
        "super_sanic": (
            sprite_tuning: Some((collision_scale: 1.6, frame_sample_inset: 1)),
            display_name: "Super Sanic",
            spritesheet: "sprites/super_sanic_spritesheet.png",
            manifest: "sprites/super_sanic_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            composition: None,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["player", "super", "transformation"],
            // The SUPER form is a real transformation, not a palette swap: the
            // boosted movement is authored ON the identity row (classic Super
            // Sonic ratios over the base row — ~2x accel, ~5/3 top speed,
            // ~1.2x jump), so wearing the form IS the grant. A worn re-wear
            // replaces params while PRESERVING live riding state
            // (`sync_worn_motion_model_preserving_state`), and reverting to
            // the base row restores the authored base exactly — one identity
            // authority, no save/restore bookkeeping. The jump apex stays
            // under the spring perch's 256px lift (840² / 2g ≈ 243px) so the
            // perch remains spring-served even for a super runner.
            momentum: Some((
                ground_accel: 1800.0,
                top_speed: 2000.0,
                jump_speed: 840.0,
                stick_factor: 4.0,
            )),
            barks: (
                hall: ["The air is falling behind.", "Immortality is a ring budget.", "The universe may submit a request to slow down."],
            ),
            hall_dialogue_id: Some("hall_super_sanic"),
        ),
        // The badnik's IDENTITY row: its sprite resolves from this display
        // name (the Mary-O crony pattern). It points its OWN name at the
        // published `ai_slop` sheet — Ambition owns the "Ai Slop" display
        // name, and a duplicate would fail catalog assembly when hosted.
        // Behavior/HP/contact come from the `sanic_badnik` ROSTER archetype
        // (see `badnik.rs`); this row is only the sprite + name.
        "sanic_badnik": (
            display_name: "Sanic Badnik",
            spritesheet: "sprites/ai_slop_spritesheet.png",
            manifest: "sprites/ai_slop_spritesheet.ron",
            tier: MainHall,
            body_kind: Standard,
            default_brain: "stand_still",
            default_action_set: "peaceful",
            tags: ["enemy"],
        ),
    },
)"#;

pub mod badnik;
pub mod ball_dash;
pub mod monitors;
pub mod provider;

pub use provider::{
    sanic_session_world, SanicExperiencePlugin, SanicSessionWorld, SANIC_EXPERIENCE,
    SANIC_GAMEPLAY_ROUTE, SANIC_LAUNCHER_ROUTE,
};

/// Content plugin for the Sanic movement demo: registers Sanic's App-local
/// authored catalogs, installs the world, and adds the engine's sim-world setup. This is the shape
/// `crates/ambition_host/tests/demo_shell_smoke.rs` prescribes, built through the
/// `ambition` umbrella alone.
pub struct SanicDemoContentPlugin;

/// Register Sanic's immutable authored definitions in one Bevy `App`: the
/// character fragment and the provider-indexed music/SFX fragments. Shared by the historical
/// [`SanicDemoContentPlugin`] (Startup-driven construction) and the new
/// [`provider::SanicExperiencePlugin`] (shell-activation-driven construction), so
/// there is one definition of Sanic's content seam.
///
/// The registered App-local resources are the sole composition authority.
/// Runtime simulation, presentation, dialogue, and combat consumers receive
/// the assembled catalog explicitly through Bevy resources.
pub fn install_sanic_content(app: &mut App) {
    use ambition::audio::catalog::{AudioCatalogAppExt, AudioCatalogFragment};
    use ambition::characters::actor::character_catalog::{
        CharacterCatalogAppExt, CharacterCatalogFragment,
    };

    app.register_character_catalog_fragment(
        CharacterCatalogFragment::from_ron(
            provider::SANIC_EXPERIENCE,
            Some(SANIC_CHARACTER_ID),
            SANIC_CATALOG_RON,
        )
        .expect("Sanic character catalog should be valid"),
    );
    badnik::register_badnik_roster(app);
    app.register_audio_catalog_fragment(
        AudioCatalogFragment::new(
            provider::SANIC_EXPERIENCE,
            Some(ambition::audio::spec::MusicRegistry {
                default_track: "you_are_too_slow".to_string(),
                tracks: vec![ambition::audio::spec::MusicTrack {
                    id: "you_are_too_slow".to_string(),
                    display_name: "You Are Too Slow".to_string(),
                    asset_path: Some(SANIC_MUSIC_ASSET_PATH.to_string()),
                }],
            }),
            // Sanic AUTHORS the cues it emits (Dash, Jump) rather than
            // inheriting them from the resident Ambition synth table. Declaring
            // them is what authorizes them under provider-relative SFX: a Sanic
            // session plays these and nothing else, and an Ambition-only bank id
            // resident in the shared bank cannot resolve here.
            Some(ambition::audio::spec::SfxRegistry {
                sample_rate: 44_100,
                sfx: sanic_sfx_specs(),
            }),
        )
        .expect("Sanic audio catalogs should be valid"),
    );
    // The animated ring sheet is CONTENT, not a property of one shell: register
    // it here so it loads identically whether Sanic runs standalone or as a mode
    // in the multi-game host (both add `SanicExperiencePlugin`, which calls this).
    // A prop is not carried in the lean sanic asset catalog, so this mirrors
    // Ambition's own intro-prop loader (a per-frame "insert if missing" GameAssets
    // mutation) rather than the catalog-fragment path — see smell #19.
    app.add_systems(bevy::prelude::Update, register_sanic_ring_prop_sheet);

    // Sanic's mutable sim state joins the rollback contract through the same
    // seam engine crates use — here, before either construction path
    // fingerprints the App, so the schema fingerprint (part of the content
    // identity) includes these rows; a non-GGRS shell records metadata only.
    {
        use ambition::runtime::rollback::AmbitionRollbackApp;
        // The act-state ANCHOR comes first: the mode owner is a bare
        // state-holder entity no engine rollback anchor reaches, and a
        // registered-but-unanchored component silently never snapshots (the
        // Mary-O behavioral restore test caught this class: a dirty mutation
        // survived a GGRS rollback). `BallDash`/`BallDashInput` ride the
        // player body, which `entity:body_kinematics` already anchors.
        app.require_rollback::<SanicActState>("ambition_demo_sanic", "entity:sanic_mode_owner")
            .rollback_component_clone::<ball_dash::BallDash>(
                "ambition_demo_sanic",
                "content.sanic_ball_dash",
            )
            .rollback_component_clone::<ball_dash::BallDashInput>(
                "ambition_demo_sanic",
                "content.sanic_ball_dash_input",
            )
            .rollback_component_clone::<SanicActState>(
                "ambition_demo_sanic",
                "content.sanic_act_state",
            )
            // A mid-burst scattered ring rides the currency pickup it decorates,
            // which `CenteredAabb`/`PickupFeature` already anchor + snapshot — so
            // like `BallDash` on the body, it only needs its own component
            // registered. Without this the burst would silently not resimulate.
            .rollback_component_clone::<ScatteredRing>(
                "ambition_demo_sanic",
                "content.sanic_scattered_ring",
            );
    }
}

/// Ensure the animated `sanic_ring_prop` sheet lives in `GameAssets.props` so the
/// pickup renderer binds it (the ring's spinning sprite) instead of the static
/// coin. Insert-if-missing rather than a one-shot latch: it self-heals after the
/// host's wholesale `GameAssets` rebuild (the quality-scale reload wipes props),
/// and the insert flips `GameAssets::is_changed()` so the prop-rebind pass runs.
/// No-ops in a headless/sim-only build where no `GameAssets` (or renderer) exists.
fn register_sanic_ring_prop_sheet(
    game_assets: Option<bevy::prelude::ResMut<ambition::sprite_sheet::game_assets::GameAssets>>,
    config: Option<bevy::prelude::Res<ambition::sprite_sheet::game_assets::GameAssetConfig>>,
    asset_server: Option<bevy::prelude::Res<bevy::prelude::AssetServer>>,
    layouts: Option<
        bevy::prelude::ResMut<bevy::prelude::Assets<bevy::prelude::TextureAtlasLayout>>,
    >,
) {
    let (Some(mut game_assets), Some(config), Some(asset_server), Some(mut layouts)) =
        (game_assets, config, asset_server, layouts)
    else {
        return;
    };
    if config.no_assets || game_assets.characters.props.contains_key(RING_SPRITE_KIND) {
        return;
    }
    if let Some(asset) = ambition::actors::character_sprites::load_prop_sheet_for_target(
        &asset_server,
        &mut layouts,
        &config.sprite_folder,
        RING_SPRITE_KIND,
        &ambition::sprite_sheet::character::SheetTuning::new(1.0, 2),
    ) {
        game_assets
            .characters
            .props
            .insert(RING_SPRITE_KIND.to_string(), asset);
    }
}

/// The whole Sanic SFX table. Every cue is procedural (the provider ships no
/// packed bank): the typed cues (`Dash`/`Jump`/`Pogo`/`Land`/`Reset`) voice the
/// engine's shared movement/hazard events, and the open `sanic.*` ids voice the
/// mode-local techniques (rev, launch, transform, monitor, badnik, skid, rings).
/// Authoring each here is what authorizes it under provider-relative playback.
fn sanic_sfx_specs() -> Vec<ambition::audio::spec::SfxSpec> {
    use ambition::audio::spec::{SoundCueKey as Cue, WaveformSpec as Wave};
    vec![
        // Shared engine movement/vitals cues, in Sanic's bright voice.
        sanic_cue(Cue::Dash, Wave::Square, 900.0, 1400.0, 0.12, 0.5, 0.0),
        sanic_cue(Cue::Jump, Wave::Square, 700.0, 1200.0, 0.12, 0.5, 0.0),
        // Springs / rebound pads: the engine writes `Pogo`; a bright rising boing.
        sanic_cue(Cue::Pogo, Wave::Square, 420.0, 1350.0, 0.16, 0.5, 0.0),
        // Touchdown footfall: a low, soft thud (the shared `Land` edge).
        sanic_cue(Cue::Land, Wave::Sine, 190.0, 95.0, 0.09, 0.32, 0.12),
        // Pit death / respawn reset: a descending "aww".
        sanic_cue(Cue::Reset, Wave::Triangle, 520.0, 120.0, 0.34, 0.42, 0.0),
        // Spin-dash rev — three ascending tiers picked by charge.
        sanic_open(SFX_REV_TIERS[0], Wave::Saw, 300.0, 520.0, 0.10, 0.40, 0.05),
        sanic_open(SFX_REV_TIERS[1], Wave::Saw, 430.0, 760.0, 0.10, 0.42, 0.05),
        sanic_open(SFX_REV_TIERS[2], Wave::Saw, 580.0, 1020.0, 0.11, 0.45, 0.05),
        // Launch/release whoosh (descending zip).
        sanic_open(SFX_LAUNCH, Wave::Saw, 1300.0, 320.0, 0.22, 0.5, 0.10),
        // Transform on (bright rising power chord) / off (softer descent).
        sanic_open(SFX_TRANSFORM, Wave::Square, 520.0, 1500.0, 0.34, 0.5, 0.0),
        sanic_open(SFX_DETRANSFORM, Wave::Square, 950.0, 420.0, 0.20, 0.4, 0.0),
        // Monitor pop and badnik splat.
        sanic_open(SFX_MONITOR, Wave::Square, 240.0, 900.0, 0.10, 0.45, 0.15),
        sanic_open(SFX_BADNIK, Wave::Square, 720.0, 170.0, 0.12, 0.45, 0.20),
        // Braking scrape (heavy noise).
        sanic_open(SFX_SKID, Wave::Saw, 250.0, 190.0, 0.16, 0.38, 0.55),
        // Rings: a bright collect ding and a scatter on loss.
        sanic_open(SFX_RING, Wave::Triangle, 1000.0, 1560.0, 0.09, 0.40, 0.0),
        sanic_open(SFX_RING_LOSS, Wave::Saw, 900.0, 220.0, 0.18, 0.42, 0.10),
        // Shell / menu vocabulary.
        sanic_open(
            "ui.menu.move_icon",
            Wave::Square,
            760.0,
            980.0,
            0.09,
            0.35,
            0.0,
        ),
        sanic_open(
            "ui.menu.accept",
            Wave::Square,
            880.0,
            1320.0,
            0.09,
            0.35,
            0.0,
        ),
        sanic_open("ui.menu.back", Wave::Square, 620.0, 360.0, 0.09, 0.35, 0.0),
    ]
}

/// An open provider-local procedural cue (full control). `attack` is a short
/// fixed onset; `release` trails a fixed fraction of the duration.
fn sanic_open(
    id: &str,
    waveform: ambition::audio::spec::WaveformSpec,
    frequency: f32,
    frequency_end: f32,
    duration: f32,
    volume: f32,
    noise: f32,
) -> ambition::audio::spec::SfxSpec {
    ambition::audio::spec::SfxSpec {
        cue: None,
        id: Some(id.to_owned()),
        waveform,
        frequency,
        frequency_end,
        duration,
        volume,
        attack: 0.005,
        release: (duration * 0.4).min(0.08),
        noise,
    }
}

/// A typed engine cue in Sanic's voice (full control).
fn sanic_cue(
    cue: ambition::audio::spec::SoundCueKey,
    waveform: ambition::audio::spec::WaveformSpec,
    frequency: f32,
    frequency_end: f32,
    duration: f32,
    volume: f32,
    noise: f32,
) -> ambition::audio::spec::SfxSpec {
    ambition::audio::spec::SfxSpec {
        cue: Some(cue),
        id: None,
        waveform,
        frequency,
        frequency_end,
        duration,
        volume,
        attack: 0.005,
        release: (duration * 0.4).min(0.08),
        noise,
    }
}

impl Plugin for SanicDemoContentPlugin {
    fn build(&self, app: &mut App) {
        use ambition::runtime::demo_fixture::{ActiveRoomMetadata, RoomSet};
        use bevy::prelude::IntoScheduleConfigs;

        install_sanic_content(app);
        let room = sanic_speedway();
        let source = ambition::runtime::PreparedPlatformerSource::new(
            SANIC_EXPERIENCE,
            RoomSet::from_parts(SPEEDWAY_ROOM_ID, vec![room.clone()], Vec::new()),
            ae::RoomGeometry(room.world.clone()),
            ActiveRoomMetadata(room.metadata.clone()),
            ambition::runtime::demo_fixture::StartingCharacter::new(SANIC_CHARACTER_ID),
            ambition::runtime::demo_fixture::LdtkRuntimeIndex::default(),
        );
        let content = ambition::provider::prepare_platformer_content_for_app(
            app,
            source,
            &provider::sanic_authored_catalogs(),
        )
        .expect("Sanic direct prepared-content assembly must succeed");
        app.world_mut().spawn((
            ambition::platformer::lifecycle::SessionRoot(
                ambition::platformer::lifecycle::SessionScopeId(0),
            ),
            content.source().instantiate_live(),
            content.identity(),
            content,
        ));
        app.add_systems(
            bevy::app::Startup,
            sanic_setup.in_set(ambition::runtime::demo_fixture::SimulationSetupSet),
        );
    }
}

/// The demo's world construction: the engine's `simulation_world` on the
/// speedway. Labeled `SimulationSetupSet` so the host's input attach orders after
/// the player body exists.
#[allow(clippy::too_many_arguments)]
fn sanic_setup(
    mut commands: bevy::prelude::Commands,
    world: ambition::platformer::lifecycle::SessionWorldRef<ae::RoomGeometry>,
    room_set: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::RoomSet,
    >,
    ldtk_index: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::LdtkRuntimeIndex,
    >,
    editable_abilities: bevy::prelude::Res<ambition::runtime::demo_fixture::EditableAbilitySet>,
    tuning: bevy::prelude::Res<ambition::runtime::demo_fixture::ActiveMovementTuning>,
    starting_character: ambition::platformer::lifecycle::SessionWorldRef<
        ambition::runtime::demo_fixture::StartingCharacter,
    >,
    asset_server: bevy::prelude::Res<bevy::asset::AssetServer>,
    character_catalog: bevy::prelude::Res<
        ambition::characters::actor::character_catalog::CharacterCatalog,
    >,
    character_roster: bevy::prelude::Res<ambition::actors::features::CharacterRoster>,
    boss_catalog: bevy::prelude::Res<ambition::actors::boss_encounter::BossCatalog>,
    placement_lowering: bevy::prelude::Res<
        ambition::runtime::demo_fixture::PlacementLoweringRegistry,
    >,
    content_staging: bevy::prelude::Res<
        ambition::runtime::demo_fixture::RoomContentStagingRegistry,
    >,
    construction_recipes: bevy::prelude::Res<
        ambition::runtime::demo_fixture::ActorConstructionRegistry,
    >,
) {
    ambition::runtime::demo_fixture::simulation_world(
        &mut commands,
        ambition::platformer::lifecycle::SessionSpawnScope::UNSCOPED,
        ambition::runtime::demo_fixture::SimulationSetup {
            world: &world,
            room_set: &room_set,
            ldtk_index: &ldtk_index,
            editable_abilities: &editable_abilities,
            tuning: &tuning,
            starting_character: &starting_character,
            character_catalog: &character_catalog,
            character_roster: &character_roster,
            placement_lowering: &placement_lowering,
            content_staging: &content_staging,
            // A demo enters directly rather than through provider activation,
            // so it has no prepared-content generation to state.
            construction: ambition::runtime::demo_fixture::ActorConstructionContext::new(
                &construction_recipes,
                Default::default(),
            ),
            boss_catalog: &boss_catalog,
            default_character_id: SANIC_CHARACTER_ID,
            sandbox_data_asset: None,
            sandbox_asset_collection: None,
            asset_server: &asset_server,
        },
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// The RULES plugin — the D-C mode-scope seam, used for real.
// ─────────────────────────────────────────────────────────────────────────────

/// The act's live state, owned by the mode. It rides a `ModeScopedEntity`, so
/// leaving the Sanic rooms tears it down through the engine's lifetime-scope
/// vocabulary rather than a bespoke reset.
#[derive(bevy::prelude::Component, Clone, Copy, Debug, Default, PartialEq)]
pub struct SanicActState {
    /// Seconds the act has been running (sim clock, so bullet-time slows it).
    pub elapsed: f32,
    /// Running vs cleared. The clock stops on a clear, which is what turns the
    /// elapsed time from a stopwatch into a RESULT.
    pub phase: SanicActPhase,
    /// Next index in [`SPEED_MARKER_XS`] that should emit its one-shot progress
    /// cue. Mode-scoped with the act, so leaving and re-entering the demo resets
    /// the audible ruler without a global resource leak.
    pub next_milestone: usize,
}

/// Where the act is. `Cleared` carries the numbers the results card reads,
/// captured at the instant of the clear rather than re-derived afterwards —
/// otherwise the rings you pick up during the outro would keep changing your
/// result while you look at it.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum SanicActPhase {
    #[default]
    Running,
    Cleared {
        time: f32,
        rings: i32,
        /// Seconds the results card has left before the act restarts.
        dwell: f32,
    },
}

/// Sanic's level rules. **ONE system list; a constructor flag decides its gating**
/// — [`SanicRulesPlugin::hosted`] when Ambition hosts the demo alongside its own
/// rooms, [`SanicRulesPlugin::global`] when the demo IS the game. That is the D-C
/// pattern (`docs/planning/engine/decomposition.md` §Phase D-C), and this is its
/// first real consumer: before this, `in_mode` had no ruleset to gate.
pub struct SanicRulesPlugin {
    hosted: bool,
}

impl SanicRulesPlugin {
    /// Ambition hosts this demo: every rule sleeps outside the Sanic rooms.
    pub fn hosted() -> Self {
        Self { hosted: true }
    }

    /// The demo IS the game: the rules run unconditionally.
    pub fn global() -> Self {
        Self { hosted: false }
    }
}

impl Plugin for SanicRulesPlugin {
    fn build(&self, app: &mut App) {
        // The plugin OWNS its mandatory message channels and shared resources:
        // its systems write SFX cues, pop VFX bursts, read room-load facts, and
        // contribute to the collision overlay. A full app registers all of
        // these through the engine plugins; a thin rules-only harness may not,
        // and `add_message`/`init_resource` are idempotent.
        app.add_message::<ambition::sfx::OwnedSfxMessage>();
        app.add_message::<ambition::vfx::VfxMessage>();
        app.add_message::<ambition::actors::rooms::RoomLoaded>();
        // The act cycle restarts the room on a clear, exactly as Mary-O's level
        // cycle does. The engine registers this in a full app; a thin
        // rules-only harness may not, and `add_message` is idempotent.
        app.add_message::<ambition::actors::session::reset::RoomReplayRequested>();
        app.init_resource::<ambition::actors::features::FeatureEcsWorldOverlay>();
        use bevy::prelude::IntoScheduleConfigs;
        let sim = ambition::platformer::schedule::SimScheduleExt::sim_schedule(app);
        app.init_resource::<ball_dash::BallDashTuning>();
        // BEFORE the persona gate: attach the mode-local state + DECLARE the
        // spin-dash technique on the Attack slot, so the shared resolver inside
        // `gate_worn_player_control` resolves Attack -> `Technique("spin_dash")`
        // and routes its device edge into the sanctioned `ResolvedTechniqueEdges`
        // (clearing the raw melee verb). Utility is D in the classic preset; the
        // transform system consumes that edge so it cannot also toggle a host-code
        // flight ability inherited by the control box.
        let sanic_pre_gate = (ball_dash::attach_ball_dash, toggle_sanic_form)
            .chain()
            .in_set(ambition::platformer::schedule::SandboxSet::PlayerInput)
            .after(ambition::actors::avatar::tick_player_brains)
            .before(ambition::actors::avatar::gate_worn_player_control);
        // AFTER the gate: read Sanic's spin-dash rev from the sanctioned technique
        // edge the gate resolved — the fragile before-gate `melee_pressed`
        // interception window is GONE (a plain melee edge is no longer the API).
        let sanic_post_gate = ball_dash::capture_ball_dash_input
            .in_set(ambition::platformer::schedule::SandboxSet::PlayerInput)
            .after(ambition::actors::avatar::gate_worn_player_control);
        if self.hosted {
            app.add_systems(
                sim,
                sanic_pre_gate.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(
                sim,
                sanic_post_gate.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
        } else {
            app.add_systems(sim, sanic_pre_gate);
            app.add_systems(sim, sanic_post_gate);
        }

        // The ball dash is a RULE, not world content: it exists while the Sanic
        // mode is live and nowhere else, exactly like the act clock. Effects run
        // after PlayerInput captured the technique and before later presentation.
        // `tick_ball_dash` precedes `tick_rolling`, so a launch cannot un-ball in
        // the same frame even if tuning changes.
        let rules = (
            spawn_sanic_mode_owner,
            tick_sanic_act,
            ball_dash::tick_ball_dash,
            ball_dash::tick_rolling,
            // Project the roll authority (`Rolling`) onto the anim fact AFTER
            // both the launch (insert) and the stand-up (remove) have settled,
            // so the looping `ball` row tracks the physical ball for the frame.
            ball_dash::mirror_ball_anim_fact,
            // The super form's derived traits (invincibility + sparkles) track
            // the worn identity every frame — toggle- and monitor-agnostic.
            sync_super_form_traits,
            // Braking scrape on the skid onset (reads the published skid fact).
            emit_sanic_skid_sfx,
            // The goal, then the cycle: a clear captured this frame must be
            // read by the card before the dwell can retire it.
            clear_act_at_goal,
            cycle_act_after_clear,
        )
            .chain()
            .in_set(ambition::platformer::schedule::SandboxSet::GameplayEffects);
        let milestone_sfx = emit_sanic_milestone_sfx
            .in_set(ambition::platformer::schedule::SandboxSet::GameplayEffects);
        // The badnik defeat runs BEFORE the engine's shared body-contact-damage
        // pass so a stomp/roll never also hurts Sanic (the rule zeroes the
        // badnik's health that frame; the contact pass skips a dead attacker).
        let badniks =
            badnik::defeat_badniks.before(ambition::actors::features::apply_actor_contact_damage);
        // Ring loss reads the health the contact pass just wrote, so it runs
        // AFTER it — the hit has to have landed before rings can absorb it.
        let ring_loss =
            scatter_rings_on_hit.after(ambition::actors::features::apply_actor_contact_damage);
        // The scattered-ring burst flies out BETWEEN the coin magnet and the
        // collect: it owns each ring's position during the lock so the magnet
        // can't reclaim it, and collect then sees the ring out at its arc rather
        // than on top of the knocked-back body.
        let scatter_arc = arc_scattered_rings
            .after(ambition::actors::features::magnetize_pickups)
            .before(ambition::actors::features::collect_ecs_pickups);
        // Monitor boxes: re-arm on (re)load, break on stomp/roll, tick the
        // speed-shoes grant. Broken monitors contribute to the overlay's
        // `removed_block_names` AFTER the engine's per-frame rebuild clears it
        // (the same slot Mary-O's bricks and encounter lock walls take).
        app.init_resource::<monitors::SpentMonitors>();
        let monitor_rules = (
            monitors::rearm_monitors_on_room_loaded,
            monitors::break_monitor_boxes,
            monitors::tick_speed_shoes,
        );
        let monitor_overlay = monitors::contribute_broken_monitors_to_overlay
            .after(ambition::actors::features::rebuild_feature_ecs_world_overlay);
        if self.hosted {
            app.add_systems(sim, rules.run_if(ambition::runtime::in_mode(SANIC_MODE)));
            app.add_systems(
                sim,
                milestone_sfx.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(sim, badniks.run_if(ambition::runtime::in_mode(SANIC_MODE)));
            app.add_systems(
                sim,
                ring_loss.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(
                sim,
                scatter_arc.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(
                sim,
                monitor_rules.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
            app.add_systems(
                sim,
                monitor_overlay.run_if(ambition::runtime::in_mode(SANIC_MODE)),
            );
        } else {
            app.add_systems(sim, rules);
            app.add_systems(sim, milestone_sfx);
            app.add_systems(sim, badniks);
            app.add_systems(sim, ring_loss);
            app.add_systems(sim, scatter_arc);
            app.add_systems(sim, monitor_rules);
            app.add_systems(sim, monitor_overlay);
        }
    }
}

/// Play the braking scrape on the frame the controlled body STARTS skidding.
///
/// `BodyMotionFacts::skidding` is published every step by the momentum
/// integration (steer-against-fast-travel while riding); a rising edge fires the
/// scrape once per skid onset instead of every tick it holds. One controlled body
/// plays it, so a `Local` edge latch is sufficient.
fn emit_sanic_skid_sfx(
    subject: Option<bevy::prelude::Res<ambition::platformer::markers::ControlledSubject>>,
    mut was_skidding: bevy::prelude::Local<bool>,
    bodies: bevy::prelude::Query<(&ae::BodyMotionFacts, &ae::BodyKinematics)>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    let skid = subject.and_then(|s| s.0).and_then(|e| bodies.get(e).ok());
    let (skidding, pos) = skid.map_or((false, ae::Vec2::ZERO), |(facts, kin)| {
        (facts.skidding, kin.pos)
    });
    if skidding && !*was_skidding {
        sfx.write(ambition::sfx::SfxMessage::Play {
            id: ambition::sfx::SfxId::from_static(SFX_SKID),
            pos,
        });
    }
    *was_skidding = skidding;
}

/// Toggle the controlled body between the two catalog-authored Sanic forms.
///
/// This consumes the already-semantic Utility edge (`D` in the demo's classic
/// keyboard preset), never a raw key. The super row authors the form's boosted
/// movement and `sync_super_form_traits` derives the rest (invincibility,
/// sparkles, badnik destroy-on-touch) from the worn identity every frame — so
/// this toggle grants and revokes the FULL form, and `WornCharacter` stays the
/// single gameplay + presentation authority. No timer: a future ring drain can
/// wear the form off the same way this toggle does.
fn toggle_sanic_form(
    subject: Option<bevy::prelude::Res<ambition::platformer::markers::ControlledSubject>>,
    mut bodies: bevy::prelude::Query<(
        &mut ambition::characters::brain::ActorControl,
        &mut ambition::characters::actor::WornCharacter,
    )>,
) {
    let Some(entity) = subject.and_then(|subject| subject.0) else {
        return;
    };
    let Ok((mut control, mut worn)) = bodies.get_mut(entity) else {
        return;
    };
    if !control.0.fly_toggle_pressed {
        return;
    }

    // Utility belongs to this mode-local transformation. Consume the edge before
    // lower movement layers can interpret it as the generic fly toggle.
    control.0.fly_toggle_pressed = false;
    let next = match worn.id() {
        SANIC_CHARACTER_ID => SUPER_SANIC_CHARACTER_ID,
        SUPER_SANIC_CHARACTER_ID => SANIC_CHARACTER_ID,
        _ => return,
    };
    // The transform SOUND fires from the worn-identity edge in
    // `sync_super_form_traits`, so wearing the form is all this does.
    *worn = ambition::characters::actor::WornCharacter::new(next);
}

/// How often the super form's sparkle trail pulses (sim seconds).
const SUPER_SPARKLE_PERIOD: f32 = 0.14;
/// Radius of the sparkle orbit around the body centre (px).
const SUPER_SPARKLE_RADIUS: f32 = 15.0;
/// Upward bias of the sparkle ring (px, toward the torso) so the falling motes
/// hover AROUND the body rather than pooling at the feet.
const SUPER_SPARKLE_RISE: f32 = 8.0;

/// Derive the super form's non-movement traits from the worn identity, every
/// sim frame. The movement boost is authored on the `super_sanic` catalog row
/// (the wear itself grants it); what the catalog CANNOT express lives here:
///
/// - **Invincibility**: `Health::invulnerable` tracks the worn identity, so
///   badnik contact can't hurt a super Sanic. (Kernel hazards — the pit, the
///   spikes — still reset the body: falling off the world outranks any form.)
/// - **Sparkles**: a golden pulse trails the form, so the transformation reads
///   on screen and not just on the spritesheet.
///
/// The form is NOT a timed grant: the D-toggle (or a future ring drain) wears
/// it off, and every trait here reverts the same frame because it is derived,
/// never stored. Badnik destroy-on-touch derives from the same identity read
/// in `badnik::defeat_badniks`.
fn sync_super_form_traits(
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut sparkle_accum: bevy::prelude::Local<f32>,
    mut sparkle_orbit: bevy::prelude::Local<f32>,
    mut was_super: bevy::prelude::Local<bool>,
    mut vfx: bevy::prelude::MessageWriter<ambition::vfx::VfxMessage>,
    mut sfx: ambition::sfx::SfxWriter,
    mut players: bevy::prelude::Query<
        (
            &ambition::characters::actor::WornCharacter,
            &mut ambition::characters::actor::BodyHealth,
            &ae::BodyKinematics,
        ),
        bevy::prelude::With<ambition::actors::actor::PrimaryPlayer>,
    >,
) {
    // `None` = no controlled player (the session has retired; a player is present
    // for every in-session frame, surviving room changes). Derive invincibility
    // and capture the emit position while the body is borrowed.
    let (worn_is_super, pos) = match players.single_mut() {
        Ok((worn, mut health, kinematics)) => {
            let is_super = worn.id() == SUPER_SANIC_CHARACTER_ID;
            if health.health.invulnerable != is_super {
                health.health.invulnerable = is_super;
            }
            (Some(is_super), kinematics.pos)
        }
        Err(_) => (None, ae::Vec2::ZERO),
    };

    // The transform SOUND derives from the worn-identity EDGE, so it fires once no
    // matter what wore the form (the D-toggle, a monitor, a future ring drain). The
    // edge is resolved session-turnover-safe: no controlled player RESETS the latch
    // so the edge state never leaks into the next session — otherwise a session that
    // ended super would fire a phantom detransform on the next session's first
    // frame. These `Local` latches can't be reached by the resource-only
    // `SessionTeardownPlugin`, so this IS their reset-on-retirement.
    let (cue, next_super) = super_form_edge(worn_is_super, *was_super);
    *was_super = next_super;
    if let Some(to_super) = cue {
        sfx.write(ambition::sfx::SfxMessage::Play {
            id: ambition::sfx::SfxId::from_static(if to_super {
                SFX_TRANSFORM
            } else {
                SFX_DETRANSFORM
            }),
            pos,
        });
    }

    // Sparkles only while a super body is present; otherwise the accumulator + orbit
    // reset, so two consecutive super sessions start with identical sparkle phase.
    if worn_is_super != Some(true) {
        *sparkle_accum = 0.0;
        *sparkle_orbit = 0.0;
        return;
    }
    *sparkle_accum += time.scaled_dt;
    if *sparkle_accum >= SUPER_SPARKLE_PERIOD {
        *sparkle_accum -= SUPER_SPARKLE_PERIOD;
        // Orbit the emit point AROUND the body so the motes read as a golden
        // aura ring, not a stream out of one point (Shard's heavy gravity turned
        // a centre-emit burst into a dribble). The golden-angle step spreads
        // successive pulses evenly around the ring; the upward bias keeps the
        // (still-falling) Spark motes hovering around the torso.
        *sparkle_orbit += 2.399_963; // golden angle, radians
        let ring = ae::Vec2::new(sparkle_orbit.cos(), sparkle_orbit.sin()) * SUPER_SPARKLE_RADIUS;
        vfx.write(ambition::vfx::VfxMessage::Burst {
            pos: pos + ring - ae::Vec2::new(0.0, SUPER_SPARKLE_RISE),
            count: 2,
            speed: 26.0,
            color: [1.0, 0.9, 0.4, 1.0],
            kind: ambition::vfx::ParticleKind::Spark,
        });
    }
}

/// The super-form transform-cue edge, resolved so session-local latch state never
/// leaks across a session turnover.
///
/// `worn_is_super` is `None` when no player is controlled (the session has
/// retired). Returns `(cue, next_latch)`: a `Some(true)` cue is a transform, a
/// `Some(false)` a detransform, `None` no cue. With no controlled player the latch
/// RESETS to `false` and no cue fires, so a session that ended super cannot make
/// the next session emit a phantom detransform on its first frame.
fn super_form_edge(worn_is_super: Option<bool>, was_super: bool) -> (Option<bool>, bool) {
    match worn_is_super {
        None => (None, false),
        Some(is_super) if is_super != was_super => (Some(is_super), is_super),
        Some(_) => (None, was_super),
    }
}

/// Bring the act state into being the first frame the mode is live. Spawned
/// `spawn_mode_scoped`, so the engine despawns it when the active room's mode
/// changes — no teardown code here.
fn spawn_sanic_mode_owner(
    mut commands: bevy::prelude::Commands,
    existing: bevy::prelude::Query<(), bevy::prelude::With<SanicActState>>,
    session: Option<bevy::prelude::Res<ambition::platformer::lifecycle::ActiveSessionScope>>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    use ambition::platformer::lifecycle::{SessionSpawnScope, SpawnSessionScopedExt};
    // Sleep when a session-scoped host has retired the live session (i.e. at the
    // launcher): the room metadata may still read "sanic" until the next
    // activation overwrites it, but there is no session to own new state, so the
    // act owner must not be resurrected. When no `ActiveSessionScope` exists at
    // all (the historical Startup path and the D-C tests) the guard is inert.
    let session_live = session
        .as_ref()
        .map_or(true, |scope| scope.current().is_some());
    let spawn_scope = session
        .as_ref()
        .map_or(SessionSpawnScope::UNSCOPED, |scope| scope.spawn_scope());
    if session_live && existing.iter().next().is_none() {
        // Owned by BOTH the mode (survives in-session room changes) and the
        // active session (torn down on a shell relaunch, which a same-mode
        // reload is NOT — so mode-scope alone would leak the act across a
        // launch → quit → relaunch cycle).
        commands
            .spawn_session_scoped(spawn_scope, SanicActState::default())
            .insert(ambition::platformer::lifecycle::ModeScopedEntity(
                SANIC_MODE.to_string(),
            ));
        // Audible confirmation that the standalone shell is draining the
        // standard SfxMessage seam. Distance markers emit alternating cues as
        // the player advances, so this one also proves the bank at room entry.
        sfx.write(ambition::sfx::SfxMessage::Dash {
            pos: ae::Vec2::ZERO,
        });
    }
}

/// The act timer runs on the SIM clock (`scaled_dt`), so bullet-time and pause
/// slow it exactly as they slow everything else — `WorldTime`, never `Res<Time>`.
fn tick_sanic_act(
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut act: bevy::prelude::Query<&mut SanicActState>,
) {
    for mut state in &mut act {
        if matches!(state.phase, SanicActPhase::Running) {
            state.elapsed += time.scaled_dt;
        }
    }
}

/// Emit a small, existing Ambition cue when the primary body crosses each
/// visible distance marker. These are deliberately simple diagnostic sounds:
/// the demo is proving that its shell drains the standard [`ambition::sfx::SfxMessage`] seam,
/// not inventing a parallel Sanic audio stack.
fn emit_sanic_milestone_sfx(
    player: bevy::prelude::Query<
        &ae::BodyKinematics,
        bevy::prelude::With<ambition::actors::actor::PrimaryPlayer>,
    >,
    mut act: bevy::prelude::Query<&mut SanicActState>,
    mut sfx: ambition::sfx::SfxWriter,
) {
    let Ok(kin) = player.single() else {
        return;
    };
    for mut state in &mut act {
        while let Some(&marker_x) = SPEED_MARKER_XS.get(state.next_milestone) {
            if kin.pos.x < marker_x {
                break;
            }
            let message = if state.next_milestone % 2 == 0 {
                ambition::sfx::SfxMessage::Dash { pos: kin.pos }
            } else {
                ambition::sfx::SfxMessage::Jump { pos: kin.pos }
            };
            sfx.write(message);
            state.next_milestone += 1;
        }
    }
}

/// Install the Sanic demo content layer into an engine app.
pub fn add_demo_content(app: &mut App) {
    app.add_plugins(SanicDemoContentPlugin);
}

#[cfg(test)]
mod tests;

// ---------------------------------------------------------------------------
// Ring loss — what makes a ring worth anything.
// ---------------------------------------------------------------------------

/// How many of the rings you were carrying actually scatter. The rest are gone.
///
/// Losing everything and being able to recover everything are both boring; the
/// classic answer is "you can get SOME of it back if you are quick", and the cap
/// is what keeps a big purse from turning a hit into a shower.
const SCATTERED_RINGS_MAX: usize = 12;

/// Outward launch speed (px/s) a scattered ring bursts from the body with.
const SCATTER_BURST_SPEED: f32 = 250.0;

/// Downward pull (px/s²) that arcs a scattered ring back down, screen-relative
/// (the demo runs under normal screen gravity).
const SCATTER_GRAVITY: f32 = 900.0;

/// How long (s) a scattered ring is airborne-and-uncollectible by the magnet:
/// during this window `arc_scattered_rings` OWNS its position (bursting outward),
/// so the coin magnet cannot vacuum it straight back the instant it drops. After
/// it, the ring is an ordinary currency pickup the shared economy collects —
/// that hand-off is what makes "run back and grab them" a real scramble rather
/// than a same-frame refund. Just short of a second, the classic feel.
const SCATTER_LOCK_S: f32 = 0.85;

/// Marks the body's "I just lost my rings" window, so a single hit cannot be
/// billed twice while the damage frame is still resolving.
#[derive(bevy::prelude::Component, Debug, Default)]
pub struct SanicRingLoss {
    /// Health the body had last time this ran. A DROP is the hit edge.
    seen_health: Option<i32>,
}

/// A ring in mid-BURST after a hit (classic Sonic scatter): it flies out from the
/// body and arcs down under gravity, and while its `lock` is live it is NOT yet
/// magnet-collectible. Rollback-registered sim state — the burst has to
/// resimulate identically, so its velocity/position/lock ride the snapshot the
/// same way `BallDash` does. `arc_scattered_rings` integrates it; when the lock
/// expires the component is removed and the ring becomes an ordinary pickup.
#[derive(bevy::prelude::Component, Clone, Copy, Debug)]
pub struct ScatteredRing {
    /// Current burst velocity (screen frame, px/s).
    pub vel: ae::Vec2,
    /// The position this system OWNS while locked — integrated here so it wins
    /// over the coin magnet, which also writes the pickup's `CenteredAabb`.
    pub arc_pos: ae::Vec2,
    /// Seconds left in the airborne/uncollectible window.
    pub lock: f32,
}

/// **Rings absorb the hit.**
///
/// This is the rule the whole ring economy exists to serve: carrying rings is
/// not a score, it is a life. Take a hit holding rings and you survive it and
/// they scatter; take one holding none and it lands normally.
///
/// The hit is detected as a DROP in the body's health rather than by listening
/// for a damage message, for the same reason Mary-O counts deaths off the
/// engine's respawn counter: every current and future source of damage — badnik
/// contact, spikes, a hazard nobody has authored yet — is already accounted for,
/// with no per-source wiring.
///
/// The scattered rings are ordinary `currency` pickups spawned through the
/// engine's own `spawn_pickup`, so the shared economy collects them on the exact
/// path an authored ring takes. A dropped ring and an authored ring are the same
/// thing once they exist, which is what makes "run back and grab them" work
/// without a single line of demo collection code.
pub fn scatter_rings_on_hit(
    mut commands: bevy::prelude::Commands,
    active_session: Option<bevy::prelude::Res<ambition::platformer::lifecycle::ActiveSessionScope>>,
    mut vfx: bevy::prelude::MessageWriter<ambition::vfx::VfxMessage>,
    mut sfx: ambition::sfx::SfxWriter,
    mut bodies: bevy::prelude::Query<
        (
            bevy::prelude::Entity,
            &ae::BodyKinematics,
            &mut ambition::characters::actor::BodyHealth,
            &mut ambition::characters::actor::BodyWallet,
            Option<&mut SanicRingLoss>,
        ),
        ambition::platformer::markers::PrimaryPlayerOnly,
    >,
) {
    let Some(scope) =
        ambition::platformer::lifecycle::SessionSpawnScope::for_optional_active_session(
            active_session.as_deref(),
        )
    else {
        return;
    };

    for (entity, kin, mut health, mut wallet, loss) in &mut bodies {
        let current = health.health.current;
        let Some(mut loss) = loss else {
            // First sight: adopt the health we find rather than reading the
            // session's starting value as a hit.
            commands.entity(entity).try_insert(SanicRingLoss {
                seen_health: Some(current),
            });
            continue;
        };
        let previous = *loss.seen_health.get_or_insert(current);
        let took_a_hit = current < previous;
        loss.seen_health = Some(current);

        if !took_a_hit || wallet.balance <= 0 {
            // No rings: the hit lands exactly as it would have. Ring loss is a
            // privilege of carrying rings, not a blanket shield.
            continue;
        }

        // Carrying rings: the hit is SPENT on them instead of on health.
        health.health.current = previous;
        let carried = wallet.balance;
        wallet.balance = 0;

        let scattered = (carried as usize).min(SCATTERED_RINGS_MAX);
        for i in 0..scattered {
            // Classic Sonic: the rings BURST from the body and arc outward under
            // gravity, rather than appearing in a static fan. Each ring launches
            // up-and-out; alternating x-sign fans the spray symmetrically to both
            // sides. The arc + the no-magnet lock live on `ScatteredRing`, ticked
            // by `arc_scattered_rings`.
            let t = (i as f32 + 0.5) / scattered as f32;
            let angle = std::f32::consts::PI * (0.18 + 0.64 * t);
            let dir = if i % 2 == 0 { 1.0 } else { -1.0 };
            let vel = ae::Vec2::new(
                angle.cos() * SCATTER_BURST_SPEED * dir,
                // Screen +y is down, so a negative y launches them upward.
                -angle.sin() * SCATTER_BURST_SPEED,
            );
            let size = ae::Vec2::splat(18.0);
            let authored = ambition::actors::rooms::Authored {
                id: format!("sanic_dropped_ring_{}_{i}", entity.index()),
                name: "ring".to_string(),
                // Every ring is born AT the body and flies out from there.
                aabb: ae::Aabb::new(kin.pos, size * 0.5),
                payload: {
                    let mut spec = ambition::entity_catalog::placements::PickupSpec::new(
                        ambition::entity_catalog::placements::PickupKindSpec::Currency {
                            amount: 1,
                        },
                    );
                    spec.sprite = Some(RING_SPRITE_KIND.to_string());
                    spec
                },
            };
            let ring = ambition::actors::features::ecs::spawn_static::spawn_pickup(
                &mut commands,
                scope,
                &authored,
            );
            commands.entity(ring).insert(ScatteredRing {
                vel,
                arc_pos: kin.pos,
                lock: SCATTER_LOCK_S,
            });
        }

        vfx.write(ambition::vfx::VfxMessage::Burst {
            pos: kin.pos,
            count: 18,
            speed: 210.0,
            color: [1.0, 0.86, 0.28, 1.0],
            kind: ambition::vfx::ParticleKind::Dust,
        });
        sfx.write(ambition::sfx::SfxMessage::Play {
            id: ambition::sfx::SfxId::from_static(SFX_BADNIK),
            pos: kin.pos,
        });
    }
}

/// Fly the mid-burst scattered rings outward and arc them down (classic Sonic).
///
/// Ordered `.after(magnetize_pickups).before(collect_ecs_pickups)`: it OWNS the
/// ring's `CenteredAabb` during the lock, so the coin magnet — which wrote the
/// same AABB a step earlier — cannot reel the ring straight back, and `collect`
/// then sees the ring out at its arced position (well away from the knocked-back
/// body) instead of on top of the player. When the lock expires the component is
/// dropped and the ring is an ordinary currency pickup again, collectible on the
/// shared path. Deterministic (all state is the rollback-registered
/// `ScatteredRing` plus the scaled sim dt), so it resimulates identically.
pub fn arc_scattered_rings(
    mut commands: bevy::prelude::Commands,
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut rings: bevy::prelude::Query<(
        bevy::prelude::Entity,
        &mut ScatteredRing,
        &mut ae::CenteredAabb,
    )>,
) {
    let dt = time.scaled_dt;
    for (entity, mut ring, mut aabb) in &mut rings {
        // The burst arc is authoritative while locked — overwrite whatever the
        // magnet just did to the AABB.
        aabb.center = ring.arc_pos;
        let step = ring.vel * dt;
        ring.arc_pos += step;
        ring.vel.y += SCATTER_GRAVITY * dt;
        ring.lock -= dt;
        if ring.lock <= 0.0 {
            commands.entity(entity).remove::<ScatteredRing>();
        }
    }
}

// ---------------------------------------------------------------------------
// The goal — what an act is FOR.
// ---------------------------------------------------------------------------

/// World x of the goal line.
///
/// Set back from the level's right edge because the body cannot reach the edge
/// itself: the runnable extent tops out around `LEVEL_WIDTH - 270`, so a goal
/// any closer to the wall is one a player can never cross. The first version of
/// this sat at `LEVEL_WIDTH - 130` and made the act literally uncompletable —
/// you could run the speedway forever and nothing would ever happen.
pub const GOAL_X: f32 = LEVEL_WIDTH - 400.0;

/// How long the results card holds before the act restarts.
pub const ACT_CLEAR_DWELL: f32 = 4.0;

/// Points per second of time left on a nominal par run, and the par itself.
/// A time bonus is what makes going FAST pay, which is the entire premise of
/// this demo — without it, a route that is safer but slower always wins.
///
/// Par is 30s against a measured ~6s clean run (see the act-completion proof),
/// so the bonus spreads meaningfully across real finishing times instead of
/// bunching every plausible run near the maximum.
pub const ACT_PAR_SECONDS: f32 = 30.0;
pub const TIME_BONUS_PER_SECOND: i32 = 100;
/// Each ring you finish holding is worth this.
///
/// Sized against the time bonus deliberately: a clean run banks roughly 2400
/// from time, and a full ring purse is worth roughly as much again. Two
/// currencies only pull against each other if they are of comparable size — at
/// the original 10/ring the time bonus swamped rings by an order of magnitude
/// and the "tension" this demo is built on did not exist in the arithmetic.
pub const RING_BONUS: i32 = 100;

/// The act's score, from the numbers captured at the clear.
pub fn act_score(time: f32, rings: i32) -> i32 {
    let remaining = (ACT_PAR_SECONDS - time).max(0.0);
    (remaining * TIME_BONUS_PER_SECOND as f32) as i32 + rings.max(0) * RING_BONUS
}

/// Format a duration the way a results screen does.
pub fn act_time_text(seconds: f32) -> String {
    let whole = seconds.max(0.0) as i32;
    format!("{}:{:02}", whole / 60, whole % 60)
}

/// **Crossing the goal clears the act.**
///
/// Captures the time and the rings AT THE CLEAR — the results card reads those,
/// not the live values, so picking a ring up during the outro cannot rewrite a
/// result the player is already looking at.
pub fn clear_act_at_goal(
    player: bevy::prelude::Query<
        (
            &ae::BodyKinematics,
            &ambition::characters::actor::BodyWallet,
        ),
        ambition::platformer::markers::PrimaryPlayerOnly,
    >,
    mut act: bevy::prelude::Query<&mut SanicActState>,
    mut sfx: ambition::sfx::SfxWriter,
    mut vfx: bevy::prelude::MessageWriter<ambition::vfx::VfxMessage>,
) {
    let Ok((kin, wallet)) = player.single() else {
        return;
    };
    for mut state in &mut act {
        if !matches!(state.phase, SanicActPhase::Running) || kin.pos.x < GOAL_X {
            continue;
        }
        state.phase = SanicActPhase::Cleared {
            time: state.elapsed,
            rings: wallet.balance,
            dwell: ACT_CLEAR_DWELL,
        };
        vfx.write(ambition::vfx::VfxMessage::Burst {
            pos: kin.pos,
            count: 40,
            speed: 320.0,
            color: [1.0, 0.92, 0.35, 1.0],
            kind: ambition::vfx::ParticleKind::Dust,
        });
        sfx.write(ambition::sfx::SfxMessage::Play {
            id: ambition::sfx::SfxId::from_static(SFX_TRANSFORM),
            pos: kin.pos,
        });
    }
}

/// **The act restarts once the results have been read.**
///
/// Same shape as Mary-O's cyclic level: the dwell is what makes the tally
/// legible before the world rebuilds under it, and the restart itself is the
/// engine's ordinary `RoomReplayRequested` rather than anything demo-specific.
pub fn cycle_act_after_clear(
    time: bevy::prelude::Res<ambition::time::WorldTime>,
    mut act: bevy::prelude::Query<&mut SanicActState>,
    mut replay: bevy::prelude::MessageWriter<ambition::actors::session::reset::RoomReplayRequested>,
) {
    for mut state in &mut act {
        let SanicActPhase::Cleared { dwell, .. } = &mut state.phase else {
            continue;
        };
        *dwell -= time.scaled_dt;
        if *dwell > 0.0 {
            continue;
        }
        *state = SanicActState::default();
        replay.write(ambition::actors::session::reset::RoomReplayRequested);
    }
}
